### ISSUE TITLE
Error: Undefined index:TOKEN

### ISSUE THREAD

**Issue by nfunwigabga** [srmklive/laravel-paypal#100]
I get this error when I try to set the Express checkout. Also occurs in the demo you have online:

```
ErrorException in ExpressCheckout.php line 127:
Undefined index: TOKEN
```
Any ideas? Does it mean PayPal is not sending back a response or what?

**Comment by srmklive** [comment]
It means the credentials are incorrect or there is a duplicate invoice id etc.

**Comment by nfunwigabga** [comment]
So the credentials in the online demo you have set are not correct either?

**Comment by srmklive** [comment]
You need to update these credentials according to your requirements. The purpose of demo app is to just give you a starting point. Its up to you to make changes.

**Comment by hemantnarang33** [comment]
i have got the same problem ...but if i use the 1.4.1 version than it does not give this error...and works perfectly fine...please explain what to do?

**Comment by srmklive** [comment]
@hemantnarang33 please check your api credentials or the data you are passing to `SetExpressCheckout` API call. Issue might be there. Also have a look at the demo app, this should be a good starting point for you
