### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by glorita** [srmklive/laravel-paypal#101]
I get this error:
Using this link: https://laravel-paypal-demo.srmk.info/
ErrorException in ExpressCheckout.php line 127: Undefined index: TOKEN
Today 30/04/2017

I'm looking for a PayPal integration module for Laravel.

**Comment by srmklive** [comment]
The demo is just for testing purpose. Just clone this [repo](https://github.com/srmklive/laravel-paypal-demo.git) and update your changes accordingly.

This package supports PayPal Express Checkkout. Head over to the [README](https://github.com/srmklive/laravel-paypal/blob/master/README.md) for details regarding this package.
