### ISSUE TITLE
Express Checkout issue

### ISSUE THREAD

**Issue by startupmasters** [srmklive/laravel-paypal#102]
Does not work on express checkout. Here is my screenshot.
![image](https://cloud.githubusercontent.com/assets/18697248/25699302/59a9ada6-30cb-11e7-891c-ca88d446ce34.png)

The demo does not work for express checkout also. See screenshot. Will a fix be out soon ?
![image](https://cloud.githubusercontent.com/assets/18697248/25699332/7b882862-30cb-11e7-98c2-d532eb899645.png)

**Comment by srmklive** [comment]
you need to provide correct api credentials for express checkout. I will have the demo app fiixed in a day or two.

**Comment by srmklive** [comment]
I have fixed the demo app.
