### ISSUE TITLE
Do reoccurring payments make initial charge?

### ISSUE THREAD

**Issue by MatthewSH** [srmklive/laravel-paypal#105]
Testing out the reoccurring payments on the sandbox. Was checking the payments and saw that it will charge on the next cycle, but not an initial charge. Is this deliberate or what @srmklive? Not too sure.

**Comment by srmklive** [comment]
@MatthewSH it depends on when you actually start a billing cycle & also the parameters you provide to the api. The README file just lists an example on creating a recurring profile. I would suggest that you look at [CreateRecurringPaymentsProfile](https://developer.paypal.com/docs/classic/api/merchant/CreateRecurringPaymentsProfile_API_Operation_NVP/) documentation. 

I also have created a [demo application](https://github.com/laravel-paypal-demo) for this purpose. Following is the demo link for this application:

https://laravel-paypal-demo.srmk.info

**Comment by MatthewSH** [comment]
I have been. I've been basing it off documentation and [this](https://github.com/srmklive/laravel-paypal-demo/blob/master/app/Http/Controllers/PayPalController.php#L85) part of your example. However, looking in the sandbox I see this...

![Sandbox Image](http://i.imgur.com/qzPCQFX.png)

I see that the next payment is due today (I just activated this subscription before I took that picture). I'm trying to figure out why the initial charge is 0.


This is the snippet creating the subscription.
```php
        $provider = new ExpressCheckout();
        $response = $provider->getExpressCheckoutDetails($token);

        if (in_array(strtoupper($response['ACK']), ['SUCCESS', 'SUCCESSWITHWARNING'])) {
            $response = $provider->createMonthlySubscription($token, $amount, $description);

            if (!empty($response['PROFILESTATUS']) && in_array($response['PROFILESTATUS'], ['ActiveProfile', 'PendingProfile'])) {
                dd($response);
            }
        }
```

Am I missing something here?

**Comment by MatthewSH** [comment]
Just checked the test store. Same thing here...

![Image](http://i.imgur.com/Xl3TnHf.png)

Is there just some sort of delay?

**Comment by srmklive** [comment]
@MatthewSH The charge will happen i believe at a later time on the same day. Sometimes there is a delay, but the amount is usually charged instantly.

**Comment by srmklive** [comment]
As you can see below, amount has been charged to the user, and the next payment date is on June 30

![download](https://cloud.githubusercontent.com/assets/839335/26649669/2e262510-4660-11e7-82c1-08a2bd8f8083.jpg)

**Comment by srmklive** [comment]
@MatthewSH Remember that the charge for a recurring payment will be shown in your paypal account as a separate charge.

**Comment by MatthewSH** [comment]
Intersting, this is very weird that PayPal does this. I think everything is going through. I just checked. Thank you so much.
