### ISSUE TITLE
Missing argument 2 from Trait

### ISSUE THREAD

**Issue by yasenivanov** [srmklive/laravel-paypal#106]
I followed the demo and tried to execute express payment, but stuck on this one:
`local.ERROR: exception 'ErrorException' with message 'Missing argument 2 for Srmklive\PayPal\Services\ExpressCheckout::Srmklive\PayPal\Traits\{closure}()' in .../vendor/srmklive/paypal/src/Traits/PayPalRequest.php:331`

I am using Laravel version 5.1 and  "srmklive/paypal": "~1.0"

**Comment by srmklive** [comment]
Upgrade the package to the latest version. I don't think i have come across this issue for 5.1. I will look into it and will add a fix if i can replicate the issue.
