### ISSUE TITLE
Error 524 on redirecting to Paypal link

### ISSUE THREAD

**Issue by aishabadar** [srmklive/laravel-paypal#107]
I am getting an error 524 when the page is redirecting to express check out page. Here is the attached image:
![capture](https://cloud.githubusercontent.com/assets/26408749/26736060/f9b7ca0c-47dd-11e7-9392-32bd15a40689.PNG)

Here is my code:

         use Srmklive\PayPal\Services\ExpressCheckout;
         public function makePaypalPayment($product, $country){
         $provider = \PayPal::setProvider('express_checkout');

         $data = [];
         if($product == 'single-issue'){
            $data['items'] = [
                [
                    'name' => 'Single Issue',
                    'price' => 15.00,
                    'qty' => 1
                ]
            ];
        }
        elseif($product == 'subscription'){
            $data['items'] = [
                [
                    'name' => '2 Year Subscription - 4 Issues',
                    'price' => 25.00,
                    'qty' => 1
                ]
            ];
        }

        $data['invoice_id'] = 1;
        $data['invoice_description'] = "Order #{$data['invoice_id']} Invoice";
        $data['return_url'] = url('/payment/success');
        $data['cancel_url'] = url('/cart');

        $total = 0;
        foreach($data['items'] as $item) {
            $total += $item['price']*$item['qty'];
        }

        $data['total'] = $total;

        $response = $provider->setExpressCheckout($data);
        $response = $provider->getExpressCheckoutDetails($token);
        /*$response = $provider->doExpressCheckoutPayment($data, $token, $PayerID);*/
        // This will redirect user to PayPal
        return redirect($response['paypal_link']);
    }

Please tell me what is wrong in my code.

Thank you.

**Comment by tsegayegit** [comment]
if($response['paypal_link'] == null){
   // custom redirection
   return redirect()->back()->with(['error'=>'paypal link no set'])
}
return redirect()->away($response['paypal_link']);
