### ISSUE TITLE
Security header is not valid for live credentials

### ISSUE THREAD

**Issue by raihancse104** [srmklive/laravel-paypal#108]
Hi srmklive,
I am using your package. For Express Checkout,  when i am using sandbox API then everything OK and work fine. But live credential problem.
In sandbox account , i get user name, password, and API secret and they provides us this information.but when i create live app in REST API apps section then they provide sandbox and live two different section . I select live where i get pay-pal account, client id, secret but password missing.
In your application i used this pay-pal account as a user name, secret as a secret, and my login password as a password. After configure that i am trying to express checkout for my live  application but they provide me error such as : 

[TIMESTAMP] => 2017-06-08T10:58:42Z
    [CORRELATIONID] => xxxxxxxxxx
    [ACK] => Failure
    [VERSION] => 123
    [BUILD] => xxxxxx
    [L_ERRORCODE0] => 10002
    [L_SHORTMESSAGE0] => Security error
    [L_LONGMESSAGE0] => Security header is not valid
    [L_SEVERITYCODE0] => Error

Please help me to solve this. And give me guideline to recover this problem.
am i doing any wrong then please suggest me.

@srmklive 
I am using Laravel version 5.3 and "srmklive/paypal": "~1.0"

**Comment by srmklive** [comment]
I would say upgrade openssl on server to the latest version. I myself have checked on my live paypal account credentials, haven't been able to replicate what you have posted.

**Comment by raihancse104** [comment]
Hi srmklive @srmklive ,

I am upgrading latest version openssl on local server ( xampp ) but problem not solved. Can you suggest me how can i recover this issue? . 
Really its a big problem for me and wastes huge time for that.

**Comment by srmklive** [comment]
@raihancse104 I haven't come across the issue you mentioned. Test your application on a staging server not on your local machine.

**Comment by raihancse104** [comment]
@srmklive, i ma testing live server and same problem faced. Undefined index token that means security header is not valid.
How can i solve this,Please help me.

**Comment by srmklive** [comment]
Check your api request for SetExpressCheckOut. You might be passing wrong values there. I am even using this package in a couple of client's applications. Never ever have i come across an issue like you have mentioned.

**Comment by amitchaudhary2024** [comment]
Hi Srmklive,
We are also facing the same issue, while testing on stagging server its working fine and openssl version is  "OpenSSL 1.0.1e-fips 11 Feb 2013" , but in production server is throwing the error 
(
    [TIMESTAMP] => 2017-12-19T07:27:29Z
    [CORRELATIONID] => ###############
    [ACK] => Failure
    [VERSION] => 123
    [BUILD] => 40680762
    [L_ERRORCODE0] => 10002
    [L_SHORTMESSAGE0] => Security error
    [L_LONGMESSAGE0] => Security header is not valid
    [L_SEVERITYCODE0] => Error
    [paypal_link] =>
)

production server also has an upgraded open ssl "OpenSSL 1.0.2k-fips  26 Jan 2017".  
Please help us to reslove this issue.

**Comment by umerm** [comment]
I am having the same problem. Has anyone found the solution ?

**Comment by amitchaudhary2024** [comment]
To resolve this issue you need to create a signature key for your api.
Follow the steps to create signature key. 
1-      Login to this url https://www.paypal.com/businessmanage/credentials/apiAccess
Username: **************
Password: ******************
2-      Click on Manage Api Credentials  under  NVP\SOAP API

**Comment by umerm** [comment]
I did the same but its giving the same error.

**Comment by amitchaudhary2024** [comment]
Also accept the option to accept online payment trough api. 
go to Tools-> Api credentials->Manage paypal Checkout Settings 
then accept and submit.

**Comment by umerm** [comment]
Didn't work.. Same issue.

**Comment by mukundindianic** [comment]
Same issue, its not working. 
  "ACK" => "Failure"
  "VERSION" => "123"
  "BUILD" => "45452353"
  "L_ERRORCODE0" => "10002"
  "L_SHORTMESSAGE0" => "Security error"
  "L_LONGMESSAGE0" => "Security header is not valid"
  "L_SEVERITYCODE0" => "Error"
  "paypal_link" => null

I have disabled to SSL Verification though it checks for it

**Comment by mukundindianic** [comment]
Issue is it trying to verify SSL even its disabled: 
Can you please add option             CURLOPT_SSL_VERIFYHOST => 0,
if verify SSL set to false

Inside TraitsPayPalHttpClient.php 
$this->httpClientConfig = [
            CURLOPT_SSL_VERIFYHOST => $this->validateSSL,

            CURLOPT_SSLVERSION     => CURL_SSLVERSION_TLSv1_2,
            CURLOPT_SSL_VERIFYPEER => $this->validateSSL,
        ];


or add option to add custom CURL headers. I think  that is better

**Comment by kevnk** [comment]
I was getting this same error, but once I used the correct API credentials, it worked.

"Sandbox account" != `PAYPAL_SANDBOX_API_USERNAME`
"Client ID" != `PAYPAL_SANDBOX_API_PASSWORD`

View and edit your sandbox account at https://developer.paypal.com/developer/accounts/ and then view the "API Credentials" tab

![paypal tab](https://api.monosnap.com/file/download?id=aGs97LbDmmJZ1Aw6KThW2Rsw6pnbYe)

**Comment by Dalamar** [comment]
> I was getting this same error, but once I used the correct API credentials, it worked.

Would you please share where can we take correct API credentials as the information in PayPal API Credentials is very contradictional and doesn't fully match the package  .env params.

**Comment by davemin** [comment]
There is a misunderstanding about words in config: PAYPAL_SANDBOX_API_SECRET in reality is API SIGNATURE, login in your business sandbox account, manage api credentials and get API Signature value, don't use api secret

**Comment by isDOSe** [comment]
> There is a misunderstanding about words in config: PAYPAL_SANDBOX_API_SECRET in reality is API SIGNATURE, login in your business sandbox account, manage api credentials and get API Signature value, don't use api secret

Dudeeeeeee!!!!! I have hours, literally hours finding the solution and this is the one and trully solution for my error... I was typing api secret in PAYPAL_SANDBOX_API_SECRET value.... For god sake @srmklive change this!!!!

**Comment by seunoyebode** [comment]
I'm having this error too @eflames I have the right values yet, I'm still getting....

```
array:10 [▼
  "TIMESTAMP" => "2020-09-22T16:06:27Z"
  "CORRELATIONID" => "f6b197edc1dab"
  "ACK" => "Failure"
  "VERSION" => "123"
  "BUILD" => "54906389"
  "L_ERRORCODE0" => "10002"
  "L_SHORTMESSAGE0" => "Security error"
  "L_LONGMESSAGE0" => "Security header is not valid"
  "L_SEVERITYCODE0" => "Error"
  "paypal_link" => null
]
```

@eflames Do you mean, even on the Live server I need to pass in values for env('PAYPAL_SANDBOX_API_USERNAME', ''), env('PAYPAL_SANDBOX_API_PASSWORD', ''), env('PAYPAL_SANDBOX_API_SECRET', '')?

I'm asking this because, the integration on my Local works perfectly fine (sandbox), in fact it works on my live app if I set to sandbox mode. But I have not been to make it work on Live.

Please help.

cc: @davemin @kevnk

**Comment by Samiys** [comment]
> There is a misunderstanding about words in config: PAYPAL_SANDBOX_API_SECRET in reality is API SIGNATURE, login in your business sandbox account, manage api credentials and get API Signature value, don't use api secret

Thank You. This really worked

**Comment by procodingtools** [comment]
> ![1step](https://user-images.githubusercontent.com/31889053/37032754-9a6a933e-2169-11e8-8e8c-dbca4ef1106d.png) ![2step](https://user-images.githubusercontent.com/31889053/37032762-a0012984-2169-11e8-8ba7-8ca0c9a779bd.png) ![3step](https://user-images.githubusercontent.com/31889053/37032766-a38494ce-2169-11e8-8272-340b3ef766de.png) ![4step](https://user-images.githubusercontent.com/31889053/37032774-a7218308-2169-11e8-8212-f6e3c3c69064.png)
> 
> Also accept the option to accept online payment trough api. go to Tools-> Api credentials->Manage paypal Checkout Settings then accept and submit.

You saved My DAY
