### ISSUE TITLE
parsePayPalIPN doesn't work

### ISSUE THREAD

**Issue by d3ce1t** [srmklive/laravel-paypal#117]
Next code from **Handling PayPal IPN** example in README.md doesn't work:
```
// Import the namespace Srmklive\PayPal\Services\ExpressCheckout first in your controller.
$provider = new ExpressCheckout;
$response = (string) $provider->parsePayPalIPN($request);
    
if ($response === 'VERIFIED') {                      
    // Your code goes here ...
}   
```
AFAIK ExpressCheckout provider doesn't have a method with that name. However, there exists a trait in src/Traits/IPNResponse with that functionality (which isn't used in ExpressCheckout provider).

Is this a documentation or a source code error?

Anyway, assuming that IPNResponse trait should be used in a controller, it doesn't work either.

What would be a working example of PayPal IPN validation?

Thank you very much,

**Comment by srmklive** [comment]
What i have listed in the example works perfectly. Refer to the demo application in this regard.

**Comment by d3ce1t** [comment]
From demo application [PayPalController.php](https://github.com/srmklive/laravel-paypal-demo/blob/master/app/Http/Controllers/PayPalController.php):

```
/**
 * Parse PayPal IPN.
 *
 * @param \Illuminate\Http\Request $request
 */
 public function notify(Request $request)
 {
        $request->merge(['cmd' => '_notify-validate']);
        $post = $request->all();

        $response = (string) $this->provider->verifyIPN($post);

        $logFile = 'ipn_log_'.Carbon::now()->format('Ymd_His').'.txt';
        Storage::disk('local')->put($logFile, $response);
    }
```

It doesn't even call "parsePayPalIPN" from IPNResponse trait. Please, review your example because it doesn't work.

**Comment by srmklive** [comment]
@d3ce1t Have you even tried to setup the demo app? If you can identify issues you are facing, let me know.

**Comment by srmklive** [comment]
To be honest, this is simply an oversight issue. I haven't updated the README section for IPN. There is no issue regarding IPN that i have come across or anyone has reported it for that matter, therefore your assertion that it doesn't work is incorrect.

**Comment by d3ce1t** [comment]
To be fair, first thing I did was to ask if it was a documentation or source code related error. Anyway,  I've just seen you changed README.md so it's done. Now I'm using `$response = (string) $provider->verifyIPN($post);`. However, I always get "INVALID" as response. Any idea?

BTW: There is an open [issue](https://github.com/laravel/framework/issues/19961) where you cannot get values from a request with url-encoded characters like %F3. I was affected by this too.

**Comment by srmklive** [comment]
You may need to look at your api credentials.
