### ISSUE TITLE
notify_url on laravel 5.4 && sandbox

### ISSUE THREAD

**Issue by yshaish1** [srmklive/laravel-paypal#118]
Hi, I put my url on config/paypal.php under: notify_url.
I didnt try it on live, I dont have it yet, but its not working on sandbox.

need to do somthing special to get the notify?
This is the url that paypal send post request on success payment right?

help please. thanks

**Comment by srmklive** [comment]
Kindly set the ipn in PayPal as well, and follow the steps that i have listed in the README. For Sandbox & Live, IPN should always be set in your paypal account.

**Comment by yshaish1** [comment]
thanks for the answer.
where do I set the ipn in paypal ? cant find it..
when i try the IPN Simulator its all work fine with your code.

**Comment by srmklive** [comment]
Search Google for this.
