### ISSUE TITLE
Curl Error

### ISSUE THREAD

**Issue by Hodel1** [srmklive/laravel-paypal#120]
Hey,

i have a issue and i did debugged the last night this problem.
I couldn't get a token for Express Checkout, so i searched and debugged this lib.

Issue #1: The response:
type=>error, message => empty
There is a problem in PayPalRequest::doPayPalRequest(). It doesn't collect the Exception.

Issue #2: Curl Configuration
In my case, the problem was occurred by a missing configuration for SSL in PayPalRequest::setClient().
So i turned off the SSL Verifing with CURLOPT_SSL_VERIFYPEER => false

Its nice, when you fix this officialy or document a solution for this problem for other confused peoples :D

Greets :)

**Comment by srmklive** [comment]
Haven't been able to replicate what you mentioned. But i have added feature to disable SSL verification by default.

**Comment by Hodel1** [comment]
My developer enviroment is: Windows, php artisan serv
No extra configuration

**Comment by egisberto** [comment]
The same occurs in the demo project:

ErrorException {#207 ▼
  #message: "Undefined index: TOKEN"
  #code: 0
  #file: "/Users/egisbertovsilva/Sites/valet/laravel-paypal-demo/vendor/srmklive/paypal/src/Services/ExpressCheckout.php"
  #line: 127
  #severity: E_NOTICE

**Comment by srmklive** [comment]
@egisberto Kindly check other issue tickets to debug issue you mentioned in your reply.
