### ISSUE TITLE
Sandbox error - SSL Handshake

### ISSUE THREAD

**Issue by egisberto** [srmklive/laravel-paypal#121]
I try to figure out what is happening because it`s work last week.

Bellow my current setup and 
return [
    'mode'    => 'sandbox', // Can only be 'sandbox' Or 'live'. If empty or invalid, 'live' will be used.
    'sandbox' => [
        'username'    => env('PAYPAL_SANDBOX_API_USERNAME', 'egisberto-facilitator_api2.gmail.com'),
        'password'    => env('PAYPAL_SANDBOX_API_PASSWORD', '[PASSWORD]'),
        'secret'      => env('PAYPAL_SANDBOX_API_SECRET', '[SECRET]'),
        'certificate' => env('PAYPAL_SANDBOX_API_CERTIFICATE', ''),
        'app_id'      => '', // Used for testing Adaptive Payments API in sandbox mode
    ],
    'live' => [
        'username'    => env('PAYPAL_LIVE_API_USERNAME', ''),
        'password'    => env('PAYPAL_LIVE_API_PASSWORD', ''),
        'secret'      => env('PAYPAL_LIVE_API_SECRET', ''),
        'certificate' => env('PAYPAL_LIVE_API_CERTIFICATE', ''),
        'app_id'      => '', // Used for Adaptive Payments API
    ],

    'payment_action' => 'Sale', // Can only be 'Sale', 'Authorization' or 'Order'
    'currency'       => 'BRL',
    'notify_url'     => '', // Change this accordingly for your application.
    'locale'         => 'pt_BR', // force gateway language  i.e. it_IT, es_ES, en_US ... (for express checkout only)
];

And the result are:

cURL error 35: SSL peer handshake failed, the server most likely requires a client certificate to connect (see http://curl.haxx.se/libcurl/c/libcurl-errors.html 

Ps: The error is get from a debug in doPayPalRequest method.

**Comment by Hodel1** [comment]
Its the same bug i reported today.
To fix it (hard) look this: #120

**Comment by srmklive** [comment]
Kindly update version in `composer.json` to `dev-master` and run `composer update`.

**Comment by srmklive** [comment]
I myself am using Windows 10, XAMPP with PHP 7.1. Haven't encountered this issue. You might update openssl to the latest stable version. This sort of issue happens when OpenSSL isn't fully updated on OS such as Windows, Linux.
