### ISSUE TITLE
client token is not getting in response

### ISSUE THREAD

**Issue by RV-8395** [srmklive/laravel-paypal#123]
Helllo, i'm facing problem in my windows server. 
 In my PaypalRequest.php file around line number 349 

return $this->client->post($this->apiUrl, [
                $this->httpBodyParam => $this->post->toArray(),
            ])->getBody();

this code is return nothing that is why i'm not getting TOKEN for paypal redirect url.

please help me with this issue.

Thanks in advance.
Regrads.

**Comment by srmklive** [comment]
Primarily the issue is with that you are not sending a proper INVOICE ID. Issue might be there.

**Comment by RV-8395** [comment]
No, sir this code is executed before invoice generate so how can i send invoice id ?

**Comment by srmklive** [comment]
Kindly refer to the README file.
