### ISSUE TITLE
Give links to docs of PayPal doc's that this lib uses

### ISSUE THREAD

**Issue by vladyslavstartsev** [srmklive/laravel-paypal#124]
It took me a while first time to find the real docs (the PayPal) of this lib, can you please give a link to them?
For example I used https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/ and others too, that will be awesome thing to have.

**Comment by srmklive** [comment]
I have the PayPal documentation links in the README
