### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by vladyslavstartsev** [srmklive/laravel-paypal#125]
What the min PHP version of the lib? Probably the min of laravel 5 (5.4). Can you place that info into composer.json. 
It will help us to prevent some bugs after update.
What I mean is - for example, I have app that users PHP 5.4 and after your update you added something that was only added in further versions of PHP (let say you used `finally`). I will update with `composer update`, and it will broke my app randomly.

**Comment by srmklive** [comment]
No need for it in my opinion. This package uses `illuminate/support` which already requires a specific PHP version. So there is no need to directly specify this in `composer.json`
