### ISSUE TITLE
Make optional fields really optional

### ISSUE THREAD

**Issue by vladyslavstartsev** [srmklive/laravel-paypal#127]
I found that when I call `setExpressCheckout` it's required to set `invoice_description` (which is `PAYMENTREQUEST_0_DESC` in the request), can you please make optional filed really optional
It's easy just change `$data['invoice_description']`  to `isset($data['invoice_description']) ? $data['invoice_description'] : null` 
Fields that I found in code that can be set to that (at least according to docs, there is more, I just put those some of them)

|  |
|--------------------------------|
| PAYMENTREQUEST_0_CURRENCYCODE  |
| PAYMENTREQUEST_0_DESC          |
| PAYMENTREQUEST_0_INVNUM        |
| LOCALECODE                     |
| L_BILLINGAGREEMENTDESCRIPTION0 |
| PAYMENTREQUEST_0_NOTIFYURL     |

**Comment by srmklive** [comment]
Hi,

On this issue, can you open up a PR to implement what you are suggesting?
