### ISSUE TITLE
declaration

### ISSUE THREAD

**Issue by soly2014** [srmklive/laravel-paypal#13]
how can i get my sandbox username , password,secret ,appid, certicate 
 for express checkout for config file
```
return [
    'mode' => 'sandbox', // Can only be 'sandbox' Or 'live'. If empty or invalid, 'live' will be used.
    'sandbox' => [
        'username' => 'solyooo398523_api1.gmail.com',
        'password' => 'LPEP4ZJNMW3UY746',
        'secret' => '',
        'certificate' => '',
        'app_id' => '',    // Used for testing Adaptive Payments API in sandbox mode
    ],
    'live' => [
        'username' => '',
        'password' => '',
        'secret' => '',
        'certificate' => '',
        'app_id' => '',         // Used for Adaptive Payments API 
    ],

```
    'payment_action' => 'Sale', // Can Only Be 'Sale', 'Authorization', 'Order'
    'currency' => 'USD',
    'notify_url' => 'http://localhost:8000/home', // Change this accordingly for your application.
];

**Comment by srmklive** [comment]
You can get your sandbox config like this:

    $sandbox = config('paypal.sandbox');

**Comment by soly2014** [comment]
no, this isn't actually what i mean. 
i mean how can i get this credentials from my PayPal account
i am really stuck here and i need quick help
sincerely, Soliman

**Comment by srmklive** [comment]
you need to create your sandbox accounts from https::/developer.paypal.com/. Once you login there, you can get your sandbox credentials by visiting this URL: https://developer.paypal.com/developer/accounts/

**Comment by soly2014** [comment]
i have already have an account. this link give me my personal and business emails
still stuck to get.username , password,secret ,appid, certificate

**Comment by srmklive** [comment]
Kindly google it yourself on how to setup paypal sandbox accounts.
