### ISSUE TITLE
Empty paypal_link

### ISSUE THREAD

**Issue by ajilmv138** [srmklive/laravel-paypal#130]
My code is 
public function getCheckout()
    {
        $provider = new ExpressCheckout;

        $data['items'] = [
        [
        'name' => 'Payment order',
        'price' => 100,
        'qty' => 1
        ],
        ];
        $data['total'] = 100;

        $data['invoice_id'] = 999;
        $data['invoice_description'] = "Order 999 Invoice";
        $data['return_url'] = url('/payment/success');
        $data['cancel_url'] = url('/cart');

        $response = $provider->setExpressCheckout($data);

        return $response['paypal_link'];
    }

While i print $response it gives ,
 Array
(
    [type] => error
    [message] => 
    [paypal_link] => 
).

The same code works well at localhost. but when i try in server paypal_link become empty. 

Please help. what is the mistake in my code. Is there any other settings needed while hosting in server.

**Comment by srmklive** [comment]
Please refer to the demo application in the README file. You may need to check whether any extensions are missing on your server.

**Comment by ajilmv138** [comment]
@srmklive  No. All extensions were installed. I had followed all the steps mentioned in your documentation. 
But paypal_link is empty. Will you please share me a tip to solve this.

**Comment by srmklive** [comment]
You may have messed up some configuration or put incorrect credentials. Kindly look into closed issues section of this repo or search forums on setting up ExpressCheckout api credentials in sandbox/live mode.

**Comment by Viliukas** [comment]
@ajilmv138 did you managed to fix it? Today I started to get this error from nowhere. For the last two months it has been successfully working in both live and local. But since this morning when I'm trying to test it locally I'm getting "error" and empty link. I compared live and local paypal code, it's absolutely identical. Do not know what happened. Huh

**Comment by karam94** [comment]
@Viliukas I'm currently experiencing this issue despite never seeing it before. Any chance you could share your composer files or at least point out what was different about the backed up versions?
