### ISSUE TITLE
Question for Configuration.

### ISSUE THREAD

**Issue by FredLopes0203** [srmklive/laravel-paypal#132]
Should I add configuration value for below?
'certificate' => env('PAYPAL_SANDBOX_API_CERTIFICATE', ''),
I don't understand which value should I add here?
And for this am I needed to add application for NVP/SOAP API apps?
Please explain me in details....
Thanks.

**Comment by srmklive** [comment]
Kindly search the closed issues for this repo or forums for setting up Express Checkout API credentials.

**Comment by srmklive** [comment]
The env variables are self explanatory. The certificate part is only used if your PayPal sandbox/live API credentials contain a certificate.
