### ISSUE TITLE
Error 10411

### ISSUE THREAD

**Issue by VilmantasSaulys** [srmklive/laravel-paypal#133]
Hello, 

I have a problem after website migration to the new domain. 
I have redirected to the PayPal in success, but after payment I have got an error like this: 
http://prntscr.com/gfgznt (Error code 10411). 

Have someone any idea where is the problem?

**Comment by vladyslavstartsev** [comment]
@VilmantasSaulys 
Probably PayPal issue, not library.

You have
```
PAYPAL_LIVE_API_USERNAME=""
PAYPAL_LIVE_API_PASSWORD=""
PAYPAL_LIVE_API_SECRET=""
```

they stick to your app and your domain, change them in PayPal settings

**Comment by srmklive** [comment]
Please check your api credentials.
