### ISSUE TITLE
How to Add Custom Variable in setExpressCheckout and get it back in IPN response

### ISSUE THREAD

**Issue by AlexBrend** [srmklive/laravel-paypal#138]
How to Add Custom Variable in setExpressCheckout and get it back in IPN response, Below is my code but not getting CustomId which i have set in options in IPN response

public function setExpressCheckout($planId,$userId)
    {
        $provider = $this->getProvider();
    
        $data = $this->getData($planId,$userId);
        
        $options = [
            'BRANDNAME' => 'MyBrand',
            'LOGOIMG' => 'https://example.com/mylogo.png',
            'CHANNELTYPE' => 'Merchant',
            'CustomId' => 'Custom_'.$planId.'_'.$userId
        ];
        
        try
        {
            $response = $provider->addOptions($options)->setExpressCheckout($data,true);
            
            //$response = $provider->setExpressCheckout($data, true);
            
            // This will redirect user to PayPal
            if (isset($response ['paypal_link']) && isset($response['ACK']) && $response['ACK'] == 'Success')
            
                return $response ['paypal_link'];
            else
                return false;
        }
        catch (\Exception $e) 
        {
            $result = Utility::jsonOutput(0,$e->getMessage());
            
            return false;
        }
    }

**Comment by srmklive** [comment]
Any parameters you provide in `addOptions` method should be available in a specific API call such as `SetExpressCheckout`

**Comment by 3gHub** [comment]
I am using this plugin. 
I added in `addOptions ` method like this:

```
 $options = [
        'USERID' => $userId,
        ];
$response = $this->provider->addOptions($options)->setExpressCheckout($cart, $recurring, $package);
```
Now I do `dd($response)` but not got `USERID ` in response, which I am sending as custom value/field.

Also Can I get it on IPN like this:

```
public function note(Request $request)
    {
        $request->merge(['cmd' => '_notify-validate']);
        $post = $request->all();

        $response = (string) $this->provider->verifyIPN($post);

        if ($response === 'VERIFIED') {

            if ($post['txn_type'] == 'recurring_payment' && $post['payment_status'] == 'Completed') {

                $transaction_id = rand(10000000,99999999);

                $userId = $post['USERID'];
}
```

Looking forward to your reply.
