### ISSUE TITLE
Add Shipping and Total Discount parameters to send to Paypal

### ISSUE THREAD

**Issue by himalaya-ahuja** [srmklive/laravel-paypal#139]
Hi , how can we add shipping cost and total discount availed by the customer , and send it to paypal so that it shows in the order details list on paypal payment confirmation page when the customer is about to make payments.

**Comment by srmklive** [comment]
Kindly refer to README file.

**Comment by himalaya-ahuja** [comment]
can't seem to find anything there..were you able to add shipping cost or discounts in your implementation.?

**Comment by srmklive** [comment]
Kindly refer to the following link:

https://github.com/srmklive/laravel-paypal/blob/master/PAYPALDOCS.md
