### ISSUE TITLE
bad error handling

### ISSUE THREAD

**Issue by escapeboy** [srmklive/laravel-paypal#14]
in PayPalRequest.php
doPayPalRequest()
```
if (!empty($response['TOKEN'])) {....
else{
// no connection
}
```
but it's also thrown "no connection" if other error happen. As in my case when total of items is different from the order total. I suppose it's for the translation.
I think better way of this will be to return the error returned by paypal. To know what really happened.

**Comment by srmklive** [comment]
I am actually working on better error reporting. Thanks for pointing it out.

**Comment by srmklive** [comment]
Added exception handling. I have also added another release for it. Kindly update to the latest release by running ```composer update```.
