### ISSUE TITLE
Change Currency

### ISSUE THREAD

**Issue by himalaya-ahuja** [srmklive/laravel-paypal#140]
When i try to change currency  as :
$response = $this->provider->setCurrency('MYR')->setExpressCheckout($cart, $recurring);

it throws error : 
![image](https://user-images.githubusercontent.com/31985973/31172642-ff2213c6-a921-11e7-8754-bfab4e80189b.png)

**Comment by srmklive** [comment]
PHP version?

**Comment by himalaya-ahuja** [comment]
5.6.30

**Comment by srmklive** [comment]
Kindly read the instructions for creating subscriptions in the README file for this repo.
