### ISSUE TITLE
Do option parameters get returned back on success?

### ISSUE THREAD

**Issue by himalaya-ahuja** [srmklive/laravel-paypal#141]
I added some option as follows:
        $options = ['order_id' => $order_id];
$response = $this->provider->setCurrency($currency_code)->addOptions($options)->setExpressCheckout($cart, $recurring);

I am not getting the option 'order_id' back on success Method.. I should be getting that parameter back right.?

**Comment by srmklive** [comment]
Please read the PayPal API documentation. Any custom parameters should be the ones PayPal allows.

**Comment by himalaya-ahuja** [comment]
simply asking regarding your implementation , where and how would you pass a custom parameter to paypal , so that paypal returns that custom parameter on success or on failure..!?

**Comment by himalaya-ahuja** [comment]
.?
