### ISSUE TITLE
Return Custom Parameters

### ISSUE THREAD

**Issue by himalaya-ahuja** [srmklive/laravel-paypal#142]
In your implementation where and how would you pass a custom parameter to paypal , so that paypal returns that custom parameter on success or on failure..
Please help  , imp.

**Comment by srmklive** [comment]
As i have said before, kindly review PayPal API documentation. Here is the file in this repo which references those links:

https://github.com/srmklive/laravel-paypal/blob/master/PAYPALDOCS.md
