### ISSUE TITLE
Missing argument (amount) in  doReferenceTransaction

### ISSUE THREAD

**Issue by aravindbhardwaj** [srmklive/laravel-paypal#143]
I was using doReferenceTransaction. It was throwing an error.
    Array
    (
        [TIMESTAMP] => 2017-10-17T07:27:09Z
        [CORRELATIONID] => e82da8143d67e
        [ACK] => Failure
        [VERSION] => 123
        [BUILD] => 39206242
        [L_ERRORCODE0] => 10413
        [L_ERRORCODE1] => 10004
        [L_SHORTMESSAGE0] => Transaction refused because of an invalid argument. See additional error messages for details.
        [L_SHORTMESSAGE1] => Invalid Data
        [L_LONGMESSAGE0] => The totals of the cart item amounts do not match order amounts.
        [L_LONGMESSAGE1] => This transaction cannot be processed.
        [L_SEVERITYCODE0] => Error
        [L_SEVERITYCODE1] => Error
    )

So I came with this solution to pass amount as the third parameter, as i have tested it and it is working fine now. There is a missing amount argument for doReferenceTransaction in
 /vendor/srmklive/paypal/src/Traits/PayPalTransactions.php

We need to pass : 
     $transaction = $billingAgreementID;
    $action = 'Authorization';
    $amount = 100;

$amount is the sum you want to deduct from payer's PayPal account for the agreement.

    public function doReferenceTransaction($transaction, $action, $amount) {
        $this->setRequestData([
            'REFERENCEID'       => $transaction,
            'PAYMENTACTION'     => $action,
            'AMT'               => $amount,
        ]);
        return $this->doPayPalRequest('DoReferenceTransaction');
    }

Please correct me if this is not the correct way of doing it.

**Comment by srmklive** [comment]
Can you open a PR so i can merge it?

**Comment by srmklive** [comment]
You can also do it the following way:

```
use Srmklive\PayPal\Services\ExpressCheckout;

$provider = new ExpressCheckout();
$response = $provider->addOptions(
    ['AMT' => $amount]
)>doReferenceTransaction($transaction, 'Sale');
```

**Comment by srmklive** [comment]
I have added the requested change

**Comment by aravindbhardwaj** [comment]
After adding $amount as the third parameter. It is working fine. Thanks

**Comment by rahim3070** [comment]
I am using Laravel 5.7, **My Data is -**

Array
(
    [items] => Array
        (
            [0] => Array
                (
                    [name] => Product 2
                    [price] => 335
                    [qty] => 1
                )

        )

    [invoice_id] => 20190218DA40D
    [invoice_description] => Test Invoice
    [return_url] => http://localhost/magic_shop/successfull-order
    [cancel_url] => http://localhost/magic_shop/un-successfull-order
    [total] => 302
    [shipping_discount] => 30
)

**My response Error is -** 

Array
(
    [TIMESTAMP] => 2019-02-18T15:55:56Z
    [CORRELATIONID] => 970212ef8c1ce
    [ACK] => Failure
    [VERSION] => 123
    [BUILD] => 51861407
    [L_ERRORCODE0] => 10413
    [L_SHORTMESSAGE0] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_LONGMESSAGE0] => The totals of the cart item amounts do not match order amounts.
    [L_SEVERITYCODE0] => Error
    [paypal_link] => 
)
