### ISSUE TITLE
error cant redirect to paypal

### ISSUE THREAD

**Issue by guitarmaor** [srmklive/laravel-paypal#149]
Hey i've uplodaded the project on air and got this laravel error:

> ErrorException (E_NOTICE)
> Use of undefined constant CURLOPT_SSLVERSION - assumed 'CURLOPT_SSLVERSION

/var/www/vendor/srmklive/paypal/src/Traits/PayPalRequest.php
>   protected function setClient()
>     {
>         return new HttpClient([
>             'curl' => [
>                 **CURLOPT_SSLVERSION     => CURL_SSLVERSION_TLSv1_2**,
>                 **CURLOPT_SSL_VERIFYPEER** => false,
>             ],
>         ]);
>     }

**Comment by Ronen-dev** [comment]
Same here.

**Comment by srmklive** [comment]
Update openssl version on your system.

**Comment by anbu369** [comment]
I've updated the openssl in ubuntu 16.04 still the same error. Any other suggestions? I've got the following version

OpenSSL 1.0.2m  2 Nov 2017

**Comment by srmklive** [comment]
Might be an issue with API credentials

**Comment by matteoerrera** [comment]
Same problem, any updates?
