### ISSUE TITLE
Adaptive 520003 Authentication failed

### ISSUE THREAD

**Issue by jorgealexandro** [srmklive/laravel-paypal#15]
When trying to do chained payment I always get this error:

<?xml_version" => "'1.0' encoding='UTF-8'?><ns3:FaultMessage xmlns:ns3="http://svcs.paypal.com/types/common" xmlns:ns2="http://svcs.paypal.com/types/ap"><responseEnvelope><timestamp>2016-06-13T18:04:28.165-07:00</timestamp><ack>Failure</ack><correlationId>002d6b3b4261a</correlationId><build>20420247</build></responseEnvelope><error><errorId>520003</errorId><domain>PLATFORM</domain><subdomain>Application</subdomain><severity>Error</severity><category>Application</category><message>Authentication failed. API credentials are incorrect.</message></error></ns3:FaultMessage>

ErrorId 520003
Message Authentication failed. API credentials are incorrect.

I double check my sandbox credentials and are correct:

        'username' => 'jorge.alexandro-facilitator_api1.gmail.com',
        'password' => '1364842417',
        'secret' => 'A8.lGiHnS.gATAUMTDDqJEv32m7eAEygtB5hcwPxiugnKJ6bio.Hl6xY',
        //'certificate' => '',
        'app_id' => 'APP-80W284485P519543T',

Same credentials works good in express checkout only adaptive is not working. Any idea or help?

**Comment by jorgealexandro** [comment]
Looks like Guzzle client is not sending properly the Paypal headers, I'll continue my debugging...

**Comment by srmklive** [comment]
@jorgealexandro Thanks for pointing the errors you are facing. I will look into it immediately.

**Comment by jorgealexandro** [comment]
At AdaptivePayments.php I changed the call from 

            $request = $this->client->post($post_url, [
                'form_params' => $post,
                'headers' => $this->setHeaders(),
            ]);

to

            $request = $this->client->request('POST', $post_url, [
                'form_params' => $post,
                'headers' => $this->setHeaders(),
            ]);

and headers part from

        $headers = [
            'X-PAYPAL-SECURITY-USERID: ' . $this->config['username'],
            'X-PAYPAL-SECURITY-PASSWORD: ' . $this->config['password'],
            'X-PAYPAL-SECURITY-SIGNATURE: ' . $this->config['secret'],
            'X-PAYPAL-REQUEST-DATA-FORMAT: NV',
            'X-PAYPAL-RESPONSE-DATA-FORMAT: NV',
            'X-PAYPAL-APPLICATION-ID: ' . $this->config['app_id'],
        ];

to

        $headers = [
            'X-PAYPAL-SECURITY-USERID' => $this->config['username'],
            'X-PAYPAL-SECURITY-PASSWORD' => $this->config['password'],
            'X-PAYPAL-SECURITY-SIGNATURE' => $this->config['secret'],
            'X-PAYPAL-REQUEST-DATA-FORMAT' => 'NV',
            'X-PAYPAL-RESPONSE-DATA-FORMAT' => 'NV',
            'X-PAYPAL-APPLICATION-ID' => $this->config['app_id'],
        ];

And now the auth is working but I'm getting another issue:

  "responseEnvelope_timestamp" => "2016-06-14T11:45:02.250-07:00"
  "responseEnvelope_ack" => "Failure"
  "responseEnvelope_correlationId" => "00d236d35bbd8"
  "responseEnvelope_build" => "20420247"
  "error(0)_errorId" => "580001"
  "error(0)_domain" => "PLATFORM"
  "error(0)_subdomain" => "Application"
  "error(0)_severity" => "Error"
  "error(0)_category" => "Application"
  "error(0)_message" => "Invalid request: {0}"

Also at this same file I think this is need it to change from:

        if (!empty($data['feesPayer']))
            $post['feesPayer'] = $data['payer'];

to

        if (empty($data['feesPayer']))
            $post['feesPayer'] = $data['payer'];

I will try to debug more later at night, wish me good luck.

**Comment by srmklive** [comment]
Working on the issues reported in this ticket.

**Comment by mapoDesigns** [comment]
Hello @jorgealexandro @srmklive 

Excellent package. Express payment working without a hitch. 

However, I have also reached the same error as jorge: "error(0)_message" => "Invalid request: {0}" for the AdaptivePayments API

Tried debugging and found in [PayPal's Adaptive API](https://developer.paypal.com/docs/classic/adaptive-payments/ht_ap-basicChainedPayment-curl-etc/) documentation reference to a

**&clientDetails.ipAddress=127.0.0.1     #Address from which request is sent** 

that seems to be missing...?

How's the debugging coming along on your end?

Thanks

**Comment by jorgealexandro** [comment]
@mapoDesigns so far I think the problem is related to guzzle library, however I'm afraid I couldn't make it work's. I'm not familiar with that library I'd tried to research about paypal adaptive payments and guzzle client and I couldn't find something solid to work with

**Comment by mapoDesigns** [comment]
@jorgealexandro 

Thanks for the lead -i'll go have a look at the guzzle library.

This function is quite crucial for my project so I've got a lot of effort vested in it.

Have you found any alternative packages to implement the Adaptive Payments API for your project?

**Comment by srmklive** [comment]
@mapoDesigns I believe you can use paypal sdk in this regard. I myself am having a look at that, as to figure out the issues.

**Comment by srmklive** [comment]
@mapoDesigns @jorgealexandro I have temporarily removed Adaptive payments implementation in the new tagged release.  Will have it reinstated when the issues reported have been fixed.

If you both are able to fix it, can you generate a PR as well?

**Comment by mapoDesigns** [comment]
@srmklive Thanks for the update. I'll certainly update/generate a PR if I ever figure it out

**Comment by srmklive** [comment]
@mapoDesigns I have solved this issue. First issue was i had the **config.php** file configurations in wrong order :D. I corrected it, but still it wasn't resolved. 

I had to utilize the adaptive payments sdk to get it working. The **Pay** API call is fixed, so it always returns the **payKey** value from paypal. The remaining include refactoring of **SetPaymentOptions** & **GetPaymentOptions** API implementations and adding the remaining API features.

**Comment by srmklive** [comment]
@mapoDesigns I have tagged a new release. Kindly update to v1.2.2 by running ````composer update````

**Comment by jorgealexandro** [comment]
Hello guys,

So removing guzzle and adding Paypal SDK brings the solution, it cross my mind but I was not sure about that was in line on this project. nevermind is good to know is working now.

**Comment by srmklive** [comment]
@jorgealexandro @mapoDesigns i have fixed the issue with guzzle. Previously the adaptive payments API call would be like this:

    $request = $this->client->post($post_url, [
        'form_params' => $post,
        'headers' => $this->setHeaders(),
    ]);

I had to change it to the following to remove "Invalid Request error"


    $request = $this->client->post($post_url, [
        'json' => $post,
        'headers' => $this->setHeaders(),
    ]);

I had to also change the following header values from ```NV``` to ```JSON```:

    'X-PAYPAL-REQUEST-DATA-FORMAT' => 'JSON',
    'X-PAYPAL-RESPONSE-DATA-FORMAT' => 'JSON',

**Comment by mapoDesigns** [comment]
@srmklive Awesome! Just updated the package and works like a charm!

Thank YOU!
