### ISSUE TITLE
"custom" parameter

### ISSUE THREAD

**Issue by IvanDanilov** [srmklive/laravel-paypal#150]
Hey i do not understand how to pass a "custom" parameter?

The code added a "custom" parameter:

> [...]
    $data['custom'] = "12345";
    [...]
    $response = $this->gateway->createPayRequest($data);

I receive in response ("custom" parameter is empty):
> Array
    (
        [transaction_subject] => 
        [txn_type] => web_accept
        [payment_date] => 17:15:29 Nov 14, 2017 PST
        [last_name] => buyer
        [residence_country] => US
        [item_name] => 
        [payment_gross] => 0.50
        [mc_currency] => USD
        [business] => kek-facilitator@gmail.com
        [payment_type] => instant
        [protection_eligibility] => Ineligible
        [verify_sign] => AVkS-tHU2h7x-Z4geedc48Ls6tx5AL7T2k3mU42hvwIHyYy2gZJsKI9x
        [payer_status] => verified
        [test_ipn] => 1
        [tax] => 0.00
        [payer_email] => kek-buyer@gmail.com
        [txn_id] => 1X458576Y30075809
        [quantity] => 0
        [receiver_email] => kek-facilitator@gmail.com
        [first_name] => test
        [payer_id] => YZTALJQKECQ9C
        [receiver_id] => LHSY3385FB6KJ
        [item_number] => 
        [payment_status] => Completed
        [mc_gross] => 0.50
        [custom] => 
        [charset] => UTF-8
        [notify_version] => 3.8
        [ipn_track_id] => 916db89c72175
        [cmd] => _notify-validate
    )

**Comment by srmklive** [comment]
Custom parameters are specific to an API call. Refer to the README file for details & documentation links
