### ISSUE TITLE
dynamic data

### ISSUE THREAD

**Issue by venkatavinash** [srmklive/laravel-paypal#151]
I have understood the flow and paypal works fine for data array which has static data.

When I pass custom data items array to getCheckoutData as second argument it will work first time.
But again the $cart is being rebuilt in function getExpressCheckoutSuccess
$cart = $this->getCheckoutData($recurring);

In the above I can not pass second argument as the there is no data from paypal.Paypal only response is payerID and token.

How can persist the dynamic cart? 

Any help would be extremely helpful. Thank you or your time and effort in building this library.

**Comment by srmklive** [comment]
Sounds like you are creating a recurring profile. Refer to the demo application repo I have linked in the README
