### ISSUE TITLE
how to get success response after redirect to payment/success

### ISSUE THREAD

**Issue by bhattaxay** [srmklive/laravel-paypal#153]
Hello,

I have follow this plugin and integrate it in my project but i do not get any response after successful transaction. How should i get it? For example i need Transaction status as either PENDING, FAILED or SUCCESS. 

What kind of parameters i will get on this and how?
'return_url' => url('payment/success'), 
'cancel_url' => url('payment/cancel'),

You have mentioned only you will get 
 'responseEnvelope.ack', 'payKey', 'paymentExecStatus' but i did not require this.

**Comment by srmklive** [comment]
Are you using Adaptive Payments?

**Comment by srmklive** [comment]
You need to refer to the Adaptive Payments API documentation. Links are provided in the README file.
