### ISSUE TITLE
guest payment

### ISSUE THREAD

**Issue by tedinpcshool** [srmklive/laravel-paypal#154]
Excuse me, Could this package support guest payment in Paypal?
Buyers Can Checkout Without a PayPal Account.

We enable the PayPal Account Optional option in our account settings, but still can't do guest payment.

Not sure if there is a setting missed or Paypal policy, though we are using Taiwan Business account.

Any suggestions or hints are appreciated.

Thanks a lot.

**Comment by srmklive** [comment]
If you have enabled PayPal optional in your account settings, then you need to do the following:

```
$options = [
    'SOLUTIONTYPE' => 'Sole',
];

$response = $provider->addOptions($options)->setExpressCheckout($data);
```

**Comment by tedinpcshool** [comment]
Thanks a lot.   It works.

And there is another question.

Is it possible to do guest payment in recurring payment ??

I tried to add the same code as doing recurring payment, but it seems not work.

I'm not sure if recurring payment can checkout without a PayPal Account.

Thanks for you help again.

**Comment by pakogn** [comment]
Hi!,

I'm facing kind of simmilar issue. Could you please @tedinpcshool explain me what policy o option do I have to enable in my account so I can use this option? 

I'm also using other options like:

```
$options = [
            'BRANDNAME' => trans('company.name'),
            'LOGOIMG' => asset('assets/images/logo-small.png'),
            'EMAIL' => currentUser()->email,
            'SOLUTIONTYPE' => 'Sole',
        ];
```
but still no success.


many thanks!

**Comment by TEDinTW** [comment]
Hi,
you can check this link
https://www.paypal.com/businessprofile/mytools

and see the page of "Website preferences". 

At the page, you can find something like "PayPal Account Optional".

check if it works after turn on the feature.

Good luck!

"Following is the description from Paypal"
When this feature is turned on, your customers will go through an optimized checkout experience. This feature is available for Buy Now and Shopping Cart buttons, but not for Subscription buttons.

**Comment by pakogn** [comment]
Yes, I have already done this but with no success.

Is there other another point to consider?

**Comment by TEDinTW** [comment]
Hi,
Did you do the following?
$response = $provider->addOptions($options)->setExpressCheckout($data);

**Comment by pakogn** [comment]
Yes,

but it redirects me to the paypal checkout page to login or register. ):

**Comment by TEDinTW** [comment]
What is your Account type?

It seems to be Business to make it work.

**Comment by pakogn** [comment]
Yes, it's a business account because I can receive payments with no problems, but only with registered users. Maybe I should contact paypal support.

thanks!

**Comment by rawscripter** [comment]
Hey. I was also facing same issue. I turn on "Paypal Account Optional" and also added the  'SOLUTIONTYPE' => 'Sole', but it wasn't working. then i found this solution :) and its working 

$options = [
            'SOLUTIONTYPE' => 'Sole',
            'LANDINGPAGE' => 'Billing',
            'USERSELECTEDFUNDINGSOURCE' => 'CreditCard',
        ];

**Comment by aliraza93** [comment]
> Hey. I was also facing same issue. I turn on "Paypal Account Optional" and also added the 'SOLUTIONTYPE' => 'Sole', but it wasn't working. then i found this solution :) and its working
> 
> $options = [
> 'SOLUTIONTYPE' => 'Sole',
> 'LANDINGPAGE' => 'Billing',
> 'USERSELECTEDFUNDINGSOURCE' => 'CreditCard',
> ];

Can you please tell me where can I add these options ?

**Comment by alirezaporthos** [comment]
> Yes, I have already done this but with no success.
> 
> Is there other another point to consider?

are you using sandbox? if so you should change it to live.

**Comment by raymondTheDev** [comment]
So does the guest checkout only work for live accounts?

For reference, here's a screenshot of my checkout page with the parameter  'SOLUTIONTYPE' => 'Sole',
![image](https://user-images.githubusercontent.com/10400150/115326141-63325300-a1bf-11eb-810c-809849b88049.png)

As you can see even though it does allow for a card to be used, it also requires the user to register for a PayPal account.

**Comment by rawscripter** [comment]
Add these params to make it work

$options = [
'SOLUTIONTYPE' => 'Sole',
'LANDINGPAGE' => 'Billing',
'USERSELECTEDFUNDINGSOURCE' => 'CreditCard',
];

**Comment by raymondTheDev** [comment]
Yep, it's coded like this at the moment and same results. It still required the user to register for a PayPal account.

  $provider = new ExpressCheckout;
        $options = [
            'SOLUTIONTYPE' => 'Sole',
            'LANDINGPAGE' => 'Billing',
            'USERSELECTEDFUNDINGSOURCE' => 'CreditCard',
        ];
      $response = $provider->addOptions($options)->setExpressCheckout($data, false);

**Comment by sohil123123** [comment]
Is it possible to do guest payment in recurring payment ??

If 'Yes' than How?
