### ISSUE TITLE
Which API Credentials to use

### ISSUE THREAD

**Issue by jcsoriano** [srmklive/laravel-paypal#155]
Hi, 

First of all, thank you so much for this package, it's really awesome.

### To my issue:

I'm confused which API credentials to use when going Live. While the Sandbox accounts work fine, I'm confused where to get the Live credentials. In the "My Apps & Credentials" tab of Paypal Developer (https://developer.paypal.com/developer/applications/) I get **2** choices (more actually, but I know we're not using Braintree SDK) :

## 1. REST API:
![image](https://user-images.githubusercontent.com/5937317/33290099-9d4635aa-d3fc-11e7-8e5c-dfe9091d1963.png)

## 2. NVP/SOAP API:
![image](https://user-images.githubusercontent.com/5937317/33290119-abc1a452-d3fc-11e7-87c8-0d1b0c561d7f.png)

### The problem with REST API
The problem with the REST API credentials is they don't perfectly map. Ie, our .env needs:
PAYPAL_LIVE_API_USERNAME=
PAYPAL_LIVE_API_PASSWORD=
PAYPAL_LIVE_API_SECRET=

But REST API live credentials provide the ff.:
Sandbox Account
Client ID
Secret

### The problem with NVP/SOAP API
The problem with the NVP/SOAP API is that it says it's deprecated and it will no longer be available starting December 1 (a few days later, as of this posting)
![image](https://user-images.githubusercontent.com/5937317/33290262-1e4b0e28-d3fd-11e7-95d3-e1ec72a39251.png)

It is for these reasons, along with unclear documentation in Paypal's site, that I'm confused where to get the Live credentials.

From previous issues of this nature I read that you advised the OP to "read the Paypal docs" on how to get the Live credentials but the docs are really difficult to wrestle with, there are different API credentials to choose from (including that of Braintree SDK), and I don't know which one applies to this Laravel package.

If it's the NVP/SOAP one, how should we move forward starting after December 1?

Your help would be greatly appreciated. Thank you again for writing this package!

**Comment by srmklive** [comment]
You should generate Live API credentials by logging into your PayPal account. This link should give you all the details in this regard:

https://developer.paypal.com/docs/classic/api/apiCredentials/

**Comment by MisterBrownRSA** [comment]
This is what I was referring to earlier. @jcsoriano did you come right, because I'm sitting in the same predicament. I cannnot find the details that is expected...
