### ISSUE TITLE
Payment failed

### ISSUE THREAD

**Issue by falconxxx** [srmklive/laravel-paypal#156]
I followed the docs and all went well except when i wanted to try the payment for the first time

`
"TIMESTAMP": "2017-11-28T01:59:54Z",
"CORRELATIONID": "81c0d974794a2",
"ACK": "Failure",
"VERSION": "123",
"BUILD": "40680762",
"L_ERRORCODE0": "10002",
"L_SHORTMESSAGE0": "Security error",
"L_LONGMESSAGE0": "Security header is not valid",
"L_SEVERITYCODE0": "Error",
"paypal_link": null
`

**Comment by srmklive** [comment]
Try passing a unique invoice id like this`FALCONXXX_PAYPAL_INVOICEID`, where `INVOICEID` represents the order no you create in your application.

**Comment by tedinpcshool** [comment]
I got this error before.

May you use live Credentials in sandbox mode?

If you are using in live mode, you can choose API signature or API certificate.

I suggest you can choose API signature first.

then back to .env file.

PAYPAL_LIVE_API_USERNAME="something"
PAYPAL_LIVE_API_PASSWORD="something"
PAYPAL_LIVE_API_SECRET="something"
PAYPAL_LIVE_API_CERTIFICATE=

leave certificate to blank, test it if it work.
