### ISSUE TITLE
guest payment in recurring payment? (Recurring payment without a Paypal account)

### ISSUE THREAD

**Issue by tedinpcshool** [srmklive/laravel-paypal#157]
Excuse me, 
I can do guest payment by adding the options.
```
$options = [
    'SOLUTIONTYPE' => 'Sole',
];

$response = $provider->addOptions($options)->setExpressCheckout($data);
```
But it seems can't do guest payment in recurring payment with the same action?

I found it seems related to Enhanced Recurring Payments (ERP)?

Any suggestions or hints are appreciated.

Thanks a lot.

**Comment by srmklive** [comment]
Try the same when creating a recurring payment profile. Refer to README file for this.

**Comment by tedinpcshool** [comment]
Yes, I can follow the README file to do a recurring payment.
But It needs to login to Paypal account to do recurring payment.
Not sure if it is related to we don't have Enhanced Recurring Payments(ERP), Or we missed something in programming.

In setExpressCheckout section
```
$options = [
            'SOLUTIONTYPE' => 'Sole',
        ];
        $response = $this->provider->addOptions($options)->setExpressCheckout($this->cart, $recurring);
```


In the callback_success section :

`$response = $this->provider->addOptions($options)->createRecurringPaymentsProfile($cart_data['data'], $token);`
