### ISSUE TITLE
Doubt Recurring payment

### ISSUE THREAD

**Issue by gabohm** [srmklive/laravel-paypal#158]
Hi, If I create the Recurring payment profile:
$response = $provider->createRecurringPaymentsProfile($data, $token);
And then I do the Express Checkout Paymet:
$response = $provider->getExpressCheckoutDetails($token);
$response = $provider->doExpressCheckoutPayment($data, $token, $PayerID);

Is the charge made 2 times?

Thanks.

**Comment by srmklive** [comment]
Refer to the README file. I have listed the steps for creating a recurring payment profile.
