### ISSUE TITLE
Can I use this without Laravel?

### ISSUE THREAD

**Issue by dam-man** [srmklive/laravel-paypal#161]
Hi,

You package looks great, but the big question for me is if this library can be used without Laravel?

Regards,
Robert

**Comment by srmklive** [comment]
Yes you can use it without Laravel.

**Comment by dam-man** [comment]
And is there a small description for it?

**Comment by dam-man** [comment]
As it is not completely clear how to use it without Laravel as it is now based on laravel.

**Comment by srmklive** [comment]
You can use it in any PHP application. Refer to the README file for instructions. A working example will be:

```
use Srmklive\PayPal\Providers\ExpressCheckout;

$provider = new ExpressCheckout();
$provider->setApiCredentials($credentials);

```
