### ISSUE TITLE
IPN not VERIFIED via ExpressCheckout verifyIPN

### ISSUE THREAD

**Issue by awwit** [srmklive/laravel-paypal#163]
Hi.

For some reason, the notification does not pass verification if it is carried out through the library function: verifyIPN(...)

Code:

```php
public function __construct() {
  $this->provider = new ExpressCheckout;
}

protected function verifyIpn(array $post) {
  $data = ['cmd' => '_notify-validate'];

  foreach ($post as $key => $value) {
    $data[$key] = $value;
  }

  $response = strval(
    $this->provider->verifyIPN($data)
  );

  $result = '';

  if ($response === 'VERIFIED') {
    $result = $this->process($post);
  }
}

public function store(Request $request) {
  return $this->verifyIpn($request->all());
}
```

Every times `$response` gives me a **INVALID** status.
(I use sandbox account. `config/paypal.php` by default)

But, if I change the code to this:

```php
protected function verifyIpn(array $post) {
  $data = 'cmd=_notify-validate';

  foreach($post as $key => $value) {
    $value = urlencode($value);
    $data .= "&{$key}={$value}";
  }

  $ch = curl_init('https://www.sandbox.paypal.com/cgi-bin/webscr');
  curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1);
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
  curl_setopt($ch, CURLOPT_FORBID_REUSE, 1);
  curl_setopt($ch, CURLOPT_HTTPHEADER, array('Connection: Close'));
  $response = curl_exec($ch);
  curl_close($ch);

  $result = '';

  if ($response === 'VERIFIED') {
    $result = $this->process($post);
  }
}
```

I get the status **VERIFIED**

I'm using:
PHP 7.1.7
Laravel 5.5

Your library:
srmklive/paypal 1.5.7

And dependicies:
guzzlehttp/guzzle 6.3.0
nesbot/carbon 1.22.1

What could be the problem?
I lost the time, faced with this problem.

**Comment by srmklive** [comment]
Refer to the code [here](https://github.com/srmklive/laravel-paypal-demo). It should give you clues on what you are doing wrong.

**Comment by vstruhar** [comment]
I just wanted to leave a comment on the issue that I had with an INVALID response when verifying with IPN.

The issue was that I had an empty string coming from PayPal and from Laravel 5.4 by default there is a middleware that's applied to all routes called `ConvertEmptyStringsToNull`. What this did was changed `"custom": "",` to `"custom": null` which didn't match with the payload that PayPal has sent.

You can find it in the `app/Http/Kernel.php` file `$middleware` array property.

Hope this helps somebody :)

**Comment by bearcy** [comment]
@vstruhar Oh man, you saved my day! Thanks for leaving this comment, I had exactly the same problem.

**Comment by SpookyDae** [comment]
@vstruhar Same problem occurring on Laravel 5.8. Thank you for your answer!
So how can I disable the middleware ConvertEmptyStringsToNull only on the notify method?

**Comment by ZBrettonYe** [comment]
@SpookyDae  At this before `$post = $request->all();` 
``` php 
foreach($request->input() as $key => $value){
    if($value == null){
        $request->request->set($key, '');
    }
}
```

This function will convert null to empty strings.
