### ISSUE TITLE
checkout response

### ISSUE THREAD

**Issue by zaheris** [srmklive/laravel-paypal#164]
Hello,

I'm using setExpressCheckout Method for the checkout, but when i add the email and password the response i got is the same if the account i add have money or no.
I tested the payment with two different emails, one empty and other one that have money.
On the callback url i'm using getExpressCheckoutDetails method but i'm getting same array response.
How should i know if payment was made successfully or no if i got same response?

Thank you in advance.

**Comment by srmklive** [comment]
You might be missing some parameters as to why you are not getting right response. Might be due to a duplicated invoice id etc. Refer to the demo application i have listed in the README file.

**Comment by zaheris** [comment]
The Invoice id is generated each time so it's not possible to be the same.
Find below the array we are sending

Array
(
    [items] => Array
        (
            [0] => Array
                (
                    [name] => 10000099913198
                    [price] => 104.46
                    [qty] => 1
                )
        )
    [invoice_id] => 10000099913198
    [invoice_description] => Order #10000099913198 Invoice
    [return_url] => http://payments.ilimitsinvest.com/payments/success
    [cancel_url] => http://payments.ilimitsinvest.com/payments
    [total] => 104.46
)

And Response we are getting is the same if the account have the requested amount or no:

Array
(
    [TOKEN] => EC-11L89761WS627741F
   [BILLINGAGREEMENTACCEPTEDSTATUS] => 1
   [CHECKOUTSTATUS] => PaymentActionNotInitiated
   [TIMESTAMP] => 2017-12-11T12:54:23Z
   [CORRELATIONID] => 4b04165e9dfe6
   [ACK] => Success
   [VERSION] => 123
   [BUILD] => 40680762
   [EMAIL] => demo@ilimitsinvest.com
   [PAYERID] => FGSRY8JAGHK2W
   [PAYERSTATUS] => verified
   [FIRSTNAME] => ILIMITS
   [LASTNAME] => INVEST
   [COUNTRYCODE] => NZ
   [CURRENCYCODE] => USD
   [AMT] => 104.46
   [ITEMAMT] => 104.46
   [SHIPPINGAMT] => 0.00
   [HANDLINGAMT] => 0.00
   [TAXAMT] => 0.00
   [DESC] => Order #10000099913198 Invoice
   [INVNUM] => 10000099913198 
   [INSURANCEAMT] => 0.00
   [SHIPDISCAMT] => 0.00
   [L_NAME0] => 10000099913198 
   [L_QTY0] => 1
   [L_TAXAMT0] => 0.00
   [L_AMT0] => 104.46
   [L_ITEMWEIGHTVALUE0] => 0.00000
   [L_ITEMLENGTHVALUE0] => 0.00000
   [L_ITEMWIDTHVALUE0] => 0.00000
   [L_ITEMHEIGHTVALUE0] => 0.00000
   [PAYMENTREQUEST_0_CURRENCYCODE] => USD
   [PAYMENTREQUEST_0_AMT] => 104.46
   [PAYMENTREQUEST_0_ITEMAMT] => 104.46
   [PAYMENTREQUEST_0_SHIPPINGAMT] => 0.00
   [PAYMENTREQUEST_0_HANDLINGAMT] => 0.00
   [PAYMENTREQUEST_0_TAXAMT] => 0.00
   [PAYMENTREQUEST_0_DESC] => Order #10000099913198 Invoice
   [PAYMENTREQUEST_0_INVNUM] => 10000099913198 
   [PAYMENTREQUEST_0_INSURANCEAMT] => 0.00
   [PAYMENTREQUEST_0_SHIPDISCAMT] => 0.00
   [PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED] => false
   [PAYMENTREQUEST_0_ADDRESSNORMALIZATIONSTATUS] => None
   [L_PAYMENTREQUEST_0_NAME0] => 10000099913198 
   [L_PAYMENTREQUEST_0_QTY0] => 1
   [L_PAYMENTREQUEST_0_TAXAMT0] => 0.00
   [L_PAYMENTREQUEST_0_AMT0] => 104.46
   [L_PAYMENTREQUEST_0_ITEMWEIGHTVALUE0] => 0.00000
   [L_PAYMENTREQUEST_0_ITEMLENGTHVALUE0] => 0.00000
   [L_PAYMENTREQUEST_0_ITEMWIDTHVALUE0] => 0.00000
   [L_PAYMENTREQUEST_0_ITEMHEIGHTVALUE0] => 0.00000
   [PAYMENTREQUESTINFO_0_ERRORCODE] => 0
)
