### ISSUE TITLE
Better Example?

### ISSUE THREAD

**Issue by MisterBrownRSA** [srmklive/laravel-paypal#166]
Hello,

I'm currently trying to use your package. I haven't worked with PayPal express checkout before, and don't know what information they're looking for, or where to look for the information they're looking for.

Thus, I think it would be a good idea to create a more completed example which either includes links to the place you mentioned, or provides a more complete example in the readme in order to get my first response.

Take it or leave it :)

**Comment by srmklive** [comment]
I have created a demo application which implements this package. You can find the link in the README.

**Comment by srmklive** [comment]
Here is the link to demo application:

https://github.com/srmklive/laravel-paypal-demo

**Comment by MisterBrownRSA** [comment]
Thanks for the fast response. I'm currently going through the code, however I have no idea where to get the sandbox/live username, password or secret api key.

Do you perhaps have a link for this as well ?

**Comment by MisterBrownRSA** [comment]
@srmklive you closed this issue, but going back in history - I'm not the only person who has asked for better guidelines on how to use your package. I think this package would benefit from making it easier for the user to follow instructions, if the instructions are more clear.

Don't you agree ?

**Comment by srmklive** [comment]
The configuration itself is self explanatory. If the configuration lists PAYPAL_SANDBOX then use the sandbox API credentials otherwise use the live API credentials. There is nothing else you need to do.

**Comment by srmklive** [comment]
Furthermore since PayPal has deprecated this method it hasn't been phased out.

I am working on the latest implementation of the checkout sdk for PayPal in this package and I am hoping to release it soon

**Comment by MisterBrownRSA** [comment]
@srmklive I understand that the configuration is self explanatory. But as the other guy (who wonderfully posted a bunch of photo's) also stated, when I register as a PayPal developer, I don't get a SANDBOX_API_USERNAME and SANDBOX_API_PASSWORD, I'm given a client ID and a secret key.

It makes it very difficult for a first time user of the PayPal SDK and first time user of laravel-paypal package to correctly identify where to get the correct credentials to use in this package.

Anyways, thanks for the fast responses, and I'll be glad to see the new release of this package.

Kind Regards,

**Comment by srmklive** [comment]
Look the Sandbox or Live API credentials this package refers are ones created by logging into the sandbox/live paypal accounts. Refer to this link:

https://developer.paypal.com/docs/classic/api/apiCredentials/#create-an-api-signature

**Comment by MisterBrownRSA** [comment]
That does it. Thanks you!

**Comment by leiiinad** [comment]
How to use signature instead certificate?

**Comment by MisterBrownRSA** [comment]
Hello, I don’t know what you’re talking about ?

**Comment by osamamoinchawla** [comment]
@MisterBrownRSA
@danieljausovec
@srmklive 

Hello guys, did you all solve the issue? I have place real api live credentials (username, pwd and signature) but what about the certificate, can we implement payment proceed without certificate!!!!!
