### ISSUE TITLE
How to set shipping fees and tax

### ISSUE THREAD

**Issue by blu94** [srmklive/laravel-paypal#169]
How do i set shipping method, shipping fees and tax amount into express checkout??

`$data = [];
        $data['items'] = [
            [
                'name' => 'Product 1',
                'price' => 9.99,
                'qty' => 1
            ],
            [
                'name' => 'Product 2',
                'price' => 4.99,
                'qty' => 2
            ]
        ];

        $data['invoice_id'] = 1;
        $data['shipping_method'] = "test";
        $data['shipping_total'] = [
          'value' => 12
        ];
        $data['invoice_description'] = "Order #1 Invoice";
        $data['return_url'] = url('/payment/success');
        $data['cancel_url'] = url('/cart');`

here is my code, but it is not working...

**Comment by srmklive** [comment]
Please refer to PayPal documentation. Links are provided in the README file.

**Comment by blu94** [comment]
Impossible to add those record in to the express checkout, try many time without a result, please show me some example or usefull documentation

**Comment by srmklive** [comment]
I alluded to [this](https://github.com/srmklive/laravel-paypal/blob/master/PAYPALDOCS.md) link in my previous comment.
