### ISSUE TITLE
live problem

### ISSUE THREAD

**Issue by andream1977** [srmklive/laravel-paypal#173]
hi
i use your plugin and in sandbox mode it works ! 
it does not work in the live version
i have a live paypal vendor account, and i take the credentials:
https://gyazo.com/624f01da8917a209f03129e8312abb38
i write them into config file:
https://gyazo.com/f91fb8aa1f38456cecba4abfaca0d7b4
I downloaded the certificate file cert_key_pem.txt and saved it inside the dir storage
https://gyazo.com/eadc71738e05a7d11ac77809f1d760b6

when i try to use, i get this error:
https://gyazo.com/ea61a5d987e20b472aced82ea7b685f7

array:10 [▼
  "TIMESTAMP" => "2018-01-12T18:57:40Z"
  "CORRELATIONID" => "d05942697ae1"
  "ACK" => "Failure"
  "VERSION" => "123"
  "BUILD" => "40680762"
  "L_ERRORCODE0" => "10002"
  "L_SHORTMESSAGE0" => "Security error"
  "L_LONGMESSAGE0" => "Security header is not valid"
  "L_SEVERITYCODE0" => "Error"
  "paypal_link" => null
]

can you help me?

**Comment by srmklive** [comment]
You need to send contents of the certificate file to paypal. Refer to the README file for details.

**Comment by andream1977** [comment]
hi, i send contents of the certificate file with the paypal.php config:

    'live' => [
        'username'    => env('PAYPAL_LIVE_API_USERNAME', 'andrea.manneschi_api1.gmail.com'),
        'password'    => env('PAYPAL_LIVE_API_PASSWORD', 'Q8RPWY47V9MWWRM2'),
        'secret'      => env('PAYPAL_LIVE_API_SECRET', '34DCEAD86C27CB284290CEEB14E788F0'),
        'certificate' => env('PAYPAL_LIVE_API_CERTIFICATE', storage_path('cert_key_pem.txt')),
        'app_id'      => ''
    ],

there are no other settings in the readme file, can you help me?

**Comment by TakiDDine** [comment]
did you found the solution for this
