### ISSUE TITLE
Which function I need to use to set Recurring payments status : Pending Cancellation

### ISSUE THREAD

**Issue by chiragrc71** [srmklive/laravel-paypal#174]
Hello
Can you please provide a suggestion Which function I need to use to set Recurring payments status: Pending Cancellation

**Comment by srmklive** [comment]
Refer to the README for this.

**Comment by chiragrc71** [comment]
I already read your README. But in that, there is nothing mentioned about pending-cancel.
I am taking about pending-cancel status not cancel status

In your README one section like *ManageRecurringPaymentsProfileStatus* in that you mentioned about
1) Cancel recurring payment profile
2) Suspend recurring payment profile
3) Reactivate recurring payment profile

What I need is that If user cancels the subscription then we need to set their status pending-cancel and after their billing period end I need to set their status cancel
So for Ex: User A paid a subscription for month  01-01-2018 to 31-01-2018
And In between this month user cancel the subscription For Ex: 17-01-2018
Then I need to allow that user to use subscription benefits up to 31-01-2018 because he paid for this month

If I use your function *$response = $provider->cancelRecurringPaymentsProfile($profileid);*
Then it cancel the subscription immediatley.

Normally all the payment gateway provides this type of facility.
So Can you please explain this

**Comment by chiragsenjaliya** [comment]
@chiragrc71  can you tell me if you have done that with this package?
