### ISSUE TITLE
what is certificate in config? 

### ISSUE THREAD

**Issue by v1shky** [srmklive/laravel-paypal#18]
Does it means ssl certificate form here: http://bit.ly/292cxw7 or anything else ?

**Comment by srmklive** [comment]
Its actually the paypal api certificate path ...

**Comment by novakben** [comment]
v1shky did you make it work? can you provide an example of the path you've put? I'm struggling with this :/

**Comment by v1shky** [comment]
@novakben  Here is what i did to make it work

1. Saved this file at storage path i.e. : storage/cert_key_pem.txt
2. In config i did something like this:
`'mode' => 'sandbox', // Can only be 'sandbox' Or 'live'. If empty or invalid, 'live' will be used.
    'sandbox' => [
        'username' => env('PAYPAL_LIVE_API_USERNAME', 'mail-facilitator_api1.xyz.com'),
        'password' => env('PAYPAL_LIVE_API_PASSWORD', 'NY8G9Q268X######'),
        'secret' => env('PAYPAL_LIVE_API_SECRET', 'An5ns1Kso7MWUdW4ErQKJJJ4qi4-AQrsFvozf3Me0klfMNLlvJ######'),
        'certificate' => env('PAYPAL_LIVE_API_CERTIFICATE',storage_path('cert_key_pem.txt')),
        'app_id' => 'APP-80W284485P5######',   
    ]`

**Comment by novakben** [comment]
Thanks @v1shky !

**Comment by novakben** [comment]
@v1shky @srmklive Problem was, that the secret field is actually the signature field. Not secret.
