### ISSUE TITLE
Authorization::get() not accessible

### ISSUE THREAD

**Issue by grcasanova** [srmklive/laravel-paypal#182]
Hi,
it seems your package doesn't support
`Authorization::get($authorizationId, $apiContext)`

Is it accessible through Paypalpayment trait?
Thank you

**Comment by srmklive** [comment]
Can you further explain your question?

**Comment by grcasanova** [comment]
Hi, sorry I missed the notification.

Here is an example on how to capture a previously authorised transaction with PayPal.
However, the Authorization::get() trait is missing, maybe it is named differently.
```
$apiContext = Paypalpayment::apiContext();
                
// Retrieve the authorization
$authorization = Authorization::get($authorizationId, $apiContext); //< Error
$amt = Paypalpayment::amount();
$amt->setCurrency("EUR")->setTotal($price_normalized);
// Capture
$capture = Paypalpayment::capture();
$capture->setAmount($amt);
// Perform a capture
$getCapture = $authorization->capture($capture, $apiContext);
```
