### ISSUE TITLE
How to pass custom data to adaptive

### ISSUE THREAD

**Issue by jaymehtavaluecoders** [srmklive/laravel-paypal#183]
This is not a issue but , how do i post additional data on adaptive payment . I tried to add a custom field but it does not rerturn in the IPN data that is sent by paypal .

$data = [
    'receivers'  => ['
    'return_url' => url('payment/success'), 
    'cancel_url' => url('payment/cancel'),
    'custom' => 'my custom field'
];

Any Help ?

**Comment by srmklive** [comment]
This package doesn't fully support Adaptive Payments API. It primarily supports Express Checkout.

Primarily you should add custom options just like they should be added to an API call.

**Comment by cyberkishor** [comment]
@srmklive, How can I pass custom data to Express Checkout. 

I have created a new issue for this [Express Checkout Custome Data ](https://github.com/srmklive/laravel-paypal/issues/190)
