### ISSUE TITLE
Digital Goods

### ISSUE THREAD

**Issue by adrianoGaspar** [srmklive/laravel-paypal#185]
Hello, thank you very much for the work, you are really saving my life. I have a question about Digital Goods. On the paypal site I found the following guideline:
"Digital Goods and recurring payments
As mentioned earlier, there are cases where the product is not tangible, such as signing in a content portal, where when signing, the customer is entitled to the content offered by the portal. Whenever we are selling intangible products, that is, those products that will be consumed digitally, without the delivery or negotiation of a physical product, we can do the integration informing that it is a Digital Good, or digital product, allowing the negotiation will benefit from special rates for this type of product.

The definition of a digital product for recurring payments follows the same rules and format as a regular transaction using Express Checkout. Below are the fields that identify a digital or physical product:

L_PAYMENTREQUEST_m_ITEMCATEGORYn - Informs the product category, it can be Digital, for a digital product, or Physical, for a tangible product.
L_PAYMENTREQUEST_m_NAMEn - Informs the name of the product.
L_PAYMENTREQUEST_m_AMTn - Informs the value of the product.
L_PAYMENTREQUEST_m_QTYn - Informs the quantity of the product.
"
Digital products have lower rates and I understand that they should be identified. Does this feature exist in this package? How to configure it?

I do not speak English so I'm sorry for grammar errors.

Again thank you very much for everything.

**Comment by srmklive** [comment]
You need to provide additional parameters before performing a specific API call. Kindly read this [link](https://github.com/srmklive/laravel-paypal#usage-paypal-params).
