### ISSUE TITLE
Paypal responser return type error

### ISSUE THREAD

**Issue by batenko1** [srmklive/laravel-paypal#186]
array:3 [▼
  "type" => "error"
  "message" => ""
  "paypal_link" => null
]

Paypal return. I can not understand what the problem is

**Comment by srmklive** [comment]
Duplicate of #100, #101, #102 & #149

**Comment by himalaya-ahuja** [comment]
It was working fine on local before , but not working on local anymore still working good on server , what could be the issue .? Credentials are fine for sandbox working on test server.
