### ISSUE TITLE
security issue?

### ISSUE THREAD

**Issue by ndar0430** [srmklive/laravel-paypal#193]
i can spam this and create a lot of invoice and items.

((LINK.com))/paypal/ec-checkout-success?token=EC-9KU028578S3572745&PayerID=TZDHNBXHA2R6L

**Comment by srmklive** [comment]
It's up to you to properly configure & secure specific routes from spamming.

**Comment by ndar0430** [comment]
ok got it. but may i ask where are these urls being stored?
