### ISSUE TITLE
PAYPAL_SANDBOX_API_CERTIFICATE'

### ISSUE THREAD

**Issue by gautamgdeft** [srmklive/laravel-paypal#197]
Not able to find the PAYPAL_SANDBOX_API_CERTIFICATE in my paypal account please guide

Thanks in advance.

**Comment by srmklive** [comment]
The variable itself in self explanatory. Please refer to the issues section.

**Comment by shalemperez** [comment]
Here is the documentation to generate certificates and signatures: [How to get PayPal API username, password and signature information?](https://www.putler.com/support/faq/how-to-get-paypal-api-username-password-and-signature-information/)

**Comment by nastefan** [comment]
@shalemperez  is a signature now the same as API certificate?  I can see only this : 

![Bildschirmfoto 2019-05-17 um 11 49 01](https://user-images.githubusercontent.com/8930118/57919765-d0356380-7899-11e9-936f-8f1eaed9bda9.png)

**Comment by nastefan** [comment]
Ah ok, clearly explained at #242. Thanks!
