### ISSUE TITLE
"paypal_link" => null

### ISSUE THREAD

**Issue by dbos1504** [srmklive/laravel-paypal#198]
I tried everything ( i mean everything, google, read everything from github, live and local), is it posible because i am from Serbia that paypal sanbox won t work...

**Comment by srmklive** [comment]
Duplicate of #100, #101, #102 & #149

**Comment by srmklive** [comment]
You need to provide correct api credentials for express checkout.

**Comment by friana** [comment]
This issue may be solve in this link. Thanks

https://github.com/srmklive/laravel-paypal/issues/229#issuecomment-472755054
