### ISSUE TITLE
Add shipping cost to my ExpressCheckout : amounts do not match order amounts.

### ISSUE THREAD

**Issue by ryzs** [srmklive/laravel-paypal#199]
I've tried to add shipping cost to ExpressCheckout but paypal return with this error message.
I just add shipping cost from latest commit  #195 by @pakogn using $data['shipping'], the calculated amount is fine but return error message. Then i tried to add $data[total] = $total_detail + $data['shipping'], but still error. Any solutions?

"TIMESTAMP" => "2018-04-16T10:02:07Z"
  "CORRELATIONID" => "36fa6217409c8"
  "ACK" => "Failure"
  "VERSION" => "123"
  "BUILD" => "45840284"
  "L_ERRORCODE0" => "10413"
  "L_SHORTMESSAGE0" => "Transaction refused because of an invalid argument. See additional error messages for details."
  "L_LONGMESSAGE0" => "The totals of the cart item amounts do not match order amounts."
  "L_SEVERITYCODE0" => "Error"
  "paypal_link" => null

**Comment by pakogn** [comment]
Hi!

Excuse me, but Have you already checked that my commit is in your downloaded version of the package. I don't know but I was making some tests, and sometimes composer doesn't download the current version with the latest commits.

Greetings!

**Comment by ryzs** [comment]
Thank you for replying. Yes before i try the code, i've check the package whether contain your commit.
Even if the downloaded package in my project doesn't contain your commit, i think it won't bother the code flow right. 
There is no problem if i just add the shipping cost to the items array, but i want to try your code too.

**Comment by ryzs** [comment]
Oh i see, after i add the subtotal the code works fine, but without subtotal the calculated amount is wrong. 
I thought we need a condition if subtotal is doesnt exist in array data.

$data['subtotal'] = $total;
$data['total'] = $total + $data['shipping'];

**Comment by pakogn** [comment]
@ryzs oh yes, an implementation could be, something like this:

To authorize:

```php
$provider = new ExpressCheckout;

$cart = app(CartRepository::class);
$shippingInformation = app(ShippingRepository::class);

$order = app(Order::class)->createWithPaymentPending($cart->all(), currentCustomer(), $shippingInformation->getShippingAddress());

$data = [];
$data['items'] = app(PaypalItemsFactory::class)->makeFromOrder($order);
$data['invoice_id'] = config('paypal.invoice_prefix').'_'.$order->identifier;
$data['invoice_description'] = "ShopName Order #{$order->identifier} Invoice";
$data['return_url'] = route('shop.paypal.success');
$data['cancel_url'] = url('/');
$data['subtotal'] = $order->sub_total;
$data['total'] = $order->total;
$data['shipping'] = $order->total_shipping;

$options = [
    'BRANDNAME' => trans('company.name'),
    'LOGOIMG' => asset('assets/images/logo-small.png'),
    'EMAIL' => currentUser()->email,
];

try {
    $response = $provider->addOptions($options)->setExpressCheckout($data);

    return redirect($response['paypal_link']);
} catch (\Exception $e) {
    Log::info($e);

    $order->markAsDeclined();

    alert()->error('Ha ocurrido un error al procesar el pago. Vuelva a intentarlo más tarde');

    return redirect()->back();
}
```

after the authorization.
```php
$provider = new ExpressCheckout;
$cart = app(CartRepository::class);

$token = $request->get('token');
$PayerID = $request->get('PayerID');

// Verify Express Checkout Token
$response = $provider->getExpressCheckoutDetails($token);
$order = $this->retrieveOrderFromPayPal($response);

$data = [];
$data['items'] = app(PaypalItemsFactory::class)->makeFromOrder($order);
$data['invoice_id'] = config('paypal.invoice_prefix').'_'.$order->identifier;
$data['invoice_description'] = "ShopName Order #{$order->identifier} Invoice";
$data['return_url'] = route('shop.paypal.success');
$data['cancel_url'] = url('/');
$data['subtotal'] = $order->sub_total;
$data['total'] = $order->total;
$data['shipping'] = $order->total_shipping;

if (in_array(strtoupper($response['ACK']), ['SUCCESS', 'SUCCESSWITHWARNING'])) {
    // Perform transaction on PayPal
    $payment_status = $provider->doExpressCheckoutPayment($data, $token, $PayerID);
    $status = $payment_status['PAYMENTINFO_0_PAYMENTSTATUS'];

    if ($status == "Completed") {
        alert()->success('Success!', 'We have received your order!');

        $order->markAsPaid();
        $cart->flush();

        return redirect()->route('shop.checkout.success');
    }
}

$order->markAsDeclined();
alert()->error("We couldn't make the charge. Try again, please!");

return redirect()->back();
```
