### ISSUE TITLE
Digital Goods

### ISSUE THREAD

**Issue by adrianoGaspar** [srmklive/laravel-paypal#201]
Good morning, is there a possibility of implementing Digital Goods in this package? With Digital Goods I could make payment (in my case of a monthly fee) using a modal or something like that without leaving the site.

**Comment by srmklive** [comment]
You may need to create a recurring profile in this regard.

**Comment by srmklive** [comment]
For this package, the customer needs to be redirected to PayPal for account verification.

**Comment by adrianoGaspar** [comment]
ok, thanks
