### ISSUE TITLE
Проблема с оплатой paypal

### ISSUE THREAD

**Issue by batenko1** [srmklive/laravel-paypal#202]
Проект был на вордпрессе и был подключен paypal, все работало. переделали проект на laravel и подключили данный пакет, все успешно происходит, но с аккаунта почему то не снимает деньги, не происходит транзакция и потом paypal возвращает success. Возможно у кого то было такое и может помочь

**Comment by srmklive** [comment]
This may be an api credentials problem or may be something else entirely. Can you provide some other details in this regard?
