### ISSUE TITLE
Currency Code when using doReferenceTransaction

### ISSUE THREAD

**Issue by manbach** [srmklive/laravel-paypal#203]
Hello,

in my Project im using ReferenceTransactions to do yearly Transactions (Subscriptions cant be used in my Country - Germany).

I noticed that it is not possible to set the currencyCode for 
`doReferrenceTransaction()`

I tried using the config and $provider->setCurrency('EUR')->doReferrenceTransaction(). 

If i overwrite it inside PaypalTransactions like so:

```
public function doReferenceTransaction($transaction, $action, $amount = 0.00)
    {
        $this->setRequestData([
            "REFERENCEID"  => $transaction,
            "PAYMENTACTION" => $action,
            "AMT"           => $amount,
            "currencyCode" => "EUR",
        ]);

        return $this->doPayPalRequest("DoReferenceTransaction");
    }
```

it works but thats pretty much the worst solution i can think of. So am i missing an Option or is this currently the only way ?

**Comment by srmklive** [comment]
You can simply do it like this:

```
$provider->addOptions([
    'currencyCode' => 'EUR'
])->doReferenceTransaction($transactionid, $action, $amount);
```

**Comment by manbach** [comment]
Thanks, this works great. But is there any good reason why  $provider->setCurrency('EUR') or the config settings shouldn't work when using doReferenceTransaction? This doesn't seem obvious to me.

**Comment by manbach** [comment]
Also the documentation does not seem to mention doReferenceTransaction or getTransactionDetails is this on purpose?

**Comment by srmklive** [comment]
Might have overlooked it. Can you send a PR for this?

**Comment by manbach** [comment]
Created a pull request for the documentation. If its ok i will take a look at the setCurreny problem ?

**Comment by srmklive** [comment]
Sure
