### ISSUE TITLE
returning paypal data and store them

### ISSUE THREAD

**Issue by robertnicjoo** [srmklive/laravel-paypal#205]
Hi,
I'm newbie with this, currently i can successfully send my products data to paypal and pay/redirect. But I need help to store data from paypal in my database such as:

1. payment timestamp
2. payment id

so I can identify my users order as paid.

### Question

1. How to get paypal data (mentioned above) and store them?
 1.1. Do I need to create new function or just put my order update codes in `try` part? how exactly should i do that?

# Code

this is my current code in case I just need to edit this code and you're willing to help me:

```php
public function paypalexpressCheckout($id){
        $provider = new ExpressCheckout;

        $cart = Invoice::withTrashed()->findOrFail($id);

        $data = [];
        foreach($cart['content'] as $item)
        {
            $price = $item['subtotal'];
            $data['items'][] = array(
                'price'     => (int)$price,
                'qty'  => $item['qty'],
                'name'      => $item['name'],
            );
        }

        $data['invoice_id'] = $cart['invnum'];
        $data['invoice_description'] = "Order #{$data['invoice_id']} Invoice";
        $data['return_url'] = url('/orders');
        $data['cancel_url'] = url('/orders');

        $total = 0;
        foreach($cart['content'] as $item)
        {
            $total += $item['subtotal']*$item['qty'];
        }

        $data['total'] = $total;
        // dd($data);
        
        $options = [
            'BRANDNAME' => config('app.name'),
            'LOGOIMG' => asset('assets/images/logo-small.png'),
            'EMAIL' => 'test@trjkgj.com',
        ];

        try {
            $response = $provider->addOptions($options)->setExpressCheckout($data);
            return redirect($response['paypal_link']);
        } catch (\Exception $e) {
            Session::flash('danger', 'something went wrong with PayPal.');
            return redirect()->back();
        }
    }
```

Thanks in advance.

**Comment by reymark-torres** [comment]
Hi @robertnicjoo. 

I think you should use IPN (Instant Payment Notification) to get the payment timestamp and the payment id. Just log the all request after the IPN was triggered so that you can figure out what variables you need to get.

For IPN reference:
https://github.com/srmklive/laravel-paypal#paypalipn

**Comment by robertnicjoo** [comment]
Hi @reymark-torres thanks for response,

I did what you've suggested, unfortunately nothing changes in my database (not getting updates)

here is the codes I added:

```php
public function paypalnotify(Request $request)
    {
        $provider = new ExpressCheckout;
        $request->merge(['cmd' => '_notify-validate']);
        $post = $request->all();
        $response = (string) $provider->verifyIPN($post);
        if ($response === 'VERIFIED') {
            if ($post['txn_type'] == 'recurring_payment' && $post['payment_status'] == 'Completed') {
                $invoice = new Invoice();
                $invoice->payment_status = 'Completed';
                $invoice->recurring_id = $post['recurring_id'];
                $invoice->save();
            }
        }
    }
```

and route

```php
Route::post('paypal/notify', 'front\CartController@paypalnotify');
```

also changed my `App\Http\Middleware\VerifyCsrfToken.php` like:

```php
protected $except = [
        'paypal/notify',
    ];
```

1. what could be the issue?
2. is there a way that i can `dd` ipn results so i can be sure that i'm receiving something etc.?

**Comment by reymark-torres** [comment]
You could use Laravel's log facade (https://laravel.com/docs/master/logging#writing-log-messages) or just a logger helper (https://laravel.com/docs/master/helpers#method-logger) to check if you're receiving some from the IPN.

This time there were so many considerations why it doesn't notify, for the mean just check the log file after you made a transaction again.

Cheers.

**Comment by robertnicjoo** [comment]
@reymark-torres appreciate your helps,

I have tried `Log::info($post);` and `logger($post);` also `info($post);` and **nothing!** then I said maybe i'm doing something wrong so i just added static message to see if it saves in log file  `logger('Debug message');`

and the result is: **Empty Log file**.

So _I think_ it might be something wrong with my notify url, maybe I should specify it in my checkout process as I have `        $data['return_url']` and `$data['cancel_url'] `??

**Comment by srmklive** [comment]
Kindly see the README file for demo application link.
