### ISSUE TITLE
Adaptive Payments Error

### ISSUE THREAD

**Issue by Misiak4** [srmklive/laravel-paypal#21]
Hello,

even after fixing some SSL issues #20 I am still getting 'Authentication failed.' message.

`'response' => array('responseEnvelope' => array('timestamp' => '2016-07-12T00:57:21.056-07:00', 'ack' => 'Failure', 'correlationId' => 'ff9b97cb3df5d', 'build' => '23046607'), 'error' => array(array('errorId' => '520003', 'domain' => 'PLATFORM', 'subdomain' => 'Application', 'severity' => 'Error', 'category' => 'Application', 'message' => 'Authentication failed. API credentials are incorrect.')`

I am not sure why I am getting this error, I found older issue #15 but that did not helped me...

Any ideas where should be problem? I checked credentials and everything should be correct.

I will try to debug it even more...

**Comment by srmklive** [comment]
Just checked it. I didn't get any authentication errors. Following is the code i used for testing:

```
    $provider = adaptive_payments();

    $data = [
        'receivers'  => [
            [
                'email' => 'johndoe@example.com',
                'amount' => 10,
                'primary' => true,
            ],
            [
                'email' => 'janedoe@example.com',
                'amount' => 5,
                'primary' => false
            ]
        ],
        'payer' => 'EACHRECEIVER', // (Optional) Describes who pays PayPal fees. Allowed values are: 'SENDER', 'PRIMARYRECEIVER', 'EACHRECEIVER' (Default), 'SECONDARYONLY'
        'return_url' => url('payment/success'),
        'cancel_url' => url('payment/cancel'),
    ];

    $response = $provider->createPayRequest($data);
```

I got the following response:

```
array:3 [▼
  "responseEnvelope" => array:4 [▼
    "timestamp" => "2016-07-13T05:22:53.709-07:00"
    "ack" => "Success"
    "correlationId" => "e01f46803ba15"
    "build" => "23046607"
  ]
  "payKey" => "AP-01747504PV314203T"
  "paymentExecStatus" => "CREATED"
]
```

As you see, there is no issue authentication error.

**Comment by Misiak4** [comment]
Nevermind found the problem.

Client sent me live API credentials instead of SANDBOX one.

It works, please close this issue and I am sorry.
