### ISSUE TITLE
how to make discount, tax and shipping ?

### ISSUE THREAD

**Issue by Somesa** [srmklive/laravel-paypal#220]
Hello i would like to know how to show discount, tax and shipping

when i put in array 
```
'shipping' => 10
'total' => $total + 10 // with +10 and without i have same error

```
i have "The totals of the cart item amounts do not match order amounts" error

i would like to show something like that : 
![image](https://user-images.githubusercontent.com/11700260/41920599-58f91d62-7961-11e8-8e6a-57249d824a1b.png)

with a discount on the total price

thanks for your work

**Comment by MaxChu23** [comment]
+1 same issue here. But the most I can say about your situation is that maybe you are adding products array to that request, and the total values doesn't match products' values. I think you should show that array to us too.

**Comment by srmklive** [comment]
Refer to the README file. Use the `addOptions` method to add specific API parameters before calling a API endpoint.
