### ISSUE TITLE
no shipping data transmitted

### ISSUE THREAD

**Issue by lennow** [srmklive/laravel-paypal#222]
Hi, I am using Laravel 5.5 for my tiny shop application (https://guitarstix.de/shop). I have your laravel-paypal Express Checkout Button integrated. Everything is doing very well so far - except for that I don't get any shipping address data from PayPal. 
Is there a kind of statement to be sent to PayPal via SetCheckoutExpress or getCart Method, which is telling PayPal to get the address data?

Thanks a lot,

Lena

**Comment by tfarneau** [comment]
Hi, did you get an answer to your question ? I've got the same problem

**Comment by lennow** [comment]
No, I didn't get a answer to my question here. I finally figured it out on my own: 
The expressCheckout method in your PayPal Controller is calling the setExpressCheckout method (which is located in the ExpressCheckout Class of laravel-paypal). When you go to this setExpressCheckout method, there's the following code:

```
$this->post = $this->setCartItems($data['items'])->merge([
            'PAYMENTREQUEST_0_ITEMAMT'       => $this->subtotal,
            'PAYMENTREQUEST_0_AMT'           => $data['total'],
            'PAYMENTREQUEST_0_PAYMENTACTION' => $this->paymentAction,
            'PAYMENTREQUEST_0_CURRENCYCODE'  => $this->currency,
            'PAYMENTREQUEST_0_DESC'          => $data['invoice_description'],
            'PAYMENTREQUEST_0_INVNUM'        => $data['invoice_id'],
            'NOSHIPPING'                     => 2,
            'RETURNURL'                      => $data['return_url'],
            'CANCELURL'                      => $data['cancel_url'],
            'LOCALE'                         => $this->locale,
        ]); 
```

The 'NOSHIPPING' value was set to 1 there, but it has to be 2 to make PayPal deliver the address data of the customer. That's it, now it works fine.
