### ISSUE TITLE
You have error in method DoExpressCheckoutPayment

### ISSUE THREAD

**Issue by johny-catsvill** [srmklive/laravel-paypal#223]
`$this->post = $this->setCartItems($data['items'])->merge([
            'TOKEN'                          => $token,
            'PAYERID'                        => $payerid,
            'PAYMENTREQUEST_0_ITEMAMT'       => $data['total'],
            'PAYMENTREQUEST_0_AMT'           => $data['total'],
            'PAYMENTREQUEST_0_PAYMENTACTION' => !empty($this->config['payment_action']) ? $this->config['payment_action'] : 'Sale',
            'PAYMENTREQUEST_0_CURRENCYCODE'  => $this->currency,
            'PAYMENTREQUEST_0_DESC'          => $data['invoice_description'],
            'PAYMENTREQUEST_0_INVNUM'        => $data['invoice_id'],
            'PAYMENTREQUEST_0_NOTIFYURL'     => '/test-url',
            'RETURNFMFDETAILS' => 1,
            'PAYMENTREQUEST_0_SHIPPINGAMT'   => $data['ShippingTotal'],
            'PAYMENTREQUEST_0_TAXAMT'        => 0,
            'PAYMENTREQUEST_0_SHIPDISCAMT'   => 0,
            'PAYMENTREQUEST_0_HANDLINGAMT'   => $data['handling'],
        ]);`
In this method need to change value for key PAYMENTREQUEST_0_ITEMAMT. Instead $data['total'] need $data['subtotal'].

**Comment by MrPalamen** [comment]
+1
