### ISSUE TITLE
ErrorException (E_NOTICE) Undefined index: PAYMENTINFO_0_PAYMENTSTATUS 

### ISSUE THREAD

**Issue by waptik** [srmklive/laravel-paypal#227]
I have an error after submitting completing a payment and it seems like this constant does not exist  method DoExpressCheckoutPayment of the provider. I attached an image of the error.
![paypal_error](https://user-images.githubusercontent.com/1687551/43224572-abeb223e-9024-11e8-887e-c6d4e078b4f7.PNG)

**Comment by srmklive** [comment]
Checkout the demo app i have referred in the README.
