### ISSUE TITLE
What is the number format for $data['total']

### ISSUE THREAD

**Issue by snax4a** [srmklive/laravel-paypal#230]
Hello i cant figure out what should be the number format for $data['total'] in express checkout data its working when i calculate total like in demo example but when i divide the price by 100 i get convert to string error in paypal_link also if i hardcode the total for example to 10.99 i still get an error it only works when i have 129999.0 total price i dont understand it

**Comment by srmklive** [comment]
It may be an issue with your code. Checkout the demo app i have referred in the README.
