### ISSUE TITLE
While try following example code getting error type

### ISSUE THREAD

**Issue by testsoftuvo** [srmklive/laravel-paypal#231]
$data['items'] = [
		    [
		        'name'  => "Monthly Subscription",
		        'price' => 0,
		        'qty'   => 1,
		    ],
		];

		$data['subscription_desc'] = "Monthly Subscription #1";
		$data['invoice_id'] = 1;
		$data['invoice_description'] = "Monthly Subscription #1";
		$data['return_url'] = url('/paypal/ec-checkout-success?mode=recurring');
		$data['cancel_url'] = url('/');

		$total = 0;
		foreach ($data['items'] as $item) {
		    $total += $item['price'] * $item['qty'];
		}

		$data['total'] = $total;

		//give a discount of 10% of the order amount
		//$data['shipping_discount'] = round((10 / 100) * $total, 2);

		
		$options = [
		    'BRANDNAME' => 'Softuvo',
		    'LOGOIMG' => 'https://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_01.png',
		    'CHANNELTYPE' => 'Merchant'
		];

		$provider->addOptions($options)->setExpressCheckout($data);
		// Use the following line when creating recurring payment profiles (subscriptions)
		$provider->setCurrency('EUR')->setExpressCheckout($data);
		$response = $provider->setExpressCheckout($data, true);

****Response** :**

Array
(
    [type] => error
    [message] => 
    [paypal_link] => 
)

**Comment by srmklive** [comment]
Refer to the closed issues. You may need to provide a different invoice prefix though.
