### ISSUE TITLE
while run your demo code

### ISSUE THREAD

**Issue by testsoftuvo** [srmklive/laravel-paypal#232]
ErrorException (E_RECOVERABLE_ERROR)
Object of class Illuminate\Routing\Redirector could not be converted to string

**Comment by ksromero** [comment]
same

**Comment by ksromero** [comment]
I get it. It is an error somewhere on your code. I fixed mine already

**Comment by srmklive** [comment]
Couldn't replicate it on my end. I am glad that your issue is fixed.

**Comment by nobreferreira** [comment]
+1
