### ISSUE TITLE
Cannot pay from mozilla and few thoughts

### ISSUE THREAD

**Issue by DinVinchester** [srmklive/laravel-paypal#235]
1) 'LOCALE' is not working, so I test with 'LOCALECODE' instead of 'LOCALE', and it works, but only with chrome, when I try to use it from firefox, it redirects me to 
https://www.sandbox.paypal.com/webapps/hermes/error?cmd=_express-checkout&token=EC-6YC5889322938142B&rc=1
so I try the link for express checkout from demo https://github.com/srmklive/laravel-paypal
and it also redirects me to the error page, it only works from the private mode of Firefox, can you help me with that issue?)
2) Can you make some change in your PayPal module, for currency, sometimes I need to use different currencies in my system, and it's very uncomfortable to work with them from a config file, could you make some check, if there is currency in incoming data, use currency from incoming data?)

**Comment by srmklive** [comment]
The steps to change currency is documented in README. The file clearly states steps on how to properly setup credentials.
