### ISSUE TITLE
null paypal link

### ISSUE THREAD

**Issue by azztigz** [srmklive/laravel-paypal#236]
![image](https://user-images.githubusercontent.com/12978297/44794699-99200480-abdb-11e8-989c-ec87a7f42c56.png)

**Comment by srmklive** [comment]
Duplicate of #100, #101

**Comment by srmklive** [comment]
Kindly check whether you are passing correct data to `SetExpressCheckout` API call.

**Comment by friana** [comment]
This issue may be solve in this link. Thanks

https://github.com/srmklive/laravel-paypal/issues/229#issuecomment-472755054
