### ISSUE TITLE
Where do I get the API secret from?

### ISSUE THREAD

**Issue by petarvasilev91** [srmklive/laravel-paypal#237]
I am trying to set up my sandbox API credentials but I can't seem to find the API secret anywhere? Any help appreciated.

**Comment by srmklive** [comment]
Kindly refer to the README file.

**Comment by petarvasilev91** [comment]
@srmklive yes, there is a link in the readme but when I go to the API credentials page in the PayPal Sandbox there is no "API Secret" there is "API username", "API password", "Fingerprint" and also there is an option to download the certificate. Is any of those the "API Secret" or something else?

**Comment by neelmehta** [comment]
@petarvasilev91 were you able to figure this out? I have the exact same question.
