### ISSUE TITLE
Nothing works when I try to make a payment

### ISSUE THREAD

**Issue by Sidney-Dev** [srmklive/laravel-paypal#239]
I have the following in my view:

    <a href="{{route('payment.paypal')}}">Pay with PayPal</a>

Defined the route:

    Route::get('pay-with-paypal', 'CheckoutController@payWithPaypal')->name('payment.paypal');

My CheckoutController looks like the one below:

	use Srmklive\PayPal\Services\ExpressCheckout;

	class CheckoutController extends Controller
	{
	    public function payWithPaypal(){

	    	$provider = new ExpressCheckout; 
			$data = [];
			$data['items'] = [
			    [
			        'name' => 'Product 1',
			        'price' => 9.99,
			        'qty' => 1
			    ],
			    [
			        'name' => 'Product 2',
			        'price' => 4.99,
			        'qty' => 2
			    ]
			];

			$data['invoice_id'] = 1;
			$data['invoice_description'] = "Order #{$data['invoice_id']} Invoice";
			$data['return_url'] = url('/');
			$data['cancel_url'] = url('/');

			$total = 0;
			foreach($data['items'] as $item) {
			    $total += $item['price']*$item['qty'];
			}

			$data['total'] = $total;

			$response = $provider->setExpressCheckout($data);

			 // This will redirect user to PayPal
			return redirect($response['paypal_link']);

	    }
	}

When I click on the link "Pay with PayPal", nothing happens.
Anything I could have possibly done wrong?

My config looks like this:

    return [
        'mode'    => 'sandbox', // Can only be 'sandbox' Or 'live'. If empty or invalid, 'live' will be used.
        'sandbox' => [
            'username'    => env('PAYPAL_SANDBOX_API_USERNAME', ''),
            'password'    => env('PAYPAL_SANDBOX_API_PASSWORD', ''),
            'secret'      => env('PAYPAL_SANDBOX_API_SECRET', ''),
            'certificate' => env('PAYPAL_SANDBOX_API_CERTIFICATE', ''),
            'app_id'      => 'APP-80W284485P519543T', // Used for testing Adaptive Payments API in sandbox mode
        ],
        'live' => [
            'username'    => env('PAYPAL_LIVE_API_USERNAME', ''),
            'password'    => env('PAYPAL_LIVE_API_PASSWORD', ''),
            'secret'      => env('PAYPAL_LIVE_API_SECRET', ''),
            'certificate' => env('PAYPAL_LIVE_API_CERTIFICATE', ''),
            'app_id'      => '', // Used for Adaptive Payments API
        ],

        'payment_action' => 'Sale', // Can only be 'Sale', 'Authorization' or 'Order'
        'currency'       => 'USD',
        'billing_type'   => 'MerchantInitiatedBilling',
        'notify_url'     => '', // Change this accordingly for your application.
        'locale'         => '', // force gateway language  i.e. it_IT, es_ES, en_US ... (for express checkout only)
        'validate_ssl'   => true, // Validate SSL when creating api client.
    ];

My .env is also configured:

    PAYPAL_SANDBOX_API_USERNAME=example-facilitator_api1.hotmail.com
    PAYPAL_SANDBOX_API_PASSWORD=SLU2YLP4B
    PAYPAL_SANDBOX_API_SECRET=TF3K8CtWTEmAcRu40.XWAihLRko
    PAYPAL_SANDBOX_API_CERTIFICATE=

Hope someone can help

**Comment by srmklive** [comment]
Refer to the closed issues section. Also add an invoice prefix.
