### ISSUE TITLE
paypal-developer site reference needed in readme

### ISSUE THREAD

**Issue by zofe** [srmklive/laravel-paypal#24]
just a dumb question,  I'm new to paypal  (used cashier/stripe before)

on https://developer.paypal.com/developer/applications/ i see three kind of  app-interaction

v.zero SDK,  REST API apps,  NVP/SOAP API apps.

this package is intended to works with REST API?
I've generated  a new rest api app and all I can see are this kind of credentials:
- Sandbox account (email)
- Client ID (hash)
- Secret (another hash)

this doesn't match the configuration of package 
PAYPAL_LIVE_API_USERNAME
PAYPAL_LIVE_API_PASSWORD
PAYPAL_LIVE_API_SECRET
PAYPAL_LIVE_API_CERTIFICATE

So, can I have some reference link to paypal developer website?
thanks a lot for the package

**Comment by srmklive** [comment]
```
PAYPAL_LIVE_API_USERNAME
PAYPAL_LIVE_API_PASSWORD
PAYPAL_LIVE_API_SECRET
PAYPAL_LIVE_API_CERTIFICATE
```

@zofe The above items refer to your premier/business paypal account API credentials that you generate. Kindly check this [link](https://developer.paypal.com/docs/classic/api/apiCredentials/) on how to generate API credentials from you paypal account. 

For api credentials generated for sandbox accounts, you need to use the following and set `mode` to `sandbox` in `config/paypal.php` file after you install & configure the package:

```
PAYPAL_SANDBOX_API_USERNAME
PAYPAL_SANDBOX_API_PASSWORD
PAYPAL_SANDBOX_API_SECRET
PAYPAL_SANDBOX_API_CERTIFICATE
```

**Comment by zofe** [comment]
@srmklive  many tanks!

**Comment by novakben** [comment]
Zofe do you have a reference? I'm struggling with this.

**Comment by zofe** [comment]
@novakben  I told my flow

- You can log-in on developers.paypal.com (with the main paypal account credential)
if you do that  you can see  at the bottom of the page.. a "Sandbox Accounts" link
there you can find  both  "vendor" and "buyer" account credentials..

- then following srmklive link i've opted for  the (simplest) integration called "Signature API credentials" (instead of "Certificate API credentials")

- I've used  the express_checkout functionality, so i stored PAYPAL_SANDBOX_API_USERNAME, PAYPAL_SANDBOX_API_PASSWORD, PAYPAL_SANDBOX_API_SECRET

- then as reference for the express checkout this helped me:
https://developer.paypal.com/docs/classic/express-checkout/gs_expresscheckout/?mark=express

Now I'm struggling a bit with the IPN..  but I prefer this kind of packages,  where you need to "work with"  to understand the flow

**Comment by srmklive** [comment]
@zofe paypal ipn is handled by default in this package. I have listed down instructions [here](https://github.com/srmklive/laravel-paypal#paypalipn).

**Comment by zofe** [comment]
@srmklive absolutely, done as described and It worked, thanks a lot.  
Anyway major doubts  are about how to handle the flow (so paypal related).

I mean:
-  IPN should be a server to server negotiation (so not related to the user-session I think),  so why you're using "sessions" in the example?

-  About "best practice"..  IPN should be used also to "store" the payment record on the application side? or only used to log  the outcome of the transaction?

- IPN notification "comes first" or after  the return from payment gateway to the success pages?  I mean: If i decide to use only IPN to "store" the payment record, at the success page I already  can I be sure that  the notification/webwook was already called ?

thanks a lot for any suggestion

**Comment by srmklive** [comment]
@zofe here are my answers to your questions:

* The IPN implementation is definitely server to server communication. Use of session is just a simple line of code. The assumption here is that IPN implementation will always be different, and the code in package will always be changed.

* IPN is used to store payment records on your application. But it can also be used to do various things like reporting, processing renewals from paypal recurring profiles to manage subscriptions on application end.

* IPN is a totally different with respect to normal checkout process through paypal. IPN covers all transactions done on paypal. Suppose you pay through paypal, but there is a delay in response from paypal and as a result you are redirected to the application's error page. Whenever that transaction is processed successfully, IPN will automatically send this notification to the application where you will adequately update that specific order details.

Hope it helps.

**Comment by zofe** [comment]
@srmklive clear, thank you again. 

- The IPN webhook should rule for each log/store/update operation at application side,  including storing a payment record on success.

- Instead, The params received from paypal as `doExpressCheckoutPayment` on a  "order controller" can just be used to show the payment outcome to the customer.
