### ISSUE TITLE
Use of undefined constant CURL_SSL

### ISSUE THREAD

**Issue by augurs** [srmklive/laravel-paypal#240]
Hi,
I have Linode with  (CentOS WebPanel) server and I am using laravel 5.6 with php 7.1.6 for my application.

I am getting the error- 
**Use of undefined constant CURL_SSLVERSION_TLSv1_2 - assumed 'CURL_SSLVERSION_TLSv1_2**

Can you please help me to fix it, how I disable CURL_SSL or any other way.

Thanks
Shailesh

**Comment by fsasvari** [comment]
File: src/Traits/PayPalHttpClient.php

Add "CURLOPT_SSLVERSION => 6" instead of "CURLOPT_SSLVERSION => CURL_SSLVERSION_TLSv1_2".

    protected function setHttpClientConfiguration()
    {
         $this->httpClientConfig = [
             CURLOPT_SSLVERSION     => 6,
             CURLOPT_SSL_VERIFYPEER => $this->validateSSL,
         ];
    }

**Comment by userofadmin** [comment]
Hi,
I want createMonthlySubscription ,but the token is invalid.
what should I do?

**Comment by srmklive** [comment]
Refer to the demo app in README.
