### ISSUE TITLE
what is Sandbox API certificate ID and where can i find it?

### ISSUE THREAD

**Issue by techybirds** [srmklive/laravel-paypal#242]
I am integrating recurring payment with paypal with laravel. right now its no localhost. i have completed steps you have given. but i'm not able to find sandbox API certificate ID. how to get that? and where can i find that sandbox API certificate ID.  also there is no error message when i execute my code see below.
![image](https://user-images.githubusercontent.com/15027683/47152938-b465e100-d2fb-11e8-9cdd-e95fe97f3cbb.png)
![image](https://user-images.githubusercontent.com/15027683/47152970-ccd5fb80-d2fb-11e8-9b36-4a798e130800.png)

**Comment by YosefOberlander** [comment]
Name issue here. Do you have any updates?

**Comment by techybirds** [comment]
Yes successfully integrated.

**Comment by YosefOberlander** [comment]
Do you mind letting me know what your issue was?

**Comment by YosefOberlander** [comment]
@seitymoe I'm still awaiting a response from @techybirds

**Comment by techybirds** [comment]
[How to generate credentials paypal.pdf](https://github.com/srmklive/laravel-paypal/files/2500168/How.to.generate.credentials.paypal.pdf)

**Comment by seitymoe** [comment]
@techybirds thank you for the tutorial! but I couldn't get this working by following that instruction...
@YosefOberlander 
However I could somehow solved the issue. I'm not sure it's how this supposed to be though.
You just set signature as PAYPAL_SANDBOX_API_SECRET and leave PAYPAL_SANDBOX_API_CERTIFICATE empty like this↓.
![default](https://user-images.githubusercontent.com/16991809/47293984-ac34db00-d646-11e8-82f7-094e24d8357d.jpg)

**Comment by seitymoe** [comment]
@techybirds thank you for the tutorial. but didn't work for me...
@YosefOberlander 
However I could somehow managed to solve the issue. I'm not sure it's how you're supposed to do though.
You just set Signature as API_SECRET and leave API_CERTIFICATE empty like this↓.

![default](https://user-images.githubusercontent.com/16991809/47294530-53fed880-d648-11e8-967d-e17f785684f4.jpg)

**Comment by seitymoe** [comment]
ewe

**Comment by YosefOberlander** [comment]
@seitymoe Thanks i'll try your way. Because @techybirds tutorial didn't work i thing it's because Express Checkout is deprecated. Thanks for the tutorial!

**Comment by YosefOberlander** [comment]
@seitymoe Thanks for your help but i still can't get it to work. I tried clearing composer to make sure the .env updates but still nothing. I might try to remove the package and reinstall it. It's really frustrating that it won't even give a message with the error.

**Comment by shalemperez** [comment]
> @techybirds thank you for the tutorial! but I couldn't get this working by following that instruction...
> @YosefOberlander
> However I could somehow solved the issue. I'm not sure it's how this supposed to be though.
> You just set signature as PAYPAL_SANDBOX_API_SECRET and leave PAYPAL_SANDBOX_API_CERTIFICATE empty like this↓.
> ![default](https://user-images.githubusercontent.com/16991809/47293984-ac34db00-d646-11e8-82f7-094e24d8357d.jpg)

I use this steps to make this work, but i still getting this error:

```
"TIMESTAMP" => "2019-04-01T04:57:56Z"
  "CORRELATIONID" => "b9164c20dd429"
  "ACK" => "Failure"
  "VERSION" => "123"
  "BUILD" => "000000"
  "L_ERRORCODE0" => "10002"
  "L_SHORTMESSAGE0" => "Security error"
  "L_LONGMESSAGE0" => "Security header is not valid"
  "L_SEVERITYCODE0" => "Error"
  "paypal_link" => null
```

**Comment by Ahmad-Shahzaib** [comment]
Argument 1 passed to Symfony\Component\HttpFoundation\Response::setContent() must be of the type string or null, object given, called in 

i am getting this error

**Comment by sandeep4467** [comment]
The solution provided by @seitymoe was effective for me. Initially, it didn't work, but I discovered that the issue was due to the environment cache. To resolve this, I took the following steps:

1. Stop the Laravel server.
2. Clear the configuration cache by executing `php artisan config:clear`.
3. Restart the Laravel server with `php artisan serve --port 8080`.
