### ISSUE TITLE
demo issue

### ISSUE THREAD

**Issue by alinmiron** [srmklive/laravel-paypal#244]
I have tried to use the demo app (https://laravel-paypal-demo.srmk.info/paypal/ec-checkout)  but I got this exception:
 Illuminate \ Database \ QueryException (2054)
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from `invoices`)

**Comment by srmklive** [comment]
Hi,

Thanks for reporting. Turns out the issue was MySQL 8 configuration :stuck_out_tongue_closed_eyes:.
