### ISSUE TITLE
Adptive payment verify ipn not work 

### ISSUE THREAD

**Issue by niravm91** [srmklive/laravel-paypal#246]
1) I am not getting transaction detail from IPN message
2) And for verify IPN, Below is my code
        $provider = new AdaptivePayments();
        
        $request->merge(['cmd' => '_notify-validate']);
        $post = $request->all();
        
        $response = (string) $provider->verifyIPN($post);

**Comment by srmklive** [comment]
It will only give you 'VERFIED' or 'INVALID'.
