### ISSUE TITLE
Use of undefined constant CURLOPT_SSLVERSION - assumed 'CURLOPT_SSLVERSION'

### ISSUE THREAD

**Issue by lokeshyadav88** [srmklive/laravel-paypal#248]
Unable to initiate express checkout.
I am using following configuration:-
1) Laravel 5.4
2) Ubuntu 14
3) Apache2 => Apache/2.4.7
4) PHP 5.6.37
5) curl 7.35.0

**Comment by srmklive** [comment]
You need to define these curl constants in your code. I couldn't replicate the issue you reported using the same configuration as listed above.
