### ISSUE TITLE
Use of undefined constant CURL_SSLVERSION_TLSv1_2 

### ISSUE THREAD

**Issue by prasadmunna** [srmklive/laravel-paypal#25]
Use of undefined constant CURL_SSLVERSION_TLSv1_2 - assumed 'CURL_SSLVERSION_TLSv1_2'

**Comment by srmklive** [comment]
can you elaborate on the issue further?

**Comment by novakben** [comment]
You need to upgrade the OpenSSL on your server to 1.X

**Comment by prasadmunna** [comment]
Thanks +1:

**Comment by neutt22** [comment]
@prasadmunna have you managed to resolved the issue? Having the same right now...
