### ISSUE TITLE
ExpressCheckout isn't showing on transaction history

### ISSUE THREAD

**Issue by seitymoe** [srmklive/laravel-paypal#250]
PaypalExpressCheckout was successful, however it doesn't show on account's transaction history.
The paypal balance is changed, but this doesn't show on transaction history. both in buyer's and merchant's account.
When I make payment on the demo site, I could see the transaction history.
 
What could be the problem???

**Comment by Syednazirhussain** [comment]
Did you test on local server or live? In my case i perform express checkout from local server with my paypal sandbox account the bower tab loading still to long what can i do

**Comment by seitymoe** [comment]
@Syednazirhussain 
Thank you for the reply!
It's on Microsoft Azure, tested on a sandbox account.
Actually, I checked my account again now and it was there.
I just had to wait.
