### ISSUE TITLE
Pending ajax

### ISSUE THREAD

**Issue by blackholevn** [srmklive/laravel-paypal#251]
I use ajax request, CheckoutController

use Srmklive\PayPal\Services\ExpressCheckout;
    /**
     * @var ExpressCheckout
     */
    protected $provider;

    public function __construct()
    {
        $this->provider = new ExpressCheckout();
    }

public function ajax() {
        $data = [];
        $data['items'] = [
            [
                'name' => 'Product 1',
                'price' => 9.99,
                'qty' => 1
            ],
            [
                'name' => 'Product 2',
                'price' => 4.99,
                'qty' => 2
            ]
        ];
        
        $data['invoice_id'] = 1;
        $data['invoice_description'] = "Order #{$data['invoice_id']} Invoice";
        $data['return_url'] = url('/payment/success');
        $data['cancel_url'] = bh_url('/cart');
        
        $total = 0;
        foreach($data['items'] as $item) {
            $total += $item['price']*$item['qty'];
        }
        
        $data['total'] = $total;
        
        //give a discount of 10% of the order amount
        $data['shipping_discount'] = round((10 / 100) * $total, 2);

        try {
            $response = $this->provider->setExpressCheckout($data, false);
            dd($response);
        } catch (\Exception $e) {
            echo $e->getMessage();
        }
}

but when call ajax, pending and not reutrn 200 code.
When I remove "try...catch", ajax working, return 200 code

**Comment by Delindel** [comment]
Ive noticed this behavior as well when using Live tokens. How did you solve it @blackholevn
