### ISSUE TITLE
Payment activity not showing

### ISSUE THREAD

**Issue by bonucci** [srmklive/laravel-paypal#254]
Hi there, im been using your  package to create paypal payments, and it works fine, the only problem is that in the payment history is not showing nothing, the checkout gives a response of status complete on the doExpressscheckout but in paypal sandbox buyer account nothing shows, the same situation appears in your laravel demo store.

**Comment by srmklive** [comment]
Need to look at PayPal dashboard for this

**Comment by osamamoinchawla** [comment]
@srmklive  Assalam o alaikum Mr. Raza, what changes I need to make on dashboard because I am also facing same issue. Please guide

@bonucci  hello buddy, did you solve your problem?
