### ISSUE TITLE
Working fine when using in Localhost but does not work after deploying to Heroku..

### ISSUE THREAD

**Issue by jaab30** [srmklive/laravel-paypal#255]
Everything was working great until I deployed to Heroku... Now, when I press the Paypal link route, it hangs right on the "$response = $provider->setExpressCheckout($data);" of my code and stays there until it times out. I tried "Sandbox Mode" and "Live Mode" with my credentials, but still does not work... 

Any help will be greatly appreciated... Thanks..!

**Comment by srmklive** [comment]
I myself tried it on Heroku. You may need to add the MySQL host config. Can you explain the issue further?

**Comment by jaab30** [comment]
Hi,
Thanks for your reply.. I got it working now... Heroku was not able to read the credentials from the .env file since I was using .gitignore to hide them... Once I entered the credentials in the paypal.php file directly, it worked... so I will have to enter my credentials through the "Config Vars" in Heroku so that they are kept secret... But everything works well now... Live and Sandbox.
Again, thanks for your reply and for building this great package...
Jorge

**Comment by srmklive** [comment]
👍

**Comment by osamamoinchawla** [comment]
@srmklive  Sir, hamari bhii madad kardo
