### ISSUE TITLE
change env setting 

### ISSUE THREAD

**Issue by praveenpatel95** [srmklive/laravel-paypal#259]
I am storing Api credentials setting in database, when i call to payment method that time i want to pass credentials details from database in controller not from env file. so i do
i try but i dont know

 $provider = new ExpressCheckout; 
        $config['mode']=""; 
        $config['PAYPAL_SANDBOX_API_USERNAME']=$myusername; 
        $config['PAYPAL_SANDBOX_API_PASSWORD']=$mypass; 
        $config['PAYPAL_SANDBOX_API_SECRET']=$mysecrtekey; 
        $provider->setApiCredentials($config);

**Comment by srmklive** [comment]
You are passing credentials incorrectly to the setApiCredentials method. The format should same as what you would have in **config/paypal.php** file.

**Comment by praveenpatel95** [comment]
i am not aware, can you help

in paypl config like this
'mode'    => 'sandbox', // Can only be 'sandbox' Or 'live'. If empty or invalid, 'live' will be used.
    'sandbox' => [
        'username'    => env('PAYPAL_SANDBOX_API_USERNAME', 'patelprem1992-facilitator_api1.gmail.com'),
        'password'    => env('PAYPAL_SANDBOX_API_PASSWORD', '6TTJ8SD2CCH35XK4'),
        'secret'      => env('PAYPAL_SANDBOX_API_SECRET', 'EHIVPWRDd7SzIeegYt5mlWrupnEKUGnqboIqnljNKvC8pJl2CK26AUv0x0mzfiVBzkqscheVk03Ez8J6'),
        'certificate' => env('PAYPAL_SANDBOX_API_CERTIFICATE', 'AUK9iK_5z9zGDWuA5iWCnq6IiKUETkajcDpU26TQtyIVesF3jY33mtIhCdXJXeLwtfvjLZf1MtIPg6Wm'),
        'app_id'      => 'APP-80W284485P519543T', // Used for testing Adaptive Payments API in sandbox mode
    ],
    'live' => [
        'username'    => env('PAYPAL_LIVE_API_USERNAME', ''),
        'password'    => env('PAYPAL_LIVE_API_PASSWORD', ''),
        'secret'      => env('PAYPAL_LIVE_API_SECRET', ''),
        'certificate' => env('PAYPAL_LIVE_API_CERTIFICATE', ''),
        '

**Comment by praveenpatel95** [comment]
Done dear, thank you for your time.
