### ISSUE TITLE
Config file not updated?

### ISSUE THREAD

**Issue by novakben** [srmklive/laravel-paypal#26]
Hi!
When I try to get the data to the config file, I can only get these credentials from PayPal (sandbox and live):
```Sandbox account```  (email)
```Client ID```
``` Secret ```

But the config wants these credentials:
```username, password, secret, certificate,app_id```
Any ideas?

**Comment by srmklive** [comment]
Kindly check this [link](https://developer.paypal.com/docs/classic/api/apiCredentials/) on how to generate API credentials from you paypal account.

**Comment by novakben** [comment]
I get a certificate file from paypal, do I need to paste it's content or link to it?

**Comment by novakben** [comment]
Is it possible to use the signature instead? Do I need "file_get_content"?
Do you have maybe a working example of the config?

**Comment by srmklive** [comment]
@novakben normally you provide the certificate path in config. You can change the certificate setting to path for your paypal api certificate. I dont think there will be any issues with it. You can try to use `file_get_content` as well.
