### ISSUE TITLE
How to enable guest checkout without Paypal account create

### ISSUE THREAD

**Issue by thaodx** [srmklive/laravel-paypal#264]
Guest checkout currently available but when user input their Credit card information, they also have to input email address and password for Paypal account creation which very annoying for some users who don't want to create a Paypal account.
I've check the Paypal Express checkout javascript SDK, customer don't have to create new Paypal account when using credit card method.
How can i do it using this package?

**Comment by srmklive** [comment]
This package uses Express Checkout API. Refer to their documentation on how to enable this.
