### ISSUE TITLE
curl 58 error

### ISSUE THREAD

**Issue by aadilali** [srmklive/laravel-paypal#266]
Hi,

I am getting following error while trying Sandbox Adaptive payment.
cURL error 58: could not load PEM client certificate, OpenSSL error error:02001002:system library:fopen:No such file or directory

I am using Wamp on Windows 10.

Could you please guide me how to solve this error.

**Comment by srmklive** [comment]
It may be an issue with Certificate path or contents etc.

**Comment by jamesdigid** [comment]
I'm getting the same issue, it would be helpful to atleast make a note of where to reference the pem file

**Comment by KamilGromov1122** [comment]
On demo project, I can't find out any certificate file or config example.
Please guide me where I have to put certificate and how to write the path in config file.

**Comment by KamilGromov1122** [comment]
![image](https://user-images.githubusercontent.com/45867838/69741167-8812ca00-1175-11ea-849e-fd5d82757e3c.png)

**Comment by KamilGromov1122** [comment]
I getting above error... I can't find out the way how to fix this.

**Comment by anasschbani20** [comment]
Please any updates ? i have this problem too
