### ISSUE TITLE
Add custom Paypal ExpressCheckout options

### ISSUE THREAD

**Issue by mikadev** [srmklive/laravel-paypal#27]
in your class ExpressCheckout.php your'e using array $tmp (119) to send options to paypal please add the possibility to modify this array.

**Comment by srmklive** [comment]
What specific extra options do you wish to add?

**Comment by mikadev** [comment]
Not specific extra options i only want to be able to modify the tmp array with the paypal options

**Comment by srmklive** [comment]
I will add the ability to add extra options in the upcoming release. Thanks for pointing out this issue.

**Comment by Fedchishina** [comment]
Hello.
Tell me please!)
I created function:
    public static function sendPayPallOrder($order){

        $provider = express_checkout();

        $data['items'] = [
            [
                'name' => 'Payment order',
                'price' => 100,
                'qty' => 1
            ],
        ];
        $data['total'] = 100;

        $data['invoice_id'] = $order->id;
        $data['invoice_description'] = "Order #$data[invoice_id] Invoice";
        $data['return_url'] = url('/payment/success');
        $data['cancel_url'] = url('/cart');

        $response = $provider->setExpressCheckout($data);

        return $response['paypal_link'];
    }

Also i created route:

Route::get('/payment/success',              [ 'as' => 'order.payment-success', 'uses'=>'SiteController@paymentSuccess' ] );

And i created function:
    public static function paymentSuccess(Request $request)
    {
        $data=[]; //???????????????
        $input = $request->all();
        $provider = express_checkout();
        $response = $provider->doExpressCheckoutPayment($data, $input['token'], $input['PayerID']);
        //dd($response);
    }

How i can to receive $data in paymentSuccess function?
