### ISSUE TITLE
How to create tax and paypal commission calculation

### ISSUE THREAD

**Issue by keyur5390** [srmklive/laravel-paypal#274]
Hello,
I am using this package and there is some update require to client's end. 
Client require to show the bifurcation of the charges to end users.
i.e. Actual price  + PayPal Commission Charges (Which is run time calculation) + Canadian Tax Applicable 

in this,
- Actual price is the price which system will charge to the buyers. 
- PayPal Commission: Client wants to calculate it at the time of PayPal Express Checkout screen and show to the buyer that commission charges are that much and would be addition in to actual price.
- Canadian Tax: Client wants to integrate this as a tax as the government charges for the firm as taxes. So that should also be consider in the amount to be paid at the screen of the PayPal Express Checkout. 

Is there any scope to make this feasible through this package? or I have to use any other package?
Please guide me on this.

Thanks,
Keyur Mistry

**Comment by srmklive** [comment]
Adaptive Payments is probably the best one for your scenario

**Comment by keyur5390** [comment]
> Adaptive Payments is probably the best one for your scenario

How the Adaptive Payments is useful to me? 
I don't want to split the payment. And For the Adaptive payment I already tried and in that scenario I must have to pass master account and the sub account to submit the payment and both account have some amount which total is equivalent to total amount.
