### ISSUE TITLE
HELP: return pending payment

### ISSUE THREAD

**Issue by mangao05** [srmklive/laravel-paypal#278]
Hello , can you help me with this?

Im getting a pending return, I dont know how to fix this , why it returns pending? 

Thanks and more power to you sir.

array:26 [▼
  "TOKEN" => "EC-11025621E8085123X"
  "BILLINGAGREEMENTID" => "B-9VF46503YD101710K"
  "SUCCESSPAGEREDIRECTREQUESTED" => "false"
  "TIMESTAMP" => "2019-06-06T02:39:22Z"
  "CORRELATIONID" => "dca1e153c64cd"
  "ACK" => "Success"
  "VERSION" => "123"
  "BUILD" => "52936238"
  "INSURANCEOPTIONSELECTED" => "false"
  "SHIPPINGOPTIONISDEFAULT" => "false"
  "PAYMENTINFO_0_TRANSACTIONID" => "58572849D03946123"
  "PAYMENTINFO_0_TRANSACTIONTYPE" => "cart"
  "PAYMENTINFO_0_PAYMENTTYPE" => "instant"
  "PAYMENTINFO_0_ORDERTIME" => "2019-06-06T02:39:20Z"
  "PAYMENTINFO_0_AMT" => "700.00"
  "PAYMENTINFO_0_TAXAMT" => "0.00"
  "PAYMENTINFO_0_CURRENCYCODE" => "PHP"
  "PAYMENTINFO_0_PAYMENTSTATUS" => "Pending"
  "PAYMENTINFO_0_PENDINGREASON" => "multicurrency"
  "PAYMENTINFO_0_REASONCODE" => "None"
  "PAYMENTINFO_0_PROTECTIONELIGIBILITY" => "Eligible"
  "PAYMENTINFO_0_PROTECTIONELIGIBILITYTYPE" => "ItemNotReceivedEligible,UnauthorizedPaymentEligible"
  "PAYMENTINFO_0_SELLERPAYPALACCOUNTID" => "mangao_jeric-facilitator@yahoo.com"
  "PAYMENTINFO_0_SECUREMERCHANTACCOUNTID" => "A4AA7T5PUC884"
  "PAYMENTINFO_0_ERRORCODE" => "0"
  "PAYMENTINFO_0_ACK" => "Success"
]

**Comment by srmklive** [comment]
Need more details. Do have a look at the demo application, that should help you out as well.

**Comment by mangao05** [comment]
I already looked at your demo application and you're using USD. However I need to use other currency. But whenever I change the currency to Philippine Peso , 


![Screenshot_6](https://user-images.githubusercontent.com/31975866/59238271-e41d7c80-8c2f-11e9-9a0a-348ce23122c5.png)
![Screenshot_7](https://user-images.githubusercontent.com/31975866/59238272-e41d7c80-8c2f-11e9-9889-1122cf9ce7ad.png)
