### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by nam-co** [srmklive/laravel-paypal#28]
Hi srmklive, first of all, thanks for the great package, Im sorry to bother you but Im having real problems with the config/paypal file

For sandbox should we go to developer-> App api or paypal-> profile Certificates?
if its certificate, where can I get the secret? ( I just see the username,pass, and certificate)...
if its app I just see username(Sandbox account), secret and client_id (I don't know witch one is this), but no password or certificate...

Same goes for live (if its credentials, are they the same as live)?

Please help us, Im sure Im not the only one, appreciate the help
regards
Michael

**Comment by srmklive** [comment]
```
PAYPAL_LIVE_API_USERNAME
PAYPAL_LIVE_API_PASSWORD
PAYPAL_LIVE_API_SECRET
PAYPAL_LIVE_API_CERTIFICATE
```

@nam-co  The above items refer to your premier/business paypal account API credentials that you generate. Kindly check this [link](https://developer.paypal.com/docs/classic/api/apiCredentials/) on how to generate API credentials from you paypal account. 

For api credentials generated for sandbox accounts, you need to use the following and set `mode` to `sandbox` in `config/paypal.php` file after you install & configure the package:

```
PAYPAL_SANDBOX_API_USERNAME
PAYPAL_SANDBOX_API_PASSWORD
PAYPAL_SANDBOX_API_SECRET
PAYPAL_SANDBOX_API_CERTIFICATE
```

**Comment by Frossard** [comment]
To Express Checkout only need a api signature. The readme file needs an update.
I also had problems with this in my integration. The readme explanation is very confusing. 
But it is now working, thanks!

**Comment by leiiinad** [comment]
@Frossard How to use signature?
