### ISSUE TITLE
Pay with Credit Card without Paypal account

### ISSUE THREAD

**Issue by huyngvu** [srmklive/laravel-paypal#282]
Hello,

I'm using this package for my project. It's working well with recurring payment. But now I want to allow Guest checkout without Paypal account (one time payment).

How can I do it? 

I had also followed all the closed issues to setup my paypal account. And I checked your demo url: https://laravel-paypal-demo.srmk.info/.  Seem don't have it too.

Please help me about this issue.

Many thanks,
Huy

**Comment by srmklive** [comment]
This is a business account specific setting. You should have Guest Checkout enabled.
