### ISSUE TITLE
Object of class GuzzleHttp\Psr7\Request could not be converted to string

### ISSUE THREAD

**Issue by AidasK** [srmklive/laravel-paypal#283]
![image](https://user-images.githubusercontent.com/2088484/60596689-2f9bf400-9db2-11e9-987f-9cbd49103e23.png)

Object of class GuzzleHttp\Psr7\Request could not be converted to string
--
line | 93
code | 4096
file | /var/www/current/vendor/srmklive/paypal/src/Traits/PayPalHttpClient.php

https://github.com/srmklive/laravel-paypal/blob/c9b02546fac2abaacd877f5f7e64497ae820396c/src/Traits/PayPalHttpClient.php#L93

**Comment by srmklive** [comment]
Havent come across this issue. If it occurs for you again, kindly open a PR with detailed steps to reproduce and how this issue is fixed

**Comment by AidasK** [comment]
Do you really need an example to reproduce this? Just look at this class: https://github.com/guzzle/psr7/blob/master/src/Request.php
It clearly has no "toString" method. 

My suggestion would be to change this code:
```
try {
            return $this->client->post($this->apiUrl, [
                $this->httpBodyParam => $this->post->toArray(),
            ])->getBody();
        } catch (HttpClientException $e) {
            throw new \Exception($e->getRequest().' '.$e->getResponse());
        } catch (HttpServerException $e) {
            throw new \Exception($e->getRequest().' '.$e->getResponse());
        } catch (HttpBadResponseException $e) {
            throw new \Exception($e->getRequest().' '.$e->getResponse());
        }
```
to:
```
            return $this->client->post($this->apiUrl, [
                $this->httpBodyParam => $this->post->toArray(),
            ])->getBody();
```

It looks much more simpler and exceptions are handled much better in this way.

**Comment by AidasK** [comment]
@srmklive What do you think about my suggestion above to remove try{}catch block? I can't see any BC or threats to existing users. I can create a pull request if you want. Paypal lately has a lot of server issues and their servers are crashing.
