### ISSUE TITLE
API credentials are incorrect.

### ISSUE THREAD

**Issue by developertester1001** [srmklive/laravel-paypal#286]
When i am trying to make the connection with Adaptive Paypal
I am getting the error 
Array
(
    [ '1.0' encoding='UTF-8'?>2019-07-28T23:20:42.246-07:00Failurea57a93542d69052656287520003PLATFORMApplicationErrorApplicationAuthentication failed. API credentials are incorrect.
)

My all crendentials are those which i got from the sandbox acount. What should i do now to resolve this??

**Comment by srmklive** [comment]
You may need to check the credentials again. Setup your ExpressCheckout API credentials to use with AdaptivePayments.
