### ISSUE TITLE
Live API credentials 

### ISSUE THREAD

**Issue by MattBoxSix** [srmklive/laravel-paypal#287]
Ok so I'm trying to go live with this app and there is little to no ready information I can find to help. I've set up a test sandbox and all works fine. I have the following credentials:

PAYPAL_CLIENT_ID=
PAYPAL_CLIENT_SECRET=
PAYPAL_MODE=

PAYPAL_SANDBOX_API_USERNAME=
PAYPAL_SANDBOX_API_PASSWORD=
PAYPAL_SANDBOX_API_SECRET=

When I go to the Paypal Business live account and request their API key, I just get the following back:
Credential **Signature**
API Username
API Password
Signature

I don't seem to be able to match what Paypal gives me to what I am currently using with this package. Does the user have to make an account and app on the Paypal developer side instead of using the API keys on the Business Account? I am lost here, this is my first time integrating on paypal.

**Comment by srmklive** [comment]
You need to do the following to setup your live credentials:

PAYPAL_MODE=live
PAYPAL_LIVE_API_USERNAME=YOUR_PAYPAL_LIVE_ACCOUNT_API_USERNAME
PAYPAL_LIVE_API_PASSWORD=YOUR_PAYPAL_LIVE_ACCOUNT_API_PASSWORD
PAYPAL_LIVE_API_SECRET=YOUR_PAYPAL_LIVE_ACCOUNT_API_SIGNATURE

**Comment by mohammadjavadz** [comment]
@srmklive 
my app is worked fine in sandbox mode but in live mode, I am confused with env.
How can I find my live username and password and signature?
All I have is Paypal Username, Client ID and Secret ID.
is PAYPAL_LIVE_API_PASSWORD the same as my Paypal account password that I use to login to my Paypal dashboard?
is PAYPAL_LIVE_ACCOUNT_API_SIGNATURE the same as my Secret ID?

All I have is shown below:
![Untitljged](https://user-images.githubusercontent.com/35491888/79686981-6b2c7f80-8259-11ea-92d0-f5f50f88bb8a.png)

**Comment by DevMostafa1998** [comment]
How to get USERNAME , PASSWORD, API_SECRET And API_CERTIFICATE
