### ISSUE TITLE
How to go live with this plugin

### ISSUE THREAD

**Issue by MattBoxSix** [srmklive/laravel-paypal#288]
So I have the following in my config\paypal.php:

```
<?php
return [
    'client_id' => env('PAYPAL_CLIENT_ID',''),
    'secret' => env('PAYPAL_CLIENT_SECRET',''),
    'settings' => array(
        'mode' => env('PAYPAL_MODE','sandbox'),
        'http.ConnectionTimeOut' => 30,
        'log.LogEnabled' => true,
        'log.FileName' => storage_path() . '/logs/paypal.log',
        'log.LogLevel' => 'ERROR'
    ),
];
```

If I have my paypal account set to be live rather than sandbox, do I only need to change the mode mentioned above to be live and thats it? Or is there a URL I need to change somewhere?

**Comment by DmitrySkibitsky** [comment]
@MattBoxSix 
![DeepinScreenshot_выберите-область_20190808064344](https://user-images.githubusercontent.com/20288556/62673674-f30e7a00-b9a7-11e9-9189-6849e8e63640.png)

**Comment by srmklive** [comment]
Please view the README for the plugin.
