### ISSUE TITLE
In adaptive payments money is not sent to the other person 

### ISSUE THREAD

**Issue by abhi99sind** [srmklive/laravel-paypal#289]
The amount is only sent to the person which has primary field equals to true... Why how to solve this issue

**Comment by srmklive** [comment]
The plugin supports PayPal Express Checkout not Adaptive Payments API. If you want to add Adaptive Payments integration, kindly open a PR with implementation.

**Comment by abhi99sind** [comment]
In your paypal controller you have given a function adaptive payments what was that then
