### ISSUE TITLE
REST or SOAP?

### ISSUE THREAD

**Issue by ipkpjersi** [srmklive/laravel-paypal#292]
Hi,

I am just wondering, does this plugin use REST or SOAP, or does it use neither? I have two options under My Apps & Credentials: 
![](https://i.imgur.com/8TGPNCg.png)

The SOAP API appears to be deprecated so I am hoping that this is using REST: https://developer.paypal.com/docs/classic/express-checkout/ec-api-flow/

Thanks.

**Comment by srmklive** [comment]
This package implements the PayPal ExpressCheckout NVP API

**Comment by ipkpjersi** [comment]
Hi,

Thank you for the response. I am still wondering which protocol the API uses, SOAP or REST or neither? I would ask PayPal but I am pretty sure they would have no idea what I am talking about.

Thanks.
