### ISSUE TITLE
Illegal string offset 'name' in ExpressCheckout.php line 73

### ISSUE THREAD

**Issue by ghorochie** [srmklive/laravel-paypal#295]
I followed your readme tutorial and then put the code like this:
```
foreach (\Session::get('cart_session') as $key => $value) {
            $data['items'] = [
                            'name'          => $value['product_name'],
                            'qty'           => $value['qty'],
                            'price'         => $value['price'],
                            'sku'           => $value['sku'],
                            ];
        }
```
Any hotfix would be a great help. Thanks

**Comment by ghorochie** [comment]
to have a clear concept of what is going on i think the code above is not related. the issue lies on your code. this is my function:

` ` `
public function paypalPayment()
    {
        $model_checkout = new Model_Checkout();
        $this->paypalProvider = new ExpressCheckout;

        $options = [
            'BRANDNAME' => 'Schwarzkummelol-Original',
            'CHANNELTYPE' => 'Merchant'
        ];

        // foreach (\Session::get('cart_session') as $key => $value) {
            $data['items'] = [
                            'name'          => 'test',
                            'qty'           => 69,
                            'price'         => 69,
                            'sku'           => 'TEST',
                            ];
        // }
        $data['invoice_id'] = $model_checkout->getLastId();

        $data['return_url'] = url('/payment/success');
        $data['cancel_url'] = url('/payment/failed');

        $data['total'] = floatval(preg_replace('/[^\d.]/', '', self::calculateGrandTotal()))/100;

        $response = $this->paypalProvider->setExpressCheckout($data);

        return redirect($response['paypal_link']);
    }
` ` `

**Comment by ghorochie** [comment]
![image](https://user-images.githubusercontent.com/53556285/64748684-8e65b280-d545-11e9-88dc-144296e1b01f.png)
debugged your code and found out that $item is not an array. the echo returned an output of
```"test"6969"TEST"```

**Comment by srmklive** [comment]
Its quite obvious that you haven't read the sample code properly. The line:

            $data['items'] = [
                            'name'          => 'test',
                            'qty'           => 69,
                            'price'         => 69,
                            'sku'           => 'TEST',
                            ];

to

            $data['items'][] = [
                            'name'          => 'test',
                            'qty'           => 69,
                            'price'         => 69,
                            'sku'           => 'TEST',
                            ];

Kindly fact check first what you are writing about, before you start pointing out anyone's mistakes
