### ISSUE TITLE
Error 11452 ("Merchant not enabled for reference transactions") without RecurringPayments

### ISSUE THREAD

**Issue by lennow** [srmklive/laravel-paypal#297]
Hi, I have this issue when laravel-paypal is trying to make the PayPal Request, although I don't want to enable recurring payments (nor reference transactions) at all. I've made sure the 'L_BILLINGTYPE0' value is set to "MerchantInitiatedBilling", I checked all data built in the ExpressCheckout Service and everything is fine until the doPayPalRequest Trait is called in the SetCheckoutExpress Method. This is where I get the error 11452.

Can you help me with this issue in some way? 
I somehow got stuck with this and have no idea why it came up all of a sudden after your CheckoutExpress package worked very well for months...

**Comment by lennow** [comment]
I solved the issue - I forgot to bind a Class to my PayPal Controller and this blew up everything else. Sorry - I was just so confused about the error message received from PayPal, it took me a while to find out the REAL issue behind that.

**Comment by SquallX** [comment]
Hi,

Can you share the solution of your resolved problem ?

Thanks

**Comment by i0sa** [comment]
Hey guys, I've been insanely searching for this issue and finally came to a solution

To fix this error you need to remove "L_BILLINGTYPE0" and "L_BILLINGAGREEMENTDESCRIPTION0" that are passed

found in file src/Services/ExpressCheckout.php,

remove this :
$this->post = $this->post->merge([
                'L_BILLINGTYPE0'                 => $billingType,
                'L_BILLINGAGREEMENTDESCRIPTION0' => !empty($data['subscription_desc']) ?
                    $data['subscription_desc'] : $data['invoice_description'],
            ]);
