### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by sicsol** [srmklive/laravel-paypal#3]
Are you looking to support 5.2 soon?

I noticed there was an issue when doing a vendor:publish 

I updated the reference to the files in `PayPalServiceProvider.php` from

`/../config/config.php` to `/../../config/config.php`

After that I received an error

`PHP Catchable fatal error:  Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given`

I commented out `notify_url` in the paypal.php file and then got this error

`PHP Fatal error:  Class 'Srmklive\PayPal\PayPalServiceProvider' not found`

**Comment by srmklive** [comment]
@sicsol Can you tell me which version of the package you installed?

**Comment by srmklive** [comment]
@sicsol Laravel 5.2 is supported. As per the issue you faced, do the following in app.php:

* Change **Srmklive\PayPal\PayPalServiceProvider.php::class** to **Srmklive\PayPal\Providers\PayPalServiceProvider.php::class**.

Also update reference to the files in PayPalServiceProvider.php from
 
    /../config/config.php to /../../config/config.php

After you have done the above two steps, then you should run:

    php artisan vendor:publish

This will publish the **config/paypal.php** file.

**Comment by sicsol** [comment]
I got it working now. Thank you
