### ISSUE TITLE
error on parse_str

### ISSUE THREAD

**Issue by havryshkevych** [srmklive/laravel-paypal#300]
https://github.com/srmklive/laravel-paypal/blob/35d520d654de719fe405cf76a8d44a1bcc48803e/src/Traits/PayPalRequest.php#L381-L390

hello, i'm using part of your code for my payment gate as paypal connector...
and get an error, `ErrorException Object of class GuzzleHttp\\Psr7\\Request could not be converted to string`,  
so i just fix this for me
```php
    private function makeHttpRequest()
    {
        try {
            if ($this->client == null)
                $this->setHttpClientConfiguration();
            return $this->client->post($this->apiUrl, [
                $this->httpBodyParam => $this->post->toArray(),
-            ])->getBody();
+            ])->getBody()->getContents();
        } catch (HttpClientException $e) {
            throw new Exception($e->getRequest().' '.$e->getResponse());
        } catch (HttpServerException $e) {
            throw new Exception($e->getRequest().' '.$e->getResponse());
        } catch (HttpBadResponseException $e) {
            throw new Exception($e->getRequest().' '.$e->getResponse());
        }
    }
```

maybe it will be useful for you

**Comment by srmklive** [comment]
Kindly open a PR for this so i can merge. Thanks.

**Comment by forest1206** [comment]
thank you for your awesome work @srmklive .

>$response = $this->provider->createSubscription($data);
>if (array_key_exists('type', $response) && $response['type'] === 'error') {
>       return response()->json(['message' => $response['message']]);
>}

Currently, $response is combined message of request and response.

> $e->getRequest().' '.$e->getResponse();

But I want to get only $e->getResponse().  How can I do that?
