### ISSUE TITLE
New API Credentials

### ISSUE THREAD

**Issue by archmaster01** [srmklive/laravel-paypal#301]
I´m trying to implement laravel-paypal on my Laravel project, but apparently PayPal´s Sandbox API Credentials have changed, there´s no longer a USERNAME, PASSWORD or CERTIFICATE. 
What´s current is:
Sandbox account: sb-l.......
Client ID: Acm.......
Secret: EBI......

![191023 PayPal Sandbox API Credentials](https://user-images.githubusercontent.com/47488268/67449839-2644ca80-f5e1-11e9-8416-abf58db9d552.jpg)

Where do I go from here??

**Comment by augustinejenin** [comment]
Go to your accouns tab.there you can see the paypal accounts. Edit the business account there you can see the api credentials

**Comment by FreddyCrugger** [comment]
Same for me.
When you create on generating API credentials You only get the choice between:
-Sandbox account/Live
-Client ID
-Secret

But the ENV the script is asking are:
```
PAYPAL_SANDBOX_API_USERNAME
PAYPAL_SANDBOX_API_PASSWORD
PAYPAL_SANDBOX_API_SECRET
PAYPAL_SANDBOX_API_CERTIFICATE
```

The requested details between the script and what paypal asks for do not match.

I went to:
Dashboard>>My Apps & Credentials >> and create an app either for the sandbox or live testing.

Now even if you click on the sandbox account itself as the above post asks for and tried to get the credentials from there, the credentials do not match either.

**Comment by FreddyCrugger** [comment]
Alright I think I worked it out.
The documentation is not clear at all on this.
To get your live account credentials, follow this:
https://github.com/srmklive/laravel-paypal/issues/242

To get the sandbox credential, you will need to go here:
https://developer.paypal.com

Go to:
My apps and credentials>>select a seller account, and look for credentials settings(looking the same as the live account credentials from the first link.

the PAYPAL_SANDBOX_API_CERTIFICATE= seems to be not needed.

**Comment by 4unkur** [comment]
There is a link in the docs to Paypal docs: https://github.com/srmklive/laravel-paypal#paypal-api-credentials

There are 2 types of API credentials: Certificate & Secret

So if you are using Secret, then you don't need to specify PAYPAL_SANDBOX_API_CERTIFICATE

**Comment by srmklive** [comment]
Closing issue as queries has already been answered.
