### ISSUE TITLE
How to get the transaction id after the Payment

### ISSUE THREAD

**Issue by augustinejenin** [srmklive/laravel-paypal#302]
My transaction is working fine. I need to get the transaction id after the payment. I use below function to get the transaction details

$response = $provider->getTransactionDetails($token);

But i get the following response
Array ( [ADDRESSOWNER] => PayPal [ADDRESSSTATUS] => None [TIMESTAMP] => 2019-10-25T12:14:35Z [CORRELATIONID] => 33da24eeagg3816 [ACK] => Failure [VERSION] => 123 [BUILD] => 53714519 [L_ERRORCODE0] => 10004 [L_SHORTMESSAGE0] => Transaction refused because of an invalid argument. See additional error messages for details. [L_LONGMESSAGE0] => The transaction id is not valid [L_SEVERITYCODE0] => Error [PENDINGREASON] => None [REASONCODE] => None [L_TAXABLE0] => false )

I am using { $payment_status = $this->provider->doExpressCheckoutPayment($cart, $token, $PayerID);} 
I am stuck with how to get the transaction id Becasue the payment is succes.

Here is my function. How can i get the transaction id.

public function getExpressCheckoutSuccess(Request $request)
    {
        $recurring = ($request->get('mode') === 'recurring') ? true : false;
        $token = $request->get('token');
        $PayerID = $request->get('PayerID');

        $cart = $this->getCheckoutData($recurring);

        // Verify Express Checkout Token
        $response = $this->provider->getExpressCheckoutDetails($token);
        
        if (in_array(strtoupper($response['ACK']), ['SUCCESS', 'SUCCESSWITHWARNING'])) {
            if ($recurring === true) {
                $response = $this->provider->createMonthlySubscription($response['TOKEN'], 9.99, $cart['subscription_desc']);
                if (!empty($response['PROFILESTATUS']) && in_array($response['PROFILESTATUS'], ['ActiveProfile', 'PendingProfile'])) {
                    $status = 'Processed';
                } else {
                    $status = 'Invalid';
                }
            } else {
                // Perform transaction on PayPal
                $payment_status = $this->provider->doExpressCheckoutPayment($cart, $token, $PayerID);
               $tstat = $this->provider->getTransactionDetails($token);
                print_r($tstat);exit;// I dont get the transaction id here
                $status = $payment_status['PAYMENTINFO_0_PAYMENTSTATUS'];
            }

            $invoice = $this->createInvoice($cart, $status);

            if ($invoice->paid) {
                session()->put(['code' => 'success', 'message' => "Order $invoice->id has been paid successfully!"]);
            } else {
                session()->put(['code' => 'danger', 'message' => "Error processing PayPal payment for Order $invoice->id!"]);
            }

            return redirect('/');
        }
    }

**Comment by vipertecpro** [comment]
Please read this code more carefully,


```
    public function paymentStatus($applicationId){
        /** Get the payment ID before session clear **/
        $payment_id = Input::get('paymentId');
        /** clear the session payment ID **/
        \Session::forget('paypal_payment_id');
        if (empty(Input::get('PayerID')) || empty(Input::get('token'))) {
            return redirect()->back()->with([
                'status'    => 'danger',
                'message'   => 'Payment failed'
            ]);
        }
        $payment = Payment::get($payment_id, $this->_api_context);
        $execution = new PaymentExecution();
        $execution->setPayerId(Input::get('PayerID'));
        /**Execute the payment **/
        $result = $payment->execute($execution, $this->_api_context);
        if ($result->getState() === 'approved') {
            PaymentsTable::where('application_id',$applicationId)->update([
                'payment_status'    => 'paid',
                'transaction_id'    => $result->transactions[0]->related_resources[0]->sale->id, // Here you'll get your transaction ID
                'order_id'          => $payment_id
            ]);
	        \Notify::success('Payment Done successfully.');
            return redirect()->route('showUploadDocuments',$applicationId)->with([
                'status'    => 'success',
                'message'   => 'Payment successfully done. Please proceed to upload documents.'
            ]);
        }
        return redirect()->back()->with([
            'status'    => 'danger',
            'message'   => 'Payment failed'
        ]);
    }
```

**Comment by augustinejenin** [comment]
> Please read this code more carefully,
> 
> ```
>     public function paymentStatus($applicationId){
>         /** Get the payment ID before session clear **/
>         $payment_id = Input::get('paymentId');
>         /** clear the session payment ID **/
>         \Session::forget('paypal_payment_id');
>         if (empty(Input::get('PayerID')) || empty(Input::get('token'))) {
>             return redirect()->back()->with([
>                 'status'    => 'danger',
>                 'message'   => 'Payment failed'
>             ]);
>         }
>         $payment = Payment::get($payment_id, $this->_api_context);
>         $execution = new PaymentExecution();
>         $execution->setPayerId(Input::get('PayerID'));
>         /**Execute the payment **/
>         $result = $payment->execute($execution, $this->_api_context);
>         if ($result->getState() === 'approved') {
>             PaymentsTable::where('application_id',$applicationId)->update([
>                 'payment_status'    => 'paid',
>                 'transaction_id'    => $result->transactions[0]->related_resources[0]->sale->id, // Here you'll get your transaction ID
>                 'order_id'          => $payment_id
>             ]);
> 	        \Notify::success('Payment Done successfully.');
>             return redirect()->route('showUploadDocuments',$applicationId)->with([
>                 'status'    => 'success',
>                 'message'   => 'Payment successfully done. Please proceed to upload documents.'
>             ]);
>         }
>         return redirect()->back()->with([
>             'status'    => 'danger',
>             'message'   => 'Payment failed'
>         ]);
>     }
> ```
> 
> From your code i think if you `dd($payment_status)` your code, i'm sure you'll get your transaction ID, while direct payment you can extract your transaction ID something like this
> `$result->transactions[0]->related_resources[0]->sale->id`
> if your ordering then
> `$result->transactions[0]->related_resources[0]->order->id`
> 
> I hope this helps somehow. but that worked for me well.

There was no transaction id in dd($payment_status). I checked that.

**Comment by vipertecpro** [comment]
> > Please read this code more carefully,
> > ```
> >     public function paymentStatus($applicationId){
> >         /** Get the payment ID before session clear **/
> >         $payment_id = Input::get('paymentId');
> >         /** clear the session payment ID **/
> >         \Session::forget('paypal_payment_id');
> >         if (empty(Input::get('PayerID')) || empty(Input::get('token'))) {
> >             return redirect()->back()->with([
> >                 'status'    => 'danger',
> >                 'message'   => 'Payment failed'
> >             ]);
> >         }
> >         $payment = Payment::get($payment_id, $this->_api_context);
> >         $execution = new PaymentExecution();
> >         $execution->setPayerId(Input::get('PayerID'));
> >         /**Execute the payment **/
> >         $result = $payment->execute($execution, $this->_api_context);
> >         if ($result->getState() === 'approved') {
> >             PaymentsTable::where('application_id',$applicationId)->update([
> >                 'payment_status'    => 'paid',
> >                 'transaction_id'    => $result->transactions[0]->related_resources[0]->sale->id, // Here you'll get your transaction ID
> >                 'order_id'          => $payment_id
> >             ]);
> > 	        \Notify::success('Payment Done successfully.');
> >             return redirect()->route('showUploadDocuments',$applicationId)->with([
> >                 'status'    => 'success',
> >                 'message'   => 'Payment successfully done. Please proceed to upload documents.'
> >             ]);
> >         }
> >         return redirect()->back()->with([
> >             'status'    => 'danger',
> >             'message'   => 'Payment failed'
> >         ]);
> >     }
> > ```
> > 
> > 
> > From your code i think if you `dd($payment_status)` your code, i'm sure you'll get your transaction ID, while direct payment you can extract your transaction ID something like this
> > `$result->transactions[0]->related_resources[0]->sale->id`
> > if your ordering then
> > `$result->transactions[0]->related_resources[0]->order->id`
> > I hope this helps somehow. but that worked for me well.
> 
> There was no transaction id in dd($payment_status). I checked that.

Are you not getting response like that https://developer.paypal.com/docs/classic/express-checkout/ec-finalize-payment/#response ?

**Comment by vipertecpro** [comment]
ohhh crap, i'm using this packages ""paypal/rest-api-sdk-php": "^1.14", so sorry for misleading.
