### ISSUE TITLE
Version 1.6.10 does not have latests commits

### ISSUE THREAD

**Issue by sytheveenje** [srmklive/laravel-paypal#307]
When installing this package with composer, I don't get the latest commits from [here](https://github.com/srmklive/laravel-paypal/releases/tag/1.6.10)

Composer actually installs `1.6.10`, but when I go into `vendor/srmklive/paypal/src/Services/ExpressCheckout.php` it doen't contain what it says release note (e.g. my commits and your style fix)

What am I doing wrong?

Fixed it by using:
`"srmklive/paypal": "dev-master"` in my composer file, but somethings wrong with the versioning in this package.

**Comment by srmklive** [comment]
You may need to remove the package from composer.json and run `composer update`. Then add it again using `composer require srmklive/paypal`. This should fix the issue.
