### ISSUE TITLE
How should I check response code 400 when a card decline?

### ISSUE THREAD

**Issue by nehulagr** [srmklive/laravel-paypal#308]
Hello, I am using your payment gateway, and its an amazing package, very handy and simple to use. 

One simple thing I am not able to understand is, there is no way to check if there is any card decline for insufficient funds, then how can I check and on which URL it will be redirected? 

Also if I go to payment gateway then press back button on the browser then also I get response code 400. 

Any suggestions? 

Thank you!

**Comment by srmklive** [comment]
You need to setup IPN on your PayPal account, and check for such use cases in your IPN url.
