### ISSUE TITLE
Error with Sandbox Live

### ISSUE THREAD

**Issue by SquallX** [srmklive/laravel-paypal#309]
Hi,

Currently I am experiencing an error when I try to make a payment with Paypal. Everything seems well configured paypal side, but I always get the following error:

Merchant not enabled for reference transactions

In spite of that I receive the link paypal, the payment can continue, but when I arrive on the page of redirection, the information recovered via "createBillingAgreement" are incomplete, the key "BILLINGAGREEMENTID" is not indicated, and the payment does not in reality realized.

How can I fix that? Are there any particular settings to put in place?

Thank you !

Regards,
Alex.

**Comment by SquallX** [comment]
Anybody can help ?

**Comment by srmklive** [comment]
It is possible that your paypal account is not either a business account or it is not enabled to create recurring billing or billing agreements. You need to check with PayPal support why it is throwing this error.

**Comment by rodriigomedeiros** [comment]
Hello @SquallX, did you manage to solve your problem?
