### ISSUE TITLE
Webhooks from payments using this plugin are missing a lot of valuable info

### ISSUE THREAD

**Issue by bcceducation** [srmklive/laravel-paypal#311]
More specifically they are missing two extremely vital pieces.

"receipt_id": "xxx"
"parent_payment": "PAY-xxx"

You can use this with the paypal api to actually go further into a rabit hole of data for a purchase. Without this as far as I know it makes it so the webhook can't run smoothly with the paypal api at all.

**Comment by srmklive** [comment]
If you come up with a solution that handles most of the use cases, kindly open a PR so i can merge.
