### ISSUE TITLE
Disappointing ExpressCheckout is not handling discount_amount_cart and many other basic variables.

### ISSUE THREAD

**Issue by virkse** [srmklive/laravel-paypal#318]
Actually you dealing all discounts as shipping discounts. So user is confused here, they want to see actual cart discount with "discount_amount_cart"
Is is possible you can add this paypal variable to the package? and keep the shipping_discount separate?

Thanks

**Comment by srmklive** [comment]
You can add a specific variable to an API operation using `addOptions` method. Please review the README file before posting any comments. If you feel any additions are required, kindly open a PR for inclusion into the package.

**Comment by srmklive** [comment]
https://github.com/srmklive/laravel-paypal#additional-paypal-api-parameters

**Comment by virkse** [comment]
Hi @srmklive  Thanks for guide here is my code. But "discount_amount_cart" is not applying when landing on paypal checkout page. can you please check what is wrong with my code?
`$data = [];
        $products = Session::get('cart.products');
        $item_count = 1;
        foreach($products as $product) {
            foreach($product['options'] as $option) {
                $name = $product['product_name'];
                $desc = $product['product_name'] . ' - ' . $option['description'];
                $base_price = 0;
                if(array_key_exists('base_price', $option)) {
                    $base_price = $option['base_price'];
                }
                $price = $option['price'] + $base_price;
                $qty = $option['quantity'];
                $v = [
                    'name' => $name,
                    'price' => number_format($price, 2, '.', ''),
                    'desc'  => $desc,
                    'qty' => $qty
                ];
                $data['items'][] = $v;
                $item_count++;
            }
        }
        //$data['cmd'] = '_cart';
        //$data['upload'] = 1;
        $data['custom'] = $request->invoice_id;

        $data['subtotal'] = number_format(Session::get('cart.total'), 2, '.', '');
        $data['total'] = number_format((Session::get('cart.total') + Session::get('cart.shipping_price')), 2, '.', '');
        //$data['discount_amount_cart'] = Session::get('cart.coupon_discount_amount');
        //$data['shipping_discount'] = number_format(Session::get('cart.coupon_discount_amount'), 2, '.', '');
        $data['shipping'] = number_format(Session::get('cart.shipping_price'), 2, '.', '');
        $data['invoice_id'] = $request->invoice_id;
        $data['invoice_description'] = "Order #{$data['invoice_id']} Invoice";
        $data['return_url'] = route('checkout.success', ['ab' => base64_encode($data['invoice_id'])]);
        $data['cancel_url'] = route('cart');
        //dd($data);

        $paypal_options = [
            "cmd" => "_cart",
            "upload" => 1,
            "discount_amount_cart" => number_format(Session::get('cart.coupon_discount_amount'), 2, '.', '')
        ];

        //dd($paypal_options);

        $provider = new ExpressCheckout;
        //$response = $provider->setExpressCheckout($data);
        $response = $provider->addOptions($paypal_options)->setExpressCheckout($data);
        // This will redirect user to PayPal
        //dd($response);
        return redirect($response['paypal_link']);`
