### ISSUE TITLE
Missing 'qty' data parameter in docs

### ISSUE THREAD

**Issue by omer414** [srmklive/laravel-paypal#32]
** The doc was also missing a few new changes and some clarifications, **so i sent a pull request**** 
1) A new 'qty' attribute has been added, so the new format should be 
```
 $data['items'] = [
            [
                'name' => 'Product 1',
                'price' => 9.99,
                'qty' => 1
            ],
            [
                'name' => 'Product 2',
                'price' => 4.99,
                'qty' => 1
            ]
        ];
```
2) Also in the docs it should be clear that secret refereces the signature.

**Comment by srmklive** [comment]
Fixed in #31.
