### ISSUE TITLE
Paypal Express checkout return successfully but payment is not deducting

### ISSUE THREAD

**Issue by virkse** [srmklive/laravel-paypal#320]
Hello
i facing this critical issue, customer pay on paypal and return successfully but didn't get deducted his amount not added to merchant account.

I'll thanks to help in this issue.

**Comment by srmklive** [comment]
Kindly provide detailes for the issue being faced.

**Comment by JPQueirozPerez** [comment]
Hi, I facing the same issue. Doesn't matter if it's sandbox or live mode, the payment seems to be done correctly, returning the success page and sending the order email to the customer, but neither the amount in question is reduced in the customer's account nor in the store's account is that amount added. Thanks in advance for the help.

**My paypal.php**:

`return [
    'mode'    => env('PAYPAL_MODE', 'sandbox'), // Can only be 'sandbox' Or 'live'. If empty or invalid, 'live' will be used.
    'sandbox' => [
        'username'    => env('PAYPAL_SANDBOX_API_USERNAME', ''),
        'password'    => env('PAYPAL_SANDBOX_API_PASSWORD', ''),
        'secret'      => env('PAYPAL_SANDBOX_API_SECRET', ''),
        'certificate' => env('PAYPAL_SANDBOX_API_CERTIFICATE', ''),
        'app_id'      => '', // Used for testing Adaptive Payments API in sandbox mode
    ],
    'live' => [
        'username'    => env('PAYPAL_LIVE_API_USERNAME', ''),
        'password'    => env('PAYPAL_LIVE_API_PASSWORD', ''),
        'secret'      => env('PAYPAL_LIVE_API_SECRET', ''),
        'certificate' => env('PAYPAL_LIVE_API_CERTIFICATE', ''),
        'app_id'      => '', // Used for Adaptive Payments API
    ],

    'payment_action' => 'Sale', // Can only be 'Sale', 'Authorization' or 'Order'
    'currency'       => env('PAYPAL_CURRENCY', 'EUR'),
    'billing_type'   => 'MerchantInitiatedBilling',
    'notify_url'     => '', // Change this accordingly for your application.
    'locale'         => '', // force gateway language  i.e. it_IT, es_ES, en_US ... (for express checkout only)
    'validate_ssl'   => true, // Validate SSL when creating api client.
];`


**My PaymentController.php**:

`namespace App\Http\Controllers;

use Mail;  
  
use Illuminate\Http\Request;
use App\Sale;
use App\Product;
use App\Shipping;

use Srmklive\PayPal\Services\ExpressCheckout;
   
class PaymentController extends Controller
{

    public function payment()
    {
        $product = Product::find(request('product'));
        $shipping = Shipping::find(request('shipment'));
        $sale = new Sale([
            'product_id' => $product->id,
            'quantity' => 1,
            'name' => request('name'),
            'lastname' => request('lname'),
            'company' => request('company'),
            'country' => request('country'),
            'street' => request('street'),
            'city' => request('city'),
            'location' => request('location'),
            'postalcode' => request('postcode'),
            'email' => request('email'),
            'phone' => request('phone'),
            'notes' => request('notes'),
        ]);
        $sale->save();


        $data = [];
        $data['items'] = [
            [
                'name' => $product->title, 
                'price' => $product->price, 
                'qty' => 1 
            ],
            [
                'name' => 'Shipment',
                'price' => $shipping->price,
                'qty' => 1
            ]
        ];
  
        $data['invoice_id'] = $sale->id;
        $data['invoice_description'] = "Order #{$data['invoice_id']} Invoice";
        $data['return_url'] = route('payment.return'); 
        $data['cancel_url'] = route('shop', app()->getLocale()); 
        
        $total = 0;
        foreach($data['items'] as $item) {
            $total += $item['price']*$item['qty'];
        }

        $data['total'] = $total;
  
        $provider = new ExpressCheckout;
        $response = $provider->setExpressCheckout($data);
        $response = $provider->setExpressCheckout($data, true);

        

        return redirect($response['paypal_link']);

    }
   
    public function cancelPayment()
    {
    }
  

    public function paymentReturn(Request $request)
    {

        $provider = new ExpressCheckout;
    
        $response = $provider->getExpressCheckoutDetails($request->token);
  
        $sale = Sale::find($response['INVNUM']);
        if (in_array(strtoupper($response['ACK']), ['SUCCESS', 'SUCCESSWITHWARNING'])) {
            $sale->update(['payment_status' => 'success']);
           
          $product = Product::find($sale->product->id);
          $product->update(['available' => 0]);

            
           Mail::send('emails.shipment', ['sale' => $sale], function($m) use ($sale) {
           $m->from('', '');
           $m->to($sale->email, $sale->name)->subject('Thanks for your order');
           $m->replyto('');
           });

            return redirect()->route('payment.success', app()->getLocale());
        }else{
            $sale->update(['payment_status' => 'error']);
            return redirect()->route('payment.error', app()->getLocale());
        }
    }`

**Comment by osamamoinchawla** [comment]
Hello owner, don't be a boss here, before closing any issue ask the member if he/she has solved the problem!! totally disgusting. I am also facing the same problem. did you have any solution. IF have so reply
