### ISSUE TITLE
overriding the config file variables for SAAS platform

### ISSUE THREAD

**Issue by omer414** [srmklive/laravel-paypal#33]
I am working on a saas system where site partners add their paypal info and then get paid by their users directly. But the config file hardcodes this info, is it possible to override these variables from the controller ?

**Comment by srmklive** [comment]
@omer414 Can you update temporarily to the `dev-master` version and use the `setApiCredentials` method to dynamically set the Api Ccredentials;

**Comment by omer414** [comment]
Thanks @srmklive, i will get back to you after i test this out.
