### ISSUE TITLE
Undefined Variable: Provider 

### ISSUE THREAD

**Issue by GrnPero** [srmklive/laravel-paypal#330]
Hello, I seem to be getting an error message after I go through the payment screen for paypal.
![Code](https://user-images.githubusercontent.com/44035269/76650280-7a643300-651f-11ea-8375-83239b8bc21f.PNG)
![Error](https://user-images.githubusercontent.com/44035269/76650281-7a643300-651f-11ea-8d9d-59f74aca2304.PNG)

**Comment by rikcomery** [comment]
I am having this exact same problem.  Did you find a resolution?

**Comment by GrnPero** [comment]
> I am having this exact same problem.  Did you find a resolution?

Sadly no.

**Comment by srmklive** [comment]
You do realize your mistake right :stuck_out_tongue_closed_eyes:?

**Comment by shadracnicholas** [comment]
No we dont

**Comment by shadracnicholas** [comment]
I just realized the mistake.

Add in function;

$provider = new ExpressCheckout;
