### ISSUE TITLE
Undefined index: payKey

### ISSUE THREAD

**Issue by karan-bacancy** [srmklive/laravel-paypal#331]
Hello @srmklive

           $this->provider = new AdaptivePayments();

            $data = [
                'receivers'  => [
                    [
                        'email'   => 'sb-abc@business.example.com',
                        'amount'  => 100,
                        'primary' => true,
                    ],
                    [
                        'email'   => 'sb-xyz@business.example.com',
                        'amount'  => 10,
                        'primary' => false
                    ],
                ],
                'payer'      => 'EACHRECEIVER', // (Optional) Describes who pays PayPal fees. Allowed values are: 'SENDER', 'PRIMARYRECEIVER', 'EACHRECEIVER' (Default), 'SECONDARYONLY'
                'return_url' => url('payment/success'),
                'cancel_url' => url('payment/cancel'),
            ];
         $response = $this->provider->createPayRequest($data);
         $redirect_url = $this->provider->getRedirectUrl('approved', $response['payKey']);

I have put this code on my local for adaptive payment but it's give me error like  :: **Undefined index: payKey**. It's not creating response from createPayRequest.

My  Project PHP version : 7.3.5 Larave Version :: ^6.2  "srmklive/paypal": "^1.7",

Also on success function  how we can get success adaptive payment data..?

Please let me know solution asasp as I have stuck with problem

Thanks 
karan shah

**Comment by dblencowe** [comment]
Hey @karan-bacancy,

Do you have a full stack trace for this? Remember to remove any sensitive information it may contain.

**Comment by karan-bacancy** [comment]
No it's all same sandbox business account information that we have use before but now it's not working..
it's give me error like  :: **Undefined index: payKey. It's not creating response from createPayRequest.**

can you please tell me solution asasp.. bcz my site just stop to take payment process..

**Comment by karan-bacancy** [comment]
Hello @dblencowe @srmklive 

Please give me appropriate solution  this is issue still not resolved..Please don't close this issue.

This is bug on your lib plz give me soltuion and answer
