### ISSUE TITLE
Dynamic email receiving funds

### ISSUE THREAD

**Issue by novakben** [srmklive/laravel-paypal#334]
Hey, working on a marketplace,
how do I enable the express checkout for sellers that are not me by passing their paypal account email address? (Sellers)
Kinda like adaptive payment but the whole sum goes to the seller.

**Comment by c0ak** [comment]
Hey, sorry for not answering your question here but I was wondering if this package actually works with PayPal even with their new API?

**Comment by novakben** [comment]
I ended up using the native sdk

**Comment by c0ak** [comment]
> I ended up using the native sdk

Did you make your own wrapper for it? Would love you if you could make it public :)

**Comment by novakben** [comment]
@c0ak This is how you do with the [Paypal PHP SDK](https://github.com/paypal/PayPal-PHP-SDK)

 ```
        use PayPal\Api\Payee;
        $payee = new Payee();
        $payee->setEmail('person_who@isGettingTheMoney.com');
```

**Comment by c0ak** [comment]
> @c0ak This is how you do with the [Paypal PHP SDK](https://github.com/paypal/PayPal-PHP-SDK)
> 
> ```
>        use PayPal\Api\Payee;
>        $payee = new Payee();
>        $payee->setEmail('person_who@isGettingTheMoney.com');
> ```

An this works with the latest version of the API?

**Comment by novakben** [comment]
yep
