### ISSUE TITLE
Is there any solution for twice calling return URl..?

### ISSUE THREAD

**Issue by karan-bacancy** [srmklive/laravel-paypal#339]
Hello @srmklive 

I m using adaptive payment by using this plugin. but i have faced one issue when user click "Return" button over paypal page after paying it's calling our return success/cancel URL twice time..

But if we do not click on "Retrun" button and wait for auto redirect to success page it's call perfect one time 

Please provide suggestion or solution for same

Thanks in Advance

**Comment by srmklive** [comment]
Please refer to Readme file, Adaptive Payment is not fully supported. If you like any additions regarding that, open a PR for it.
