### ISSUE TITLE
Some issues with ipn listner sandboxed

### ISSUE THREAD

**Issue by omer414** [srmklive/laravel-paypal#34]
So i have a local setup, with ngrok (ngrok exposes your local site to the internet). I have also updated the ipn url in paypal's website.

The issue is that i dont get any notification back from paypal after the payment is complete.  But when i try using the ipn simulator it responds back with proper post request. Now when the post request is passed through the **"verifyIPN"** method, it just gives an empty array shown below.

```
Array
(
    [INVALID] => 
)
```

**So i have 2 questions,** 

1. does ipn work with Sandbox?
2. why does the verifyIpn takes in a proper POST request from the simulator and destroys it? Is it a bug?

**Thanks again for this great library, i am really loving it :)**

**Comment by srmklive** [comment]
@omer414 yes IPN definitely works with sandbox.  I would suggest that you deploy the application on a cloud server through a domain address. This way paypal will be able to post IPN data to the URL you specify. Make sure you follow the guide on how to properly set it up.
