### ISSUE TITLE
Security header is not valid

### ISSUE THREAD

**Issue by aliraza93** [srmklive/laravel-paypal#340]
Assalam O Alaikum !
I've tested the application using sandbox and it got well. Everything was okay but I changed sandbox to live and it's credentials along with, I get an error "Security header is not valid".

Kindly do let me know if it is not getting token or something like that 

Thanks

**Comment by aotearoait** [comment]
Same issue here

**Comment by srmklive** [comment]
Check your configuration & credentials. The issue is there
