### ISSUE TITLE
Add credit card/debit card option in live paypal processing

### ISSUE THREAD

**Issue by aliraza93** [srmklive/laravel-paypal#342]
Hello sir
I'v used your package and it's awesome. I just wanted to know the way we can **enable credit card/debit card option** so that we don't have to force users to pay by logging in to their account.
In sandbox testing, they show the credit card/debit card option and create an account option but in the live payment processing there is just username and password for the account.

Can you please let me know **how to enable/add that in laravel application?**
Thanks

**Comment by srmklive** [comment]
That is actually done through the PayPal business account setting. Refer to PayPal documentation for this
