### ISSUE TITLE
$provider->createPayRequest($data) returns type error with no message

### ISSUE THREAD

**Issue by hachiweb** [srmklive/laravel-paypal#344]
I am trying to implement this plugin, unfortunately not getting any success.

 ```
$response = $provider->createPayRequest($data);
 echo '<pre>';
 print_r($response);
 exit;
$response returns
```

```
Array
(
 [type] => error
 [message] => 
)
```
I have passed all the required information like PAYPAL_SANDBOX_API_USERNAME, PAYPAL_SANDBOX_API_PASSWORD, PAYPAL_SANDBOX_API_SECRET, PAYPAL_SANDBOX_API_CERTIFICATE(now signature) in the env file

I have tried it on local as well as live server which has SSL installed, still get the same response. 
Please let me know what am I doing wrong.

**Comment by Pulstarter** [comment]
Same problem here. Paypal return no message (sandbox and live), but only on server. The configuration was working a few days ago.

On localhost it's working, so it must be something related to the server, but I can't fund a way to debug it.

Any ideas?

**Comment by Pulstarter** [comment]
I found the problem. On the PayPalHttpClient class the method makeHttpRequest it's giving the exception **idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated**, and this is a [known issue of guzzle 6.5.3 ](https://github.com/guzzle/guzzle/issues/2620)

I have updated to guzzle 6.5.4 and the error is gone.

**Comment by hachiweb** [comment]
Nope, no luck here.

> I found the problem. On the PayPalHttpClient class the method makeHttpRequest it's giving the exception **idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated**, and this is a [known issue of guzzle 6.5.3 ](https://github.com/guzzle/guzzle/issues/2620)
> 
> I have updated to guzzle 6.5.4 and the error is gone.

**Comment by hachiweb** [comment]
> I found the problem. On the PayPalHttpClient class the method makeHttpRequest it's giving the exception **idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated**, and this is a [known issue of guzzle 6.5.3 ](https://github.com/guzzle/guzzle/issues/2620)
> 
> I have updated to guzzle 6.5.4 and the error is gone.

BTW, How did you find the issue? I can't see anywhere in the log.
Also, will appreciate if you can share relevant composer installable set of packages cause I don't see any prerequisites in srmklive.laravel-paypal installation instructions.

**Comment by hachiweb** [comment]
> I found the problem. On the PayPalHttpClient class the method makeHttpRequest it's giving the exception **idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated**, and this is a [known issue of guzzle 6.5.3 ](https://github.com/guzzle/guzzle/issues/2620)
> 
> I have updated to guzzle 6.5.4 and the error is gone.
It's certainly going to catch block, something is not right with http request.
![image](https://user-images.githubusercontent.com/33425893/82999056-1cc38b00-a026-11ea-9ba3-addf5f853966.png)

**Comment by hachiweb** [comment]
Finally managed to get the error
Array
(
    [type] => error
    [message] => cURL error 58: could not load PEM client certificate, OpenSSL error error:02001002:system library:fopen:No such file or directory, (no key found, wrong pass phrase, or wrong file format?) (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
)

**Comment by reovilsayed** [comment]
hello, How I can pass shipping address and billing address?
