### ISSUE TITLE
Issue with subscription: Invalid Token

### ISSUE THREAD

**Issue by omer414** [srmklive/laravel-paypal#35]
I have this createSubscrption method, which first uses setExpresscheckout to get the token (as defined in the docs). Then it passes this token to createRecurringProfile to create a profile.
```

public function createSubscription(){
        $data['items'] = [   [
                'name' => 'ISO 27000 Foundation',
                'price' => 0.99,
                'qty' => 1
            ] ];
        $response = $this->setExpressCheckout($data);

        if( isset($response['TOKEN']) ){
            $data['subscription_desc'] = 'My new Subscription';
            $result = $this->CreateRecurringProfile($response['TOKEN'], $data);
            dd($result);
        }
    }
```

**The first method i.e setExpressCheckout works fine and generates a token, but the next method gives an error** 

```
/********** Result from setExpressCheckout **************/
array:7 [▼
  "TOKEN" => "EC-8X3617038X889902Y"
  "TIMESTAMP" => "2016-08-16T14:58:26Z"
  "CORRELATIONID" => "84662783446a6"
  "ACK" => "Success"
  "VERSION" => "123"
  "BUILD" => "24362847"
  "paypal_link" => "https://www.sandbox.paypal.com/webscr?cmd=_express-checkout&token=EC-8X3617038X889902Y"
]

/********** Result from CreateRecurringProfile**************/
array:9 [▼
  "TIMESTAMP" => "2016-08-16T14:53:57Z"
  "CORRELATIONID" => "e54dd07c255f6"
  "ACK" => "Failure"
  "VERSION" => "123"
  "BUILD" => "000000"
  "L_ERRORCODE0" => "11502"
  "L_SHORTMESSAGE0" => "Invalid Token"
  "L_LONGMESSAGE0" => "The token is invalid"
  "L_SEVERITYCODE0" => "Error"
]
```
**Is this the correct way to creating a profile?**

**Comment by srmklive** [comment]
@omer414 refer to this [thread](https://github.com/srmklive/laravel-paypal/issues/16) regarding this issue.

**Comment by raihancse104** [comment]
Array
(
    [TOKEN] => EC-8692705440781714C
    [BILLINGAGREEMENTACCEPTEDSTATUS] => 1
    [CHECKOUTSTATUS] => PaymentActionNotInitiated
    [TIMESTAMP] => 2017-04-26T04:53:06Z
    [CORRELATIONID] => 5a0c99bba7267
    [ACK] => Success
    [VERSION] => 123
    [BUILD] => 32574509
    [EMAIL] => happytrading2016-buyer@gmail.com
    [PAYERID] => KWSCZR5L9LH5G
    [PAYERSTATUS] => verified
    [FIRSTNAME] => test
    [LASTNAME] => buyer
    [COUNTRYCODE] => AU
    [CURRENCYCODE] => USD
    [AMT] => 9.99
    [ITEMAMT] => 9.99
    [SHIPPINGAMT] => 0.00
    [HANDLINGAMT] => 0.00
    [TAXAMT] => 0.00
    [DESC] => Order #bff35eac09416af1c5a30876e4718465 Invoice for package 100
    [INVNUM] => bff35eac09416af1c5a30876e4718465
    [INSURANCEAMT] => 0.00
    [SHIPDISCAMT] => 0.00
    [L_NAME0] => 100bff35eac09416af1c5a30876e4718465
    [L_QTY0] => 1
    [L_TAXAMT0] => 0.00
    [L_AMT0] => 9.99
    [L_ITEMWEIGHTVALUE0] =>    0.00000
    [L_ITEMLENGTHVALUE0] =>    0.00000
    [L_ITEMWIDTHVALUE0] =>    0.00000
    [L_ITEMHEIGHTVALUE0] =>    0.00000
    [PAYMENTREQUEST_0_CURRENCYCODE] => USD
    [PAYMENTREQUEST_0_AMT] => 9.99
    [PAYMENTREQUEST_0_ITEMAMT] => 9.99
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 0.00
    [PAYMENTREQUEST_0_HANDLINGAMT] => 0.00
    [PAYMENTREQUEST_0_TAXAMT] => 0.00
    [PAYMENTREQUEST_0_DESC] => Order #bff35eac09416af1c5a30876e4718465 Invoice for package 100
    [PAYMENTREQUEST_0_INVNUM] => bff35eac09416af1c5a30876e4718465
    [PAYMENTREQUEST_0_INSURANCEAMT] => 0.00
    [PAYMENTREQUEST_0_SHIPDISCAMT] => 0.00
    [PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED] => false
    [PAYMENTREQUEST_0_ADDRESSNORMALIZATIONSTATUS] => None
    [L_PAYMENTREQUEST_0_NAME0] => 100bff35eac09416af1c5a30876e4718465
    [L_PAYMENTREQUEST_0_QTY0] => 1
    [L_PAYMENTREQUEST_0_TAXAMT0] => 0.00
    [L_PAYMENTREQUEST_0_AMT0] => 9.99
    [L_PAYMENTREQUEST_0_ITEMWEIGHTVALUE0] =>    0.00000
    [L_PAYMENTREQUEST_0_ITEMLENGTHVALUE0] =>    0.00000
    [L_PAYMENTREQUEST_0_ITEMWIDTHVALUE0] =>    0.00000
    [L_PAYMENTREQUEST_0_ITEMHEIGHTVALUE0] =>    0.00000
    [PAYMENTREQUESTINFO_0_ERRORCODE] => 0
)
Array
(
    [TIMESTAMP] => 2017-04-26T04:53:12Z
    [CORRELATIONID] => af6b14f482005
    [ACK] => Failure
    [VERSION] => 123
    [BUILD] => 25237094
    [L_ERRORCODE0] => 11502
    [L_SHORTMESSAGE0] => Invalid Token
    [L_LONGMESSAGE0] => The token is invalid
    [L_SEVERITYCODE0] => Error
)
When i subscribe to monthly agreement using this package this result given. Always return invalid token. This is big issue for me and i cant recover it, Please help me to solve this issue asap.

**Comment by srmklive** [comment]
@raihancse104 refer to the README file for this package. I have listed the procedure on how to create recurring subscriptions.

**Comment by srmklive** [comment]
@raihancse104 In case you are facing any issues with the package and are able to fix it. Kindly open a PR.

**Comment by raihancse104** [comment]
@srmklive  i am following your README file and used as your direction . but same problem occurred. alwasys show me this problem (invalid token).
First setexpress checkout give response a token but using recurring profile give me this invalid token.How can i solve this issu. Please help me.
