### ISSUE TITLE
unexpected '$obj' (T_VARIABLE) in version 1.7

### ISSUE THREAD

**Issue by d-asingwire** [srmklive/laravel-paypal#350]
![chrome_KFcUAbLX0b](https://user-images.githubusercontent.com/30871119/86767694-0e20b880-c055-11ea-90b3-fb57696bd139.png)

**Comment by DallingtonAsin** [comment]
Am encountering that error while trying to install srmklive/paypal ersion 1.7. I will appreciate any solution thank you!

**Comment by srmklive** [comment]
Haven't seen anyone else reporting it yet
