### ISSUE TITLE
A question regarding the REST version of the API

### ISSUE THREAD

**Issue by bdteo** [srmklive/laravel-paypal#353]
Hi, @srmklive, it seems that recently PayPal is pushing their REST API ahead instead of the NVP/SOAP one (which this project uses).

I can see that the project has been under development from Oct 5, 2015. By the time you started it the REST API existed.
What is your current preference? The NVP/SOAP API or the REST API?

Did you have any concerns not to choose using the REST API when you started the project?

**Comment by srmklive** [comment]
Great question.

First i have been pretty lazy with this package :smiley: . Also the package has been really popular with the community, so i didnt bother as well. I am actually looking at implementing v2.0 for PayPal REST API for this package, and would love to have contributors.

**Comment by srmklive** [comment]
Hi,

I have published a new package for Paypal rest API in v2.0. Kindly use that from now on.
