### ISSUE TITLE
No amount deducted from seller| No amount received to Buyer! BUT ExpressCheckout return successful URL.

### ISSUE THREAD

**Issue by osamamoinchawla** [srmklive/laravel-paypal#354]
Hello everyone specially the owner. Don't close the topic before acknowledging your answer is working !

I have integrated sandbox via srmlive, worked fine, While on live - No error, successful url return but but no transaction has been made what kind of manipulation that is? Kindly provide a working and valid answer to the issue. And yes
-API_USERNAME
-API_PASSWORD
-API_SECRET
-API_CERTIFICATE

I have attached the all the information except CERTIFICATE, I received this information from live business account > account > api access > request  > update

Am I doing right? kindly provide me the guide/help to make transaction to my client account (Canadian paypal account).

YES--- MODE is to live. as well

**Comment by srmklive** [comment]
You may have created a subscription with a trial date, which hasn't passed yet.

**Comment by cloudeweb** [comment]
Hello, I have same problem.

@osamamoinchawla have you fix it?

thanks!
