### ISSUE TITLE
@srmklive What USERNAME, PASSWORD, SECRET_ID, CERTIFICATE, we need to use in .env file, and from where we gonna get this?

### ISSUE THREAD

**Issue by osamamoinchawla** [srmklive/laravel-paypal#355]
@srmklive 
my app is worked fine in sandbox mode but in live mode, I am confused with env.
How can I find my live username and password and signature?
All I have is Paypal Username, Client ID and Secret ID.
is PAYPAL_LIVE_API_PASSWORD the same as my Paypal account password that I use to login to my Paypal dashboard?
is PAYPAL_LIVE_ACCOUNT_API_SIGNATURE the same as my Secret ID?

All I have is shown below:
![Untitljged](https://user-images.githubusercontent.com/35491888/79686981-6b2c7f80-8259-11ea-92d0-f5f50f88bb8a.png)

_Originally posted by @mohammadjavadz in https://github.com/srmklive/laravel-paypal/issues/287#issuecomment-616115501_

**Comment by i350** [comment]
I think this page may helps you
https://developer.paypal.com/docs/nvp-soap-api/apiCredentials/#api-signatures
