### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by soy-programador** [srmklive/laravel-paypal#360]
Hello, i tried to install this package.

Laravel 6

`Problem 1
    - Conclusion: don't install srmklive/paypal v2.0.0-beta-1
    - Conclusion: remove guzzlehttp/guzzle 7.0.1
    - Installation request for srmklive/paypal ~2.0 -> satisfiable by srmklive/paypal[v2.0.0-beta-1, v2.0.x-dev].
    - Conclusion: don't install guzzlehttp/guzzle 7.0.1
    - srmklive/paypal v2.0.x-dev requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.2.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.2, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.3, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.2, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.3, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.4.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.4.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.2, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.3, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.4, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.5, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.2, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.0, 7.0.1].
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].
`

How can fix this? In this new version 2.0, will be added the Payouts Paypal API.

Thanks.

**Comment by srmklive** [comment]
Hi,

Yes, the Payouts API will be added. `v1.0` will no longer be maintained after Laravel 8 is released.
