### ISSUE TITLE
Can u help me

### ISSUE THREAD

**Issue by fauby** [srmklive/laravel-paypal#361]
i have this problem "Call to undefined method Srmklive\PayPal\Services\PayPal::setExpressCheckout()" how to solve this? thx

**Comment by srmklive** [comment]
Please use this in composer.json:

```
srmklive/paypal: "~1.0"
```

**Comment by hareshzala96247** [comment]
> 
@srmklive 
srmklive/paypal: "~1.0" not working on Laravel 9
