### ISSUE TITLE
how to fix "secret" (v1.0)

### ISSUE THREAD

**Issue by fauby** [srmklive/laravel-paypal#363]
i got "Undefined index: secret" in srmklive\paypal\src\Traits\PayPalRequest.php:329
please tell me how to fix this?thanks sry for bother u

**Comment by shaahindeveloper** [comment]
i have same error?you fixed that?

**Comment by jasbin** [comment]
update:issue fixed check below comment

**Comment by srmklive** [comment]
This is an issue with Express Checkout API credentials. Please add the correct ones.

**Comment by jasbin** [comment]
if you install the ~1 version and publish the vendor then you will face this issue. the solution is just don't publish the vendor at last. simply install package and add provider and alias and add ur credentials in .env
