### ISSUE TITLE
End of v1.x and help needed to get v2 running

### ISSUE THREAD

**Issue by srmklive** [srmklive/laravel-paypal#364]
Hi everyone,

Thank you so much for your support over the years in using this package. Privately, many of you have reached out that I should work on the new version of this package supporting PayPal REST API. So over the past month, I have been working on the new version of the package, and have published some beta releases. So moving forward, i would like to do the following:

* End v1.x dev work.
* Bring on team members to work on the documentation.
* Develop the package further with easy to use methods, which builds the API calls to PayPal.
* Develop Blade components for v2.x.

That's all i can think of right now :smiley: . Please feel free to add anything else that i might have missed.

**Comment by quachvietcuong-laravel-php** [comment]
your code is amazing but after you upgrade this code. i have a problem like this : Call to undefined method Srmklive\PayPal\Services\PayPal::setExpressCheckout() . im not good at english sr about that. could you check this out. tks you so much

**Comment by srmklive** [comment]
Change it to `srmklive/paypal: "~1.0"` in `composer.json`.

**Comment by quachvietcuong-laravel-php** [comment]
> Change it to `srmklive/paypal: "~1.0"` in `composer.json`.

i try it tks u

**Comment by chauhanroht** [comment]
Hi Raza,

I have been using v1 from a long time, never had any issues thanks for that, i wanted to ask you 
Is it possible to use express checkout with multiple recievers as mentioned here in the paypal documentation ?

https://developer.paypal.com/docs/archive/express-checkout/ht-ec-parallelPayments/#create-a-parallel-payment.

I went through your code and looks like it wont work with multiple recievers.

From ExpressCheckout.php

$this->post = $this->setCartItems($data['items'])->merge([
            'PAYMENTREQUEST_0_ITEMAMT'       => $this->subtotal,
            'PAYMENTREQUEST_0_AMT'           => $data['total'],
            'PAYMENTREQUEST_0_PAYMENTACTION' => $this->paymentAction,
            'PAYMENTREQUEST_0_CURRENCYCODE'  => $this->currency,
            'PAYMENTREQUEST_0_DESC'          => $data['invoice_description'],
            'PAYMENTREQUEST_0_INVNUM'        => $data['invoice_id'],
            'NOSHIPPING'                     => 1,
            'RETURNURL'                      => $data['return_url'],
            'CANCELURL'                      => $data['cancel_url'],
            'LOCALE'                         => $this->locale,
        ]);

What would be the best way for me to add this on my project ?

**Comment by srmklive** [comment]
Locking the ticket as people instead of coming with suggestions to improve the package want me to fix issues which i have clearly described in the README file for v1.

**Comment by srmklive** [comment]
> Hi Raza,
> 
> I have been using v1 from a long time, never had any issues thanks for that, i wanted to ask you
> Is it possible to use express checkout with multiple recievers as mentioned here in the paypal documentation ?
> 
> https://developer.paypal.com/docs/archive/express-checkout/ht-ec-parallelPayments/#create-a-parallel-payment.
> 
> I went through your code and looks like it wont work with multiple recievers.
> 
> From ExpressCheckout.php
> 
> $this->post = $this->setCartItems($data['items'])->merge([
> 'PAYMENTREQUEST_0_ITEMAMT' => $this->subtotal,
> 'PAYMENTREQUEST_0_AMT' => $data['total'],
> 'PAYMENTREQUEST_0_PAYMENTACTION' => $this->paymentAction,
> 'PAYMENTREQUEST_0_CURRENCYCODE' => $this->currency,
> 'PAYMENTREQUEST_0_DESC' => $data['invoice_description'],
> 'PAYMENTREQUEST_0_INVNUM' => $data['invoice_id'],
> 'NOSHIPPING' => 1,
> 'RETURNURL' => $data['return_url'],
> 'CANCELURL' => $data['cancel_url'],
> 'LOCALE' => $this->locale,
> ]);
> 
> What would be the best way for me to add this on my project ?

There is a thing called Inhertiance in OOP. Use it :smile:
