### ISSUE TITLE
Live Mode not working

### ISSUE THREAD

**Issue by ifbasit** [srmklive/laravel-paypal#367]
it was working with sandbox perfectly, when i switched to live then it stopped working... 

This is error I am getting when try to pay 
**Argument 1 passed to Symfony\Component\HttpFoundation\Response::setContent() must be of the type string or null, object given, called in /Applications/MAMP/htdocs/swiitsy/vendor/laravel/framework/src/Illuminate/Http/Response.php on line 65**

**Comment by ifbasit** [comment]
The reason was, I was trying to test live mode on localhost, my bad.
The issue was resolved as I publish my app to server

**Comment by esponges** [comment]
Hey, could you share how you managed to solve this? Been struggling hard to get on live.

Here's my issue #381 

Thanks

**Comment by hierro59** [comment]
It worked perfectly for me after going to production, locally the Live mode did not work at all.
