### ISSUE TITLE
V2 version is ready to use?

### ISSUE THREAD

**Issue by lovecoding-git** [srmklive/laravel-paypal#369]
Hi @srmklive,

I have been using V1 for long time and it's the best package that I ever used to integrate Paypal in my Laravel project.
Thank you so much for it.

Now I can see V2 and V3 tagged and it's told it's supporting new Rest API.
I was going to use this but I couldn't see enough doc such as create plan, create subscription.

`https://github.com/paypal/PayPal-PHP-SDK`

This was the great package that I had been used for Rest API Integration but it seems it's not supporting new Rest API anymore.

So my question is 
- Is this package ready to use for new rest api?
- Which version should I use? V2 or V3? what are differences between them?
- and Could you please let me know where I can see document for it?

Thank you.

**Comment by srmklive** [comment]
Hi,

Thank you so much for the kind words. You can try it out the dev versions for v2 & v3 branches. The v3 branch is for Laravel 6 or greater.

**Comment by lovecoding-git** [comment]
Thank you!
