### ISSUE TITLE
Set Express Checkout Method not available

### ISSUE THREAD

**Issue by aliasgarvanak** [srmklive/laravel-paypal#371]
In the version 2, I can't use the expresscheckout method. Because their services files are missing.

![image](https://user-images.githubusercontent.com/23218418/92991360-fc4e0c80-f500-11ea-89af-e73453270858.png)

**Comment by srmklive** [comment]
use ~1.0 as version in composer.json. Please bother to read the documentation first.`

**Comment by aliasgarvanak** [comment]
Earlier I was using 1.0 only. You updated this package so I updated to version 2

**Comment by srmklive** [comment]
I have only published the beta version. You should check before updating it in your app

**Comment by aliasgarvanak** [comment]
No problem. Thank you for your response.
