### ISSUE TITLE
Is it possible to use this library to send payments to multiple recipients?

### ISSUE THREAD

**Issue by Maxcrazy1** [srmklive/laravel-paypal#372]
I've been struggling for days to send an invoice that pays 2 or 3 recipients in the process, but I can't do it, I wanted to know if with this library I can achieve that goal? 🤞

**Comment by srmklive** [comment]
Use the v2 version or v3(If Laravel 6 or greater). You may need to add these versions as dev dependency. There is so much documentation to be done. But i haven't had the time to do it.

**Comment by lovecoding-git** [comment]
Hi @srmklive ,
When could we expect the documentation?

**Comment by srmklive** [comment]
Hi,

I have no idea 😂. I need help on that end.

**Comment by lovecoding-git** [comment]
How can we help you then?  😉

So the package is ready to use? 
Just need to complete only documentation? 😬

**Comment by srmklive** [comment]
Yes. I can add you as contributor. You can start works on the docs.
