### ISSUE TITLE
Response::setContent() must be of the type string or null, object given.

### ISSUE THREAD

**Issue by AkshilSavalia** [srmklive/laravel-paypal#375]
TypeError
Argument 1 passed to Symfony\Component\HttpFoundation\Response::setContent() must be of the type string or null, object given, called in C:\Users\User\Desktop\laravel-sites\webmall\vendor\laravel\framework\src\Illuminate\Http\Response.php on line 65.

Here is my Controller Method : 

public function getExpressCheckout($orderId)
    {
        $cart = \Cart::session(auth()->id());
        $cartItems = array_map(function ($item) use($cart) {
            return [
                'name' => $item['name'],
                'price' => $item['price'],
                'qty' => $item['quantity']

            ];
        }, $cart->getContent()->toarray());
     
        $checkoutData = [
            'items' => $cartItems,
            'return_url' => route('paypal.success', $orderId),
            'cancel_url' => route('paypal.cancel'),
            'invoice_id' => uniqid(),
            'invoice_description' => " Order description ",
            'total' => $cart->getSubTotal(),
            'shipping_discount' => $cart->getSubTotal() - $cart->getTotal()
        ];

        $product = [];
        $product['items'] = $cartItems;
  
        $product['invoice_id'] = uniqid();
        $product['invoice_description'] = "PAYPALDEMOAPP #{$product['invoice_id']} ";
        $product['return_url'] = route('paypal.success',$orderId);
        $product['cancel_url'] = route('paypal.cancel');
        $product['total'] = $cart->getSubTotal();

       
        $paypalModule = new ExpressCheckout;

        $response = $paypalModule->setExpressCheckout($product);
        //$response = $paypalModule->setExpressCheckout($product, true);

        // dd($response);
       
        return redirect($response['paypal_link']);
    } 

I have also set Correct Credentials in .env

**Comment by srmklive** [comment]
Set a different invoice prefix similar to your app. How is that so difficult for all of you to understand?
