### ISSUE TITLE
Issue with multiple products

### ISSUE THREAD

**Issue by ScuffedNewt** [srmklive/laravel-paypal#376]
Heya!
I am using the ExpressCheckout expression.
Right now the erroneous code looks like:
`public function expressCheckout(Request $request) {
        // check if payment is recurring
        $recurring = $request->input('recurring', false) ? true : false;
        $product = $request->input('name');
        $item = $request->input('item');

        // get new invoice id
        $invoice_id = Invoice::count() + 1;
            
        // Get the cart data
        $cart = $this->getCart($recurring, $invoice_id, $product);`

`private function getCart($recurring, $invoice_id)
    {

        if ($recurring) {
            return [
                // if payment is recurring cart needs only one item
                // with name, price and quantity
                'items' => [
                    [
                        'name' => 'Monthly Subscription ' . config('paypal.invoice_prefix') . ' #' . $invoice_id,
                        'price' => 20,
                        'qty' => 1,
                    ],
                ],

                // return url is the url where PayPal returns after user confirmed the payment
                'return_url' => url('/paypal/express-checkout-success?recurring=1'),
                'subscription_desc' => 'Monthly Subscription ' . config('paypal.invoice_prefix') . ' #' . $invoice_id,
                // every invoice id must be unique, else you'll get an error from paypal
                'invoice_id' => config('paypal.invoice_prefix') . '_' . $invoice_id,
                'invoice_description' => "Order #". $invoice_id ." Invoice",
                'cancel_url' => url('/'),
                // total is calculated by multiplying price with quantity of all cart items and then adding them up
                // in this case total is 20 because price is 20 and quantity is 1
                'total' => 20, // Total price of the cart
            ];
        }
if($product == 1) {
            return [
                'items' => [
                    [
                        'name' => 'Mystery Core',
                        'price' => 25,
                        'qty' => 1,
                    ],
                ],

                'return_url' => url('/paypal/express-checkout-success'),
                'invoice_id' => config('paypal.invoice_prefix') . '_' . $invoice_id,
                'invoice_description' => "Order #" . $invoice_id . " Invoice",
                'cancel_url' => url('/'),
                'total' => 25,
            ];
         }
    }

else...`

However when I do this to define data on request, it returns the error
"Trying to access array offset on value of type null"

I am using version 1.0 (1.8 in composer.json) of this package!

**Comment by srmklive** [comment]
Try to add multiple products through the `addOptions` method. Please be bothered to read the documentation. Everything is listed in the README file for v1 branch.

**Comment by ScuffedNewt** [comment]
Hi, I did read the documention and try the addOption method, however it still threw a null error hence my trying a switch!

**Comment by ScuffedNewt** [comment]
@srmklive 
I'll add some more clarification for this, I do not want multiple products in the same order, I want it to get the input from my blade depending on which button the user has clicked. I could not find any information on this even with the addOption method
