### ISSUE TITLE
i have use this package in my laravel app

### ISSUE THREAD

**Issue by hiteshdevaiya** [srmklive/laravel-paypal#378]
not redirect on paypal

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Srmklive\PayPal\Services\ExpressCheckout;

class PayPalController extends Controller
{
    public function payment()
    {
        $data = [];
        $data['items'] = [
            [
                'name' => 'ItSolutionStuff.com',
                'price' => 100,
                'desc'  => 'Description for ItSolutionStuff.com',
                'qty' => 1
            ]
        ];
  
        $data['invoice_id'] = 1;
        $data['invoice_description'] = "Order #{$data['invoice_id']} Invoice";
        $data['return_url'] = route('payment.success');
        $data['cancel_url'] = route('payment.cancel');
        $data['total'] = 100;
  
        $provider = new ExpressCheckout;
  
        $response = $provider->setExpressCheckout($data);
  
        $response = $provider->setExpressCheckout($data, true);
  
        return redirect($response['paypal_link']);
    }
   
    /**
     * Responds with a welcome message with instructions
     *
     * @return \Illuminate\Http\Response
     */
    public function cancel()
    {
        dd('Your payment is canceled. You can create cancel page here.');
    }
  
    /**
     * Responds with a welcome message with instructions
     *
     * @return \Illuminate\Http\Response
     */
    public function success(Request $request)
    {
    	$provider = new ExpressCheckout;
        $response = $provider->getExpressCheckoutDetails($request->token);
  
        if (in_array(strtoupper($response['ACK']), ['SUCCESS', 'SUCCESSWITHWARNING'])) {
        	return view('user.thankyou');
        }
  
        dd('Something is wrong.');
    }
}

but not redirect on payapa
![Screenshot (98)](https://user-images.githubusercontent.com/50793883/94225058-a40c0700-ff11-11ea-8c42-4e614688d474.png)

**Comment by srmklive** [comment]
Change the invoice prefix you genius

**Comment by lovecoding-git** [comment]
@hiteshdevaiya ` Invoice_id` should be unique.

**Comment by hiteshdevaiya** [comment]
@lovecoding-git  
@srmklive
i solved error but now personel account not deducted money after success transsaction.
