### ISSUE TITLE
complete all step and alert success but not pay any mony

### ISSUE THREAD

**Issue by tayyebin** [srmklive/laravel-paypal#379]
hllo
i completed all steps and alert success but not many pay for me and not reduce from customer
where is problem? 

my code in suscess status
` public function success(Request $request)
    {
        $provider = new ExpressCheckout;
        $response = $provider->getExpressCheckoutDetails($request->token);

        if (in_array(strtoupper($response['ACK']), ['SUCCESS', 'SUCCESSWITHWARNING'])) {
            dd('Your payment was successfully. You can create success page here.');
        }

        dd('Something is wrong.');
    }
}`

please help me

**Comment by lovecoding-git** [comment]
Did you do this?
`$resp = $provider->doExpressCheckoutPayment($data, $token, $payerId);` ?

**Comment by tayyebin** [comment]
> $resp = $provider->doExpressCheckoutPayment($data, $token, $payerId);

tanks for your solution 
by this status payment customer go to pending but in my sandbox account not show any think 


how can i change status to completed?

**Comment by srmklive** [comment]
We aren't here to solve things for you. It seems quite clear that you haven't read the documentation for v1 in v1.0 branch. PayPal transactions that are completed generally take a while to appear in your account.

**Comment by tayyebin** [comment]
Thanks for the tips
