### ISSUE TITLE
How to as use the package?

### ISSUE THREAD

**Issue by agentelinux** [srmklive/laravel-paypal#38]
I have one project to sale API SaaS.
Have you  one demo?

**Comment by agentelinux** [comment]
Thanks

**Comment by srmklive** [comment]
Can you provide further details which specific PayPal API are you looking to implement.

**Comment by agentelinux** [comment]
Okay,

Easy, express check out. One button.

Example:
Vídeo about deploy PayPal with laravel.

https://www.codecourse.com/library/lessons/laravel-subscriptions/introduction

Thks.

[]s
Krishna

Em 01/09/2016 07:01, "Raza Mehdi" <notifications@github.com> escreveu:

**Comment by srmklive** [comment]
Refer to #16 regarding this.
