### ISSUE TITLE
Limited to PHP<7.2 ? 

### ISSUE THREAD

**Issue by potterpg** [srmklive/laravel-paypal#383]
Why is it limited this way?

**Comment by srmklive** [comment]
v1 is Express Checkout supports upto Laravel 8.

v2 supports Laravel 5.8 with PHP<7.2

v3 supports Laravel 6 or greater with PHP>=7.2

**Comment by potterpg** [comment]
I'm using laravel 5.8, and wasn't sure why it was limited to <7.2

**Comment by srmklive** [comment]
I just took the decision to keep one package restricted to PHP & Laravel version that are out of support.
