### ISSUE TITLE
How to set payment_failure_threshold when creating subscription?

### ISSUE THREAD

**Issue by sovrinbloc** [srmklive/laravel-paypal#384]
A problem is that there are infinite attempts to retry payments if the person does not have funding in their account, so no webhook is ever sent from PayPal. How to limit failed payment attemps with 'payment_failure_threshold'.

> When you create your plan, set the value for the payment_failure_threshold in the payment_preferences object:
>
> ```
>
>    "payment_preferences": {
>        "auto_bill_outstanding": true,
>        "payment_failure_threshold": 2
>    }
>```

**Comment by srmklive** [comment]
Kindly view this link for param reference in order to create subscription, if you are using v2.0 or v3.0 of this package:

https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_create
