### ISSUE TITLE
Error when setExpressCheckout()

### ISSUE THREAD

**Issue by jaysonhubt** [srmklive/laravel-paypal#386]
Laravel version: 8.6
Package version: 3.0

I got error when run:

$provider = PayPal::setProvider();       // use Srmklive\PayPal\Services\PayPal as PayPalClient; get the same error
$provider->setCurrency('EUR')->setExpressCheckout($data);

Call to undefined method Srmklive\\PayPal\\Services\\PayPal::setExpressCheckout();

Please help me. Thanks for reading!

**Comment by srmklive** [comment]
Please bother to use the README. Express checkout is in v1.0. Use that version.

**Comment by jaysonhubt** [comment]
> Please bother to use the README. Express checkout is in v1.0. Use that version.

Thanks for reply.

In readme file of v3.0, setExpressCheckout is still exist. I can't find any function like it in source code. Can you update readme file?

Thank you so much!
