### ISSUE TITLE
Error when setExpressCheckout()

### ISSUE THREAD

**Issue by jaysonhubt** [srmklive/laravel-paypal#387]
Sorry for creating duplicate issue but srmklive's answer can't resolve the issue (#386)

Laravel version: 8.6
Package version: 3.0

I got error when run:

$provider = PayPal::setProvider(); // use Srmklive\PayPal\Services\PayPal as PayPalClient; get the same error
$provider->setCurrency('EUR')->setExpressCheckout($data);

Call to undefined method Srmklive\PayPal\Services\PayPal::setExpressCheckout();

In readme file of v3.0, setExpressCheckout is still exist. I can't find any function like it in source code.

Please help me. Thanks for reading!

**Comment by srmklive** [comment]
Please read #386 again, and use the following in composer.json for god sake:

```
"srmklive/paypal": "~1.0"
```
