### ISSUE TITLE
verifyIPN on version 3.0 dosent exist

### ISSUE THREAD

**Issue by matheusbenedet** [srmklive/laravel-paypal#388]
The method ->verifyIPN() on version 3.0 dosent exists, what do i?

**Comment by srmklive** [comment]
The process on the new PayPal Rest API is different to verify a web hook. This is how you should verify a web hook in v2 & v3:

```
$data = $request->all();

$provider = PayPal::setProvider();
$response = $provider->verifyWebHook($data);
```

**Comment by matheusbenedet** [comment]
> The process on the new PayPal Rest API is different to verify a web hook. This is how you should verify a web hook in v2 & v3:
> 
> ```
> $data = $request->all();
> 
> $provider = PayPal::setProvider();
> $response = $provider->verifyWebHook($data);
> ```

Thank you for reply, i did it but returns this error of paypal:

`{\"name\":\"VALIDATION_ERROR\",\"message\":\"Invalid request - see details\",\"debug_id\":\"33c5e5e9b6143\",\"details\":[{\"field\":\"\/id\",\"location\":\"body\",\"issue\":\"MALFORMED_REQUEST_JSON\"}],\"links\":[]}"}`


Here is the request->all() i recive:

`{\"id\":\"WH-4U94251082967924A-5DV30715ST053080N\",\"event_version\":\"1.0\",\"create_time\":\"2020-10-15T17:29:43.275Z\",\"resource_type\":\"subscription\",\"resource_version\":\"2.0\",\"event_type\":\"BILLING.SUBSCRIPTION.ACTIVATED\",\"summary\":\"Subscription activated\",\"resource\":{\"quantity\":\"1\",\"subscriber\":{\"name\":{\"given_name\":\"John\",\"surname\":\"Doe\"},\"email_address\":\"sb-hcqxf3463770@personal.example.com\",\"payer_id\":\"8LVTP7RS2UDAY\",\"shipping_address\":{\"address\":{\"address_line_1\":\"1 Main St\",\"admin_area_2\":\"San Jose\",\"admin_area_1\":\"CA\",\"postal_code\":\"95131\",\"country_code\":\"US\"}}},\"create_time\":\"2020-10-15T17:27:28Z\",\"plan_overridden\":false,\"shipping_amount\":{\"currency_code\":\"USD\",\"value\":\"0.0\"},\"start_time\":\"2020-10-15T03:00:00Z\",\"update_time\":\"2020-10-15T17:29:24Z\",\"billing_info\":{\"outstanding_balance\":{\"currency_code\":\"USD\",\"value\":\"0.0\"},\"cycle_executions\":[{\"tenure_type\":\"REGULAR\",\"sequence\":1,\"cycles_completed\":0,\"cycles_remaining\":0,\"current_pricing_scheme_version\":1,\"total_cycles\":0}],\"last_payment\":{\"amount\":{\"currency_code\":\"USD\",\"value\":\"10.0\"},\"time\":\"2020-10-15T17:29:23Z\"},\"next_billing_time\":\"2020-10-15T17:29:22Z\",\"failed_payments_count\":0},\"links\":[{\"href\":\"https:\\\/\\\/api.sandbox.paypal.com\\\/v1\\\/billing\\\/subscriptions\\\/I-DF7KSH3JUA28\\\/cancel\",\"rel\":\"cancel\",\"method\":\"POST\",\"encType\":\"application\\\/json\"},{\"href\":\"https:\\\/\\\/api.sandbox.paypal.com\\\/v1\\\/billing\\\/subscriptions\\\/I-DF7KSH3JUA28\",\"rel\":\"edit\",\"method\":\"PATCH\",\"encType\":\"application\\\/json\"},{\"href\":\"https:\\\/\\\/api.sandbox.paypal.com\\\/v1\\\/billing\\\/subscriptions\\\/I-DF7KSH3JUA28\",\"rel\":\"self\",\"method\":\"GET\",\"encType\":\"application\\\/json\"},{\"href\":\"https:\\\/\\\/api.sandbox.paypal.com\\\/v1\\\/billing\\\/subscriptions\\\/I-DF7KSH3JUA28\\\/suspend\",\"rel\":\"suspend\",\"method\":\"POST\",\"encType\":\"application\\\/json\"},{\"href\":\"https:\\\/\\\/api.sandbox.paypal.com\\\/v1\\\/billing\\\/subscriptions\\\/I-DF7KSH3JUA28\\\/capture\",\"rel\":\"capture\",\"method\":\"POST\",\"encType\":\"application\\\/json\"}],\"id\":\"I-DF7KSH3JUA28\",\"plan_id\":\"P-8FY84601WG2841535L6D7O4Y\",\"status\":\"ACTIVE\",\"status_update_time\":\"2020-10-15T17:29:24Z\"},\"links\":[{\"href\":\"https:\\\/\\\/api.sandbox.paypal.com\\\/v1\\\/notifications\\\/webhooks-events\\\/WH-4U94251082967924A-5DV30715ST053080N\",\"rel\":\"self\",\"method\":\"GET\"},{\"href\":\"https:\\\/\\\/api.sandbox.paypal.com\\\/v1\\\/notifications\\\/webhooks-events\\\/WH-4U94251082967924A-5DV30715ST053080N\\\/resend\",\"rel\":\"resend\",\"method\":\"POST\"}]}`

**Comment by srmklive** [comment]
Please view this link on how to verify a webhook:

https://developer.paypal.com/docs/api/webhooks/v1/#verify-webhook-signature_post

**Comment by matheusbenedet** [comment]
> Please view this link on how to verify a webhook:
> 
> https://developer.paypal.com/docs/api/webhooks/v1/#verify-webhook-signature_post


I don't understand, your library that does this procedure, if it is to make a manual, why would I use your library?

**Comment by srmklive** [comment]
> > Please view this link on how to verify a webhook:
> > https://developer.paypal.com/docs/api/webhooks/v1/#verify-webhook-signature_post
> 
> I don't understand, your library that does this procedure, if it is to make a manual, why would I use your library?

If you feel comfortable doing your own implementation, please feel free to do that. If you are using a open source library and don't review its source code then the problem is yours and not with the package.
