### ISSUE TITLE
recursive payments

### ISSUE THREAD

**Issue by zeus6999** [srmklive/laravel-paypal#389]
Hello.
thanks for this great code.
I have two questions
1.This code also makes recursive payments (subscription)
2.Works with Laravel 6 or 7

Regards

**Comment by JexPY** [comment]
I guess it does, [https://github.com/srmklive/laravel-paypal/blob/v2.0/src/Traits/PayPalAPI/BillingPlans.php#L18](https://github.com/srmklive/laravel-paypal/blob/v2.0/src/Traits/PayPalAPI/BillingPlans.php#L18), here you can see creating billing plan (subscription) request. @srmklive  am I right?

And @zeus6999 use version 3.0

**Comment by srmklive** [comment]
@JexPY you are right. @zeus6999 needs to use v3.0.
