### ISSUE TITLE
Calling getAccessToken function overwrites apiUrl

### ISSUE THREAD

**Issue by petraeus** [srmklive/laravel-paypal#391]
```
$provider = new PayPal($credentials);

$provider->getAccessToken(); 

$this->apiUrl = collect([$this->apiUrl, $this->apiEndPoint])->implode('/');
```

apiUrl becomes "https://api.sandbox.paypal.com/v1/oauth2/token"

`$response = $provider->showRefundDetails('5SL176274N160993U');`

apiUrl becomes "https://api.sandbox.paypal.com/v1/oauth2/token/v2/payments/refunds/5SL176274N160993U"

**Comment by petraeus** [comment]
solution is to use static config.api_url

`$this->apiUrl = collect([$this->config['api_url'],$this->apiEndPoint])->implode('/'); `

**Comment by srmklive** [comment]
That's not true. If it was, the test suites wouldn't be returning green when i originally wrote the code.
