### ISSUE TITLE
Recurring Subscription | Error Argument 1 passed to Symfony\Component\HttpFoundation\Response::setContent()... | Tutorial followed https://www.larablocks.com/package/srmklive/paypal

### ISSUE THREAD

**Issue by marcq64** [srmklive/laravel-paypal#393]
[ Laravel 7 ]

Hi,

So happy to have found your package, thank you also for the tutorial !

It is the first time I'm integration a payment gateway, so I followed this tutorial 
`https://www.larablocks.com/package/srmklive/paypal`
that I have adapted to my needs and when I tried to subscribe one of the service of my application, the following error occurs :

`
Argument 1 passed to Symfony\Component\HttpFoundation\Response::setContent() must be of the type string or null, object given, called in /home/clients/5de53ad737249bdaef8e4153db285c7d/sites/application.com/private/vendor/laravel/framework/src/Illuminate/Http/Response.php on line 65
`

I'm stuck with the Paypal integration since a few days already (tested several other package without success)...

I don't have yet the experience and expertise to solve this by myself  so I would appreciate some help here. Thanks, 

Cheers, 

Marc

(I'm also ok to pay for the fix of this issue and to explain me why it occurs in order to have it solved soon)

**Controller**
`
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Srmklive\PayPal\Services\ExpressCheckout;
use Auth;
use Config;
use App\User;

class PayPalPaymentController extends Controller
{

    public function subscribe()
    {

        $planID = Auth::user()->subscriptionsplan_id;
        $subscriptionDate = Auth::user()->created_at;

        $data = [
            'planID' => $planID,
            'subscriptionDate' => $subscriptionDate
        ];

        return view('subscriptions.subscribe', compact('data'));
    }

    public function handlePayment()
    {
        $data = [];
        $data['items'] = [
            [
                'name' => 'Pro Subscription Plan Monthly Billing',
                'price' => 20.00,
                'qty' => 1
            ]
        ];
  
        $data['subscription_desc'] = "Pro Subscription Plan Monthly Billing";
        $data['invoice_id'] = 1;
        $data['invoice_description'] = "Pro Subscription Plan Monthly Billing";
        $data['return_url'] = url('/paypal/ec-checkout-success?mode=recurring');
        $data['cancel_url'] = url('/');

        $total = 0;
        foreach ($data['items'] as $item) {
            $total += $item['price'] * $item['qty'];
        }

        $data['total'] = $total;
  
        $provider  = new ExpressCheckout;
  
        $response = $provider ->setExpressCheckout($data);
        $response = $provider ->setExpressCheckout($data, true);
  
        return redirect($response['paypal_link']);
    }
   
    public function paymentCancel()
    {
        dd('Your payment has been declined. The payment cancelation page goes here!');
    }
  
    public function paymentSuccess(Request $request)
    {
        $paypalModule = new ExpressCheckout;
        $response = $paypalModule->getExpressCheckoutDetails($request->token);
  
        if (in_array(strtoupper($response['ACK']), ['SUCCESS', 'SUCCESSWITHWARNING'])) {
            dd('Payment was successfull. The payment success page goes here!');
        }
  
        dd('Error occured!');
    }
}
`
**Routes**

` 
Route::get('handle-payment', 'PayPalPaymentController@handlePayment')->name('make.payment');
Route::get('cancel-payment', 'PayPalPaymentController@paymentCancel')->name('cancel.payment');
Route::get('payment-success', 'PayPalPaymentController@paymentSuccess')->name('success.payment');
`

**Comment by srmklive** [comment]
Hi,

Thank you so much for the kind words. I see the following issues with your code:

* Invoice id is static. It should be unique for every time you send an API call to PayPal. Its better that you add a prefix to  invoice id something like ``MARCQAPP_``.
* Just have this call when creating a subscription ``$response = $provider->setExpressCheckout($data, true);`` not ``$response = $provider ->setExpressCheckout($data);``

If you wish to look at how i am creating a subscription, please look at the demo app code here:

https://github.com/srmklive/laravel-paypal-demo/blob/5.8/app/Http/Controllers/PayPalController.php

**Comment by marcq64** [comment]
Hi,

Very much appreciated for your feedback and expertise. I'll keep you posted about the outcome. Thank you.

**Comment by marcq64** [comment]
Hi,

Sorry, it took me a little bit more time than expected. 

Thanks to your instructions, I could make it work. Everything is fine now. Thanks a lot, take care, cheers

**Comment by esponges** [comment]
Thanks, encountered a similar issue and the id was the root of the problem.

> Hi,
> 
> Thank you so much for the kind words. I see the following issues with your code:
> 
> * Invoice id is static. It should be unique for every time you send an API call to PayPal. Its better that you add a prefix to  invoice id something like `MARCQAPP_`.
> * Just have this call when creating a subscription `$response = $provider->setExpressCheckout($data, true);` not `$response = $provider ->setExpressCheckout($data);`
> 
> If you wish to look at how i am creating a subscription, please look at the demo app code here:
> 
> https://github.com/srmklive/laravel-paypal-demo/blob/5.8/app/Http/Controllers/PayPalController.php
