### ISSUE TITLE
Class 'Srmklive\PayPal\Services\ExpressCheckout' not found

### ISSUE THREAD

**Issue by mprince2k18** [srmklive/laravel-paypal#395]
I am using laravel 8 for my project. But facing this error.

http://prntscr.com/w2wbls

**Comment by ruaq** [comment]
Express Checkout only works in v1. I think you've installed v3, right?

**Comment by mprince2k18** [comment]
Yes, I have installed the latest version. because nothing is clean in the usage.

**Comment by srmklive** [comment]
If you looked at the README file i have clearly mentioned what commands you need to run. You can directly change to v1 branch to view the instructions.

**Comment by mprince2k18** [comment]
ok i wil try
