### ISSUE TITLE
did not charge customer account in live payment

### ISSUE THREAD

**Issue by Sharifur** [srmklive/laravel-paypal#396]
i am using expresscheckout 
everything is working fine in sandbox mode,

but when i use live payment it did not charge from customer, but in return is give success status,

here is package.json package details
"srmklive/paypal": "~1.0",

here is controller code for make api request 
$product = [];
            $product['items'] = [
                [
                    'name' => $price_plan_details->title,
                    'price' =>$payable_amount,
                    'desc'  => 'Payment For Order Id: #'.$order_details->id.' Package Name: '.$price_plan_details->title.' Payer Name: '.$request->name.' Payer Email:'.$request->email,
                    'qty' => 1
                ]
            ];

            $product['invoice_id'] = $order_details->id;
            $product['invoice_description'] = 'Payment For Order Id: #'.$order_details->id.' Package Name: '.$price_plan_details->title.' Payer Name: '.$request->name.' Payer Email:'.$request->email;
            $product['return_url'] = route('frontend.paypal.ipn',$order_details->id);
            $product['cancel_url'] = route('frontend.order.payment.cancel',$order_details->id);
            $product['custom'] = $order_details->track;
            $product['total'] = $payable_amount;

            $paypalModule = new ExpressCheckout;

            $res = $paypalModule->setCurrency($currency_code);
            $res = $paypalModule->setExpressCheckout($product);
            $res = $paypalModule->setExpressCheckout($product, true);

            return redirect($res['paypal_link']);

here is controller code for verify payment
$paypalModule = new ExpressCheckout;
        $response = $paypalModule->getExpressCheckoutDetails($request->token);
        $payment_logs = OrderManage::where('id', $response['INVNUM'])->first();
        if (in_array(strtoupper($response['ACK']), ['SUCCESS', 'SUCCESSWITHWARNING'])) {

            if ( $response['AMT'] == custom_number_format($payment_logs->amount)) {
                //database update
                $this->update_database($payment_logs->id,$response['CORRELATIONID']);
                //send mail
                $this->send_order_mail($payment_logs->id);

            }
            return redirect()->route('frontend.order.payment.success',$payment_logs->id);
        }

        return redirect()->route('frontend.order.payment.cancel',$payment_logs->id);

**Comment by srmklive** [comment]
Charges may appear after a certain time. This is not the package issue. It should be clear that the transaction did go through as you were returned a success status.
