### ISSUE TITLE
Class 'Srmklive\PayPal\Services\ExpressCheckout' not found

### ISSUE THREAD

**Issue by daniieljc** [srmklive/laravel-paypal#399]
Hi, I have configured everything as it comes in the manual but when doing the test to pay this error appears

`Class 'Srmklive \ PayPal \ Services \ ExpressCheckout' not found`

Which also shows an error related to `ExpressCheckout` in `PayPalController.php`, specifically in `$provider = new ExpressCheckout;`

**Comment by srmklive** [comment]
Use v1 for ExpressCheckout.

**Comment by claudioav** [comment]
> Use v1 for ExpressCheckout.
how to use v1 express checkout?

**Comment by ruaq** [comment]
> Use v1 for ExpressCheckout.
> > how to use v1 express checkout?

Following the instructions for [v1](https://github.com/srmklive/laravel-paypal/tree/v1.0). Playing around with the [demo repo](https://github.com/srmklive/laravel-paypal-demo)... It's up to you. ;-)

**Comment by sarrim** [comment]
The same issue occurs in Laravel v.10, how to solve it, Laravel10 do not support version 1

**Comment by miguelmba2000** [comment]
moi jai le mem probleme svp. comment remedier a cela. puisque la version 9 de laravel ne prend pas la version 1 de Srmklive

**Comment by SOUFIANE-BOUSHABA** [comment]
change it to v1

**Comment by SOUFIANE-BOUSHABA** [comment]
go to composer.json and change it there , an run  compser update srmk/live

**Comment by SyntaxByte-Solution** [comment]
> go to composer.json and change it there , an run compser update srmk/live

I have changed to v1 but still having the issue. Besides, this vendor\srmklive\paypal\src\Providers\PayPalServiceProvider.php - 
use Srmklive\PayPal\Services\AdaptivePayments;
use Srmklive\PayPal\Services\ExpressCheckout;

not clickable

**Comment by SyntaxByte-Solution** [comment]
> Use v1 for ExpressCheckout.

I have changed to v1 but still having the issue. Besides, this vendor\srmklive\paypal\src\Providers\PayPalServiceProvider.php -
use Srmklive\PayPal\Services\AdaptivePayments;
use Srmklive\PayPal\Services\ExpressCheckout;

not clickable

**Comment by ramyadavrp** [comment]
Use V1 branch code for ExpressCheckout

**Comment by ramyadavrp** [comment]
v1 worked for me with Laravel 10
