### ISSUE TITLE
doExpressCheckoutPayment failure (src/Services/ExpressCheckout.php)

### ISSUE THREAD

**Issue by hcmedia** [srmklive/laravel-paypal#40]
This line:
https://github.com/srmklive/laravel-paypal/blob/master/src/Services/ExpressCheckout.php#L35

is missing here: 
https://github.com/srmklive/laravel-paypal/blob/master/src/Services/ExpressCheckout.php#L107-L118

**Comment by srmklive** [comment]
Fixed.
