### ISSUE TITLE
Is there a function to check if a transaction id exists?

### ISSUE THREAD

**Issue by merlinnusr** [srmklive/laravel-paypal#400]
I'm looking in the documentation and I didnt find any information about this also I didn't see any function for this.

**Comment by ruaq** [comment]
You find it in **v1** with

_doExpressCheckoutPayment_ as _PAYMENTINFO_0_TRANSACTIONID_

and in the

_IPN_ as _txn_id_ or _parent_txn_id_ in the following IPNs
