### ISSUE TITLE
Call to undefined method Srmklive\PayPal\Services\PayPal::setExpressCheckout()

### ISSUE THREAD

**Issue by farshadff** [srmklive/laravel-paypal#402]
hi guys i have a laravel 8 project and membership system . now its simple i want to pass a price to to a function and send my user to paypal to pay the price . i am using this package and following this toturials :
```
https://www.positronx.io/how-to-integrate-paypal-payment-gateway-in-laravel/
https://www.codecheef.org/article/how-to-integrate-paypal-payment-gateway-in-laravel
```
when i hit pay route i get this error : 
```
Call to undefined method Srmklive\PayPal\Services\PayPal::setExpressCheckout()
```
i read on issues that for expres checkout use version 1 . now i have some questions . 
1-because i am using laravel 8 is it fine to use version 1 of this package ?
2-i unfortunately dont know much a lot about paypal so as far as i know express checkout keeps user on your site to pay . so i am fine if i redirect user to paypal and call back to my site too . so what is the function to do that ? if note `setExpressCheckout()` . 
currently this is my controlller  : 
```
   public function handlePayment()
    {
        $product = [];
        $product['items'] = [
            [
                'name' => 'Nike Joyride 2',
                'price' => 112,
                'desc'  => 'Running shoes for Men',
                'qty' => 2
            ]
        ];

        $product['invoice_id'] = 1;
        $product['invoice_description'] = "Order #{$product['invoice_id']} Bill";
        $product['return_url'] = route('success.payment');
        $product['cancel_url'] = route('cancel.payment');
        $product['total'] = 224;

//        $paypalModule = new PayPal::setProvider;
       $paypalModule = new PayPalClient;

        $res = $paypalModule->c($product);
        $res = $paypalModule->setExpressCheckout($product, true);

        return redirect($res['paypal_link']);
    }

```

**Comment by ruaq** [comment]
Maybe you should check out https://github.com/srmklive/laravel-paypal-demo to understand how it's working. And yes, even v1 works with Laravel 8.

**Comment by matejsvajger** [comment]
@pyyjac Problem is, what @farshadff mentioned is that, this method shown in README does not exist in the package.

The example app shows integration for v1 where there's different services available. From v2 there is only PayPal service, I tried to search through the versions but I can't seem to find, so I could switch to the appropriate version shown in docs.
