### ISSUE TITLE
Express checkout require to create account

### ISSUE THREAD

**Issue by bonucci** [srmklive/laravel-paypal#404]
Hi guys, i been checking in some issues and following all the steps give by users i can make "almost" a guest checkout, but paypal still requrie me to create account above the credit card information, i already in my paypal business account enable the guest checkout option and my options in the checkout express are:

```
 $options = [
             'BRANDNAME' => 'My store',
             'SOLUTIONTYPE' => 'Sole',
'LANDINGPAGE' => 'Billing',
'USERSELECTEDFUNDINGSOURCE' => 'CreditCard',
        ];

        $response = $provider->addOptions($options)->setExpressCheckout($data);
```

Even than i cant make a guest checkout without requiring the create paypal account, did someone had similiar situation?

**Comment by srmklive** [comment]
I think you need to provide that in the API call itself to have guest checkout available. Please use the `addOptions` method before performing an API call to add this feature.
