### ISSUE TITLE
How to use this package v3?

### ISSUE THREAD

**Issue by lovecoding-git** [srmklive/laravel-paypal#409]
Hi Thanks for this amazing package.
I have been using v1 for many years and now I'm going to upgrade it to v3 but no clue how to use it.

```
$provider = new PayPalClient;
$provider->setApiCredentials($config);
```

I did this then what's the next?
```
$provider->setExpressCheckout($data);
```

Isn't this obvious for v1?

Thanks

**Comment by gr34tnull** [comment]
This is also my issue I hope they update it soon.

**Comment by srmklive** [comment]
@lovecoding-git you don't need to call the `setApiCredentials` method anyway if the configuration is properly set. Following is the code you need to get the access token from PayPal:

```
$provider = new PayPalClient;
$provider->getAccessToken();
```
After that, simply review the code of the package. I hope that won't be much of a hassle. Let's say you want to get the current billing plans you have setup:

```
$billing_plans = $provider->listPlans();
```

**Comment by lovecoding-git** [comment]
Thank you, @srmklive 
WE do want documentation for this package please. :)

**Comment by AlexandreBulete** [comment]
Hi, I'm trying to understand this new version a bit too. After a while looking in the Traits files I can't find how to send an order (with an object containing the payer information, the purchases_units etc ...). I expected to find an Order file in the PayPalAPI folder but I didn't find it… :/
(paypal docs : [https://developer.paypal.com/docs/api/orders/v2](https://developer.paypal.com/docs/api/orders/v2))

I have to go through the server to verify some validations of reservations before proceeding to paypal payment. And after return a thank_you page.

First of all I injected my cart id in an ajax post, with axios, inside the createOrder function. 
After this I retrieve everything from my controller. I have my provider (with access_token, currency, config etc…) and cart id that I use to get a collection with all cart items informations needed (net, gross, amount, quantity etc…).

But After all this I don't understand how I can properly send this informations to paypal to proccess to the user payment.
And an other question : How can I say to Paypal tu return me on this controller the response to know if I return the thank_you page or if I return back with the error.

Someone could help me ?

**Comment by AlexandreBulete** [comment]
Sorry for my previous message. I finally find it ! 😃 

I post here what I find and understood if it's okay for you.

I just had to use Guzzle to return the data needed (here my order id created) after all my verifications. Then, return the response to retrieve it in the callback function of the `then()` function (using axios). 

```php
public function back(Request $request) {
    // I verify all my cart items
    // ...

    // I Set up my PayPal informations
    $provider = \PayPal::setProvider(); // used from the facade (cf the README)
    $provider->setApiCredentials(config('paypal')); // set configs from the payal.php file
    // get access_token and token_type from the $provider->getAccessToken()
    $access_token = $provider->getAccessToken()['access_token'];
    $token_type = $provider->getAccessToken()['token_type'];
    $provider->setCurrency('EUR'); // set the currency

    // I make my REST API call with Guzzle
    $client = new \GuzzleHttp\Client();
    $res = $client->request('POST', 'https://api-m.sandbox.paypal.com/endpoint', [
        // informations to send 
        // (cf : https://developer.paypal.com/docs/api/overview/#make-rest-api-calls)
    ]);

    return $res;
});
```

And get the PayPal data after the transaction using the `onApprove()` function : 
```js
onApprove: function(data, actions) {
    return actions.order.capture().then(function(details) {
        // get the details after Paypal transaction
        // Can be used to another Ajax to update some tables infos (clear cart, update invoice, create invoice pdf etc…)
    })
}
```

I recommend you to check this part of the PayPal docs guys : 
[https://developer.paypal.com/docs/checkout/reference/upgrade-integration/](https://developer.paypal.com/docs/checkout/reference/upgrade-integration/)
That's really usefull to understand all the news PayPal changement.

------------------------------------------------

@srmklive After all this investigations I find this little part which will be deprecated :
Guzzle say that the json_decode will be removed in `guzzlehttp/guzzle:8.0` and to use `Utils::jsonDecode` instead
```php
class PayPalHttpClient // (line 198)
    // ...
    private function doPayPalRequest($decode = true)
    {
        try {
            // Perform PayPal HTTP API request.
            $response = $this->makeHttpRequest();

            return ($decode === false) ? $response->getContents() : \GuzzleHttp\json_decode($response, true);
        } catch (RuntimeException $t) {
            $message = collect($t->getMessage())->implode('\n');
        }
        // ...
    }
```

Here the information from Guzzle (in the comment section) : 
[https://github.com/guzzle/guzzle/blob/master/src/functions.php](https://github.com/guzzle/guzzle/blob/master/src/functions.php)
```php
/**
 * ...
 * @deprecated json_decode will be removed in guzzlehttp/guzzle:8.0. Use Utils::jsonDecode instead.
 */
function json_decode(string $json, bool $assoc = false, int $depth = 512, int $options = 0)
{
    return Utils::jsonDecode($json, $assoc, $depth, $options);
}
```
------------------------------------------------

Sorry in advance for going off topic :sweat_smile:
