### ISSUE TITLE
Issue with Laravel Cashier (Stripe)

### ISSUE THREAD

**Issue by QBLes** [srmklive/laravel-paypal#411]
So i had Laravel Cashier (Stripe) all setup and working it uses the Route::stripeWebhooks('stripe-webhooks')
So now whenever i click to pay with Stripe i enter card details i notice it says in bottom left corner waiting for strips API but before it gets a chance to load it(and redirect after payment) it sends me to paypal like it starts taking over the handle for stripe

**Comment by srmklive** [comment]
You have to look at your implementation of this package & Cashier. They might be conflicting.
