### ISSUE TITLE
Marketplaces and Platforms account

### ISSUE THREAD

**Issue by shankar-bavan** [srmklive/laravel-paypal#412]
Hi
Is it possible to create on Onboard seller account with this package?

https://developer.paypal.com/docs/api/partner-referrals/v2/

**Comment by srmklive** [comment]
@shankar-bavan since this specific API is only restricted to specific partners, i haven't added it yet.

**Comment by shankar-bavan** [comment]
> @shankar-bavan since this specific API is only restricted to specific partners, i haven't added it yet.

@srmklive , I noticed that PayPal removed the limitation few days back. Do you have any plan to add this?
