### ISSUE TITLE
Cannot find anything related to "Orders" in this library

### ISSUE THREAD

**Issue by sangio90** [srmklive/laravel-paypal#414]
Hello,
 Thanks for this project. 
Im trying to understand how to integrate this plugin to my project.

What I want to achieve is:
1. The webpage contains the paypal button, the user clicks on it and then (onCreate) I make a call to my backend where I create a new order using Paypal API.
2. The user confirms his payment details and then confirms the order, the onApprove callback is called and there I call my backend passing the order ID again.
3. On the backend I now check against Paypal API if the order is ok and I perform my business logic.

I would expect to find some Class/Trait concerning orders in your library which I cannot find.

I'm 99% sure I'm missing something.

Can you please tell me if my approach is wrong and what should I do to fix it?

Thanks a lot again.

**Comment by srmklive** [comment]
Please run `composer update` to update the package to the latest version.
