### ISSUE TITLE
Fix listPlans function

### ISSUE THREAD

**Issue by fpfp** [srmklive/laravel-paypal#416]
In Traits/PayPalAPI/BillingPlans.php > listPlans

$totals should be converted to string before call api to prevent not well formed error 

and please add the filter by product_id

the example in README is wrong please fix it

$provider->createOrder([
    "intent" => "CAPTURE",
    "purchase_units" => [
        [
            "amount" => [
                "currency_code" => "USD",
                "value" => "100.00"
            ]
        ]
    ]
]);

**Comment by srmklive** [comment]
Will have it fixed.
