### ISSUE TITLE
createOrder results in INVALID_REQUEST

### ISSUE THREAD

**Issue by nathanpayne** [srmklive/laravel-paypal#417]
I have used the example as shown in the documentation provided (although I fixed the syntax issues with the example) and no matter what I try I get:

`{"intent":"CAPTURE","purchase_units":{"amount":{"currency_code":"USD","value":"100.00"}}} {"name":"INVALID_REQUEST","message":"Request is not well-formed, syntactically incorrect, or violates schema.","debug_id":"d0dedc452521e","details":[{"field":"/purchase_units","location":"body","issue":"INVALID_SYNTAX","description":"MALFORMED_REQUEST_JSON"}],"links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_SYNTAX","rel":"information_link","encType":"application/json"}]}`

Any advice?

**Comment by fpfp** [comment]
Try this, purchase_units should be an array of objects:

$provider->createOrder([
    "intent" => "CAPTURE",
    "purchase_units" => [
        [
          "amount" => [
              "currency_code" => "USD",
              "value" => "100.00"
           ]
        ]
    ]
]);

**Comment by ali-awwad** [comment]
@fpfp Thanks, the example in the documentation missing additional array.

**Comment by esponges** [comment]
This example was quite helpfull to create my JSON body:

https://github.com/paypal/Checkout-PHP-SDK/blob/develop/samples/CaptureIntentExamples/CreateOrder.php
