### ISSUE TITLE
Trying to access array offset on value of type null ()

### ISSUE THREAD

**Issue by kobazzo** [srmklive/laravel-paypal#418]
Hi, 
  i'm trying to use your library with Laravel 8, but i have this error "**Trying to access array offset on value of type null**" relative to the row 

`$this->apiUrl = collect([$this->config['api_url'], $this->apiEndPoint])->implode('/');`

in srmklive\paypal\src\Traits\PayPalAPI\Orders.php:21

This is the code in my controller:

```
$provider = new PayPalClient;

        // Through facade. No need to import namespaces
        $provider = PayPal::setProvider();
        $provider->setCurrency('EUR');
        $provider->createOrder([
            "intent"=> "CAPTURE",
            "purchase_units"=> [
                "amount"=> [
                  "currency_code"=> "USD",
                  "value"=> "100.00"
                ]
            ]
        ]);
```

Can someone help me? There is no documentation...

**Comment by kobazzo** [comment]
config['api_url'] is null.
The class PayPal.php has setOptions($credentials) method that sets config['api_url']. This protected method is never called, is this a bug?

**Comment by sergioalmela** [comment]
Same problem here, did you found any solution?

**Comment by kobazzo** [comment]
> Same problem here, did you found any solution?

yes, thank you.

**Comment by sergioalmela** [comment]
> > Same problem here, did you found any solution?
> 
> yes, thank you.

How did you solved it?

**Comment by kobazzo** [comment]
> > > Same problem here, did you found any solution?
> > 
> > 
> > yes, thank you.
> 
> How did you solved it?

This is the basic correct setup:

PayPal::setProvider();
$paypalProvider = PayPal::getProvider();
$paypalProvider->setApiCredentials(config('paypal'));
$paypalProvider->setAccessToken($paypalProvider->getAccessToken());

**Comment by yob-yob** [comment]
@srmklive I've made a pull request #430 for this issue

**Comment by srmklive** [comment]
If you have properly set the credentials accordingly as described in README, then this error shouldn't happen.
