### ISSUE TITLE
How to simulate errors passing PayPal-Mock-Response header

### ISSUE THREAD

**Issue by esponges** [srmklive/laravel-paypal#422]
According to the docs (https://developer.paypal.com/docs/business/test-and-go-live/simulation-tests/#orders), there's a way of simulating errors passing this header `-H "PayPal-Mock-Response: {"mock_application_codes" : "INSTRUMENT_DECLINED"}"` with the http request. 

I was diving in into the `captureOrder` method -which is the method I'm most interested to test in order to avoid false positive status- and saw that you can pass a second optional argument `$data = [ ]` for the `options`. 

I have tried several option combinations (strings, json objects, json arrays) for the above mentioned header and haven't had the desired `INSTRUMENT_DECLINED` response, just `status: COMPLETED` which won't help me a lot.

Some of my unsuccessful attemps:

```
        // $options = "PayPal-Mock-Response: {'mock_application_codes' : 'INSTRUMENT_DECLINED'}";
        // $options = ['PayPal-Mock-Response' => "['mock_application_codes':'INSTRUMENT_DECLINED']"];
        // $options = ["PayPal-Mock-Response: {'mock_application_codes' : 'INSTRUMENT_DECLINED'}"];
        // $options = ['PayPal-Mock-Response' => ['mock_application_codes' => 'INSTRUMENT_DECLINED']];
        // $options = ['{\"mock_application_codes\":\"INSTRUMENT_DECLINED\"}'];
        // $options = ['PayPal-Mock-Response":{\"mock_application_codes\":\"INSTRUMENT_DECLINED\"}'];
        // $options = ['PayPal-Mock-Response: {\"mock_application_codes\":\"INSTRUMENT_DECLINED\"}'];

$response = $paypalProvider->capturePaymentOrder($paypalOrderId, $options);
```
Thanks in advance,

Fernando

**Comment by srmklive** [comment]
Kindly submit a PR for this.
