### ISSUE TITLE
[Request] Mock Fakers - For Better Testing Experience

### ISSUE THREAD

**Issue by yob-yob** [srmklive/laravel-paypal#429]
it would be nice to have `PayPal::fake()` feature

```php
PayPal::fake();

$provider = new PayPalClient();

$product = $provider->createProduct([
  "name" => "Video Streaming Service",
  "description" => "Video streaming service",
  "type" => "SERVICE",
  "category" => "SOFTWARE",
  "image_url" => "https://example.com/streaming.jpg",
  "home_url" => "https://example.com/home"
]);

$response = $this->get('/products');

$response->assertSee($product->name);
```

then the fake Order will be saved in a JSON file or maybe in a Temp SQLite Database.

I requested this since this is how I understand testing external services, if you do have other alternative suggestions on how I should test my application using your package, please do share it with me, I'm out of ideas.

**Comment by srmklive** [comment]
Please submit a PR for this.
