### ISSUE TITLE
[Concern] Is this package still actively maintained?

### ISSUE THREAD

**Issue by yob-yob** [srmklive/laravel-paypal#432]
First of all, Thank you for this package... it may not be that good but it's the only package that we have that supports the latest PayPal REST API... it's would be sad for this package to be archived or outdated...

- The last commit was a month ago...
- The `Documentation` Branch's last commit was 8 months ago...
- The `gh-pages` Branch's last commit was 5 years ago...
- The `master` Branch is outdated ( I guess since 3.0.0 is the main branch now ) ( Version Release should be a tag, not a new branch)
- Last Pull-Request that was accepted was on April 12, 2021, which was a month ago.

PayPal may have better alternatives like `Stripe` & `Paddle` but there are just some clients who don't want to use those services but instead stick with what they know and is strict about it...

If you don't have enough time to maintain this package, I'll try my best to help. I have clearly understood how this works under the hood and do think I can offer some improvements.

Here are the things I Plan to contribute

- [ ] Proper Documentation ( Already Starting on it - Will make a pull request soon )
- [ ] Better Test Coverage
- [ ] Answering/Closing/Maintaining Issues
- [ ] Accepting Pull Requests

**Comment by DeanVanGreunen** [comment]
Thanks bro, I've being super busy with other projects that I haven't had time to assist with documentation or code updates

**Comment by srmklive** [comment]
All of us have been really busy with work and family matters. I haven't had time to work on the documentation. But have enough on hand right now to work on the documentation from next week onwards.
