### ISSUE TITLE
Error on adaptive payments

### ISSUE THREAD

**Issue by dpaniagua0** [srmklive/laravel-paypal#44]
**Adaptive payments**

When i try to send an adaptive payment, show this error.

Error message.
**Client error: `POST https://api-3t.sandbox.paypal.com/nvp/Pay` resulted in a `404 Not Found` response:**

something about the actionType

**Comment by dpaniagua0** [comment]
Never mind

**Comment by mauroartizzu** [comment]
@dpaniagua0 how did you solve this? it's throwing me the same error

**Comment by dpaniagua0** [comment]
@mauroartizzu  Check this file.

Traits\PayPalRequest

In the line 84 you have this piece of code

if ($this instanceof AdaptivePayments) {

I just change that line to:

if ($this instanceof \Srmklive\PayPal\Services\AdaptivePayments) {

There was something wrong when it tries to check the instance.

**Comment by mauroartizzu** [comment]
I filed a PR. Thanks!
