### ISSUE TITLE
i just get error 

### ISSUE THREAD

**Issue by webciter** [srmklive/laravel-paypal#442]
I just get error array  with no message on all functions, could use some meaning full messages or possibly capture the paypal api messages.

**Comment by askerakbar** [comment]
did you find a solution to this ? @webciter

**Comment by shekenz** [comment]
I'm having the same issue. Getting errors message from Paypal was pretty confusing. This is how I dealt with it :

Reading through the code, I noticed that if you get an error from the Paypal API, it'll return an array like :
```
[
    'type' => 'error', 
    'message' => $paypalError 
]
```

Then, the `$paypalError` is a string containing 2 json objects separated by a space, like `"{} {}"`, which will make decode_json() return null.
Only the second json object corresponds to the original Paypal error object. I had to parse the string to get the error details.

You can see how in works in the trait `PayPalHttpClient`, methods `doPayPalRequest()` and `makeHttpRequest()`.
That being said, I think that behavior is really twisted and definitely needs some rework.

Anyway, that was maybe specific to my case, but still I hope it's helping.

**Comment by m-primo** [comment]
I had the same issue, I had to edit the `PayPalHttpClient` trait, function `doPayPalRequest`, and remove all the decode part and replaced it with

```php
return Utils::jsonDecode($response->getContents(), true);
```

It's the only way this thing worked.
Please somebody fix this in the source code.
