### ISSUE TITLE
Adjust Request Headers

### ISSUE THREAD

**Issue by tomshaw** [srmklive/laravel-paypal#445]
The header found deeply hidden in the PayPal V2 documentation under [create template response](https://developer.paypal.com/docs/api/invoicing/v2/#templates-create-response) `prefer=return=representation` is recommended if you wish to get a full response when creating an invoice. Is there anyway to push that header to options headers?

**Comment by srmklive** [comment]
No there is not. But i think a new method may be warranted. Will look into adding it.
