### ISSUE TITLE
Paypal discount not applied

### ISSUE THREAD

**Issue by howdu** [srmklive/laravel-paypal#449]
Version: 1.8.0

Paypal is not applying the shipping discount. Well is does half work - when you first redirect to paypal and click the arrow for more details is correct:

2 Test Product £11.50GBP
Subtotal £23.00GBP
Shipping £3.95GBP
Shipping discount -£2.30GBP
Total £24.65GBP

But the transaction and email customer receives are the wrong total without the discount and completely lost the shipping discount:
<img width="1023" alt="Screenshot 2021-08-08 at 18 06 09" src="https://user-images.githubusercontent.com/533658/128639757-5d97c2f6-cd7c-4c00-adda-95169d4208f0.png">

Checked that the success is posting back the shipping discount here's the full data:
```
array (
  'cancel_url' => 'https://test.com/cart',
  'return_url' => 'https://test.com/checkout/success',
  'invoice_id' => 'KJRE-LE6O',
  'invoice_description' => 'Order #KJRE-LE6O',
  'quantity' => 2,
  'subtotal' => '23.00',
  'shipping_discount' => '2.30',
  'total' => '26.95',
  'shipping' => '3.95',
  'items' => 
  array (
    0 => 
    array (
      'name' => 'Test Product',
      'price' => '11.50',
      'desc' => 'More details',
      'qty' => 2,
    ),
  ),
)
```

If I change the total to include the shipping discount I get error:

> The totals of the cart item amounts do not match order amounts

**Comment by srmklive** [comment]
This is not an issue with the package. It seems these are just paypal requirements to set the totals like this.
