### ISSUE TITLE
exception, site broken, on new composer install (laravel v 8.54)

### ISSUE THREAD

**Issue by foxyproxygirl** [srmklive/laravel-paypal#451]
I wanted to use your plugin for a project I'm doing, but when I attempt to install the repository (v3, with composer), the system throws an ErrorException (array_merge(): Expected parameter 2 to be an array, int given). The website is broken after I attempted to do the composer install. I had to uninstall it to get the site to work again. Am I using an unsupported version of laravel (8.54) for your plugin? Is there a way to get this to install correctly? Thanks for your help! : )

![Screenshot from 2021-08-23 13-00-59](https://user-images.githubusercontent.com/9323247/130511807-a600c9b7-d35b-4820-98a8-29d997ff3ce2.png)

**Comment by srmklive** [comment]
I can't replicate it on a new or current project.
