### ISSUE TITLE
refund payment

### ISSUE THREAD

**Issue by marwaaz** [srmklive/laravel-paypal#452]
I use srmklive package with Laravel in live mode when pay from Visa card the response return success but the money discount from My card but it refund after many minute to my card and not find any payments in business account what solve the problem?

**Comment by srmklive** [comment]
This is primarily an issue on the Credit Card. It may not have funds available or the card is not activated for online payments. It is not a package issue.

**Comment by marwaaz** [comment]
thanks for reply @srmklive .
the card is valid  and I use it for any payments.
the money discount and refund .
when print response it return {"TOKEN":"EC-9HV34821CT187562V","BILLINGAGREEMENTACCEPTEDSTATUS":"1","CHECKOUTSTATUS":"PaymentActionNotInitiated","TIMESTAMP":"2021-08-25T10:25:56Z","CORRELATIONID":"fc1a2e0504a40","ACK":"Success","VERSION":"123","BUILD":"55938276","EMAIL":"art.design.sy@gmail.com","PAYERID":"DE3QLLJ2NKGA6","PAYERSTATUS":"unverified","FIRSTNAME":"khaled","LASTNAME":"albadawi","COUNTRYCODE":"SA","ADDRESSSTATUS":"Confirmed","CURRENCYCODE":"USD","AMT":"1.00","ITEMAMT":"1.00","SHIPPINGAMT":"0.00","HANDLINGAMT":"0.00","TAXAMT":"0.00","DESC":"test","INVNUM":"KARAM94_PAYPAL42","INSURANCEAMT":"0.00","SHIPDISCAMT":"0.00","INSURANCEOPTIONOFFERED":"false","L_NAME0":"100 Hrs of online sessions","L_QTY0":"1","L_TAXAMT0":"0.00","L_AMT0":"1.00","PAYMENTREQUEST_0_CURRENCYCODE":"USD","PAYMENTREQUEST_0_AMT":"1.00","PAYMENTREQUEST_0_ITEMAMT":"1.00","PAYMENTREQUEST_0_SHIPPINGAMT":"0.00","PAYMENTREQUEST_0_HANDLINGAMT":"0.00","PAYMENTREQUEST_0_TAXAMT":"0.00","PAYMENTREQUEST_0_DESC":"test","PAYMENTREQUEST_0_INVNUM":"KARAM94_PAYPAL42","PAYMENTREQUEST_0_INSURANCEAMT":"0.00","PAYMENTREQUEST_0_SHIPDISCAMT":"0.00","PAYMENTREQUEST_0_SELLERPAYPALACCOUNTID":"khaled@futureskill.online","PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED":"false","L_PAYMENTREQUEST_0_NAME0":"100 Hrs of online sessions","L_PAYMENTREQUEST_0_QTY0":"1","L_PAYMENTREQUEST_0_TAXAMT0":"0.00","L_PAYMENTREQUEST_0_AMT0":"1.00","PAYMENTREQUESTINFO_0_ERRORCODE":"0"}
