### ISSUE TITLE
How to Add Custom Variable in setExpressCheckout and get it back in IPN response

### ISSUE THREAD

**Issue by 3gHub** [srmklive/laravel-paypal#455]
I am using this plugin.
I added in addOptions method like this:

`As I am using Recurring Payment so it is necessary to get IPN result along with custom id i.e USERID`

```
 $options = [
        'USERID' => $userId,
        ];
$response = $this->provider->addOptions($options)->setExpressCheckout($cart, $recurring, $package);
```

Now I do `dd($response)` but not got `USERID` in response, which I am sending as custom value/field.

Also Can I get it on `IPN` like this:

```
public function note(Request $request)
    {
        $request->merge(['cmd' => '_notify-validate']);
        $post = $request->all();

        $response = (string) $this->provider->verifyIPN($post);

        if ($response === 'VERIFIED') {

            if ($post['txn_type'] == 'recurring_payment' && $post['payment_status'] == 'Completed') {

                $transaction_id = rand(10000000,99999999);

                $userId = $post['USERID'];
}
```

Kindly help on this. 

One more thing. Kindly Do not Reply `See the Docs`. I have seen that. This is not specified in docs too.

Looking forward to your reply.

**Comment by 3gHub** [comment]
@srmklive  Are you there ?

**Comment by srmklive** [comment]
Refer to the documentation of the respective API method. I have referred to this clearly in the README. If you can't see it clearly in the documentation, look again.

**Comment by 3gHub** [comment]
Is this the documentation link ? `https://srmklive.github.io/laravel-paypal/docs.html` I have not find it on this docs.
If it is not can you kindly provide it ? @srmklive

**Comment by srmklive** [comment]
Look at the README for v1. There is a link called **PayPal Documentation**.

**Comment by 3gHub** [comment]
https://github.com/srmklive/laravel-paypal/blob/master/PAYPALDOCS.md   

Is this the link ? It is showing 404 Page not found.  @srmklive

**Comment by srmklive** [comment]
Select the v1.0 branch Einstein.

**Comment by 3gHub** [comment]
After selecting and checking I told you that it is showing 404. @srmklive

**Comment by srmklive** [comment]
I can access it even through a private window.

**Comment by 3gHub** [comment]
Even I can access this page:
![Screenshot_3](https://user-images.githubusercontent.com/85281650/136534408-1c517766-835d-4aa7-83b9-785f6159092f.png)
 

But after clicking on the link I got 404. @srmklive

**Comment by srmklive** [comment]
Great then
