### ISSUE TITLE
Refund not working

### ISSUE THREAD

**Issue by nemesesx** [srmklive/laravel-paypal#456]
Hi srmk first off all thanks for this  awesome package. I am facing  problem when i try to refund using `$paypalProvider->refundTransaction($booking->transactionId);` , errors says `Call to undefined method Srmklive\PayPal\Services\PayPal::refundTransaction()` , 
I am using v3 of package.
Thanks :)

**Comment by 00vtvt** [comment]
Need this as well, never seen a documentation so useless lmfaooo

**Comment by srmklive** [comment]
In the new payal rest api, direct refunds are not possible. It is done through creating disputes, and additional dispute actions are performed on it. 

If you can help out with the documentation, that will be great.

**Comment by 00vtvt** [comment]
What I did is just end up is just calling their REST API, feel free to create a public function by using this


        $access_token = $this->access_token($order_id);

        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, "https://api-m.paypal.com/v2/payments/captures/$order_id/refund");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, []);

        $headers = array();
        $headers[] = 'Content-Type: application/json';
        $headers[] = "Authorization: Bearer $access_token";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        return json_decode($result, true);


`$access_token` should be your access token, I'm just calling it from another function. `$order_id` should be the value you find by doing checking the transaction via the API, this is the **CAPTURE ID** but it is completely separate and unique that you find in PayPal's response back

**Comment by srmklive** [comment]
There is already a method available for this in the package. You can do it using the following:

```
$provider->refundCapturedPayment($capture_id, $invoice_id, $amount, $note);
```
