### ISSUE TITLE
IPN is not working on V1

### ISSUE THREAD

**Issue by 3gHub** [srmklive/laravel-paypal#457]
I have followed the given steps in the Docs but still after successful Payment `IPN `method is `not hit`. I checked in the `IPN `history of `Paypal Account` which I am using. But I have got no history. Kindly help on this. @srmklive

**Comment by srmklive** [comment]
Please check that whether CSRF verification is enabled for it or not. It should be disabled for it.

**Comment by 3gHub** [comment]
I have checked that. It is disabled. @srmklive

**Comment by srmklive** [comment]
Can't help you with it. In my view, it's an issue on your end.

**Comment by 3gHub** [comment]
I am using IP based URL like:  `http://182.100.25.4/foo/bar/baz ` as IPN `notify_url`.  Will it be the problem ?? @srmklive
