### ISSUE TITLE
No Orders in Traits/PayPalAPI for package v2

### ISSUE THREAD

**Issue by rebecks** [srmklive/laravel-paypal#460]
There is no Orders.php for package v2 unlike v3, how do I go about it? Is there any demo or documentation on how to use package v2 to create order? I can't upgrade to v3 as the application I am working on is using Laravel 5.6 and PHP 7.1.

**Comment by srmklive** [comment]
I am looking at merging it before the weekend. I will update this ticket when done.

**Comment by srmklive** [comment]
I have tagged a new release for v2. Please check and let me know if it resolves the issue.

**Comment by rebecks** [comment]
Yay! Awesome. Thank you so much! Will get the latest changes and let you know if got any other issues. :)
