### ISSUE TITLE
Credentials are not loaded by default resulting in error

### ISSUE THREAD

**Issue by jacobtread** [srmklive/laravel-paypal#463]
When creating via PayPal::setProvider() the default api credentials are not loaded from the config file resulting in a error
 
because Srmklive\PayPal\Services\PayPal only sets the config if its passed an array as the argument but the default is a string which is what is being used by the provider

![image](https://user-images.githubusercontent.com/33708767/139578108-0c7c7b85-6cd0-405a-9d59-3023b93a6557.png)

![image](https://user-images.githubusercontent.com/33708767/139578133-c2d12260-a1ed-4065-8fdd-0f8b81483c9c.png)

![image](https://user-images.githubusercontent.com/33708767/139578156-937185d4-046d-4025-9648-15a188da4e2b.png)

Which means I have to manually make the call to $provider->setApiCredentials(config('paypal'));  which is confusing because your documentation states that this function is indented to override the default credentials

**Comment by srmklive** [comment]
you have not set up the configuration properly. Read the documentation.

**Comment by jacobtread** [comment]
The documentation states to override the configuration but why would I want to override the configuration when in the code if that wasn't a string being provided it would load the configuration file paypal.php instead of me having to call the override function every time

**Comment by srmklive** [comment]
You haven't read it correctly. As i said your configuration might not be setup properly.

**Comment by jacobtread** [comment]
My configuration is setup exactly how its stated in the documentation however I have to make that override call every time I want to set the configuration 

Your function here for set config takes in an array and loads from the config file if the function config exists correct
 
 ​    ​private​ ​function​ ​setConfig​(​array​ ​$​config​ = []) 
 ​    { 
 ​        ​$​api_config​ = ​function_exists​(​'config'​) ? ​config​(​'paypal'​) : ​$​config​; 
  
 ​        ​// Set Api Credentials 
 ​        ​$​this​->​setApiCredentials​(​$​api_config​); 
 ​    }

However this is only ever called if an array is given to the function that calls it 

 
 ​    ​public​ ​function​ ​__construct​(​$​config​ = ​''​) 
 ​    { 
 ​        ​// Setting PayPal API Credentials 
 ​        ​if​ (​is_array​(​$​config​)) { 
 ​            ​$​this​->​setConfig​(​$​config​); 
 ​        }

As you can see it checks if config is an array but in this case the config is a string by default meaning this will never be called if you set it from the provide because the provider uses the default constructor

 
 ​    ​public​ ​static​ ​function​ ​setProvider​() 
 ​    { 
 ​        ​// Set default provider. Defaults to ExpressCheckout 
 ​        ​self​::​$​provider​ = ​new​ ​PayPalClient​();

**Comment by topninja** [comment]
same issue on my ends

I am using v2 and laravel version is 5.6 and default provider is null
attached screenshot.
![image](https://user-images.githubusercontent.com/47001971/142207133-b1ac4d86-613a-48cb-8593-cb4eb82e56d7.png)

**Comment by srmklive** [comment]
Look at the README file for v1 here:

https://github.com/srmklive/laravel-paypal/blob/v1.0/README.md

If you all can't figure it out, then I am sorry I can't help you.
