### ISSUE TITLE
Paypal Payment Processing

### ISSUE THREAD

**Issue by mmejaz** [srmklive/laravel-paypal#464]
Paypal Array returning success message but payment not getting process I am using Laravel and express-checkout
![VkESp](https://user-images.githubusercontent.com/16265213/140659177-5a4dbfd4-6538-4c07-befe-e1fd0f19f13a.png)

**Comment by srmklive** [comment]
Hi,

It seems to me that you are using the v1 package, and are creating a subscription. Please have a look at the README file, on how to properly create a subscription:

https://github.com/srmklive/laravel-paypal/blob/v1.0/README.md#create-subscriptions

Based on the attached screenshot, you have validated the payment credentials but have not processed the payment. What you need to do is perform the GetExpressCheckout API call to validate the response. Remove the **doExpressCheckoutPayment** API call, and add the **CreateRecurringPaymentsProfile** API call to create a recurring payment.

I have also created a demo application depicting the simple & recurring payment checkout:

https://github.com/srmklive/laravel-paypal-demo
