### ISSUE TITLE
How to create a billing agreement with v3?

### ISSUE THREAD

**Issue by hbr-t** [srmklive/laravel-paypal#465]
Hey,

I can create a billing agreement with v1 (= paypal nvp api).
However, I am unable to create a billing agreement in v3. I do not want to create a subscription with a fixed amount. Instead, I just want to create a billing agreement in order to create varying reference transactions in the future. Is this possible in v3?

Thank you.

**Comment by srmklive** [comment]
I think you are referring to billing plans. Following is the documentation link:

https://srmklive.github.io/laravel-paypal/docs.html
