### ISSUE TITLE
how can monthly auto subscription.this is possible for this package?

### ISSUE THREAD

**Issue by zainawan99** [srmklive/laravel-paypal#466]
how can monthly auto subscription.this is possible for this package?

**Comment by srmklive** [comment]
Read the documentation for the package. Look at the README file, the link is there?

**Comment by zainawan99** [comment]
@srmklive i m see documentation and apply code but i m facing some error

**Comment by zainawan99** [comment]
but they have not working currently you have checked

**Comment by srmklive** [comment]
You are not providing any information as to what is the error. Then how come i can help out.

**Comment by zainawan99** [comment]
array:2 [▼ "type" => "error" "message" =>
"{"product_id":"PROD-Enterprise-Plan-12","name":"Enterprise
Plan","description":null,"status":"ACTIVE","billing_cycles":[{"frequency":{"interval_unit":"DAY","interval_count":7},"tenure_type":"TRIAL","sequence":1,"total_cycles":1},{"frequency":{"interval_unit":"MONTH","interval_count":1},"tenure_type":"REGULAR","sequence":2,"total_cycles":0,"pricing_scheme":{"fixed_price":{"value":"60","currency_code":"AUD"}}}],"payment_preferences":{"auto_bill_outstanding":true,"setup_fee_failure_action":"CONTINUE","payment_failure_threshold":3},"merchant_preferences":{"return_url":null,"cancel_url":null}}
{"error":"invalid_client","error_description":"Client Authentication
failed"}

**Comment by zainawan99** [comment]
you have sent how can set parameter set subscription plan

**Comment by srmklive** [comment]
It's clear that client authentication failed. You need to first get the access token, then perform the API call. At least bother to read the documentation first.
