### ISSUE TITLE
Provider instantiation doesn't saturate instance with default config

### ISSUE THREAD

**Issue by fabilo-au** [srmklive/laravel-paypal#467]
I'm probably misunderstanding the documentation, but when I tried instantiating the provider object as per the documentation:
`$provider = new PayPalClient;`
I would get the following error `Call to a member function post() on null` as the object didn't have the default config applied. A quick look at the constructor and setConfig methods shows that an array must be passed to saturate the object with a config (including the default generated Paypal config).
What worked
`$provider = new PaypalClient([]);`

My interpretation of the documentation is that the standard declaration of `$provider = new PayPalClient;` would apply the default Paypal Laravel config.

**Comment by srmklive** [comment]
If the config is available, then it will be automatically applied. The config file should be `config/paypal.php`. Otherwise, you need to provide config when initializing the PayPal API client or through the `setApiCredentials` method. The documentation is pretty clear, and i have unit tests to backup me up on this.

**Comment by fabilo-au** [comment]
The config/paypal.php file exists, as it was generated via vender publish
command outlined in the documentation: php artisan vendor:publish
--provider "Srmklive\PayPal\Providers\PayPalServiceProvider"
Yes your documentation is clear, pity it doesn't execute as documented.

**Comment by srmklive** [comment]
Come to think of it, you are absolutely correct @fabilo-au. I have updated the flow as per your suggestion.

**Comment by fabilo-au** [comment]
Yay glad to help! Cheers mate
