### ISSUE TITLE
Cannot easily parse error message from createPlan() error response

### ISSUE THREAD

**Issue by fabilo-au** [srmklive/laravel-paypal#468]
Whilst testing the createPlan() method I noticed it's difficult to parse the error message from the response as it seems to be two JSON objects returned together (separated by spaces), therefore json_decode() will fail. Example error response, note the 2nd JSON object after the initial JSON object `{"error":"invalid_client","error_description":"Client Authentication failed"} `

Here's the output from dd() of the response from $provider->createPlan():
`array:2 [▼
  "type" => "error"
  "message" => "{"product_id":"PROD-Enterprise-Plan-12","name":"Enterprise Plan","description":null,"status":"ACTIVE","billing_cycles":[{"frequency":{"interval_unit":"DAY","interval_count":7},"tenure_type":"TRIAL","sequence":1,"total_cycles":1},{"frequency":{"interval_unit":"MONTH","interval_count":1},"tenure_type":"REGULAR","sequence":2,"total_cycles":0,"pricing_scheme":{"fixed_price":{"value":"60","currency_code":"AUD"}}}],"payment_preferences":{"auto_bill_outstanding":true,"setup_fee_failure_action":"CONTINUE","payment_failure_threshold":3},"merchant_preferences":{"return_url":null,"cancel_url":null}} {"error":"invalid_client","error_description":"Client Authentication failed"} ◀"
]`

**Comment by srmklive** [comment]
That is what is returned by PayPal, which is being returned directly on your end. Please open a PR for prospective errors response in such use cases.
