### ISSUE TITLE
Question rather than issue

### ISSUE THREAD

**Issue by Smokexyz** [srmklive/laravel-paypal#47]
Hello,

Awesome package, but i'm just wondering how to use IPN, or if it's complete.
When I log
```
$response = $this->verifyIPN($post);
Log::error($response);
```

The output is
```
array(
'INVALID' => '',
);
```
maybe if the response is valid, instead of throwing an empty exception it could be more informative as -
```
array(
'VALID' => true/false,
'ERROR_MSG' => '',
);
```

**Comment by srmklive** [comment]
Kindly refer to README regarding handling IPN [here](https://github.com/srmklive/laravel-paypal/blob/master/README.md#paypalipn)
