### ISSUE TITLE
please see issue i m create product 

### ISSUE THREAD

**Issue by zainawan99** [srmklive/laravel-paypal#470]
![image](https://user-images.githubusercontent.com/24542584/143385069-ed05deb1-454f-412e-a836-b9c5d2087485.png)

![image](https://user-images.githubusercontent.com/24542584/143385208-903e0634-ca3e-41a9-8fcd-e9dda8d9e02f.png)

![image](https://user-images.githubusercontent.com/24542584/143385151-d53d2516-6eb4-4e47-9f57-e1bd826ee3e1.png)

**Comment by srmklive** [comment]
You need to add a request id as a second parameter. It can be any identifier. I will update the documentation. FYI you can also look at the source code, as to how it is right now implemented. Do it like this:

```
$provider->createProduct($data, 'product-request-'.time());
```
