### ISSUE TITLE
Subscription plan after create issue

### ISSUE THREAD

**Issue by zainawan99** [srmklive/laravel-paypal#471]
![image](https://user-images.githubusercontent.com/24542584/143393591-2eef9a19-93d2-4b98-8f36-02c53927f666.png)

![image](https://user-images.githubusercontent.com/24542584/143393685-8ef420b2-5a4b-4596-a924-593acbf06a9d.png)

**Comment by srmklive** [comment]
Further details are needed. You need to look at the API documentation for createSubscription. I need to add documentation for the Subscription API.
