### ISSUE TITLE
APP_ID required in live environment.

### ISSUE THREAD

**Issue by MarekGogol** [srmklive/laravel-paypal#473]
Version: 3.0.8

Hello,

I think "PAYPAL_LIVE_APP_ID" should not be required, because is not available nowadays? Or am I mistaken? Because after update application fails with exception of missing app id.

Thank you.

![image](https://user-images.githubusercontent.com/11134410/143720236-5f0dc911-4649-4a4d-a9c3-f9fabb0ad684.png)

**Comment by srmklive** [comment]
You need to add the APP ID when you create it from the developer dashboard.

**Comment by vinwang** [comment]
Where can I find PAYPAL_LIVE_APP_ID？

**Comment by srmklive** [comment]
> Where can I find PAYPAL_LIVE_APP_ID？

This is just a configuration parameter. It is just meant to differentiate between live & sandbox app credentials.

**Comment by Cranbaerry** [comment]
I cant find my APP ID in the developer dashboard. 
Is it something that we can make on our own or is it given by the PayPal?

**Comment by srmklive** [comment]
It is given by PayPal once you get an access token.

**Comment by Cranbaerry** [comment]
I'm sorry but it's not clear to me. Is this app_id necessary for simple payment? Because it didn't require app_id in the previous versions. How do I even request an access token / app_id from paypal?

**Comment by srmklive** [comment]
Look at the documentation.

**Comment by Cranbaerry** [comment]
Yes, I did try to look up at the documentations. I couldn't find them, even google gave outdated answers. Please enlighten me.

**Comment by srmklive** [comment]
Look at the documentation for this package or view the README file.

**Comment by Cranbaerry** [comment]
So what I understood is:
I need to call `$provider->getAccessToken();` so that I can get the app_id
And the app_id will be returned by the getAccessToken? Or in the paypal dashboard?

**Comment by MarekGogol** [comment]
It is not clear for me as well. I could not find production app id. I was forced to downgrade version.

**Comment by MarekGogol** [comment]
I understand it now. You need receive APP ID from $paypal->getAccessToken() method. But definitally should be documented better, It was not clear at the beginning.

![image](https://user-images.githubusercontent.com/11134410/147952850-6b466903-67a4-4137-8d56-1a02658f4c9b.png)

![image](https://user-images.githubusercontent.com/11134410/147952893-2dc8fbda-c06e-4994-a3d7-8b19ca9890ed.png)
