### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by Frossard** [srmklive/laravel-paypal#48]
Hi buddy, i am looking for a solution to my app without a SSL certificate.
Can i only use this Express Checkout if i have an SSL certificate?
Thanks!

**Comment by srmklive** [comment]
You can use no SSL in your application. But it is still recommended when you are using PayPal IPN.

**Comment by Frossard** [comment]
I tried it without SSL, but i am having this error of cURL:

`cURL error 60: SSL certificate problem: unable to get local issuer certificate`

Also, im using this version of guzzle:

`"guzzlehttp/guzzle": "~5.3|~6.0"`

I tried with a previous version ~4.0 but it did not work.

what i can do in this case?

**Comment by srmklive** [comment]
I think you may need to update OpenSSL on your server

**Comment by deadmouse** [comment]
This has worked for me: https://goo.gl/fHGy6r
