### ISSUE TITLE
Set api credentials in different config file path

### ISSUE THREAD

**Issue by akozdem** [srmklive/laravel-paypal#487]
Hi,
I want to start PaypalClient with the credentials in this config path.

Config Path: "config/payment/paypal.php"

I tried the methods in your documents but failed.
Each time I try, the "vendor/srmklive/paypal/config/config.php" credentials in this file path are defined instead of the path I specified above.

Can you help me?

"version": "3.0.10"

**Comment by srmklive** [comment]
You can simply do it like this:

```
use Srmklive\PayPal\Services\PayPal as PayPalClient;

$config = config('payment.paypal');

$provider = new PayPalClient($config);
```

**Comment by akozdem** [comment]
Hi,
I do as you stated, but still the config.php file in the package is loaded.

Package Config Path: "vendor/srmklive/paypal/config/config.php"

Here is my code where I initialize PaypalClient:
![image](https://user-images.githubusercontent.com/59332767/146517195-c4943378-9dab-4709-a2eb-9806e475bc9b.png)

Origin of the problem:
![image](https://user-images.githubusercontent.com/59332767/146517915-58bbb579-9335-4d1b-ba2a-1ee6da14261d.png)

My files in the config folder:
![image](https://user-images.githubusercontent.com/59332767/146518330-f591e3ab-f805-4501-993f-21cd4ce92394.png)

The best solution I can do for now
(better if I don't have to play with the source files of course):
![image](https://user-images.githubusercontent.com/59332767/146518862-f02704c6-6b64-47a0-a4c8-1bff2eced3fa.png)

**Comment by srmklive** [comment]
That's not possible. You are doing it obviously wrong. First see, if your config has been loaded or not. It seems your configuration parameters have not been loaded.

**Comment by akozdem** [comment]
There is no problem loading my config files.

If there is something wrong:
`!empty(config('paypal'))`

Returning the result to true and defining the configuration information in your package path.

**Comment by akozdem** [comment]
@srmklive

**Comment by srmklive** [comment]
You might be caching your config. You may need to clear that, due to this it might not be working.

**Comment by srmklive** [comment]
Also kindly read the god damn documentation. If you can't figure it out, then it's not my problem.
