### ISSUE TITLE
can not create plan without trial pricing

### ISSUE THREAD

**Issue by fftfaisal** [srmklive/laravel-paypal#488]
I can not create subscription plan for a user if I pass without add addPlanTrialPricing() method, and if i send 0 days as trial days it also can not create plan. 
without addPlanTrialPricing() method its giving Request is not well-formed, syntactically incorrect, or violates schema error

here is my sample code
```
if($userPackage->regular_tier == 'D'){ 
           $plan = 'addDailyPlan';
        } elseif ($userPackage->regular_tier == 'M') {
            $plan = 'addMonthlyPlan';
        } elseif ($userPackage->regular_tier == 'W') {
            $plan = 'addWeeklyPlan';
        } else {
            $plan = 'addYearlyPlan';
        }
$provider = PayPal::setProvider();
        $provider->getAccessToken();
$response = $provider->addProduct( $userPackage->title . " teacher: #".auth()->id(), $userPackage->desc, 'SERVICE', 'SOFTWARE' )
       // ->addPlanTrialPricing( $trialTier, $userPackage->trial_period )
        ->$plan( $userPackage->title . " teacher: #".auth()->id(). " plan", $userPackage->desc, $userPackage->regular_amount )
        ->setupSubscription( auth()->user()->full_name, auth()->user()->email,now()->addMinute() );
        
```

**Comment by myfender** [comment]
I have the same problem. I am trying to make a plan without trial period without success:
`$response = $provider->addProduct('Demo Product', 'Demo Product', 'SERVICE', 'SOFTWARE')
            //->addPlanTrialPricing('DAY', 1)
            ->addMonthlyPlan('Demo Plan', 'Demo Plan', 100)
            ->setupSubscription('John Doe', 'john@example.com', '2022-01-03');`
This one not working

**Comment by fftfaisal** [comment]
> I have the same problem. I am trying to make a plan without trial period without success: `$response = $provider->addProduct('Demo Product', 'Demo Product', 'SERVICE', 'SOFTWARE') //->addPlanTrialPricing('DAY', 1) ->addMonthlyPlan('Demo Plan', 'Demo Plan', 100) ->setupSubscription('John Doe', 'john@example.com', '2022-01-03');` This one not working

Problem is maximum method are private/protected in the provider class thats why i can not over ride it, I already fix  it manually create product,plan then subscription.

**Comment by divdax** [comment]
Same here. Creative a subscription without trial doesn't work. Even when i set the trial to `0`
Could you share your code @fftfaisal 

Is there any working example for the current version to setup the complete subscription process?

**Comment by fftfaisal** [comment]
This is my version . 
```
private function createPaypalOrder()  {
  $data = $this->getUserPackageData();
  extract($data);
  if($userPackage->regular_tier == 'D'){
      $plan = 'addDailyPlan';
      $planName = 'D';
  } elseif ($userPackage->regular_tier == 'M') {
      $plan = 'addMonthlyPlan';
  } elseif ($userPackage->regular_tier == 'W') {
      $plan = 'addWeeklyPlan';
  } else {
      $plan = 'addYearlyPlan';
  }

  if($userPackage->trial_period <= 0){
      // dd($userPackage->trial_period);
      $data = [
          'name' => $userPackage->title,
          'description' => $userPackage->desc,
          'price' => $userPackage->regular_amount,
          'tier' => $tier,
          'period' => $userPackage->regular_period,
      ];
      $response = $this->getPlanDetails($data);
  } else {
      $provider = PayPal::setProvider();
      // $provider->getAccessToken();
      $provider->setAccessToken($provider->getAccessToken());
      $response = $provider->addProduct( $userPackage->title . " teacher: #".auth()->id(), $userPackage->desc, 'SERVICE', 'SOFTWARE' )
      ->addPlanTrialPricing( $trialTier, $userPackage->trial_period )
      ->$plan( $userPackage->title . " teacher: #".auth()->id(). " plan", $userPackage->desc, $userPackage->regular_amount )
      ->setupSubscription( auth()->user()->full_name, auth()->user()->email,now()->addMinute() );
  }

  if(isset($response['type']) && $response['type']  == 'error' ) {
      return response()->json(['type' => 'error','message'=> 'Something went wrong! Please refresh this page and try again.'], 200);
  }

  return response()->json(['type'=> 'success','id'=> $response['id'] ], 200);
}



private function getPlanDetails( $data ) {

    extract( $data );

    $provider = PayPal::setProvider();
    $provider->getAccessToken();
    $request_id = \Str::random();
    $product    = $provider->createProduct( [
        'name'        => $name . " teacher: #" . auth()->id(),
        'description' => $description,
        'type'        => 'SERVICE',
        'category'    => 'SOFTWARE',
    ], $request_id );
    // dd($product);
    $pricing_scheme = [
        'fixed_price' => [
            'value'         => $price,
            'currency_code' => $provider->getCurrency(),
        ],
    ];

    $billing_cycles = [
        [
            'frequency'      => [
                'interval_unit'  => $tier,
                'interval_count' => $period,
            ],
            'tenure_type'    => 'REGULAR',
            'sequence'       => 1,
            'total_cycles'   => 0,
            'pricing_scheme' => $pricing_scheme,
        ],
    ];
    $plan_params = [
        // 'product_id'          => 'PROD-9MJ90095XG5118618',
        'product_id'          => $product['id'],
        'name'                => $name . " teacher: #" . auth()->id() . " plan",
        'description'         => $description,
        'status'              => 'ACTIVE',
        'billing_cycles'      => $billing_cycles,
        'payment_preferences' => [
            'auto_bill_outstanding'     => true,
            'setup_fee_failure_action'  => 'CONTINUE',
            'payment_failure_threshold' => 3,
        ],
    ];
    // dd($plan_params);
    $plan = $provider->createPlan( $plan_params, $request_id );
    // dd($plan);

    $subscription = $provider->createSubscription( [
        'plan_id'    => $plan['id'],
        'start_time' => now()->addDay()->toIso8601String(),
        'quantity'   => 1,
        'subscriber' => [
            'name'          => [
                'given_name' => auth()->user()->full_name,
            ],
            'email_address' => auth()->user()->email,
        ],
        // 'custom_id' => '',
    ] );
    return $subscription;
}

```

> Same here. Creative a subscription without trial doesn't work. Even when i set the trial to `0` Could you share your code @fftfaisal
> 
> Is there any working example for the current version to setup the complete subscription process?

**Comment by myfender** [comment]
> Problem is maximum method are private/protected in the provider class thats why i can not over ride it, I already fix it manually create product,plan then subscription.

Where is it? i did not find the problem. In which file?

**Comment by srmklive** [comment]
My question is why you are making the plan title & description the same as the product title or description. The code snippet I mentioned in the README works as intended.

```
$package_tier = 'D';

if ($package_tier === 'D') {
    $plan_method = 'addDailyPlan';
} elseif ($package_tier === 'W') {
    $plan_method = 'addWeeklyPlan';
} elseif ($package_tier === 'M') {
    $plan_method = 'addMonthlyPlan';
} elseif ($package_tier === 'Y') {
    $plan_method = 'addAnnualPlan';
}

$provider = new \Srmklive\PayPal\Services\PayPal($config);

$provider->getAccessToken();

$response = $provider->addProduct('Demo Product', 'Demo Product', 'SERVICE', 'SOFTWARE')
    ->addPlanTrialPricing('DAY', 7)
    ->$plan_method('Demo Plan', 'Demo Plan', 6)
    ->setupSubscription('John Doe', 'john@example.com', '2022-01-10');
```

**Comment by fftfaisal** [comment]
@srmklive  the main problem is can not create plan without trial pricing. the same title & description can  be used I used in the api also in side paypal account where i can create plan visually.

**Comment by fftfaisal** [comment]
> > Problem is maximum method are private/protected in the provider class thats why i can not over ride it, I already fix it manually create product,plan then subscription.
> 
> Where is it? i did not find the problem. In which file?

You can check subscription method in this file : srmklive\paypal\src\Traits\PayPalAPI\Subscriptions\Helpers.php
```
addPlanBillingCycle() and addBillingPlan() are protected. 

```
    public function addAnnualPlan(string $name, string $description, float $price): \Srmklive\PayPal\Services\PayPal
    {
        if (isset($this->billing_plan)) {
            return $this;
        }

        $plan_pricing = $this->addPlanBillingCycle('YEAR', 1, $price);
        $billing_cycles = collect([$this->trial_pricing, $plan_pricing])->filter()->toArray();

        $this->addBillingPlan($name, $description, $billing_cycles);

        return $this;
    }
    
every plan method is now required trial pricing, which is need to be optional
```
$billing_cycles = collect([$this->trial_pricing, $plan_pricing])->filter()->toArray();

**Comment by srmklive** [comment]
Your code is wrong. `now()->addMinute()` creates a Carbon instance and returns it. Look at my code, I am passing in a simple date string. 

I just create one with & without trial pricing. Obviously, the problem seems to be with your account. The code just works. I would rather have a different description for the product & plan. 

Stop making it so complex for yourself.

**Comment by fftfaisal** [comment]
```php
->addPlanTrialPricing('DAY', 0)

```
@srmklive 
when I pass 0 day in this method its giving malformed json error 
also if i do without this method , give another malformed json error 
just tell me how to input 0 trial day

**Comment by fftfaisal** [comment]
> Your code is wrong. `now()->addMinute()` creates a Carbon instance and returns it. Look at my code, I am passing in a simple date string.
> 
> I just create one with & without trial pricing. Obviously, the problem seems to be with your account. The code just works. I would rather have a different description for the product & plan.
> 
> Stop making it so complex for yourself.

Can you please give me without trial pricing code ?

**Comment by srmklive** [comment]
If you can come up with a fix, please add a PR for this.

**Comment by myfender** [comment]
> Your code is wrong. `now()->addMinute()` creates a Carbon instance and returns it. Look at my code, I am passing in a simple date string.
> 
> I just create one with & without trial pricing. Obviously, the problem seems to be with your account. The code just works. I would rather have a different description for the product & plan.
> 
> Stop making it so complex for yourself.

I have the same problem, I can't create a plan without the trial. I have also seen that it is not possible to create a different payment cycle (every six months for example) by passing the data.
I fork your repository, now I make the changes and do the PR

**Comment by srmklive** [comment]
> ```
> $billing_cycles = collect([$this->trial_pricing, $plan_pricing])->filter()->toArray();
> ```




@fftfaisal  It means we are combining the trial & billing cycles. Currently, the packages allows one trial & a regular billing cycle.

If you are analyzing code, at least do it right.

> > > Problem is maximum method are private/protected in the provider class thats why i can not over ride it, I already fix it manually create product,plan then subscription.
> > 
> > 
> > Where is it? i did not find the problem. In which file?
> 
> You can check subscription method in this file : srmklive\paypal\src\Traits\PayPalAPI\Subscriptions\Helpers.php
> 
> ```
> addPlanBillingCycle() and addBillingPlan() are protected. 
> ```
> 
> ```
> public function addAnnualPlan(string $name, string $description, float $price): \Srmklive\PayPal\Services\PayPal
> {
>     if (isset($this->billing_plan)) {
>         return $this;
>     }
> 
>     $plan_pricing = $this->addPlanBillingCycle('YEAR', 1, $price);
>     $billing_cycles = collect([$this->trial_pricing, $plan_pricing])->filter()->toArray();
> 
>     $this->addBillingPlan($name, $description, $billing_cycles);
> 
>     return $this;
> }
> ```
> 
> every plan method is now required trial pricing, which is need to be optional
> 
> ```
> $billing_cycles = collect([$this->trial_pricing, $plan_pricing])->filter()->toArray();
> ```

What in the hell are you talking about? Not every plan method requires trial pricing. The last line you quoted means the trial & regular billing cycle is being combined. If you are analyzing something, do it right.

**Comment by fftfaisal** [comment]
@srmklive 

I am also saying that this package is now required at least one trial pricing, but there is no option to add normal pricing without trial period. I just mentioned the method and line number which can be modified for adding this feature. that's it. Dont take it personally :) . I was created manually all of this functionality.you can add this feature or we can do manually.

Thank you.

**Comment by srmklive** [comment]
@fftfaisal You are not offering a solution for the solution you reported, but you kept pointing out the mistake. You could have quietly opened a PR for this. 

The issue of no trial pricing has been fixed, and a new release has been tagged.
