### ISSUE TITLE
Error from guzzle

### ISSUE THREAD

**Issue by fjanis** [srmklive/laravel-paypal#49]
Attempting to do ExpressCheckout.   I am following the sample array $data      
  But I get this error from guzzle (v 6)   "error" ["message"]=> string(47) "No method can handle the form_params config key"  

I have not connected to my cart yet.    Using Laravel 5.1

**Comment by srmklive** [comment]
You should remove success & cancel url from the data you pass to express checkout api.

**Comment by fjanis** [comment]
I tried your suggestion.    I get this error   ErrorException in ExpressCheckout.php line 56:
Undefined index: return_url

My data looks like this 
        $data = [];
        $data['items'] = [
            [
                'name' => 'Product 1',
                'price' => 9.99,
                'qty' => 1
            ],
            [
                'name' => 'Product 2',
                'price' => 4.99,
                'qty' => 2
            ]
        ];

        $data['invoice_id'] = 1;
        $data['invoice_description'] = "Order #$data[invoice_id] Invoice";
    //    $data['return_url'] = url('/paypalSuccess');
    //    $data['cancel_url'] = url('/paypalCancel');

        $total = 0;
        foreach($data['items'] as $item) {
            $total += $item['price'];
        }

        $data['total'] = $total;

with the return and cancel url specified   I get the error 
["message"]=> string(47) "No method can handle the form_params config key" }

This is what I trying to pass this error 
       $post =  array ( 'form_params' => [

      //  'items' => ['hi', 'there!'];
        'items' =>[
            'name' => 'Product 1',
            'price' => 9.99,
            'qty' => 1
        ],
            [
                'name' => 'Product 2',
                'price' => 4.99,
                'qty' => 2
            ],
        'invoice_id' =>  1,
               'invoice_description' => "Order 1 Invoice",
       'return_url' => url('/paypalSuccess'),
        'cancel_url' => url('/paypalCancel'),
         'total' => 9.99 + (4.99 * 2),
    ]);

That causes the error  ErrorException in ExpressCheckout.php line 34:
Undefined index: items

Suggestions ??

**Comment by srmklive** [comment]
you must have a different `invoice_id` every time you do a Express Checkout payment workflow.
