### ISSUE TITLE
Redirect URL after subscription (notification/webhook?)

### ISSUE THREAD

**Issue by divdax** [srmklive/laravel-paypal#490]
Hey guys,

this is not really an issue. Maybe activate discussion tab?

After i set up the subscription with my PayPal sandbox account (create product/plan/subscription) PayPal only show a subscription success page without a button or a redirect. I thought i get a redirect to the `notifiy_url` with payment status/infos but i don't.

How do you handle the first payment to activate a users account?
When the client cancel the subscription via PayPal i could not find any webook or something else. I think i have to check every account per day and make a PayPal API call to check if the subscription is active?

**Comment by myfender** [comment]
I added in the method setupSubscription the "application_context" with return_url and cancel_url.
As soon as I have time I see to make a change to pass the parameters in the method (maybe we pass an array with everything you need) and we explode it inside the method and make the PR

![Schermata 2022-01-03 alle 17 37 21](https://user-images.githubusercontent.com/3018311/147955832-fcded765-eaec-4498-953c-43452eba2489.png)

**Comment by divdax** [comment]
I did a PR. Maybe you can checkout #491

**Comment by myfender** [comment]
@srmklive can you release the new version with this PR please?

**Comment by srmklive** [comment]
Tagged a new release.
