### ISSUE TITLE
INVALID_REQUEST Error on Float Value Like 3.54

### ISSUE THREAD

**Issue by rbmaniya** [srmklive/laravel-paypal#492]
I'm sending price amount 3.54 in addCustomPlan(). I'm getting this object 

{
  "product_id": "PROD-4VY63257AK3580223",
  "name": "Basic Plan",
  "description": "Basic Plan",
  "status": "ACTIVE",
  "billing_cycles": [{
    "frequency": {
      "interval_unit": "MONTH",
      "interval_count": 1
    },
    "tenure_type": "REGULAR",
    "sequence": 1,
    "total_cycles": 0,
    "pricing_scheme": {
      "fixed_price": {
        **"value": 3.54000000000000003552713678800500929355621337890625,**
        "currency_code": "USD"
      }
    }
  }],
  "payment_preferences": {
    "auto_bill_outstanding": true,
    "setup_fee_failure_action": "CONTINUE",
    "payment_failure_threshold": 3
  }
} {
  "name": "INVALID_REQUEST",
  "message": "Request is not well-formed, syntactically incorrect, or violates schema.",
  "debug_id": "cd21d3e0e081d",
  "details": [{
    "field": "/billing_cycles/0/pricing_scheme/fixed_price/value",
    "value": "3.54000000000000003552713678800500929355621337890625",
    "location": "body",
    "issue": "INVALID_PARAMETER_VALUE",
    "description": "The value of a field is invalid."
  }],
  "links": [{
    "href": "https://developer.paypal.com/docs/api/v1/billing/subscriptions#INVALID_REQUEST",
    "rel": "information_link",
    "method": "GET"
  }]
}

somehow price change instead of 3.54 to 3.54000000000000003552713678800500929355621337890625.
Not sure why?
If I pass only 3 in amount. I am getting a successful Responce.

**Comment by srmklive** [comment]
I would say put it in a complete decimal value to multiples of 10 something like 3.60.

**Comment by bladeodessa** [comment]
hello, @srmklive, it still does not work with decimals like an example  you gave, including 3.60
float argument $amount in PaymentAuthorizations::captureAuthorizedPayment still converts it to 3.6000000000000001
What am I doing wrong? 
http://i.imgur.com/qrr2oZx.png

**Comment by dembal1990** [comment]
I have the same issue. I pass 2.4 and catch this:
```php
[
          "field" => "/billing_cycles/0/pricing_scheme/fixed_price/value"
          "value" => "2.4000000000000004"
          "location" => "body"
          "issue" => "INVALID_PARAMETER_VALUE"
          "description" => "The value of a field is invalid."
        ]
```

**Comment by dembal1990** [comment]
Now it is work with that:`round($price,2)`, but I have no clue why :D 
`$price` value is `2.4` and the `round($price,2)` is the same.
