### ISSUE TITLE
Create subscription API creating 2 payments transactions created & completed

### ISSUE THREAD

**Issue by baramdat** [srmklive/laravel-paypal#494]
@srmklive 
We have implemented create subscription API and that is working good but creating 2 different transactions at the same time:
1. Created: When we click on this inside the activity or transactions list then it shows the message "**We are not able to find this transaction id. Can you please check & try again later.**"
2. Complete: This is the actual payment for the subscription

This is the code snippet
`public function createSubscription($id) {
        $plan=Dplan::where('plan_id',$id)->first();
        $currentTime=Carbon::now();
        $provider = new PayPalClient;
        $provider->setApiCredentials(config('paypal'));
        $provider->getAccessToken();
        $start_date=Carbon::now()->addMinute(1);
        
        $data = json_decode('{
          "plan_id": "'.$plan->plan_id.'",
          "quantity": "1",
          "status": "ACTIVE",
          "shipping_amount": {
            "currency_code": "USD",
            "value": "0"
          },
          "subscriber": {
            "name": {
              "given_name": "'.Auth::user()->first_name.'",
              "surname": "'.Auth::user()->last_name.'"
            },
            "email_address": "'.Auth::user()->email.'"
          },
            "application_context": {
            "return_url": "'.route('success-subscription',$plan->plan_id).'",
            "cancel_url": "'.route('subscription-plans').'"
            }
        
        }', true);

        $subscription = $provider->createSubscription($data);
        if (isset($subscription['id']) && $subscription['id'] != null) {
            // redirect to approve href
            foreach ($subscription['links'] as $links) {
                if ($links['rel'] == 'approve') {
                    return redirect()->away($links['href']);
                }
            }
        } else {
            return  $subscription['message'];
        }
    }`
    
    ![apy2](https://user-images.githubusercontent.com/91340351/148761735-46ec6052-efcf-482b-8a38-a83818c27b4c.png)
![pay4](https://user-images.githubusercontent.com/91340351/148761750-2a5080e6-d1e8-487e-aa92-70f2900b64ac.png)

**Comment by baramdat** [comment]
![apy2](https://user-images.githubusercontent.com/91340351/148761735-46ec6052-efcf-482b-8a38-a83818c27b4c.png)

**Comment by srmklive** [comment]
Look at the README file, i have provided helper methods to create recurring subscriptions.
