### ISSUE TITLE
Webhook usage 3.0 Example

### ISSUE THREAD

**Issue by James-Jefferies** [srmklive/laravel-paypal#497]
Hi there, I enjoy using this composer package and it is very useful, although, i am struggling to implement webhook verification. 

I try to verify but it returns with an error of "malformed JSON" I'm sure others are in the same boat and maybe some documentation could be added to help with this a quick example of how to verify an incoming webhook. 

I followed this example [this](https://github.com/srmklive/laravel-paypal/issues/388)

Many thanks

**Comment by fftfaisal** [comment]
@James-Jefferies  you can manually verify by following this [https://stackoverflow.com/questions/61041128/php-verify-paypal-webhook-signature](https://stackoverflow.com/questions/61041128/php-verify-paypal-webhook-signature)

> Hi there, I enjoy using this composer package and it is very useful, although, i am struggling to implement webhook verification.
> 
> I try to verify but it returns with an error of "malformed JSON" I'm sure others are in the same boat and maybe some documentation could be added to help with this a quick example of how to verify an incoming webhook.
> 
> I followed this example [this](https://github.com/srmklive/laravel-paypal/issues/388)
> 
> Many thanks

**Comment by srmklive** [comment]
I have added the method to verify IPN like this:

```
$provider->setWebHookID('PAYPAL_WEBHOOK_ID')->verifyIPN($request);
```

Add the above in your IPN callback in the Laravel app. Update the `PAYPAL_WEBHOOK_ID` to a valid one saved in PayPal.

Please update to the latest dev release for v3.0 using command `composer require srmklive/paypal:v3.0.x-dev`. Kindly test it to see how it works, and report your feedback. Refer to #434 for further details.
