### ISSUE TITLE
getTransactionDetails for v3.0

### ISSUE THREAD

**Issue by oziriemeka** [srmklive/laravel-paypal#498]
Please i can not find or access the method getTransactionDetails for V3.0, after successful checkout / subscription, it sends back the following details token, ba_token, and subscription_id, is there anyway to verify this information or something like we can for the IPN / web hooks

**Comment by srmklive** [comment]
You may do it like this in the current package:

```
$filters = [
    'transaction_id'    => 'SOME_TRANSACTION_ID'
];

$response = $provider->listTransactions($filters);
```

There is no such method to get transaction details.
