### ISSUE TITLE
Subscription question (Setup Fee) - no issue

### ISSUE THREAD

**Issue by icegh** [srmklive/laravel-paypal#500]
dear community (i am new at github),
iam using the subscription function in my laravel setup. now i have one question:
is there a possibility to add a "setup fee" for creating the subscription with your plugin?
currently if i create a subscription all working but it can be that if paypal charges for same day (initial day),
that then the customer has no money on his account. is there a possibility to add here a "first initial "setup fee""?
i have tried to add HANDLINGAMT but has not worked.

i using with billing type = RecurringPayments

thank you so much

**Comment by srmklive** [comment]
You can have a trial & charge setup fee for it
