### ISSUE TITLE
setApiCredentials() method is not working on Laravel 9

### ISSUE THREAD

**Issue by tfevan** [srmklive/laravel-paypal#501]
**PHP** : 8.0.6
**Laravel** : 9.1
**srmklive/paypal** : 3.0

`setApiCredentials()` is not working when `config/paypal.php` file has `'client_id' => ''` and `'client_secret' => ''`.

But it is working fine with same code on previous version of `Laravel 8`

Anyway. if I define the `'client_id' => 1, client_secret' => 1` then Its working fine with custom config `setApiCredentials()` method.

Here is the report of error https://flareapp.io/share/VP68Obl5#share

**Comment by srmklive** [comment]
The behavior is correct.
