### ISSUE TITLE
Expected parameter of type '\Srmklive\PayPal\Traits\Request', '\Illuminate\Http\Request' provided 

### ISSUE THREAD

**Issue by fangmuke** [srmklive/laravel-paypal#502]
use Illuminate\Http\Request;

I think it should be.

https://github.com/srmklive/laravel-paypal/blob/30478c73652ae04d97153f1f3564a2e27b420759/src/Traits/PayPalVerifyIPN.php#L23

**Comment by tfevan** [comment]
Yes, definitely. **Request** class is missing.
