### ISSUE TITLE
Call to a member function setExpressCheckout() on null

### ISSUE THREAD

**Issue by felixkaleke** [srmklive/laravel-paypal#509]
After using the $provider = new PayPalClient;
i got the above error here is the simple code in my controller

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Srmklive\PayPal\Services\ExpressCheckout;
use Srmklive\PayPal\Services\PayPal as PayPalClient;
class PayPalController extends Controller
{
    protected $provider;
    public function __construct(){
        $provider = new PayPalClient;
    }

    public function payment() {
        $data = [];
        $data['items'] = [
            [
                'name' => 'devnote tutorial create',
                'price' => 160,
                'desc' => 'Description for devnote tutorial!',
                'qty' => 1
            ]
        ];

        $data['invoice_id'] = 1;
        $data['invoice_description'] = "Your order #{$data['invoice_id']} Invoice";
        $data['return_url'] = route('payment.success');
        $data['cancel_url'] = route('payment.cancel');
        $data['total'] = 160;

        $provider = $this->provider;
        $response = $provider->setExpressCheckout($data);
        $response = $provider->setExpressCheckout($data, true);
        return redirect($response['paypal_link']);
    }
    public function success(Request $request) {
        $provider = $this->provider;
        $response = $provider->getExpressCheckoutDetails($request->token);
        if (in_array(strtoupper($response['ACK']), ['SUCCESS', 'SUCCESSWITHWARNING'])) {
            return view('success');
        }
        dd('Something is wrong.');
    }
    public function cancel() {
        return view('cancel');
    }
}

**Comment by srmklive** [comment]
You should be using the v1.0 version of this package. Please refer to its README file here:

https://github.com/srmklive/laravel-paypal/blob/v1.0/README.md
