### ISSUE TITLE
Documentation version

### ISSUE THREAD

**Issue by loranger** [srmklive/laravel-paypal#510]
Hello,

Thank you so much for this paypal wrapper.
I'm a bit confused because I don't know what documentation is reliable.

I'd like to add a trial on my plan.
My plan may have juste been created or an existing one, so I though I could do something like this

```php

if ($product_id) {
    $product = $provider->showProductDetails($product_id);
} else {
    $product = $provider->addProduct('Demo Product', 'Demo Product', 'SERVICE', 'SOFTWARE');
}

return $product->addPlanTrialPricing('DAY', 7)->addMonthlyPlan('Demo Plan', 'Demo Plan', 100);
```

But it seems I can only chain methods not split them in a classic OOP usage.
It tried to search the [documentation](https://srmklive.github.io/laravel-paypal/docs.html) but was not able to find the `addPlanTrialPricing` nor the `addProduct` method whereas they are shown on the repository readme file.

Can you please clarify ?

**Comment by srmklive** [comment]
You need to provide a unique:

* Product/Billing Plan Title
* Product/Billing Plan Description
* Product Type
* Product Category.

The following snippet shall work. You just need to provide a unique return & cancel URL. Also, the customer email, name & subscription start date should be in the future. 

```
$response = $provider->addProduct('Demo Product', 'Demo Product', 'SERVICE', 'SOFTWARE')
            ->addPlanTrialPricing('DAY', 7)
            ->addMonthlyPlan('Demo Plan', 'Demo Plan', 100)
            ->setReturnAndCancelUrl('https://example.com/paypal-success', 'https://example.com/paypal-cancel')
            ->setupSubscription('John Doe', 'john@example.com', '2021-12-10');
```

**Comment by loranger** [comment]
Hello,

Thank you for your reply, but I'm afraid you did not answer my questions.

Why do I have to chain those methods when I would like call them depending on my app context:

```php
$product = $provider->addProduct('Demo Product', 'Demo Product', 'SERVICE', 'SOFTWARE');

if($trial) {
    $product->addPlanTrialPricing('DAY', 7);
}

switch($checked){
    case 'monthly':
        $product->addMonthlyPlan('Demo Plan', 'Demo Plan', 100);
        break;
    case 'yearly':
        $product->addAnnualPlan('Demo Plan', 'Demo Plan', 600);
        break;
}

$response = ->setReturnAndCancelUrl('https://example.com/paypal-success', 'https://example.com/paypal-cancel')
            ->setupSubscription('John Doe', 'john@example.com', '2021-12-10');
```

And the most important one: Where can I find the corresponding up-to-date documentation avoiding me to disturb you for every issue I would have?

Thanks

**Comment by srmklive** [comment]
These are just helper methods for your convenience. Chaining them makes sense. You don't need to use the API method calls to set up the product & billing plan. If you have already created a product & billing plan, you can use this:

```
$response = $provider->addProductById('PRODUCT-ID')
            ->addBillingPlanById('PLAN-ID')
            ->setReturnAndCancelUrl('https://example.com/paypal-success', 'https://example.com/paypal-cancel')
            ->setupSubscription('John Doe', 'john@example.com', '2021-12-10');
```

You need to have the relevant product & billing plan id under `PRODUCT-ID` & 'PLAN-ID' respectively.
