### ISSUE TITLE
Error Responses

### ISSUE THREAD

**Issue by ben-demotic** [srmklive/laravel-paypal#511]
The error messages which are returned from the various methods are problematic in that the "message" array key contains 2 JSON objects concatenated together, and it is difficult to separate them back out for decoding.

Someone tried to resolve this via a pull request #444, though this was not merged.

It was most recently mentioned in November 2021 under issue #468.  In the reply you noted "That is what is returned by PayPal, which is being returned directly on your end. Please open a PR for prospective errors response in such use cases."

However, having examined the code, I can see that it is not the case that this 2 object string is being returned by PayPal, actually what is happening is that the package's http client is concatenating the request and the response, using a space to separate them.

In PayPalHttpClient.php this exception is thrown on an http error:

```php
throw new RuntimeException($e->getRequest()->getBody().' '.$e->getResponse()->getBody());
```
You can see the request and the response and the space separating them.

As we already know the content of the request (we sent it), why do we need to return it?  Instead just return the response (which will be valid JSON):

```php
throw new RuntimeException($e->getResponse()->getBody());
```
This is actually part of what pull request #444 wanted to do.

Would you accept a pull request to make this change?

**Comment by srmklive** [comment]
Hi, 

Thanks for your feedback. I got no problems accepting a PR on this.
