### ISSUE TITLE
cant find app_id from paypal

### ISSUE THREAD

**Issue by subtain-haider** [srmklive/laravel-paypal#513]
I am trying to use this package but I cant do anything even I cant list plans, I get this error when I do `$provider->getAccessToken()`
![DkI3SQo](https://user-images.githubusercontent.com/60756535/170825265-9632574a-fca9-46f1-bca5-7fcb3e432dd0.png)

here is what I get when I do `dd($provider)`
![WTCrBf3](https://user-images.githubusercontent.com/60756535/170825351-e64b6219-c53b-4fd7-9e23-e5fc299e3b71.png)

I think the reason is the app_id, as I cant find app id in my Paypal, here is what I see in my Paypal dashboard

![HbPSURS](https://user-images.githubusercontent.com/60756535/170825417-edc72dc7-f50f-4ee4-a618-ff30d5e24cd8.png)

**Comment by subtain-haider** [comment]
anyone help????

**Comment by tyonly** [comment]
> anyone help????

no need appid

**Comment by vedmant** [comment]
I have the same problem, looks like this package is outdated, paypal is not using APP_ID anymore

**Comment by srmklive** [comment]
This has been fixed already.
