### ISSUE TITLE
An exception missing client_id while it did have.

### ISSUE THREAD

**Issue by mnsoraaa** [srmklive/laravel-paypal#516]
Hi, I have a question regarding this fixed.

First of all, I developed a system where every users have different kind of credentials. So I can't solely rely on `config/paypal.php`. I have to set the config respective to the user credentials.

At this line https://github.com/srmklive/laravel-paypal/blob/ffe6929ad8a0f6fa747dceb0766954dadfefb43d/src/Services/PayPal.php#L22 force you to send `$config` when you initialized the class.

From `$provider = new PayPalClient;` to `$provider = new PayPalClient($config);`. 
Otherwise you will get an exception saying you missing `client_id` or `client_secret` at here https://github.com/srmklive/laravel-paypal/blob/ffe6929ad8a0f6fa747dceb0766954dadfefb43d/src/Traits/PayPalRequest.php#L149

So what I did is I setup `$config` with respective information and `$provider = new PaypayClient($config)` , but this line https://github.com/srmklive/laravel-paypal/blob/ffe6929ad8a0f6fa747dceb0766954dadfefb43d/src/Traits/PayPalRequest.php#L146 override my `$config`. Therefore it throws an exception saying that client_id missing from the provided configuration.

My question is, shouldn't above line priority on `$config` instead of `config/paypal.php` ?

**Comment by Flexusma** [comment]
I'm having the same issue, I'll probably end up creating my own version of that class with that line removed...

**Comment by srmklive** [comment]
You didn't review the documentation. It might be an issue with your config.
