### ISSUE TITLE
 process order with card vault

### ISSUE THREAD

**Issue by developcreativo** [srmklive/laravel-paypal#519]
Is there an example in that library to process orders with the paypal card vault?

Since in version v1 after storing a paypal credit card, for example **CARD-1YE76616JL1119629MCSXFCY** was returned and this could be used to process payments in the new version of the api I don't see a process on how to do it in the orders, could you guide me?

I don't speak English sorry if I'm wrong in the translation

**Comment by srmklive** [comment]
https://developer.paypal.com/docs/api/orders/v2/#orders_create

Once you specify the payment source while creating an order, the process order will work.
