### ISSUE TITLE
Can i Possible Use this For Multiple User?

### ISSUE THREAD

**Issue by g0ld3lux** [srmklive/laravel-paypal#52]
as i can see the paypal config is hard coded...
im planning to add a database for config...
with sandbox - boolean , username, password, secret, certificate , app_id and user_id
How can i Use Eloquent instead of the config file?
Is that possible thanks for the answer

**Comment by srmklive** [comment]
You can use the `setApiCredentials` method to override default api credentials like:

```
$provider = (new \Srmklive\PayPal\Services\ExpressCheckout);
$provider->setApiCredentials($credentials);
```

Remember that `$credentials` should be an array.

**Comment by g0ld3lux** [comment]
ok thanks
