### ISSUE TITLE
Custom Header (PayPal-Partner-Attribution-Id)

### ISSUE THREAD

**Issue by salahy** [srmklive/laravel-paypal#522]
Hello,
I want to send in the request custom header `PayPal-Partner-Attribution-Id` [Ref](https://developer.paypal.com/api/rest/requests/)
is it possible to do it ?

Thanks

**Comment by srmklive** [comment]
You need to call the `setRequestHeader` function for this:

```
$provider->setRequestHeader('PayPal-Partner-Attribution-Id', 'some-value');
```
