### ISSUE TITLE
Is there any way to refund without invoice id

### ISSUE THREAD

**Issue by Rahat89** [srmklive/laravel-paypal#532]
Hello there, 

I have tried to refund a captured payment by `refundCapturedPayment` method for an order which I have created by `createOrder` method.  But `refundCapturedPayment` method need `invoice_id` as parameter which is not required by Paypal. Is there any other way to refund? Or maybe you can make `invoice_id` optional?

**Comment by moamahfouz** [comment]
I have the same issue. Did you find any solution? @Rahat89

**Comment by Rahat89** [comment]
@moamahfouz Yes, I have a workaround with a direct request to paypal api. 
`/v2/payments/captures/{$captureId}/refund`

**Comment by srmklive** [comment]
Please add a PR for this.

**Comment by kosmonowt** [comment]
@srmklive how can i do this now?
