### ISSUE TITLE
Pay another account

### ISSUE THREAD

**Issue by EvannG1** [srmklive/laravel-paypal#533]
Hello,

I am creating a platform where users can sell their products themselves (Laravel 9).
I would like to use PayPal for the payment platform, I came across this library.

I would like to know if it's possible to specify a personalized email address (the user's) for the payment of an order instead of mine?

I saw this in the PayPal documentation: https://developer.paypal.com/docs/checkout/standard/customize/pay-another-account/

But I didn't see anything similar in the documentation of this library.

Thanks you for your help

**Comment by srmklive** [comment]
https://developer.paypal.com/docs/api/orders/v2/#orders_create

Add in the payload as mentioned in the link above. It should work.
