### ISSUE TITLE
Is there an easy way to cancel a Paypal Subscription?

### ISSUE THREAD

**Issue by thebeautyofcoding** [srmklive/laravel-paypal#536]
Hello, I am looking for a way to cancel a Paypal Subscription, so that no recurring payment occurs after the end data of the subscription.
Are there any helpers that this Laravel package provides? I have not seen any. 
Thank you so much for this great package.

**Comment by ks-dipeshc** [comment]
Hello @thebeautyofcoding 
**$response = $provider->cancelSubscription('I-BW452GLLEP1G', 'Not satisfied with the service');**

I think this should be work.
Did you try this?

**Comment by thebeautyofcoding** [comment]
Hi @dipeshchangawala,
Thanks for your super quick response. I had not seen this helper (totally my fault) but actually found it in the code now... and it's all working.
Thx for the nice help 👍
