### ISSUE TITLE
How can i add a donations Button to my page using this package

### ISSUE THREAD

**Issue by HermanCeaser** [srmklive/laravel-paypal#537]
Hello Team, i commend you for the wonderful job you've done. Mine is a Question
Do we have a way of creating a donations button using this package? something similar to [Donations Button](https://developer.paypal.com/sdk/donate/).

I have looked through the [documentation](https://srmklive.github.io/laravel-paypal/docs.html) of the package and i can't find it.

Kindly guide me on this

**Comment by sahilsharma100** [comment]
> Hello Team, i commend you for the wonderful job you've done. Mine is a Question Do we have a way of creating a donations button using this package? something similar to [Donations Button](https://developer.paypal.com/sdk/donate/).
> 
> I have looked through the [documentation](https://srmklive.github.io/laravel-paypal/docs.html) of the package and i can't find it.
> 
> Kindly guide me on this

Hi @HermanCeaser donation button is simple frontend checkout u don't need this package for that simply follow the document
