### ISSUE TITLE
subscriptions list? (question)

### ISSUE THREAD

**Issue by zofe** [srmklive/laravel-paypal#542]
is there any way to get the subscription list via api?
this feature does not seem to be implemented by paypal, is there an alternative way, starting with plans for example?

**Comment by srmklive** [comment]
Hi @zofe,

You can do something like this to list all plans.

```
$plans = $provider->listPlans();
```

OR

```
$fields = ['id', 'product_id', 'name', 'description'];
$plans = $provider->listPlans(1, 30, true, $fields);
```
