### ISSUE TITLE
json_decode error: Syntax error

### ISSUE THREAD

**Issue by christian-at-sevenlab** [srmklive/laravel-paypal#543]
In `Srmklive\PayPal\Traits\PayPalHttpClient` 

When a RuntimeError occurs the JsonDecode always fails.
Because this line `Utils::jsonDecode('{"error":'.$t->getMessage().'}', true);` always generates invalid Json

![image](https://user-images.githubusercontent.com/86957084/213137835-df1477da-1119-4810-a1b5-d4e1e75a053e.png)

**Comment by hananint** [comment]
I get the same error but occasionally.  Did you manage to get a solution?

**Comment by lao9s** [comment]
I have the same error

**Comment by srmklive** [comment]
On which API call does it happen? When creating an order?

**Comment by arfan-hostingshouse** [comment]
@srmklive  on every request
