### ISSUE TITLE
Support for setting PayPal-Request-Id header

### ISSUE THREAD

**Issue by gjm** [srmklive/laravel-paypal#547]
In the create order documentation page (https://developer.paypal.com/docs/api/orders/v2/#orders_create) documentation page it is suggested that we set the `PayPal-Request-Id` header to prevent multiple requests from creating multiple orders, but there is no way to specify this value.

**Comment by srmklive** [comment]
You can just use the following method call before doing any API call:

```
$provider->setRequestHeader('PayPal-Request-Id', 'some-value')->createOrder();
```
