### ISSUE TITLE
There is not a ready code for handling Database tables regarding Webhook events ?

### ISSUE THREAD

**Issue by ibrahimsebbane** [srmklive/laravel-paypal#559]

**Comment by srmklive** [comment]
Not neeeded.

**Comment by ibrahimsebbane** [comment]
Hi can you explain why it is not needed, if someone after the payment on
paypal receives a notification about his bank and refuses the payment how
we will know that
Can you give me an example how to kno that someone has really paid and that
he is subscribed

**Comment by srmklive** [comment]
This is something you need to work on your own.

**Comment by ibrahimsebbane** [comment]
Ok thank you
