### ISSUE TITLE
Issue with OpenSSL OR CURL

### ISSUE THREAD

**Issue by omer414** [srmklive/laravel-paypal#56]
I am getting this error

`Use of undefined constant CURL_SSLVERSION_TLSv1_2 - assumed 'CURL_SSLVERSION_TLSv1_2`

But i already have OpenSSL 1.0.1 installed which supports TLS 1.2, do you think this might be some other issue?

**Comment by srmklive** [comment]
You should upgrade OpenSSL to the latest version.

**Comment by hemantnarang33** [comment]
i am getting same problem. i have upgraded openssl to 1.0.1t but still getting this error

**Comment by omer414** [comment]
Well the issue was from my end. I reinstalled everything to the latest version and used self signed ssl certificates, then everything started working fine. 

My applications are mostly quite complicated almost all are SAAS and some are using multiple TLD's on a single laravel instance. But i soon found out that vargrant was way too much configuration for this sort of setup. Now i mostly use laragon instead of vagrant, because it gives instant access to different versions of php, mysql, apache, nginx comes with ssl self signed certificates and it comes with ngrok which makes it pretty easy to test paypal's ipn while still on localhost. You can try it, atleast to test the payment mechanism and i am sure you will love it :)
