### ISSUE TITLE
How to add Trial period to an existing Plan Id while doing a subscription ?

### ISSUE THREAD

**Issue by ibrahimsebbane** [srmklive/laravel-paypal#560]
![image](https://user-images.githubusercontent.com/45486188/228478482-c2794b32-639c-4ecc-a4e7-2f37ad49ec95.png)
Such as in this picture, addPlanTrialPricing is used with a new Plan creation, I want to do the same with existing plan. I tried to call addPlanTrialPricing then addBillingPlanById, but it ignored the trial period.

**Comment by srmklive** [comment]
You would need to created a separate plan to add the trial pricing. As you can see here:

https://developer.paypal.com/docs/api/subscriptions/v1/#plans_patch

You can not add any billing cycle to an already created plan. So it is not possible, to add trial pricing for an available plan.

**Comment by srmklive** [comment]
If you look at the following, you can update the pricing:

https://developer.paypal.com/docs/api/subscriptions/v1/#plans_update-pricing-schemes

But please note that, you would essentially be replacing the previously added pricing schemes.

If you have an implementation where we can update the plan pricing on the fly when creating a subscription that would be great. Please send a PR if you do it.
