### ISSUE TITLE
->setupSubscription is not working when I don't specify $start_date parameter

### ISSUE THREAD

**Issue by ibrahimsebbane** [srmklive/laravel-paypal#562]
![image](https://user-images.githubusercontent.com/45486188/229258602-f6820fa5-6964-4818-bc34-5cf1ac10ecc8.png)
![image](https://user-images.githubusercontent.com/45486188/229258620-adb365c3-521a-45e5-9411-1d6c91284986.png)
**Serialization of 'Closure' is not allowed error : **
![Uploading image.png…]()

**Comment by srmklive** [comment]
You need to specify the start date here.
