### ISSUE TITLE
I have a problem, the Paypal Checkout displays 0€ cost for a Subscription, even though it cuts 1€ from the account

### ISSUE THREAD

**Issue by ibrahimsebbane** [srmklive/laravel-paypal#563]
I tried several ways to get rid of this issue, but No Way, I need your suggestions. here are screens : 
![image](https://user-images.githubusercontent.com/45486188/229312705-dac3e6d8-11be-44b6-8a44-2554ee1b80bb.png)
![image](https://user-images.githubusercontent.com/45486188/229312803-b031ffce-cb9a-4dce-8f7c-e826bfe7d115.png)

**Comment by srmklive** [comment]
I think it maybe a one time transaction for account verification. Although you may need to look at the specific billing plan & product being used there.

**Comment by ibrahimsebbane** [comment]
thank you
