### ISSUE TITLE
How to apply date filters in the listInvoices function

### ISSUE THREAD

**Issue by COV-AmardeepSingh** [srmklive/laravel-paypal#564]
Hi Guys, 

I need to fetch the invoices for the last week only. I am trying to apply the date filter in the listInvoices method. 

 $provider = new PayPalClient;
            $provider->getAccessToken();
            $params = [
                'from' => '2023-04-03',
                'to' => '2023-04-04',
            ];
            $invoices = $provider->listInvoices($params);

But it is giving me the error that the first parameter should be integer(page number).

Is there any way to apply the date filter for the invoices?

Thanks

**Comment by srmklive** [comment]
This is not possible through an API. You are doing it wrong. In order to filter the invoices with dates, first get all the invoices. After that, filter the data based on `invoice_date` field in the response.

Maybe something like the following snippet may work. You would need to change the code accordingly to your needs.

```
$from = Carbon::parse('2023-04-03');
$to = Carbon::parse('2023-04-04');

$filtered_invoices = [];
$invoices = $provider->listInvoices(1, 50);
if ($invoices['total_items'] > 0) {
    $filtered_invoices = collect($invoices['items'])->filter(function ($invoice) use ($from, $to) {
         $detail = $invoice['details'];
         $invoice_date = Carbon::parse($detail['invoice_date']);

         if ($invoice_date->gte($from) && $invoice_date->lte($to)) {
            return $invoice;
         }
         
         return null;
    });
}
```

**Comment by srmklive** [comment]
@amardeepgp  I deleted my previous comment as it was the wrong reply from my end. In your case, you need to use `searchInvoices` API call. You can look it up from the documentation, and goto *Search Invoices* part to view the details:

https://srmklive.github.io/laravel-paypal/docs.html
