### ISSUE TITLE
On php 8.0 float price on subscription give error.

### ISSUE THREAD

**Issue by majid831** [srmklive/laravel-paypal#566]
On local machine I have php 8.0.2 and everything works fine on it.But when i push the changes to my live server php 8.0 .On subscription i start getting the error when I gave a float value.

 $response = $provider->addProduct('Demo Product', 'Demo Product', 'SERVICE', 'SOFTWARE')
                    ->addPlanTrialPricing('DAY', 7)
                    ->addMonthlyPlan('Demo Plan', 'Demo Plan', 31.25)
                    ->setReturnAndCancelUrl('https://example.com/paypal-success', 'https://example.com/paypal-cancel')
                    ->setupSubscription('John Doe', 'john@example.com', '2021-12-10');
                    
Same price works fine in php 8.0.2 but in not in 8.0. When i pass decimal value it also work fine. Please check this issue 
Thanks

**Comment by srmklive** [comment]
What is the error response you are getting?

**Comment by majid831** [comment]
Undefined array key "id"
In /home/xxxxx/xxxxxx/vendor/srmklive/paypal/src/Traits/PayPalAPI/Subscriptions/Helpers.php on line 72 

I am getting undefined array key id but the actual problem was the monthly plan amount. I have fixed this error by converting the price again in addPlanBillingCycle in helpers.php file line 274. 
Code before change.

        $pricing_scheme = [
            'fixed_price' => [
                'value'         => $price,
                'currency_code' => $this->getCurrency(),
            ],
        ];

I have the convert the price in bcdiv.(code after change). Now the problem is temporarily fixed but whenever i will update the composer I will start getting this error again. 

'value'         => bcdiv($price, 1, 2),

protected function addPlanBillingCycle(string $interval_unit, int $interval_count, float $price, bool $trial = false): array
    {
        $pricing_scheme = [
            ‘fixed_price’ => [
                'value'         => bcdiv($price, 1, 2),
                ‘currency_code’ => $this->getCurrency(),
            ],
        ];
        if (empty($this->trial_pricing)) {
            $plan_sequence = 1;
        } else {
            $plan_sequence = 2;
        }
        return [
     	    ‘frequency’ => [
                ‘interval_unit’  => $interval_unit,
                ‘interval_count’ => $interval_count,
            ],
            ‘tenure_type’    => ($trial === true) ? ‘TRIAL’ : ‘REGULAR’,
            ‘sequence’       => ($trial === true) ? 1 : $plan_sequence,
            ‘total_cycles’   => ($trial === true) ? 1 : 0,
            ‘pricing_scheme’ => $pricing_scheme,
        ];
    }

**Comment by srmklive** [comment]
It seems you have an error creating a billing plan. If you have already created a billing plan then try using `addBillingPlanById` function call.

**Comment by majid831** [comment]
I have not already created the billing plan. The same thing works fine on php 8.0.2 but on live serve php 8.0. So round function actually creating the problem. While when i was trying to create plan with 15.23 so on  addPlanBillingCycle function it shows 15.2300000009  so that why i got the error.
