### ISSUE TITLE
How to make a refund using transaction id?

### ISSUE THREAD

**Issue by COV-AmardeepSingh** [srmklive/laravel-paypal#567]
Hi Guys,

 I am using srmklive package for Paypal integration. 

 https://srmklive.github.io/laravel-paypal/docs.html

I want to refund a payment using transaction id but this package or the rest API doesn't provide any such end point. 

Is it possible to refund a payment using transaction id? 

I have already tried the sample codes such as:

$transactionId = "XYZ";
$amount = 10.00; 
$provider = new PayPalClient();
$refundResponse = $provider->refund([
'transaction_id' => $transactionId,
'amount' => [
'total' => $amount,
'currency' => 'USD',
],
]);

Please suggest! 

Thanks

**Comment by srmklive** [comment]
In this case, you would need to do a `TransactionsSearch` API call to get the transaction details. So something like this may work:

```
$filters = [
    'start_date'    => Carbon::now()->subDays(60)->toIso8601String(),
    'end_date'      => Carbon::now()->toIso8601String(),
    'transaction_id' => 'YOUR_TRANSACTION_ID'
];

$response = $provider->listTransactions($filters);
```

Once you get the response, filter out the invoice id. Once you get the invoice id you can then send a refundInvoice call to issue a refund.

Look at the API documentation as well, so this can help you out:

https://developer.paypal.com/docs/api/transaction-search/v1/#search_get

**Comment by COV-AmardeepSingh** [comment]
Hi,
But there can be direct payments in which case I am not getting the invoice_id. Also, the above API calls fails and gives call to undefined method call.  

So is it possible to refund an amount using transaction id?

Please suggest!

Thanks

**Comment by srmklive** [comment]
There is no API provided by PayPal on which you can issue a refund by using a transaction id. I am surprised that you are unable to  do a `List Transactions` API call. The above was a sample code. You had to change it to fit your own requirements.

**Comment by COV-AmardeepSingh** [comment]
Ok. I am able to list the transactions. The only question I had was if it is possible to make a refund using transaction id. So the only way to make a refund is using the invoice_id, correct?

https://developer.paypal.com/docs/api/invoicing/v2/#invoices_refunds

**Comment by COV-AmardeepSingh** [comment]
Additionally, I have tried a simple curl request for refund:

$ch = curl_init();

			$data = array(
				'transaction_id' => 'XYZ',
				'amount' => array(
					'value' => '10.00',
					'currency_code' => 'USD'
				),
				'payment_destination' => array(
					'paypal' => array(
							'account_id' => 'ABC'
					)				
				)			
			
			);

			$headers = array(
				'Content-Type: application/json',
				'Authorization: Bearer SDFFSDDFSFFSF1223'
			);

			$url = 'https://api.sandbox.paypal.com/v2/payments/refunds';

			curl_setopt($ch, CURLOPT_URL, $url);
			curl_setopt($ch, CURLOPT_POST, 1);
			curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
			curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

			$response = curl_exec($ch);

			curl_close($ch);

In this case I am getting permission error.

"{"name":"NOT_AUTHORIZED","message":"Authorization failed due to insufficient permissions.","debug_id":"b7a0d2d8d807a","details":[{"issue":"PERMISSION_DENIED","description":"You do not have permission to access or perform operations on this resource."}],"links":[{"href":"https://developer.paypal.com/docs/api/v2/payments/#NOT_AUTHORIZED-PERMISSION_DENIED","rel":"information_link"}]}

Please suggest!
