### ISSUE TITLE
How to receive $data in paymentSuccess function

### ISSUE THREAD

**Issue by Fedchishina** [srmklive/laravel-paypal#57]
Hello.
Tell me please!)
I created function:
public static function sendPayPallOrder($order){

```
$provider = express_checkout();

$data['items'] = [
    [
        'name' => 'Payment order',
        'price' => 100,
        'qty' => 1
    ],
];
$data['total'] = 100;

$data['invoice_id'] = $order->id;
$data['invoice_description'] = "Order #$data[invoice_id] Invoice";
$data['return_url'] = url('/payment/success');
$data['cancel_url'] = url('/cart');

$response = $provider->setExpressCheckout($data);

return $response['paypal_link'];
```

}
Also i created route:

Route::get('/payment/success', [ 'as' => 'order.payment-success', 'uses'=>'SiteController@paymentSuccess' ] );

And i created function:
public static function paymentSuccess(Request $request)
{
$data=[]; //???????????????
$input = $request->all();
$provider = express_checkout();
$response = $provider->doExpressCheckoutPayment($data, $input['token'], $input['PayerID']);
//dd($response);
}

How i can to receive $data in paymentSuccess function?

**Comment by srmklive** [comment]
`$data` will be what you initially passed to `setExpressCheckout` API call.

**Comment by Fedchishina** [comment]
I don`t understand...
1) I'm calling the function sendPayPallOrder. This function redirect to PayPall-website (runs "setExpressCheckout" and redirect on PayPall website). 
2) After from PayPall-website (after payment) I get to function paymentSuccess. In this function in request I have 2 variables: token and PayID. But I don`t have my $data (I don`t have $data with its structure: items, total, etc.)

What am I doing wrong? And how do I get the $data  to pass it into function "doExpressCheckoutPayment"?

**Comment by Fedchishina** [comment]
public static function paymentSuccess(Request $request)
{
$data=[]; //???????????????
$input = $request->all();
$provider = express_checkout();
/* where is $data????*/
$response = $provider->doExpressCheckoutPayment($data, $input['token'], $input['PayerID']);
//dd($response);
}

**Comment by dann95** [comment]
you must store $data in session, or serialize it in cache or file. When you redirect user to paypal link, you loose $data.. so q simple implementation could be:

## checkout
```php
$provider = express_checkout();

$data['items'] = [
    [
        'name' => 'Payment order',
        'price' => 100,
        'qty' => 1
    ],
];
$data['total'] = 100;

$data['invoice_id'] = $order->id;
$data['invoice_description'] = "Order #$data[invoice_id] Invoice";
$data['return_url'] = url('/payment/success');
$data['cancel_url'] = url('/cart');

$response = $provider->setExpressCheckout($data);
session()->put($response['TOKEN'], $data);
return $response['paypal_link'];
```

## paymentSuccess
```php
public static function paymentSuccess(Request $request)
{
$data=[]; //???????????????
$input = $request->all(); // this is two params: token and PayID
$provider = express_checkout();
/* where is $data????*/
$response = $provider->doExpressCheckoutPayment(session($input['token']), $input['token'], $input['PayerID']);
//dd($response);
}
```

i hope it fix your ask.

**Comment by dann95** [comment]
@srmklive maybe its a good idea update readme.md and add this information, that people must store $data in session, or cache, or also store in db and re-generate it on the success or fail url callback.

**Comment by Fedchishina** [comment]
@dann95, Thank you very much. You helped me.

**Comment by srmklive** [comment]
@dann95 good suggestion. I will look to create a demo application detailing all express checkout payment process.

**Comment by dann95** [comment]
@srmklive if you want i can do a pull request with that.

**Comment by dann95** [comment]
@Fedchishina we are here for that :3

**Comment by srmklive** [comment]
@dann95 I myself am doing that. Will it uploaded to github in a few days.
