### ISSUE TITLE
Subscription Pending status

### ISSUE THREAD

**Issue by muhammad-07** [srmklive/laravel-paypal#571]
When we create subscription it generates subscription but in "APPROVAL_PENDING" status like following, and when we click on the link provided to approve("https://www.sandbox.paypal.com/webapps/billing/subscriptions?ba_token=BA-8XY65047RG697291X")
Paypal page shows unknown error.

array:4 [▼ // app\Http\Controllers\PaypalSubscriptionController.php:36
  "status" => "APPROVAL_PENDING"
  "id" => "I-BBSTT1479KGV"
  "create_time" => "2023-06-09T12:19:25Z"
  "links" => array:3 [▼
    0 => array:3 [▼
      "href" => "https://www.sandbox.paypal.com/webapps/billing/subscriptions?ba_token=BA-8XY65047RG697291X"
      "rel" => "approve"
      "method" => "GET"
    ]
    1 => array:3 [▼
      "href" => "https://api-m.sandbox.paypal.com/v1/billing/subscriptions/I-BBSTT1479KGV"
      "rel" => "edit"
      "method" => "PATCH"
    ]
    2 => array:3 [▼
      "href" => "https://api-m.sandbox.paypal.com/v1/billing/subscriptions/I-BBSTT1479KGV"
      "rel" => "self"
      "method" => "GET"
    ]
  ]
]

**Comment by srmklive** [comment]
You may need to process payment for the subscription.
