### ISSUE TITLE
Documentation Webhook

### ISSUE THREAD

**Issue by Qoraiche** [srmklive/laravel-paypal#572]
Thanks for this package,

I couldn't find how to use the webhook In the docs, I can see that there is a configuration to set the PayPal/notify URL but is it already implemented, or should we add our custom controller?

a link to the docs where webhooks described would be much appreciated

**Comment by srmklive** [comment]
Which version of the package are you using v1 or v3?

**Comment by Qoraiche** [comment]
"srmklive/paypal": "~3.0"

**Comment by Qoraiche** [comment]
> Which version of the package are you using v1 or v3?

"srmklive/paypal": "~3.0"

**Comment by ghost** [comment]
@Qoraiche same issue, do you have document ?
