### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by reina3596** [srmklive/laravel-paypal#573]
Update documentation please¡¡¡
Thanksss for your job¡¡¡

<img width="2011" alt="Captura de pantalla 2023-06-30 a las 15 17 27" src="https://github.com/srmklive/laravel-paypal/assets/93212/4dbc6c15-5202-4c72-8f33-34e0a0156e5c">

**Comment by srmklive** [comment]
Fixed in d1185022593c85d7da1dc5f11aa5a4108100e9a2
