### ISSUE TITLE
Subscriptions payments refunds

### ISSUE THREAD

**Issue by pieteroskam** [srmklive/laravel-paypal#574]
I use the package (v3) with much joy as I moved from Native PHP to Laravel (10),

I encounter an issue handling refunds for subscriptions. I create the subscription with your package. Paypal only supports subscriptions handling over their V1 API. However, when i want to refund a subscription, i have to use the V1 paypal api. However, the package does not include the payments refund v1. Can you add it to the library? Or is there another method to bypass it for now?

please note, my system uses both "normal" payments and subscription.

**Comment by srmklive** [comment]
You may use the `refundCapturedPayment` method to refund the payment. `payments/v1` API has been deprecated, and is not supported anymore.

**Comment by pieteroskam** [comment]
For subscriptions (which is v1 anyway). You can only refund using the v1 API. 
You can also can only get the payment details using V1. For now, I have added a CustomCall Trait.

Perhaps you can add this?

 ```
 trait CustomCall
{

    public function customCall( $url, $method, $data = [])
    {
        $this->apiEndPoint = $url;

        $this->verb = $method;

        $this->setData($data);

        return $this->doPayPalRequest();
    }

}
```
