### ISSUE TITLE
No method for setting tax when create subscription

### ISSUE THREAD

**Issue by sachinpatidar12** [srmklive/laravel-paypal#575]
I am creating a subscription and adding a manual tax in that.. but there is no method in 
Srmklive\PayPal\Traits\PayPalAPI\Subscriptions\Headers

**Comment by sachinpatidar12** [comment]
like this
public function addTax(float $tax): \Srmklive\PayPal\Services\PayPal
    {
        $this->taxes = [
            'inclusive'     => false,
            'percentage' => $tax,
        ];

        return $this;
    }

**Comment by srmklive** [comment]
Do you have something in mind to implement this?

**Comment by srmklive** [comment]
Added the helper method `addTaxes` through commit ceae395de0d6c4b7c5a415e515f1baee6359379d. You just need to provide a percentage value to it.
