### ISSUE TITLE
Set idempotency key

### ISSUE THREAD

**Issue by hashimaziz1** [srmklive/laravel-paypal#578]
Firstly, thanks for all your work on this package that we've been relying on for a few months, it's much appreciated, and apologies if this has already been asked or is somewhere in the docs, I couldn't find it after a quick search of both.

What's the best way to implement PayPal's [idempotency](https://developer.paypal.com/api/rest/reference/idempotency/) using this library? There doesn't seem to be a specific function for this as there is in [other APIs](https://stackoverflow.com/questions/70789049/how-to-set-the-paypal-request-id-using-the-php-paypal-sdk), so would `setRequestHeader` be the only option here, and if so, would the following be all that's needed?

    $paypal->setRequestHeader("PayPal-Request-Id", <unique_id>);

**Comment by srmklive** [comment]
@hashimaziz1 thanks for the kind words. Are you suggesting, that this package automatically adds the request header `PayPal-Request-Id` whenever you do an API call, and you get this header value through a separate function after an API call?

**Comment by hashimaziz1** [comment]
> 

`PayPal-Request-Id` is a special header that PayPal expects to prevent duplicate payments (i.e. idempotency). Some SDKs like [this one here](https://stackoverflow.com/questions/70789049/how-to-set-the-paypal-request-id-using-the-php-paypal-sdk)  have a function to set the value for this header. I'm asking whether this package has such a function, and if not, what the best way is to create that header in my controller.

**Comment by srmklive** [comment]
Just use the `setRequestHeader` everytime before you perform any API call. This will work. Maybe making this feature dynamic would work, but you would need to call the `getRequestHeader` function after every API call.
