### ISSUE TITLE
AUTHENTICATION_FAILURE

### ISSUE THREAD

**Issue by Mazharqwe** [srmklive/laravel-paypal#579]
function abc()
    {

 $config =  [
            'mode'    =>setting('paypal.paypal_mode'), // Can only be 'sandbox' Or 'live'. If empty or invalid, 'live' will be used.
            'sandbox' => [
                'client_id'         => setting('paypal.sandbox_client_id'),
                'client_secret'     => setting('paypal.sandbox_secret'),

            ],
            'live' => [
                'client_id'         => setting('paypal.live_client_id'),
                'client_secret'     => setting('paypal.live_secret'),

                'app_id'            => '',
            ],

            'payment_action' => env('PAYPAL_PAYMENT_ACTION', 'Sale'), // Can only be 'Sale', 'Authorization' or 'Order'
            'currency'       => env('PAYPAL_CURRENCY', 'USD'),
            'notify_url'     => env('PAYPAL_NOTIFY_URL', ''), // Change this accordingly for your application.
            'locale'         => env('PAYPAL_LOCALE', 'en_US'), // force gateway language  i.e. it_IT, es_ES, en_US ... (for express checkout only)
            'validate_ssl'   => env('PAYPAL_VALIDATE_SSL', true), // Validate SSL when creating api client.
        ];
        $provider = new PayPalClient($config);
        $provider->setApiCredentials($config);
        dd($provider->listPlans());
}
Authentication failed due to invalid authentication credentials or a missing Authorization header.

**Comment by Mazharqwe** [comment]
![auth_failed](https://github.com/srmklive/laravel-paypal/assets/31176831/61b8c19f-d167-4ac6-905d-f4ac4fc91e80)

dd($provider)
![provider_response](https://github.com/srmklive/laravel-paypal/assets/31176831/247f978f-4a5f-4297-b8f0-081b55a778f1)

**Comment by srmklive** [comment]
Please read the documentation first.

**Comment by Mazharqwe** [comment]
### Error
Invalid configuration provided. Please provide valid configuration for PayPal API. You can also refer to the documentation at https://srmklive.github.io/laravel-paypal/docs.html to setup correct configuration.


### config/paypal.php
`return [
    'mode'    => env('PAYPAL_MODE', 'sandbox'), // Can only be 'sandbox' Or 'live'. If empty or invalid, 'live' will be used.
    'sandbox' => [
        'client_id'         => env('PAYPAL_SANDBOX_CLIENT_ID', 'AWXvil1L-FIhWWeXqsxmzdvYMtm9UZXP7pdSkzbQQE7MXcK1NYF9IQHeDWYP534Zjp6i8P_lRvrzLLKy'),
        'client_secret'     => env('PAYPAL_SANDBOX_CLIENT_SECRET', 'EOChOoY27rXgwrU-1ITencJCToo1cWPoawNe2baANMVxKMmjJLyJBnpR5h30zOgVDKbG5fxgWBAlyVDi'),
        'app_id'            => 'APP-80W284485P519543T',
    ],
    'live' => [
        'client_id'         => env('PAYPAL_LIVE_CLIENT_ID', ''),
        'client_secret'     => env('PAYPAL_LIVE_CLIENT_SECRET', ''),
        'app_id'            => '',
    ],

    'payment_action' => env('PAYPAL_PAYMENT_ACTION', 'Sale'), // Can only be 'Sale', 'Authorization' or 'Order'
    'currency'       => env('PAYPAL_CURRENCY', 'USD'),
    'notify_url'     => env('PAYPAL_NOTIFY_URL', 'https://al-khidmat.org/'), // Change this accordingly for your application.
    'locale'         => env('PAYPAL_LOCALE', 'en_US'), // force gateway language  i.e. it_IT, es_ES, en_US ... (for express checkout only)
    'validate_ssl'   => env('PAYPAL_VALIDATE_SSL', true), // Validate SSL when creating api client.
];`

### .env
`#PayPal API Mode
# Values: sandbox or live (Default: live)
PAYPAL_MODE=

#PayPal Setting & API Credentials - sandbox
PAYPAL_SANDBOX_CLIENT_ID=
PAYPAL_SANDBOX_CLIENT_SECRET=

#PayPal Setting & API Credentials - live
PAYPAL_LIVE_CLIENT_ID=
PAYPAL_LIVE_CLIENT_SECRET=`


### Controller
` 
function listPlans()
    {
 $provider = new PayPalClient;

        dd($provider->listPlans());
}`

**Comment by BuiltByBucky** [comment]
well, that's one way to handle issues.
Maybe more people have this error AFTER reading the docs?
Got that same response when trying to deal with single orders (non-subscriptions)

**Comment by BuiltByBucky** [comment]
> function abc() {
> 
> $config = [ 'mode' =>setting('paypal.paypal_mode'), // Can only be 'sandbox' Or 'live'. If empty or invalid, 'live' will be used. 'sandbox' => [ 'client_id' => setting('paypal.sandbox_client_id'), 'client_secret' => setting('paypal.sandbox_secret'),
> 
> ```
>         ],
>         'live' => [
>             'client_id'         => setting('paypal.live_client_id'),
>             'client_secret'     => setting('paypal.live_secret'),
> 
>             'app_id'            => '',
>         ],
> 
>         'payment_action' => env('PAYPAL_PAYMENT_ACTION', 'Sale'), // Can only be 'Sale', 'Authorization' or 'Order'
>         'currency'       => env('PAYPAL_CURRENCY', 'USD'),
>         'notify_url'     => env('PAYPAL_NOTIFY_URL', ''), // Change this accordingly for your application.
>         'locale'         => env('PAYPAL_LOCALE', 'en_US'), // force gateway language  i.e. it_IT, es_ES, en_US ... (for express checkout only)
>         'validate_ssl'   => env('PAYPAL_VALIDATE_SSL', true), // Validate SSL when creating api client.
>     ];
>     $provider = new PayPalClient($config);
>     $provider->setApiCredentials($config);
>     dd($provider->listPlans());
> ```
> 
> } Authentication failed due to invalid authentication credentials or a missing Authorization header.

I think in your case you didn't set an access token at all. Try adding 
 ```
$token = $provider->getAccessToken();
$provider->setAccessToken($token);
 ```
before getting the plans

**Comment by srmklive** [comment]
Please see the README file for the repo or view the documentation.
