### ISSUE TITLE
Question about ipn implimentation

### ISSUE THREAD

**Issue by omer414** [srmklive/laravel-paypal#58]
I followed the guide exactly and finally got everything working. But i have some confusions on the ipn implementation. Right now i am just testing the library, so i dont have any tables for orders, carts or any other table neither do i have any data in my sessions. 

So i am following this order: 
setExpressCheckout
getExpressCheckoutDetails
doExpressCheckoutPayment
createRecurringPaymentsProfile

Then on the notify url i am getting a verified status.
**My question is how does the ipn check whether the payment is exactly what was supposed to go through?**

**Comment by srmklive** [comment]
@omer414 Thanks for your question. IPN sends the details of every transaction to your server, regardless of whether its a recurring subscription payment or a single transaction. All those details will be sent back to your server. Now it is up to you, on how you have setup invoicing on your system that differentiates between different type of transactions on your system.

**Comment by omer414** [comment]
Thank you @srmklive, so basically it just gets the status from the IPN POST request, ignores rest of the fields and shows you whether it was verified or not. Am i right?

If you have a bit of time on hand, i have one more question. How do i change the profile description. It always have to be the invoice id, if i change it to something else it throws an error. more details can be found on my commented on this thread https://github.com/srmklive/laravel-paypal/issues/16

**Comment by srmklive** [comment]
@omer414 for any transaction done on paypal, IPN will send all its details regardless of whether transaction was successful or not. 

With regards to your other question regarding changing recurring profile description. If you are doing a transaction which actually is creating a recurring profile, it will be better that define a clear invoice description in `setExpressCheckout` first.
