### ISSUE TITLE
3.0.25 release / Undefined method getClientToken()

### ISSUE THREAD

**Issue by mc0657** [srmklive/laravel-paypal#580]
Hello,

The upgrade 3.0.24 => 3.0.25 broke my app because of the non existing getClientToken()

How are we supposed to do that now ?

```
use Srmklive\PayPal\Services\PayPal as PayPalClient;

$provider = new PayPalClient;
$provider->setApiCredentials(config('paypal'));
$provider->getAccessToken();
$this->paypal_token = $provider->getClientToken()['client_token'];
```

**Comment by srmklive** [comment]
Are you referring to the Identity API Client Token method? Meanwhile, please update your composer.json file to `3.0.24` and run `composer update`.

**Comment by mc0657** [comment]
Yes, the getClientToken() method in the Identity trait. You removed this method in your last commit.

I already rollbacked to 3.0.24 and everything is fine with it.

**Comment by srmklive** [comment]
Is the `getClientToken` API still functioning? The documentation is no longer there. So that's why i removed it.

**Comment by mc0657** [comment]
Yes, working fine. It's in the official documentation for implementing Advanced Checkout : https://developer.paypal.com/docs/checkout/advanced/integrate/#link-integratebackend

![Integrate-Advanced-Checkout](https://github.com/srmklive/laravel-paypal/assets/78485125/0163ea0e-8191-4a56-82bb-29187499951f)

**Comment by srmklive** [comment]
Thanks for pointing it out. I will add these back later today.
