### ISSUE TITLE
Palan list errorRequest is not well-formed, syntactically incorrect, or violates schema

### ISSUE THREAD

**Issue by Mazharqwe** [srmklive/laravel-paypal#581]
array:1 [▼ // app/Http/Controllers/paypal/PaypalController.php:575
  "error" => array:5 [▼
    "name" => "INVALID_REQUEST"
    "message" => "Request is not well-formed, syntactically incorrect, or violates schema."
    "debug_id" => "19687a87fb8fd"
    "details" => array:1 [▼
      0 => array:5 [▼
        "field" => "total_required"
        "value" => "1"
        "location" => "query"
        "issue" => "INVALID_PARAMETER_VALUE"
        "description" => "The value of a field is invalid."
      ]
    ]
    "links" => array:1 [▼
      0 => array:3 [▼
        "href" => "https://developer.paypal.com/docs/api/v1/billing/subscriptions#INVALID_REQUEST"
        "rel" => "information_link"
        "method" => "GET"
      ]
    ]
  ]
]

**Comment by srmklive** [comment]
Please look at your code. Might be an issue there.
