### ISSUE TITLE
error on plan list

### ISSUE THREAD

**Issue by Mazharqwe** [srmklive/laravel-paypal#582]
### Please help me  i have problem on plan list 

    function payplasSetConfig()
    {
        $provider = new PayPalClient;
        $provider->getAccessToken();
        $plans = $provider->listPlans();
        dd($plans);
    }
   
### Response

array:1 [▼ // app/Http/Controllers/paypal/PaypalController.php:575
  "error" => array:5 [▼
    "name" => "INVALID_REQUEST"
    "message" => "Request is not well-formed, syntactically incorrect, or violates schema."
    "debug_id" => "19687a87fb8fd"
    "details" => array:1 [▼
      0 => array:5 [▼
        "field" => "total_required"
        "value" => "1"
        "location" => "query"
        "issue" => "INVALID_PARAMETER_VALUE"
        "description" => "The value of a field is invalid."
      ]
    ]
    "links" => array:1 [▼
      0 => array:3 [▼
        "href" => "https://developer.paypal.com/docs/api/v1/billing/subscriptions#INVALID_REQUEST"
        "rel" => "information_link"
        "method" => "GET" 
      ]
    ]
  ]
]

**Comment by srmklive** [comment]
Please look at your API credentials. You might be using incorrect ones.

**Comment by Mazharqwe** [comment]
no, i'm using correct credentials 
when i create add  monthly subscription it works fine
look at the following code


 function payplasSetConfig()
    {
        $provider = new PayPalClient;
        $provider->getAccessToken();
        $response = $provider->addProduct('Demo Product', 'Demo Product', 'SERVICE', 'SOFTWARE')
            ->addCustomPlan('Demo Plan', 'Demo Plan', 150, 'MONTH', 3)
            ->setReturnAndCancelUrl('https://example.com/paypal-success', 'https://example.com/paypal-cancel')
            ->setupSubscription('John Doe', 'john@example.com', '2023-12-10');
        dd($response);
       
    }
    
    ###Response
array:4 [▼ // app/Http/Controllers/paypal/PaypalController.php:581
  "status" => "APPROVAL_PENDING"
  "id" => "I-2BG9SKM5FBLX"
  "create_time" => "2023-09-14T09:09:51Z"
  "links" => array:3 [▼
    0 => array:3 [▼
      "href" => "https://www.sandbox.paypal.com/webapps/billing/subscriptions?ba_token=BA-3EP349903Y8618813"
      "rel" => "approve"
      "method" => "GET"
    ]
    1 => array:3 [▼
      "href" => "https://api-m.sandbox.paypal.com/v1/billing/subscriptions/I-2BG9SKM5FBLX"
      "rel" => "edit"
      "method" => "PATCH"
    ]
    2 => array:3 [▼
      "href" => "https://api-m.sandbox.paypal.com/v1/billing/subscriptions/I-2BG9SKM5FBLX"
      "rel" => "self"
      "method" => "GET"
    ]
  ]
]

**Comment by Mazharqwe** [comment]
problem still not resolved
