### ISSUE TITLE
False does not work for list plans

### ISSUE THREAD

**Issue by BetaRaff** [srmklive/laravel-paypal#589]
$plans = $this->paypalService->listPlans(1, 30, false, $fields);
passing:
array:2 [
  "plans" => array:20 [
    0 => array:7 [
      "id" => "P-5PL60391PN086362YMPQSCEA"
      "product_id" => "PROD-66K12244AJ158460B"
      "name" => "Mr. Craig Feest I"
      "status" => "ACTIVE"
      "usage_type" => "LICENSED"
      "create_time" => "2023-02-06T15:47:28Z"
      "links" => array:1 [
        0 => array:4 [
          "href" => "https://api.sandbox.paypal.com/v1/billing/plans/P-5PL60391PN086362YMPQSCEA"
          "rel" => "self"
          "method" => "GET"
          "encType" => "application/json"
        ]
      ]
    ]
    1 => array:7 [
      "id" => "P-6GJ702908L2281604MPQSCMA"

$this->apiEndPoint = "v1/billing/plans?page={$this->current_page}&page_size={$this->page_size}&total_required=false";
When hardcoded only

array:1 [
  "error" => array:5 [
    "name" => "INVALID_REQUEST"
    "message" => "Request is not well-formed, syntactically incorrect, or violates schema."
    "debug_id" => "32e62a5fc8738"
    "details" => array:1 [
      0 => array:5 [
        "field" => "total_required"
        "value" => "1"
        "location" => "query"
        "issue" => "INVALID_PARAMETER_VALUE"
        "description" => "The value of a field is invalid."
      ]
    ]
    "links" => array:1 [
      0 => array:3 [
        "href" => "https://developer.paypal.com/docs/api/v1/billing/subscriptions#INVALID_REQUEST"
        "rel" => "information_link"
        "method" => "GET"
        
        When not hardcoded

**Comment by srmklive** [comment]
This is wrong. You should try it like this:

```
$provider = $provider->setPageSize(30)->showTotals(true);
$plans = $provider->setCurrentPage(1)->listPlans();
```
