### ISSUE TITLE
paypal.php Configuration

### ISSUE THREAD

**Issue by neutt22** [srmklive/laravel-paypal#59]
Hello!

I tried to execute the sample process in the readme but this is what I got:

`array:9 [▼
  "TIMESTAMP" => "2016-11-10T07:09:09Z"
  "CORRELATIONID" => "a4fc0e9a1e21"
  "ACK" => "Failure"
  "VERSION" => "123"
  "BUILD" => "26899334"
  "L_ERRORCODE0" => "10002"
  "L_SHORTMESSAGE0" => "Security error"
  "L_LONGMESSAGE0" => "Security header is not valid"
  "L_SEVERITYCODE0" => "Error"
]`

I have followed the guide from https://developer.paypal.com/docs/classic/api/apiCredentials/ have the
API USERNAME (from Manage API Certificate page classic)
API PASSWORD (from Manage API Certificate page classic)
API SECRET (from sandbox, i created an app and it gave me secret key)
API CREDENTIAL (from Manage Api Certificate page classic, put in storage_path('app/cert_key_pem.txt')

Is there anything I'm missing here?

Thanks!

**Comment by neutt22** [comment]
Okay, I've managed to get this through by not using the cert file and opt to use signature, instead. Thanks for the awesome package!

**Comment by thom7kick** [comment]
@neutt22 i have the same error 

when i created an app on the sandbox i am only getting

> Client_id, and

> secret

The configuration is asking for this

> 'username'=> '',

> 'password' => '',

> 'secret' => '',  

> 'certificate' => '',    

which i don't have

**Comment by webreinvent** [comment]
@neutt22 how to opt for signature? can you guide me?
thanks

**Comment by leiiinad** [comment]
@neutt22 How to opt for signature?

**Comment by shalemperez** [comment]
signature?? i am having the same issue ... how can i go true signature!!?? :\
