### ISSUE TITLE
listProducts invalid parameter value by default

### ISSUE THREAD

**Issue by BetaRaff** [srmklive/laravel-paypal#590]
$products = $this->paypalService->listProducts();

"name" => "INVALID_REQUEST"
    "message" => "Request is not well-formed, syntactically incorrect, or violates schema."
    "debug_id" => "41461d92508ff"
    "details" => array:1 [
      0 => array:5 [
        "field" => "total_required"
        "value" => "1"
        "location" => "query"
        "issue" => "INVALID_PARAMETER_VALUE"
        "description" => "The value of a field is invalid."
      ]
    ]
    
        public function setUp(): void
    {
        parent::setUp();

        // Ensure the PayPal API mode is set to 'sandbox'
        config(['paypal.mode' => 'sandbox']);

        $apiContext = new ApiContext(
            new OAuthTokenCredential(
                config('paypal.sandbox.client_id'),
                config('paypal.sandbox.client_secret')
            )
        );

        $this->paypalService = new PaypalService($apiContext);
        $this->paypalService->getAccessToken();
    }
    
    --
    class PaypalService extends PayPalProvider
{

    public function listProducts()
    {
        $this->apiEndPoint = "v1/catalogs/products?page={$this->current_page}&page_size={$this->page_size}&total_required=false";

        $this->verb = 'get';

        return $this->doPayPalRequest();
    }
    
srmklive\paypal\src\Traits\PayPalAPI\CatalogProducts.php
Line 38
$this->apiEndPoint = "v1/catalogs/products?page={$this->current_page}&page_size={$this->page_size}&total_required=false";

This will pass ^ producing:
array:2 [
  "products" => array:3 [
    0 => array:5 [
      "id" => "PROD-66K12244AJ158460B"
      "name" => "Rent-A-Friend"
      "description" => "Social Media Website"
      "create_time" => "2023-02-06T15:47:13Z"
      "links" => array:1 [

$this->apiEndPoint = "v1/catalogs/products?page={$this->current_page}&page_size={$this->page_size}&total_required={$this->show_totals}";
This will fail
Producing the mentioned.
All defaults are retained and follow the provided doc

**Comment by srmklive** [comment]
The implementation has been changed. I haven't been able to update the documentation:

```
$provider = $provider->setPageSize(30)->showTotals(true);
$products = $provider->setCurrentPage(1)->listProducts();
```

**Comment by yash9386** [comment]
thank srmklive
