### ISSUE TITLE
Create Recurring Subscription

### ISSUE THREAD

**Issue by VishalChandora** [srmklive/laravel-paypal#591]
I need to add future date to generate payment link 

code :  // Adding (7 days from the current date) for free trial
            $start_date = Carbon::now()->addDays(1)->format('Y-m-d');

            // Create the PayPal subscription
            $response = $provider->addProductById($data['payment_data']['data'][0]['slug'])
                ->addBillingPlanById($data['payment_data']['data'][0]['paypal_plan_id'])
                ->setReturnAndCancelUrl(route('user.plan.payment.success'), route('user.plan.payment.cancel'))
                ->setupSubscription($request->firstName . ' ' . $request->lastName, $request->email, $start_date);
                
But i want to charge the customer today itself how can i do this ?

**Comment by srmklive** [comment]
That is not possible. In order to do that, you set the subscription date to the today and not add a trial period. Or you add a trial period with a payment.

To do that, you need to create a separate billing plan with relevant pricing schemes you want.
