### ISSUE TITLE
Creating subscription plan not works when request_id not provided

### ISSUE THREAD

**Issue by meenoyseesongkham** [srmklive/laravel-paypal#595]
Hi, there.
I found this library very useful in implementing payment gateway in ecommerce website when building with Laravel and Paypal.
However I found a slight small mistake, I think.
Maybe I might be wrong but when we call "createPlan" without "request_id", it gives me error.
Here is screenshot
![image](https://github.com/srmklive/laravel-paypal/assets/147667043/0f1f0512-580c-4ef5-aa6f-b4b3fa664cbd)

And the code snippet
$payload_array = array(
          "product_id"=> $product->paypal_product_id,
          "name"=> $product->name,
          "description"=> $product->description,
          "status"=> "ACTIVE",
          "billing_cycles"=> array(
            array(
              "frequency"=> array(
                "interval_unit"=> $data["period_unit"],
                "interval_count"=> $data["period_date"]
              ),
              "tenure_type"=> "REGULAR",
              "sequence"=> 1,
              "total_cycles"=> 1,
              "pricing_scheme"=> array(
                "fixed_price"=> array(
                  "value"=> $data["price"],
                  "currency_code"=> "USD"
                )
              )
            )
          ),
          "payment_preferences"=> array(
            "auto_bill_outstanding"=> true,
            "setup_fee"=> array(
              "value"=> "0",
              "currency_code"=> "USD"
            ),
            "setup_fee_failure_action" => "CONTINUE",
            "payment_failure_threshold"=> 3
          ),
          // "taxes"=> array(
          //   "percentage"=> "10",
          //   "inclusive"=> false
          // )
        );

        try{
          $this->provider->getAccessToken();
          $plan = $this->provider->createPlan($payload_array);
        }catch(Throwable $t){
          return response()->json([
            'error'=> 'Cannot create plan in paypal',
            'error_message' => $t->getMessage()
          ]);
        }catch(Exception $e){
          return response()->json([
            'error'=> 'Cannot create paypal plan',
            'error_message' => $e->getMessage()
          ]);
        }

**Comment by meenoyseesongkham** [comment]
So, I suggest easy solution like this.
![image](https://github.com/srmklive/laravel-paypal/assets/147667043/872d5b23-f5ff-4a7f-aafa-8b6730e8b907)

**Comment by srmklive** [comment]
Please update to the latest version first. Your code should be:

```
    try {
      $this->provider->getAccessToken();
      $plan = $this->provider->setRequestHeader('PayPal-Request-Id', 'header-value' )->createPlan($payload_array);
    } catch (Throwable $t) {
      return response()->json([
        'error'=> 'Cannot create plan in paypal',
        'error_message' => $t->getMessage()
      ]);
    } catch(Exception $e) {
      return response()->json([
        'error'=> 'Cannot create paypal plan',
        'error_message' => $e->getMessage()
      ]);
    } 
```

**Comment by srmklive** [comment]
There are also helper methods that enable you to create a product, billing plan and a new subscription.
```
$response = $provider->addProduct('Demo Product', 'Demo Product', 'SERVICE', 'SOFTWARE')
            ->addPlanTrialPricing('DAY', 7)
            ->addMonthlyPlan('Demo Plan', 'Demo Plan', 100)
            ->setReturnAndCancelUrl('https://example.com/paypal-success', 'https://example.com/paypal-cancel')
            ->setupSubscription('John Doe', 'john@example.com', '2021-12-10');
```

Please change the code accordingly for your own use case.
