### ISSUE TITLE
how can i add billing cycles for subscription

### ISSUE THREAD

**Issue by webmuneeb** [srmklive/laravel-paypal#599]
i want to add billing cycles for make it to behave installment system.
what should i add in this call?
$response = $provider->addProduct('Demo Product', 'Demo Product', 'SERVICE', 'SOFTWARE')
            ->addPlanTrialPricing('DAY', 7)
            ->addMonthlyPlan('Demo Plan', 'Demo Plan', 100)
            ->setReturnAndCancelUrl('https://example.com/paypal-success', 'https://example.com/paypal-cancel')
            ->setupSubscription('John Doe', 'john@example.com', '2021-12-10');

**Comment by srmklive** [comment]
You need to update a billing plan's pricing schemes.
