### ISSUE TITLE
Curl + SSL version

### ISSUE THREAD

**Issue by neutt22** [srmklive/laravel-paypal#60]
I got this error:

`Use of undefined constant CURL_SSLVERSION_TLSv1_2 - assumed 'CURL_SSLVERSION_TLSv1_2'`

So I made a search from closed issues and found out I need to update my OpenSSL version to 1.x. So did I:
`root@vps# openssl version
OpenSSL 1.0.2j  26 Sep 2016`

Restarted the VPS, got the same error. So I thought I should also update my Curl:
`>>> curl_version();
=> [
     "version_number" => 471808,
     "age" => 3,
     "features" => 1016733,
     "ssl_version_number" => 0,
     "version" => "7.51.0",
     "host" => "x86_64-redhat-linux-gnu",
     "ssl_version" => "OpenSSL/1.0.1e",
     "libz_version" => "1.2.3",
     "protocols" => [
       "dict",
       "file",
       "ftp",
       "ftps",
       "gopher",
       "http",
       "https",
       "imap",
       "imaps",
       "ldap",
       "ldaps",
       "pop3",
       "pop3s",
       "rtsp",
       "scp",
       "sftp",
       "smb",
       "smbs",
       "smtp",
       "smtps",
       "telnet",
       "tftp",
     ],
   ]
>>> 
`

But im still having the same exact error.

**Comment by srmklive** [comment]
What is the php version on your server?

**Comment by srmklive** [comment]
Also from http://php.net/manual/en/curl.constants.php:

CURL_SSLVERSION_TLSv1_2 (integer)
Available since PHP 5.5.19 and 5.6.3

**Comment by neutt22** [comment]
Im using PHP7 but i guess this is because im using cPanel EasyApache 4 and still using older version of openssl?

**Comment by srmklive** [comment]
Most probably.

**Comment by neutt22** [comment]
I will give a feedback here once i got back tomorrow. Thanks

**Comment by neutt22** [comment]
Okay, this is a server concern. EasyApache 4 won't pickup new OpenSSL version in the system. Thanks for prompt response.
