### ISSUE TITLE
how can i add installment for 12 months

### ISSUE THREAD

**Issue by webmuneeb** [srmklive/laravel-paypal#602]
here the is the function which i am using to create subscription and plan.
$response = $provider->addSetupFee($amount)->addProduct($plan_name, $plan_details, 'SERVICE', 'SOFTWARE')
                ->addMonthlyPlan($plan_name, $plan_name, $amount)
                ->setReturnAndCancelUrl(url('/client/payment/success/'.$id.'/'.$package_id), url('/client/payment/failed/'.$id))
                ->setupSubscription($get_user->full_name, $get_user->email, $startDate);
I want to create an installment plan for 12 months or 6 month according to the requirement of the user. what function need to add to installment months.

**Comment by srmklive** [comment]
I think this feature can be added. By default, we are creating recurring plans.

**Comment by srmklive** [comment]
Hi, i have added this feature where you can specify total installments for a subscription.
```
addMonthlyPlan($plan_name, $plan_name, $amount, 12) // 12 months installment plan
addMonthlyPlan($plan_name, $plan_name, $amount, 6) // 6 months installment plan
```
