### ISSUE TITLE
Paypal recurring payment charge immediately?

### ISSUE THREAD

**Issue by enmanuel97** [srmklive/laravel-paypal#605]
Is there a way to  charge immediately, right now I'm using the herlper
`$provider->addProductById($subscriptionPlan->paypal_product_id)
            ->addBillingPlanById($subscriptionPlan->paypal_monthly_plan_id)
            ->setReturnAndCancelUrl(route('paypal.recurring.success'), route('paypal.recurring.failed'))
            ->setupSubscription($user->full_name, $user->email, $startDate);`

**Comment by srmklive** [comment]
It depends on how you set the billing cycle.
