### ISSUE TITLE
SHIPPING INFORMATION

### ISSUE THREAD

**Issue by RamoseZandry** [srmklive/laravel-paypal#608]
![image](https://github.com/srmklive/laravel-paypal/assets/159796408/db5986b6-4e85-425d-aa71-b12733205b7e)

I want to add information on PAYPAL PAYMENT page but it can't show it.
My source code:

$amount=$request->input('amount');
        $provider = new PayPalClient;
        $provider->setApiCredentials(config('paypal'));
        $paypalToken = $provider->getAccessToken();

        $response = $provider->createOrder([
            "intent" => "CAPTURE",
            "application_context" => [
                'locale' => 'en-US',
                "return_url" => route('success'),
                "cancel_url" => route('abort'),
            ],
            
            'purchase_units' => [
                [
                    'amount' => [
                        "currency_code" => "EUR",
                        "value" => $amount,
                    ],

                    'item' => [
                        'name' => 'photo',
                        'description' => 'SELL PHOTO',
                        'quantity' => '1',
                    ]
                ]
            ],

**Comment by srmklive** [comment]
You can add the shipping information now under payment_source. 

https://developer.paypal.com/docs/api/orders/v2/#orders_create
