### ISSUE TITLE
how can i get the transactionID in AdaptivePayment??

### ISSUE THREAD

**Issue by amournet** [srmklive/laravel-paypal#61]
Login PayPal account, and u will see the transationID of a payment.
Ex: Payment Received (Unique Transaction ID #0SP037792C904160H)
How can i get this ID,?? 
And in function **setPaymentOptions**, I want to add a Description of ReceiverOptions fields, u can help me add this parameter in your package.

**Comment by srmklive** [comment]
@amournet AdaptivePayments as of now is not fully supported in this package. If you are able to get this done, can you open a PR for this so i can merge it?
