### ISSUE TITLE
app_id

### ISSUE THREAD

**Issue by samk1r0** [srmklive/laravel-paypal#618]
I've ended integrating one-time payments via paypal now the question is Where can i obtain my prod app id? I have a client_id and secret key on paypal app page but thereis noapp_id required for generating checkout session

**Comment by otnansirk** [comment]
maybe you can see the response from this method `$this->provider->getAccessToken()`. You should see `app_id` from the response.

and you can use override config for set app_id

**Comment by srmklive** [comment]
It is automatically set after you get the access token. There is no specific method to get the app id, and its not needed anyway.
