### ISSUE TITLE
Paypal refund shows  DECIMAL_PRECISION error, while printing the request from the   PaymentCaptures.php: shows only 2 decimal points but response have many decimal point, 

### ISSUE THREAD

**Issue by sujithzz** [srmklive/laravel-paypal#622]
array:3 [ // vendor/srmklive/paypal/src/Traits/PayPalAPI/![image_2024_02_21T16_32_42_245Z](https://github.com/srmklive/laravel-paypal/assets/160768016/af9d2c05-fcd4-4d29-96b8-d5e480786b4f)53
  "amount" => array:2 [
    "value" => 4.48
    "currency_code" => "GBP"
  ]
  "invoice_id" => ""
  "note_to_payer" => "rejected"
]

array:1 [ // vendor/srmklive/paypal/src/Traits/PayPalAPI/PaymentCaptures.php:56
  "error" => array:5 [
    "name" => "UNPROCESSABLE_ENTITY"
    "message" => "The requested action could not be performed, semantically incorrect, or failed business validation."
    "debug_id" => ""
    "details" => array:1 [
      0 => array:5 [
        "issue" => "DECIMAL_PRECISION"
        "field" => "/amount/value"
        "value" => "4.480000000000000426325641456060111522674560546875"
        "description" => "The value of the field should not be more than two decimal places."
        "location" => "body"
      ]
    ]
    "links" => array:1 [
      0 => array:2 [
        "href" => "https://developer.paypal.com/docs/api/payments/v2/#error-DECIMAL_PRECISION"
        "rel" => "information_link"
      ]
    ]
  ]
]

**Comment by srmklive** [comment]
I would suggest you pass in the refund amount, like this:

```
bcdiv($amount, 1, 2)
```
