### ISSUE TITLE
Did not found any option for paypal payout webhook event receive

### ISSUE THREAD

**Issue by rokonappdevs** [srmklive/laravel-paypal#632]
I created a batch payout but I am unable to configure webhook for receiving state change response.

**Comment by srmklive** [comment]
You need to setup a webhook through the Webhook API call, then use the  specific web hook to process the specific batch payout event.

**Comment by srmklive** [comment]
Or maybe you can setup the IPN in your PayPal account for processing any additional processing on batch payout.
