### ISSUE TITLE
Small bug: Setup fee price not formated

### ISSUE THREAD

**Issue by wwjames** [srmklive/laravel-paypal#634]
Hi first of all Thanks for the awesome package!

We found a small bug when creating a subscription with setup fee the price is not formated on sent and the float gets send with all the decimals as "8.3000000000000007" even though it was sent as a float with one decimal $provider->addSetupFee(8.3)

I think you only neet to change one line of code in src/Traits/PayPalAPI/Subscriptions/Helpers.php@addSetupFee 
```
'setup_fee'                 => [
      'value'         => $price, // use bcdiv($price, 1, 2) like in addPlanBillingCycle
      'currency_code' => $this->getCurrency(),
  ],
```

![Screenshot from 2024-05-10 13-21-05](https://github.com/srmklive/laravel-paypal/assets/108329786/e51a3b7b-6739-48a4-b91a-783cce6b8735)

Regards

**Comment by otnansirk** [comment]
Yeah I think this need to be improve for the `addSetupFee` method.
Thanks @wwjames for your share specific file and method to improve this issue.

I have created PR for this issue.
