### ISSUE TITLE
How can I have EPS or Card integration with this repo?

### ISSUE THREAD

**Issue by hesammoosapour** [srmklive/laravel-paypal#635]
Hi
I can use this package for standard paypal checkout , but when it comes to debit card, I can't and don't know how to do it and 
also when it comes to EPS, I get the error in sandbox testing without authentication:
 "The order was created with processing_instruction of ORDER_COMPLETE_ON_PAYMENT_APPROVAL. The customer has approved the payment and PayPal is still in the process of capturing the order on your behalf as instructed. Please try your request again."
 
 I dont' know what to do, any help would be appreciated.

**Comment by srmklive** [comment]
I think you have to enable this setting in your merchant account to capture payment from debit card & EPS. You may need to capture the payment by doing the capturePayment API call, if you are getting this message.
