### ISSUE TITLE
cannot instal srmklive/paypal:~2.0

### ISSUE THREAD

**Issue by devquen51** [srmklive/laravel-paypal#641]
![image](https://github.com/srmklive/laravel-paypal/assets/98214026/02fc02e9-a6c1-4bd8-8994-6e0dbb6f8142)

please help me, I can't find solution

**Comment by srmklive** [comment]
The package is only supported for Laravel 5.1 to 5.8.

**Comment by devquen51** [comment]
but when I install 3.0, this error still occured
