### ISSUE TITLE
undefined index paypal_link

### ISSUE THREAD

**Issue by alankarmore** [srmklive/laravel-paypal#65]
I am trying to user express checkout. I am getting following error.

'response' => array('TIMESTAMP' => '2016-12-10T16:09:32Z', 'CORRELATIONID' => 'b1867d622585f', 'ACK' => 'Failure', 'VERSION' => '123', 'BUILD' => '000000', 'L_ERRORCODE0' => '10002', 'L_SHORTMESSAGE0' => 'Security error', 'L_LONGMESSAGE0' => 'Security header is not valid', 'L_SEVERITYCODE0' => 'Error'))) 

I think this is because I have not provided the certificate path in config/papal.php is it correct?
If yes then how I can create sandbox account certificate?

**Comment by srmklive** [comment]
Kindly refer to paypal documentation for this.
