### ISSUE TITLE
ErrorException file_get_contents(): Filename cannot be empty. PayPalRequest:95

### ISSUE THREAD

**Issue by simbeto** [srmklive/laravel-paypal#72]
Hello,
Am using this package for paypal IPN and its giving the following error
`` "ErrorException file_get_contents(): Filename cannot be empty. PayPalRequest:95" ``
Line 95 is this
``   $this->config['signature'] = file_get_contents($this->config['certificate']); ``

For IPN we don't need any credential or certificate file to respond with, so i have not provided any in the paypal config file, thus this error must be coming.

So there should also be a check for IPN, as did in line 264, and don't check and include credentials or certificate file when making request for IPN verification
``        if ($method == 'verifyipn') { ``

**Comment by srmklive** [comment]
For IPN verification, you need the PayPal API credentials to verify whether IPN data sent by PayPal is valid.

If you are getting a certificate file error, you should use PayPal API secret. For this, you should generate new API credentials.
