### ISSUE TITLE
Not able to process payment on Live mode via credit / debit card.

### ISSUE THREAD

**Issue by alankarmore** [srmklive/laravel-paypal#75]
Currently I am using this library and I am able to make payment on sandbox environment. 
On live user is trying to make payment via credit or debit card user is redirected to PayPal website, but payment is not completed. 

**Is this library supports for credit and debit card payment.?**

I am getting below value in paypal_link:

 "paypal_link" => "https://www.paypal.com/webscr?cmd=_express-checkout&token=EC-4RY600814B770294Y"

Also I checked with the paypal technical assistance they are saying "The API request stopped at SetExpressCheckOut" and from there it is  not proceeding. 

Kindly let me know is this correct for live or am I missing something.

**Comment by srmklive** [comment]
@alankarmore Have you the PayPal Live API credentials in your `config/paypal.php` file?

**Comment by alankarmore** [comment]
yes I have,  I have added the credentials in paypal.php file from config folder in 'live' key.
The "certificate" is required, because at my paypal merchant account dashboard I can able to create the credentials using username, password and secrete. But not with certificate. 

If I am choosing the certificate one menu to create credentials then I am not able to get the "secrete."
How I can get all this parameters.? Is this will affect the code.

**Comment by srmklive** [comment]
@alankarmore Try to use it with username, password & secret. It should work. I just tested it with my own live paypal api credentials.

**Comment by alankarmore** [comment]
Okay but if I am providing the certificate value will it create an issue.? How I can get the secrete could you tell me the procedure may be I am doing something wrong at paypal merchant dashboard settings. 

Is the secrete key is same as the API Key that I am getting for express checkout from paypal dashboard?

**Comment by srmklive** [comment]
@alankarmore Just the documentation on the link i sent you in my previous reply.

**Comment by alankarmore** [comment]
Sorry to say but it is not there. Don't mind Could you please send it again ?

**Comment by srmklive** [comment]
https://developer.paypal.com/docs/classic/api/apiCredentials/#creating-an-api-signature

**Comment by alankarmore** [comment]
@srmklive  Shall I use this Signature API credentials types as describe in paypal documentation?

**Comment by srmklive** [comment]
@alankarmore Yeah.

**Comment by alankarmore** [comment]
@srmklive  Okay thanks for really quick feedback. I will try it today I let you know if anything more help needs from you. Really appreciate your quick reply. Will let you know status.

**Comment by alankarmore** [comment]
```
public function __construct()
    {
        $this->options = [
            'BRANDNAME' => 'XXXXXX',
            'LOGOIMG' => asset('uploads/logo.png'),
            'CHANNELTYPE' => 'Merchant'
        ];

        parent::__construct();
    }

    public function process($data)
    {
        try{
            if(!empty($data)) {
                $provider = new ExpressCheckout();
                $provider->addOptions($this->options);
                $provider->setCurrency('USD');
                $response = $provider->setExpressCheckout($data);
                if(isset($response['paypal_link'])) {
                    return redirect($response['paypal_link']);
                }
            }

            $this->log->addError(PHP_EOL . ' Something went wrong : ' . __FUNCTION__.__LINE__. PHP_EOL);
            // returning to common error page
        } catch (\PayPal\Exception\PayPalConnectionException $ex) {
            $this->log->addError(PHP_EOL . ' PayPalConnectionException: ' . $ex->getMessage(). PHP_EOL);
            // returning to the error page
        } catch(\Exception $ex) {
            // returning to the error page
            $this->log->addError(PHP_EOL . ' Exception: ' . $ex->getMessage(). PHP_EOL);
        }
    }
```

I have changed credentials & I have written this code, could you please let me know what I am making wrong here...

**Comment by srmklive** [comment]
@alankarmore  I have created a demo app for this. You can review the code here
https://github.com/srmklive/laravel-paypal-demo

**Comment by alankarmore** [comment]
Thanks @srmklive. Really thanks for your help. It was the credentials issues as you stated earlier. 
I was using credentials with certificate for Express Checkout that's why it was not working now it is working fine after changing credentials as per your suggestions. Thanks for your help :+1:
