### ISSUE TITLE
Method [parsePayPalIPN] does not exist.

### ISSUE THREAD

**Issue by ritutest** [srmklive/laravel-paypal#76]
please explain how to use this method

public function postNotify(Request $request)
{
    $response = $this->parsePayPalIPN($request);

    if ($response === 'VERIFIED') {                      
        // Your code goes here ...
    }                            
}

**Comment by srmklive** [comment]
@ritutest Kindly refer to the README file.

**Comment by ritutest** [comment]
but it doesn't explain about this function'
$this->parsePayPalIPN($request);

**Comment by srmklive** [comment]
@ritutest You just need to follow the instructions in the README file. The function simply verifies that the response sent by PayPal is a valid one or not.
