### ISSUE TITLE
Calling addOptions make provider `null`

### ISSUE THREAD

**Issue by klodha** [srmklive/laravel-paypal#78]
Hi,

I cloned demo app from another `srmklive/laravel-paypal-demo`. Following the steps, everything worked fine and I can see orders being placed perfectly, DB being updated as well. I was even able to manage the running state with my own Paypal sandbox details. 

However, when I tried to add options using following:

`
$options = [
            'BRANDNAME' => 'MyApp',
            'LOGOIMG' => 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Eye.png',
            'CHANNELTYPE' => 'Merchant'
        ];
`

Then I changed 
`$response = express_checkout()->setExpressCheckout($cart);` to 
`$response = express_checkout()->addOptions($options)->setExpressCheckout($cart);`

But it started throwing error that `setExpressCheckout` is being called on a null object. I tried changing helper function to Facade method, but no luck. I even tried breaking it in 2 parts:

`
$provider = Paypal:: setProvider('express_checkout');
$provider->addOptions($options);
$provider->setExpressCheckout($cart);
`

But it gives same error. However I remove call to _addOptions_ method, it works fine. I tried to debug $provider after addOption and getting null instead of an object. Earlier, when I wasn't using this demo and was trying my own following the documentation, I didn't face this problem (though with that IPN was failing).

**Comment by srmklive** [comment]
Hi,

Sorry for responding late. I will look into this issue as soon as possible.

**Comment by srmklive** [comment]
Fixed

**Comment by klodha** [comment]
thanks for quick fix.
