### ISSUE TITLE
[Question] Recurring payments value

### ISSUE THREAD

**Issue by JCarlosR** [srmklive/laravel-paypal#79]
Hi.

Using this package I can create recurring payments, right?

My question is, is it possible to **change the amount to pay** in the future? _(notifying the user)_

Thank you in advance.

**Comment by srmklive** [comment]
For PayPal, you need to cancel the previous profile. Then create a new profile and charge specific amount to user.

**Comment by JCarlosR** [comment]
@srmklive Thank you.

Do you have some tutorial or example about creating a recurring payment?

I see the next methods, but I am not sure which ones I have to use and the right order:

- SetExpressCheckout
- GetExpressCheckoutDetails
- DoExpressCheckoutPayment
- RefundTransaction
- CreateBillingAgreement
- CreateRecurringPaymentsProfile
- GetRecurringPaymentsProfileDetails
- UpdateRecurringPaymentsProfile
- ManageRecurringPaymentsProfileStatus

**Comment by srmklive** [comment]
@JCarlosR Have a look at the discussion in #16. This should help you out.
