### ISSUE TITLE
some declaration

### ISSUE THREAD

**Issue by soly2014** [srmklive/laravel-paypal#8]
config.php require some things isn't familiar with me like 
        'username' => '',
        'password' => '',
        'secret' => '',
        'certificate' => '',
but my paypal app gave me Client id and secret 

still confused

**Comment by srmklive** [comment]
The package currently supports PayPal Express Checkout. The credentials you mentioned are for PayPal REST API.

**Comment by srmklive** [comment]
I am also working on implementing the Adaptive Payments integration into the current package
