### ISSUE TITLE
Should be able to dynamically set payment action

### ISSUE THREAD

**Issue by vinsonyung** [srmklive/laravel-paypal#82]
I am currently working on a project which needs both Sale and Authorization payment actions.

'PAYMENTREQUEST_0_PAYMENTACTION'    => !empty($this->config['payment_action']) ? $this->config['payment_action'] : 'Sale',

should be changed to 

'PAYMENTREQUEST_0_PAYMENTACTION'    => array_key_exists('payment_action', $data) ? (!empty($data['payment_action']) ? $data['payment_action'] : (!empty($this->config['payment_action']) ? $this->config['payment_action'] : 'Sale')) : 'Sale',

**Comment by srmklive** [comment]
You can do both:

If you want to Authorize the transaction, then set `payment_action` to `Authorization`. After completing the Express Checkout flow simply use `DoCapture` to capture the transaction. 

For sale, use the normal workflow.
