### ISSUE TITLE
Adding JWT Token to the Paypal Success Redirect Header

### ISSUE THREAD

**Issue by karam94** [srmklive/laravel-paypal#83]
Hi,

I'm currently using laravel-paypal (great job, btw) within an API that utilises JWT Tokens for user authentication.

The issue I face at the moment is that when the user completes payment in the PayPal sandbox, they get redirected back to my application success URL without the JWT Token (Auth Bearer) in the header.

Now there has been some touching up regarding JWT Token's and OAuth in PayPal's REST API documentation, but not exactly in terms of what I think we're looking for:
https://developer.paypal.com/docs/api/auth-headers/

I was wondering what the best approach in terms of modifying things would be to deal with this issue. Would it be best for me to define my own Middleware that intercepts requests, identifies if they are from PayPal & adds the user's JWT Token to the header of the request before it reaches the Controller? If so, do you want to perhaps give me a push in terms of what you personally recommend? Or would it be best to perform these modifications elsewhere?

Let me know what you think.

Cheers!

**Comment by srmklive** [comment]
Hi @karam94 

Thanks for the kind words brother. It really means a lot. 

The scenario you are describing is a sort of unique in nature. I would keep the current work flow that you have. But i would handle processing against transactions in the route which handles IPN notifications from PayPal. Here i would add JWT token to the request header through a middleware and check which transactionid is stored against the current JWT token.

I may be wrong in this regard. But if you have working app in which you are trying to implement such a scenario, i would love to help you out.

**Comment by karam94** [comment]
I like that idea @srmklive, but I've actually decided to take an alternate route. However, I do like your suggestion so maybe you could expand your laravel-paypal-demo repo to include an example for this too as with the popularity of JWT's, API's etc growing, it wouldn't surprise me if this became a common query in the future!

In terms of my alternate route, before returning the PayPal link to the user, I'm saving their short lived JWT token as a cookie to make it available to the API upon the loading of the payment success page. I achieve this by disabling the JWT Authorisation checking middleware I have in place for this particular payment successful route and if a cookie cannot be found containing the user's JWT, they are simply redirected elsewhere. If the cookie is found, I then delete the cookie and utilise the user's information I need post-payment.

I know there are risks to storing tokens as cookies, but as long as I delete the cookies almost immediately after payment is made & refresh the user's token, I'd assume this should get the job done quite comfortably. So I'll close this issue for now, but if you do decide to expand the laravel-paypal-demo repository with an example that uses the IPN approach, do let me know! 👍
