### ISSUE TITLE
Cannot make it work with guzzle 5.3

### ISSUE THREAD

**Issue by mpartarrieu** [srmklive/laravel-paypal#87]
This package is supposed to work with guzzlehttp/guzzle versions "~5.0|~6.0", but when making a post request I get an error "No method can handle the form_params config key". Guzzle 5.3 does not have a "form_params" option, but it has a "body" option that works just the same. Any chance you could check and use "form_params" or "body" option depending on guzzle version?

**Comment by srmklive** [comment]
Hi,

Can you give me the exact error log when this issue happens?

**Comment by mpartarrieu** [comment]
There's no exception. Is method doPayPalRequest() of the PayPalRequest trait that returns an array:
```
[
     'type'      => 'error',
     'message'   => 'No method can handle the form_params config key',
]

```
On line 285 the trait uses the option 'form_params' to make the request, but Guzzle does not have this option; it uses 'body' instead. That's why it fails.

**Comment by srmklive** [comment]
Hi,

Can you temporarily change the version to `dev-master` & check whether the issue for Guzzle 5.3 still exists?

**Comment by mpartarrieu** [comment]
When trying to install dev-master version I get the following error:

> Your requirements could not be resolved to an installable set of packages.
>   Problem 1
>     - Installation request for srmklive/paypal dev-master -> satisfiable by srmklive/paypal[dev-master].
>     - srmklive/paypal dev-master requires illuminate/support dev-master -> no matching package found.
>

**Comment by srmklive** [comment]
Hi,

Try again to update the version to `dev-master` and see what happens?
