### ISSUE TITLE
Partial refund feature

### ISSUE THREAD

**Issue by sasha13** [srmklive/laravel-paypal#88]
Hello,

I was wondering if you could maybe add the functionality for a partial refund?

Maybe something along the lines of:

    public function refundTransaction($transaction, $amount = null) 
    {
        $post = [
            'TRANSACTIONID' => $transaction,
        ];

        if (!empty($amount)) {
            $post = array_merge($post, ['REFUNDTYPE' => 'Partial', 'AMT' => $amount]);
        }

        $response = $this->doPayPalRequest('RefundTransaction', $post);

        return $response;
    }

**Comment by srmklive** [comment]
Added feature and tagged a new release.

**Comment by sasha13** [comment]
Thank you very much.
