### ISSUE TITLE
getRecurringPaymentsProfileDetails - 'Unspecified Method' error

### ISSUE THREAD

**Issue by sasha13** [srmklive/laravel-paypal#89]
After switching to 1.4.5 i get an 'Unspecified Method' error when I try to call    
getRecurringPaymentsProfileDetails($profileId)

    'ACK' => 'Failure',
    'L_ERRORCODE0' => '81002',
    'L_SHORTMESSAGE0' => 'Unspecified Method',
    'L_LONGMESSAGE0' => 'Method Specified is not Supported',
    'L_SEVERITYCODE0' => 'Error',

Same code worked fine on the previous version.. 1.4.2 I think it was.

**update**

I'm now finding that all the calls towards paypal's API are failing with the same error..

Is this just me or..?

**Comment by srmklive** [comment]
@sasha13 Can you temporarily revert back to `1.4.2` and see whether the issue still happens?

**Comment by sasha13** [comment]
@srmklive Sure.. one moment..

**Comment by sasha13** [comment]
Switching back to 1.4.2 resolved the issue

**Comment by srmklive** [comment]
@sasha13 I actually tried to streamline the code a lot in the `1.4.5` release. I was hoping that issues won't happen, but apparently thats not the case :laughing:.

Thanks for reporting it though. Hopefully i will these issues fixed soon.

**Comment by sasha13** [comment]
@srmklive Thanks for responding so quickly! And thanks for a great package.

**Comment by srmklive** [comment]
@sasha13 Fixed. Can you update to `1.4.6` and confirm whether the issue still happens?

**Comment by sasha13** [comment]
@srmklive The issue itself is fixed, but another one appeared.. 

With 1.4.2 I was able to create data for the `setExpressCheckout($data, true)` for a recurring payment with the price and total of 0 and the method call worked fine..

        $data['items'] = [
            [
                'name' => 'some name',
                'price' => 0,
                'qty' => 1
            ]
        ];

        $data['total'] = 0;

Now, when I call the method I get: 

    'L_ERRORCODE0' => '10525',
    'L_SHORTMESSAGE0' => 'Invalid Data',
    'L_LONGMESSAGE0' => 'This transaction cannot be processed. The amount to be charged is zero.',
    'L_SEVERITYCODE0' => 'Error',

**Comment by srmklive** [comment]
@sasha13 To create a recurring payment profile, i would utilize a different workflow.

Suppose i want to charge a user $10 per month, i would go through a normal express checkout flow and charge user $10. However, upon creating a recurring payment profile i would add a trial period of 1 month for the user. If the user was charged $10 today, then the recurring payment profile start date would be `2017-04-27`.

**Comment by sasha13** [comment]
@srmklive Thanks for the advice.. I'll try that

**Comment by sasha13** [comment]
@srmklive I adjusted my code to follow your suggested workflow.. This is the gist of it.. 

SetExpressCheckout
GetExpressCheckoutDetails
DoExpressCheckout
CreateRecurringPaymentsProfile

Everything works fine until I call `CreateRecurringPaymentsProfile`.. I get: 

    'L_ERRORCODE0' => '11502',
    'L_SHORTMESSAGE0' => 'Invalid Token',
    'L_LONGMESSAGE0' => 'The token is invalid',
    'L_SEVERITYCODE0' => 'Error',

The same token works fine for the `GetExpressCheckoutDetails` call

Please advise

**Comment by srmklive** [comment]
Try adding the billing agreement id which gets returned by PayPal in `SetExpressCheckout`.

**Comment by sasha13** [comment]
@srmklive This is what gets returned when I call `setExpressCheckout`

    'TOKEN' => 'EC-8W****************',
    'TIMESTAMP' => '2017-03-28T12:22:32Z',
    'CORRELATIONID' => '74dce********',
    'ACK' => 'Success',
    'VERSION' => '123',
    'BUILD' => '317******',
    'paypal_link' => 'https://www.sandbox.paypal.com/webscr?cmd=_express-checkout&token=EC-8W****************'

I don't have 'billing agreement id' in the response..

The documentation for `CreateRecurringPaymentsProfile` states that I should pass in 

    A timestamped token, the value of which was returned in the response to the first call to SetExpressCheckout

which I am passing in. 

Could the problem be in the initial `setExpressCheckout` call? 

Here's a sample from that part of my code.. 

        $data['items'] = [
            [
                'name' => 'test name',
                'price' => 10,
                'qty' => 1
            ]
        ];

        $data['total'] = 10;
        $data['invoice_id'] = 'TEST APP #' . md5(microtime());
        $data['invoice_description'] = 'TEST APP Invoice #' . md5(microtime());
        $data['return_url'] = url('/payment/success');
        $data['cancel_url'] = url('/payment/cancel');

        $response = express_checkout()->setExpressCheckout($data, true);

Thanks for you help.

**Comment by sasha13** [comment]
@srmklive I think I found the problem.. 

In the `ExpressCheckout` class, on line 107: 

        if ($subscription) {
            $this->post->merge([
                'L_BILLINGTYPE0'                    => 'RecurringPayment',
                'L_BILLINGAGREEMENTDESCRIPTION0'    => !empty($data['subscription_desc']) ?
                    $data['subscription_desc'] : $data['invoice_description'],
            ]);
        }

Even though `$subscription` is true, the fields necessary for the recurring payment never get appended to the `$this->post` array.

**Comment by sasha13** [comment]
Also, at least that's what paypal's documentation says, the value for `'L_BILLINGTYPE0'` must be `'RecurringPayments'` (plural) instead of `'RecurringPayment'` (singular)

**Comment by sasha13** [comment]
@srmklive I finally got everything working with the fore-mentioned changes. 

But 😄 , now I have trouble with the IPN request that comes in.. 

    [2017-03-28 19:35:59] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function post() on null in ../vendor/srmklive/paypal/src/Traits/PayPalRequest.php:319
    Stack trace:
    #0 ../vendor/srmklive/paypal/src/Traits/PayPalRequest.php(242): App\Services\Payment\PaymentService->doPayPalRequest('verifyipn')
    #1 ../vendor/srmklive/paypal/src/Traits/IPNResponse.php(23): App\Services\Payment\PaymentService->verifyIPN(Array)

**Comment by sasha13** [comment]
I think the problem is that this function

    private function setConfig(array $config = [])
    {
        // Setting Http Client
        $this->client = $this->setClient();

        // Set Api Credentials
        if (function_exists('config')) {
            $this->setApiCredentials(
                config('paypal')
            );
        } elseif (!empty($config)) {
            $this->setApiCredentials($config);
        }

        // Set options to be empty.
        $this->options = [];

        $this->setRequestData();
    }

never gets called in the IPN lifecycle, and the `$this->client` which calls the `post()` method in the `doPayPalRequest($method)` is never set.

**Comment by srmklive** [comment]
@sasha13 Thanks man for pointing out some glaring mistakes & correcting them :+1: I am actually rewriting a lot of the package code, so that's these bugs are occuring.

**Comment by sasha13** [comment]
@srmklive Don't mention it.. glad I could help.. 

When do you expect to have the next stable and tested release?

I'm heavily relying on the package for the project I'm working on and these bugs are making me stick to 1.4.2 which doesn't have some of the functionalities I require.

Thanks again.

**Comment by srmklive** [comment]
Referencing #92 to fix recurring payments issue with the package.
