### ISSUE TITLE
Curl issue

### ISSUE THREAD

**Issue by sicsol** [srmklive/laravel-paypal#9]
i'm constantly getting the following from my local

`error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`

**Comment by srmklive** [comment]
Haven't run into this issue on my local system. When do you get this error message?

**Comment by v1shky** [comment]
I am also getting the issue please help!

**Comment by srmklive** [comment]
@v1shky Can you give the whole error stack you are seeing. Also can you describe the LAMP stack configuration with version details for PHP, Mysql & Apache.

**Comment by v1shky** [comment]
I am using mamp pro and found one issue i.e PayPayRequest.php on line 168 use $message = $e->getMessage(); instead existing and i think the certificate in config has some issue and error is curl error CURLE_SSL_CONNECT_ERROR (35)

**Comment by srmklive** [comment]
Fixed.
