### ISSUE TITLE
RecurringPayment issue

### ISSUE THREAD

**Issue by alexa026** [srmklive/laravel-paypal#92]
Hi, im trying to implement the recurring payment. Im referring to the the issue #16 but im always getting either message "Invalid token" or "User havent accepted billing agreement". Any solution for it?

**Comment by srmklive** [comment]
Working on a fix for this. Hopefully i will have it ready in a day or two.

**Comment by srmklive** [comment]
Issue has been fixed. Refer to [demo application](https://github.com/srmklive/laravel-paypal-demo) here.
