### ISSUE TITLE
Error $this->post->isNotEmpty() in Laravel 4.2

### ISSUE THREAD

**Issue by esedArk** [srmklive/laravel-paypal#93]
Hi, in laravel 4.2 don't exist 'isNotEmpty', only exist isEmpty()

In PayPalRequest.php line 218

if (($this->post instanceof Collection) && (!$this->post->isEmpty())) {

https://laravel.com/docs/5.2/collections#method-isnotempty

Thanks por the repo

**Comment by srmklive** [comment]
This package does not support Laravel 4.2. Only Laravel 5 or greater is supported.

**Comment by esedArk** [comment]
Sorry Laravel 5.2! ;)

**Comment by srmklive** [comment]
Fixed. I have tagged a new version of the package.
