### ISSUE TITLE
Paypal partial refund is not working

### ISSUE THREAD

**Issue by svjkumar** [srmklive/laravel-paypal#95]
Hello,

When I tried to refund a transaction partially. Its not working. It issue the full refund.
Please check and fix this issue soon.

**Comment by srmklive** [comment]
You can simply call `$provider->refundTransaction($transactionId, $amount)` to issue partial refund.

**Comment by svjkumar** [comment]
I already tried this method. Still not working. You can check again on this issue. 
I got this from : 
public function refundTransaction($transaction, $amount = 0.00)
    {
        $this->setRequestData([
            'TRANSACTIONID' => $transaction,
        ]);
        if ($amount > 0) {
            $this->post->merge([
                'REFUNDTYPE' => 'Partial',
                'AMT'        => $amount,
            ]);
        }
        return $this->doPayPalRequest('RefundTransaction');
    }

When I changed this function to this: 
    public function refundTransaction($transaction, $amount = 0.00)
    {


        if ($amount > 0) {
          $this->setRequestData([
              'TRANSACTIONID' => $transaction,
              'REFUNDTYPE' => 'Partial',
              'AMT' => $amount,
           ]);
        } else {
          $this->setRequestData([
              'TRANSACTIONID' => $transaction,
          ]);
        }

        return $this->doPayPalRequest('RefundTransaction');
    }

it's working. So can you check this?

**Comment by srmklive** [comment]
Check now.

**Comment by svjkumar** [comment]
Yes, Now its working fine.
