### ISSUE TITLE
I dont know where to find this info 

### ISSUE THREAD

**Issue by faizan-shah** [srmklive/laravel-paypal#97]
i created an app in my paypal developer account , after that i have following information 
-> Sandbox account
-> Client ID
-> Secret
i dont know where to find 
'certificate' => '',    // Link to paypals cert file, storage_path('cert_key_pem.txt')
and you are using this info in paypal.php

**Comment by srmklive** [comment]
Please refer to paypal documentation on how to create sandbox accounts.
