### ISSUE TITLE
Custom params refer to API params from doc?

### ISSUE THREAD

**Issue by ckissi** [srmklive/laravel-paypal#98]
Hi,

I need to send some custom params (e.g. product ID from DB) with paypal api call and get them back from paypal after payment processed so I can identify the product purchased. Do "Additional PayPal API Parameters" in doc refer to custom params or am I wrong?

Can I do something like this?

```
$options = [
    'ITEM_ID' => '1',  // 1 refers to product id in DB
];

$provider->addOptions($options)->setExpressCheckout($data);
```

**Comment by srmklive** [comment]
You can pass those parameters but these have to be specific to the API call you are making.
