### ISSUE TITLE
createRecurringProfile invalid token problem

### ISSUE THREAD

**Issue by raihancse104** [srmklive/laravel-paypal#99]
When i am trying to create a recurring profile then this value show. Please help me to find out this problem.

Array
(
    [TIMESTAMP] => 2017-04-26T06:40:54Z
    [CORRELATIONID] => 79380063dcc30
    [ACK] => Failure
    [VERSION] => 123
    [BUILD] => 25237094
    [L_ERRORCODE0] => 11502
    [L_SHORTMESSAGE0] => Invalid Token
    [L_LONGMESSAGE0] => The token is invalid
    [L_SEVERITYCODE0] => Error
)

**Comment by srmklive** [comment]
Refer to the demo application i have created [here](https://github.com/srmklive/laravel-paypal-demo)

**Comment by raihancse104** [comment]
First time i am using your demo application for testing and add to my paypal credential, Express Checkout works fine but when i try to Create Recurring Payments Profile then invalid token problem.
Array
(
[TIMESTAMP] => 2017-04-26T06:40:54Z
[CORRELATIONID] => 79380063dcc30
[ACK] => Failure
[VERSION] => 123
[BUILD] => 25237094
[L_ERRORCODE0] => 11502
[L_SHORTMESSAGE0] => Invalid Token
[L_LONGMESSAGE0] => The token is invalid
[L_SEVERITYCODE0] => Error
)
this array information given.

**Comment by srmklive** [comment]
Its obvious that you might be missing something or are not following the steps correctly.

**Comment by raihancse104** [comment]
thanks for your notify..missing code section for this reason i faced some probem. Now recurring agreement works fine .
Thanks .if i faced any problem then i will contact you
